---
permalink: install-hw-cabinet/prepare-move-cabinet-task.html 
sidebar: sidebar 
keywords: 3040 40U cabinet, cabinet installation, drive tray installation, controller installation, shelf installation, E2800, E5700, EF300, EF600 
summary: キャビネットを移動する準備をします。 
---
= 3040 40Uキャビネット（Eシリーズ）の移動準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
キャビネットを納入場所から移動するための準備として、キャビネットの総重量を概算し、キャビネットを室内温度に適応させ、梱包材を取り除き、梱包内容を確認します。



== 手順 1 ：キャビネットの重量を見積もります

キャビネットは総重量が 909.1kg （ 2 、 000 ポンド）以内であれば確実かつ安全に運搬できます。キャビネットを安全に移動できるように、おおよその重量を把握しておく必要があります。

.手順
. 次の表を使用して、キャビネットの総重量を見積もります。
+
キャビネットの総重量は、キャビネットに取り付けるトレイの数とタイプによって異なります。

+
|===
| コンポーネント | 重量 | 注： 


 a| 
キャビネット
 a| 
138.80 kg （ 306.0 ポンド）
 a| 
背面ドアを取り付けた状態で空になっています



 a| 
配電ユニット（ PDU ）（ペア）
 a| 
19.96 kg （ 44.0 ポンド）
 a| 



 a| 
マウントレール（ペア）
 a| 
1.59 kg （ 3.50 ポンド）
 a| 



 a| 
E2612 コントローラのドライブトレイ
 a| 
27 kg （ 59.52 ポンド）
 a| 
最大構成



 a| 
E2624 コントローラのドライブトレイ
 a| 
26.12 kg （ 57.32 ポンド）
 a| 
最大構成



 a| 
E2660 コントローラのドライブトレイ
 a| 
105.2 kg （ 232 ポンド）
 a| 
最大構成



 a| 
E2712 コントローラドライブトレイ
 a| 
27.12 kg （ 59.8 ポンド）
 a| 
最大構成



 a| 
E2724 コントローラドライブトレイ
 a| 
26 kg （ 57.32 ポンド）
 a| 
最大構成



 a| 
E2760 コントローラドライブトレイ
 a| 
105.2 kg （ 232 ポンド）
 a| 
最大構成



 a| 
E5412 コントローラのドライブトレイ
 a| 
27.92 （ 61.52 ポンド）
 a| 
最大構成



 a| 
E5424 コントローラのドライブトレイ
 a| 
26.92 kg （ 59.32 ポンド）
 a| 
最大構成



 a| 
E5460 コントローラのドライブトレイ
 a| 
105.2 kg （ 232 ポンド）
 a| 
最大構成



 a| 
E5512 コントローラドライブトレイ
 a| 
28.89 kg （ 63.7 ポンド）
 a| 
最大構成



 a| 
E5524 コントローラのドライブトレイ
 a| 
27.9 kg （ 61.52 ポンド）
 a| 
最大構成



 a| 
E5560 コントローラドライブトレイ
 a| 
107.13 kg （ 236.2 ポンド）
 a| 
最大構成



 a| 
E5612 コントローラドライブトレイ
 a| 
28.89 kg （ 63.7 ポンド）
 a| 
最大構成



 a| 
E5624 コントローラドライブトレイ
 a| 
27.9 kg （ 61.52 ポンド）
 a| 
最大構成



 a| 
E5660 コントローラドライブトレイ
 a| 
107.13 kg （ 236.2 ポンド）
 a| 
最大構成



 a| 
EF540 フラッシュアレイ
 a| 
23.64 kg （ 52.12 ポンド）
 a| 
最大構成



 a| 
EF550 フラッシュアレイ
 a| 
24.63 kg （ 54.32 ポンド）
 a| 
最大構成



 a| 
EF560 フラッシュアレイ
 a| 
24.63 kg （ 54.32 ポンド）
 a| 
最大構成



 a| 
DE1600 ドライブトレイ
 a| 
26.3 kg （ 58 ポンド）
 a| 
最大構成



 a| 
DE5600 のドライブトレイ
 a| 
25.31 kg （ 55.8 ポンド）
 a| 
最大構成



 a| 
DE6600 のドライブトレイ
 a| 
104.1 kg （ 229.6 ポンド）
 a| 
最大構成

|===
. 次の注意事項を確認してください。
+

CAUTION: キャビネットを最終的な設置場所に移動する前に、 DE6600 ドライブトレイからすべてのドライブを取り外してください。

+

CAUTION: * 機器が破損する可能性 * - DE6600 ドライブトレイを搭載したキャビネットは、出荷重量を軽くするためにドライブを取り外した状態で出荷されます。DE6600 ドライブトレイを搭載したキャビネットは、フル装備の重量が 1247.3kg （ 2750 ポンド）を超える可能性があるため、必ずキャビネットを所定の位置に移動してからドライブを装着してください。また、キャビネットの設置場所の床耐荷重がこの重量に対応していることを確認します。

+

CAUTION: * トレイコンポーネントが破損する可能性 * -- DE6600 ドライブトレイは平らな場所に置かないでください。DE6600 ドライブトレイは、ドロワーを作動させたり動かしたりする前にキャビネットに取り付けてください。





== 手順 2 ：キャビネットを適応させる

梱包材を取り除く前に、キャビネットとトレイを室内環境に適応させます。

.手順
. 屋外の温度が 0 ° C （ 32 ° F ）を下回っている場合は、結露を防ぐために、キャビネットとトレイを輸送木箱に入れたまま少なくとも 24 時間室内に放置します。
. 到着時の屋外の温度に応じて、 24 時間の待機時間を延長または短縮します。
+

CAUTION: * トレイコンポーネントの破損の可能性 * -- キャビネットとトレイが納入されたときに屋外の温度が 0 ° C （ 32 ° F ）を下回っていた場合は、すぐに開梱しないでください。冷たくなったコンポーネントを暖かい室温にさらすと、原因による結露が生じてコンポーネントが破損したり故障したりする可能性があります。





== 手順 3 ：梱包材を取り除く

キャビネットが室温に適応したら、梱包材を取り除きます。

.手順
. 梱包箱の前面に記載されている開梱手順を参照してください。
. 同梱されている手順書に従って梱包材を取り除きます。




== 手順 4 ：梱包内容を確認します

梱包内容を調べて、すべての機器が届いたことを確認します。

.手順
. 納入された機器と梱包明細書を比較します。
. すべての機器が届いたことを確認します。
. 足りない項目がある場合は、営業担当者にお問い合わせください。




== 手順 5 ：キャビネットから重量のあるコンポーネントを取り外す

安定性を確保するために、キャビネットの上部から重量のあるコンポーネントをいくつか取り外します。

.作業を開始する前に
* キャビネットを移動する前に、最大重量が 2000 ポンドを超えないようにしてください。
* トレイ、コンポーネント、およびケーブルを取り外すときは、元の場所に再度取り付けることができるように、事前に場所をメモしておきます。


.手順
. ケーブルを外す必要がある場合は、あとで再び取り付けられるように、ケーブル構成を記録しておいてください。
. キャビネットの上半分にあるドライブトレイとコントローラドライブトレイを取り外します。すべてのコンポーネントを同じトレイから一緒に保管します。
+

NOTE: 各トレイの背面にある電源装置やその他のコンポーネントを取り外す必要はありません

. 各コンポーネントを別々の静電気防止用バッグに入れます。元の梱包箱がある場合は、コンポーネントを輸送するために使用します。

