---
permalink: cloud-connector/backup-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector backup 
summary: SANtricity Cloud Connector アプリケーションの左側のナビゲーションパネルで、バックアップオプションにアクセスできます。Backups オプションを使用すると、 Backups ページが表示され、イメージベースまたはファイルベースのバックアップジョブを新たに作成することができます。 
---
= バックアップ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Cloud Connector アプリケーションの左側のナビゲーションパネルで、バックアップオプションにアクセスできます。Backups オプションを使用すると、 Backups ページが表示され、イメージベースまたはファイルベースのバックアップジョブを新たに作成することができます。

SANtricity Cloud Connector アプリケーションの「 * Backups * 」ページを使用して、 E シリーズボリュームのバックアップを作成、処理します。イメージベースまたはファイルベースのバックアップを作成し、それらの処理をただちにまたはあとから実行できます。また、フルバックアップを実行するか、最後に実行されたフルバックアップからの増分バックアップを実行するかを選択できます。SANtricity Cloud Connector アプリケーションで最後に実行されたフルバックアップをベースに、最大 6 つの増分バックアップを実行できます。


NOTE: SANtricity Cloud Connector アプリケーションで表示されるバックアップジョブとリストアジョブのタイムスタンプは、いずれもローカル時間のタイムスタンプです。



== イメージベースのバックアップの新規作成

イメージベースのバックアップを新規作成するには、 SANtricity Cloud Connector アプリケーションの Backups ページの Create 機能を使用します。

.作業を開始する前に
Web Services Proxy から SANtricity Cloud Connector にストレージアレイが登録されていることを確認してください。

.手順
. バックアップページで、 * 作成 * をクリックします。
+
[ バックアップの作成 ] ウィンドウが表示されます。

. [ * イメージベースのバックアップの作成 * ] を選択します。
. 「 * 次へ * 」をクリックします。
+
バックアップの作成ウィンドウに、使用可能な E シリーズボリュームのリストが表示されます。

. 目的の E シリーズボリュームを選択し、 * Next * をクリックします。
+
[ 概要バックアップの作成 ] 確認ウィンドウの [ バックアップ名 ] ページと [ バックアップの作成 ] ページが表示されます。

. 自動生成されたバックアップ名を変更するには、 [ * ジョブ名 * ] フィールドに任意の名前を入力します。
. 必要に応じて、 * Job 概要 * フィールドにバックアップ用の概要を追加します。
+

NOTE: バックアップの内容が簡単にわかるように、ジョブの概要を入力する必要があります。

. 「 * 次へ * 」をクリックします。
+
選択したイメージ・ベースのバックアップの概要が、 [ バックアップ作成 ] ウィンドウの [ バックアップ情報の確認 ] ページに表示されます。

. 選択したバックアップを確認し、「 * 完了 * 」をクリックします。
+
バックアップの作成ウィンドウの確認ページが表示されます。

. 次のいずれかのオプションを選択します。
+
** * YES * -- 選択したバックアップのフル・バックアップを開始します
** * NO * -- 選択したイメージベースのバックアップのフルバックアップは実行されません。
+

NOTE: 選択したイメージベースのバックアップのフルバックアップは、バックアップページの実行機能を使用してあとから実行できます。



. [OK] をクリックします。
+
選択した E シリーズボリュームのバックアップが開始され、バックアップページの結果リストセクションにタスクのステータスが表示されます。





== フォルダ / ファイルベースのバックアップの新規作成

フォルダ / ファイルベースのバックアップを新規に作成するには、 SANtricity Cloud Connector アプリケーションの Backups ページの Create 機能を使用します。

.作業を開始する前に
Web Services Proxy から SANtricity Cloud Connector にストレージアレイが登録されていることを確認してください。

ファイルベースのバックアップでは、指定したファイルシステム上のすべてのファイルが無条件にバックアップされます。ただし、リストアはファイルとフォルダを選択して実行できます。

.手順
. バックアップページで、 * 作成 * をクリックします。
+
[ バックアップの作成 ] ウィンドウが表示されます。

. [ * フォルダー / ファイルベースのバックアップの作成 * ] を選択します。
. 「 * 次へ * 」をクリックします。
+
バックアップに使用できるファイルシステムを含むボリュームのリストが、バックアップの作成ウィンドウに表示されます。

. 目的のボリュームを選択し、 * 次へ * をクリックします。
+
選択したボリュームで使用可能なファイル・システムのリストが ' バックアップの作成ウィンドウに表示されます

+

NOTE: ファイルシステムが表示されない場合は、ファイルシステムの種類が SANtricity Cloud Connector アプリケーションでサポートされていることを確認します。詳細については、を参照してください link:learn-intro-concept.html#supported-file-systems["サポートされているファイルシステム"]。

. バックアップするフォルダまたはファイルが格納されているファイル・システムを選択し ' 次へをクリックします
+
[ 概要バックアップの作成 ] 確認ウィンドウの [ バックアップ名 ] ページと [ バックアップの作成 ] ページが表示されます。

. 自動生成されたバックアップ名を変更するには、 [ * ジョブ名 * ] フィールドに任意の名前を入力します。
. 必要に応じて、 * Job 概要 * フィールドにバックアップ用の概要を追加します。
+

NOTE: バックアップの内容が簡単にわかるように、ジョブの概要を入力する必要があります。

. 「 * 次へ * 」をクリックします。
+
選択したフォルダ / ファイルベースのバックアップの概要が、バックアップ作成ウィンドウの * バックアップ情報の確認 * ページの下に表示されます。

. 選択したフォルダ / ファイルベースのバックアップを確認し、 [ 完了 ] をクリックします。
+
バックアップの作成ウィンドウの確認ページが表示されます。

. 次のいずれかのオプションを選択します。
+
** * YES * -- 選択したバックアップのフル・バックアップを開始します
** * NO * -- 選択したバックアップのフルバックアップは実行されません。
+

NOTE: 選択したファイルベースのバックアップのフルバックアップは、後で Backups ページの Run 機能を使用して実行することもできます。



. [* 閉じる * ] をクリックします。
+
選択した E シリーズボリュームのバックアップが開始され、バックアップページの結果リストセクションにタスクのステータスが表示されます。





== フル・バックアップと増分バックアップを実行します

バックアップページの実行機能を使用して、フルバックアップと増分バックアップを実行できます。増分バックアップは、ファイルベースのバックアップでのみ使用できます。

.作業を開始する前に
SANtricity Cloud Connector でバックアップジョブを作成しておきます。

.手順
. [ バックアップ ] タブで、目的のバックアップ・ジョブを選択し、 [* 実行 ] をクリックします。
+

NOTE: イメージベースのバックアップジョブまたは以前に実行された初期バックアップを含まないバックアップジョブを選択すると、自動的にフルバックアップが実行されます。

+
バックアップの実行ウィンドウが表示されます。

. 次のいずれかのオプションを選択します。
+
** * フル * -- 選択したファイルベースのバックアップのすべてのデータをバックアップします
** * Incremental * ：最後に実行されたバックアップ以降に行われた変更のみをバックアップします
+

NOTE: SANtricity Cloud Connector アプリケーションで最後に実行されたフルバックアップをベースに、最大 6 つの増分バックアップを実行できます。



. [ ファイル名を指定して実行 ] をクリック
+
バックアップが開始されます。





== バックアップジョブを削除

削除機能を使用すると、選択したバックアップの指定したターゲット・ロケーションにあるバックアップ・データとバックアップ・セットが削除されます。

.作業を開始する前に
バックアップのステータスが ［ 完了 ］ 、 ［ 失敗 ］ 、または ［ キャンセル済み ］ であることを確認します。

.手順
. [ バックアップ ] ページで、目的のバックアップを選択し、 [ 削除 ] をクリックします。
+

NOTE: フルベースバックアップを選択した場合は、関連する増分バックアップもすべて削除されます。

+
削除の確認ウィンドウが表示されます。

. 「 * タイプ DELETE * 」フィールドに「削除」と入力して、削除操作を確認します。
. [ 削除（ Delete ） ] をクリックします。
+
選択したバックアップが削除されます。


