---
permalink: cloud-connector/config-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector configuration 
summary: インストールが完了したら、設定ウィザードを使用して SANtricity Cloud Connector アプリケーションをセットアップできます。設定ウィザードは、 SANtricity Cloud Connector に最初にログインしたときに表示されます。 
---
= SANtricity Cloud Connector を初めて設定します
:icons: font
:imagesdir: ../media/


[role="lead"]
インストールが完了したら、設定ウィザードを使用して SANtricity Cloud Connector アプリケーションをセットアップできます。設定ウィザードは、 SANtricity Cloud Connector に最初にログインしたときに表示されます。



== SANtricity Cloud Connector に初めてログインします

SANtricity Cloud Connector に初めてログインするときは、アプリケーションにアクセスするためのデフォルトのパスワードを入力する必要があります。

インターネットに接続されたブラウザにアクセスできることを確認してください。

.手順
. サポートされているブラウザを開きます。
. 構成済みの SANtricity Cloud Connector サーバに接続します（例：「 + http://localhost:8080/+` 」）。
+
SANtricity Cloud Connector アプリケーションの初回ログインページが表示されます。

. Administrator Password フィールドに 'password' のデフォルトのパスワードを入力します
. * ログイン * をクリックします。
+
SANtricity クラウドコネクタ構成ウィザードが表示されます。





== 設定ウィザードを使用する

SANtricity Cloud Connector への初回ログインが成功すると、設定ウィザードが表示されます。

設定ウィザードを使用して、管理者パスワード、 Web サービスプロキシログイン管理クレデンシャル、目的のバックアップターゲットタイプ、および SANtricity Cloud Connector の暗号化パスフレーズを設定します。



=== 手順 1 ：管理者パスワードを設定します

管理者パスワードの設定ページを使用して、 SANtricity Cloud Connector への以降のログインに使用するパスワードをカスタマイズできます。

管理者パスワードの設定ページでパスワードを確立すると、 SANtricity Cloud Connector アプリケーションへの初回ログイン時に使用されていたデフォルトのパスワードが、実質的に置き換えられます。

.手順
. 管理者パスワードの設定ページで、 SANtricity クラウドコネクタに必要なログインパスワードを新しい管理者パスワードを入力 * フィールドに入力します。
. 新しい管理者パスワードを再入力 * フィールドに、最初のフィールドからパスワードを再入力します。
. 「 * 次へ * 」をクリックします。
+
SANtricity Cloud Connector のパスワードセットアップが承認され、設定ウィザードの下にパスフレーズの設定ページが表示されます。

+

NOTE: ユーザ定義の管理者パスワードは、設定ウィザードを完了するまで設定されません。





=== 手順 2 ：パスフレーズを設定する

[ 暗号化パスフレーズの入力 ] ページでは、 8 ～ 32 文字の英数字パスフレーズを指定できます。

ユーザ指定のパスフレーズは、 SANtricity Cloud Connector アプリケーションで使用されるデータ暗号化キーで必要です。

.手順
. [ * パスフレーズを定義 * ] フィールドに、必要なパスフレーズを入力します。
. [ * パスフレーズを再入力 * ] フィールドに、最初のフィールドからパスフレーズを再入力します。
. 「 * 次へ * 」をクリックします。
+
入力した SANtricity Cloud Connector アプリケーションのパスフレーズが受け入れられ、設定ウィザードの [Select Target Type] ページが表示されます。





=== 手順 3 ：ターゲットタイプを選択します

AltaVault Cloud Connector では、バックアップ / リストア機能のターゲットタイプとして、 Amazon S3 、 StorageGRID 、 SANtricity を選択できます。ターゲットタイプの選択ページで、 SANtricity クラウドコネクタアプリケーションに必要なストレージターゲットタイプを指定できます。

AltaVault マウントポイント、 Amazon AWS アカウント、または StorageGRID アカウントのいずれかがあることを確認します。

.手順
. ドロップダウンメニューで、次のいずれかのオプションを選択します。
+
** Amazon AWS
** AltaVault
** StorageGRID
+
選択したオプションの [ ターゲットタイプ ] ページが設定ウィザードに表示されます。



. AltaVault 、 Amazon AWS 、または StorageGRID の該当する設定手順を参照してください。




==== AltaVault アプライアンスを設定します

[Select the Target Type] ページで AltaVault アプライアンスオプションを選択すると、 AltaVault ターゲットタイプの設定オプションが表示されます。

.作業を開始する前に
* AltaVault アプライアンスの NFS マウントパスを確認しておきます。
* ターゲットタイプとして AltaVault アプライアンスを指定した。


.手順
. NFS マウントパス * フィールドに、 AltaVault ターゲットタイプのマウントポイントを入力します。
+

NOTE: NFS Mount Path * フィールドの値は、 Linux のパス形式に従う必要があります。

. [ このターゲットに構成データベースのバックアップを保存する *] チェックボックスをオンにして、選択したターゲットタイプの構成データベースのバックアップを作成します。
+

NOTE: 接続のテスト時に指定したターゲットタイプで既存のデータベース設定が検出された場合は、 SANtricity Cloud Connector ホストの既存のデータベース設定情報を、設定ウィザードで入力した新しいバックアップ情報に置き換えることができます。

. [ 接続のテスト * ] をクリックして、指定した AltaVault 設定で接続をテストします。
. 「 * 次へ * 」をクリックします。
+
指定した SANtricity Cloud Connector のターゲットタイプが承認され、設定ウィザードに Web サービスプロキシページが表示されます。

. 「手順 4 ： Web Services Proxy への接続」に進みます。




==== Amazon AWS アカウントを設定します

Select the Target Type ページで Amazon AWS オプションを選択すると、 Amazon AWS ターゲットタイプの設定オプションが表示されます。

.作業を開始する前に
* Amazon AWS アカウントを確立しておきます。
* ターゲットタイプとして Amazon AWS を指定している。


.手順
. [Access Key ID*] フィールドに、 Amazon AWS ターゲットのアクセス ID を入力します。
. [* Secret Access Key] フィールドに、ターゲットのシークレットアクセスキーを入力します。
. [* Bucket Name*] フィールドに、ターゲットのバケット名を入力します。
. [ このターゲットに構成データベースのバックアップを保存する *] チェックボックスをオンにして、選択したターゲットタイプの構成データベースのバックアップを作成します。
+

NOTE: この設定を有効にして、データベースが失われた場合にバックアップターゲットからデータをリストアできるようにすることを推奨します。

+

NOTE: 接続のテスト時に指定したターゲットタイプで既存のデータベース設定が検出された場合は、 SANtricity Cloud Connector ホストの既存のデータベース設定情報を、設定ウィザードで入力した新しいバックアップ情報に置き換えることができます。

. [ 接続のテスト * ] をクリックして、入力した Amazon AWS クレデンシャルを確認します。
. 「 * 次へ * 」をクリックします。
+
指定した SANtricity Cloud Connector のターゲットタイプが受け入れられ、設定ウィザードの下に Web サービスプロキシページが表示されます。

. 「手順 4 ： Web Services Proxy への接続」に進みます。




==== StorageGRID アカウントを設定します

ターゲットタイプの選択ページで StorageGRID オプションを選択すると、 StorageGRID ターゲットタイプの設定オプションが表示されます。

.作業を開始する前に
* StorageGRID アカウントを確立しておきます。
* SANtricity Cloud Connector キーストアに署名済みの StorageGRID 証明書を格納しておきます。
* StorageGRID をターゲットタイプとして指定しました。


.手順
. [* URL] フィールドに、 Amazon S3 クラウドサービスの URL を入力します
. Access Key ID * フィールドに、 S3 ターゲットのアクセス ID を入力します。
. 「 * Secret Access Key * 」フィールドに、 S3 ターゲットのシークレットアクセスキーを入力します。
. 「 * Bucket Name * 」フィールドに、 S3 ターゲットのバケット名を入力します。
. パス形式のアクセスを使用するには、 * パス形式のアクセスを使用 * チェックボックスを選択します。
+

NOTE: オフにすると、仮想ホスト形式のアクセスが使用されます。

. [ このターゲットに構成データベースのバックアップを保存する *] チェックボックスをオンにして、選択したターゲットタイプの構成データベースのバックアップを作成します。
+

NOTE: この設定を有効にして、データベースが失われた場合にバックアップターゲットからデータをリストアできるようにすることを推奨します。

+

NOTE: 接続のテスト時に指定したターゲットタイプで既存のデータベース設定が検出された場合は、 SANtricity Cloud Connector ホストの既存のデータベース設定情報を、設定ウィザードで入力した新しいバックアップ情報に置き換えることができます。

. Test Connection * をクリックして、入力した S3 クレデンシャルを確認します。
+

NOTE: S3 準拠のアカウントの中には、セキュアな HTTP 接続が必要なものがあります。キーストアへの StorageGRID 証明書の格納については、を参照してください link:install-intro-concept.html#add-storagegrid-certificate-into-a-keystore["キーストアに StorageGRID 証明書を追加します"]。

. 「 * 次へ * 」をクリックします。
+
指定した SANtricity Cloud Connector のターゲットタイプが承認され、設定ウィザードの下に Web サービスプロキシページが表示されます。

. 「手順 4 ： Web Services Proxy への接続」に進みます。




=== 手順 4 ： Web Services Proxy に接続する

SANtricity Cloud Connector と一緒に使用する Web サービスプロキシのログイン情報と接続情報は、 Web サービスプロキシの URL とクレデンシャルの入力ページで入力します。

SANtricity Web サービスプロキシへの接続が確立されていることを確認してください。

.手順
. [* URL] フィールドに、 SANtricity クラウドコネクタで使用する Web サービスプロキシの URL を入力します。
. 「 * User Name * 」フィールドに、 Web Services Proxy 接続のユーザ名を入力します。
. 「 * Password * 」フィールドに、 Web Services Proxy 接続のパスワードを入力します。
. [ 接続のテスト * ] をクリックして、入力した Web Services Proxy クレデンシャルの接続を確認します。
. 入力した Web Services Proxy クレデンシャルを接続テストで確認したら、
. 「 * 次へ * 」をクリックします
+
SANtricity クラウドコネクタの Web サービスプロキシのクレデンシャルが承認され、ストレージアレイの選択ページが設定ウィザードに表示されます。





=== 手順 5 ：ストレージアレイを選択します

設定ウィザードで入力した SANtricity Web サービスプロキシのクレデンシャルに基づいて、使用可能なストレージアレイのリストがストレージアレイの選択ページに表示されます。このページから、 SANtricity Cloud Connector でのバックアップジョブとリストアジョブに使用するストレージアレイを選択できます。

SANtricity Web サービスプロキシアプリケーションにストレージアレイが設定されていることを確認してください。


NOTE: 到達不能なストレージアレイが SANtricity Cloud Connector アプリケーションで検出された場合、ログファイルに API 例外が出力されます。これは、到達不能なアレイからボリュームリストが取得された場合の SANtricity Cloud Connector アプリケーションの想定される動作です。ログファイルにこの API 例外が出力されないようにするには、ルート問題をストレージアレイで直接解決するか、該当するストレージアレイを SANtricity Web サービスプロキシアプリケーションから削除します。

.手順
. バックアップとリストアの処理用に SANtricity Cloud Connector アプリケーションに割り当てるストレージアレイの横にある各チェックボックスを選択します。
. 「 * 次へ * 」をクリックします。
+
選択したストレージアレイが受け入れられ、ホストの選択ページが設定ウィザードに表示されます。

+

NOTE: ストレージアレイの選択ページで選択したストレージアレイに有効なパスワードを設定する必要があります。ストレージアレイのパスワードは、 SANtricity Web サービスプロキシ API のドキュメントを参照して設定してください。





=== 手順 6 ：ホストを選択する

設定ウィザードで選択した Web サービスプロキシでホストされるストレージアレイに基づいて、バックアップとリストアの候補ボリュームを SANtricity Cloud Connector アプリケーションにマッピングするホストを選択できます。ホストの選択ページを使用します。

SANtricity Web サービスプロキシ経由でホストを使用できることを確認してください。

.手順
. 表示されたストレージアレイのドロップダウンメニューで、目的のホストを選択します。
. ホストの選択ページに表示されたその他のストレージアレイについて、手順 1 を繰り返します。
. 「 * 次へ * 」をクリックします。
+
選択した SANtricity クラウドコネクタ用のホストが承認され、設定ウィザードに確認ページが表示されます。





=== 手順 7 ：初期設定を確認する

SANtricity Cloud Connector 設定ウィザードの最後のページには、入力内容の概要が確認用に表示されます。

検証済みの構成データの結果を確認します。

* すべての設定データが正常に検証され、確立されたら、 [* 終了 ] をクリックして設定プロセスを完了します。
* 構成データのいずれかのセクションを検証できない場合は、 ［ * 戻る ］ をクリックして、構成ウィザードの該当するページに移動し、送信されたデータを改訂します。

