---
permalink: cloud-connector/restore-intro-concept.html 
sidebar: sidebar 
keywords: Cloud Connector restore, 
summary: SANtricity Cloud Connector アプリケーションの左側のナビゲーションパネルで、リストアオプションにアクセスできます。Restore （復元）オプションを選択すると、 Restore （復元）ページが表示されます。このページでは、イメージベースまたはファイルベースの復元ジョブを新規作成できます。 
---
= リストアします
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Cloud Connector アプリケーションの左側のナビゲーションパネルで、リストアオプションにアクセスできます。Restore （復元）オプションを選択すると、 Restore （復元）ページが表示されます。このページでは、イメージベースまたはファイルベースの復元ジョブを新規作成できます。

SANtricity Cloud Connector では、「ジョブ」を使用して E シリーズボリュームのリストアを実行します。リストアを実行する前に、処理に使用する E シリーズボリュームを特定する必要があります。SANtricity Cloud Connector ホストにリストア用の E シリーズボリュームを追加すると、 SANtricity Cloud Connector アプリケーションの「リストア」ページを使用してリストアの作成と処理を行うことができます。


NOTE: SANtricity Cloud Connector アプリケーションで表示されるバックアップジョブとリストアジョブのタイムスタンプは、いずれもローカル時間のタイムスタンプです。



== イメージベースのリストアの新規作成

SANtricity Cloud Connector アプリケーションのリストアページの作成機能を使用して、イメージベースのリストアを新規作成できます。

SANtricity Cloud Connector で使用可能なイメージベースのバックアップがあることを確認してください。

.手順
. SANtricity Cloud Connector アプリケーションの [ リストア ] ページで、 [* 作成 ] をクリックします。
+
[ 復元 ] ウィンドウが表示されます。

. 目的のバックアップを選択します。
. 「 * 次へ * 」をクリックします。
+
[ リストア ] ウィンドウに [ バックアップ・ポイントの選択 ] ページが表示されます。

. 目的の完了済みバックアップを選択します。
. 「 * 次へ * 」をクリックします。
+
[ リストア先の選択 ] ページが [ リストア ] ウィンドウに表示されます。

. 復元ボリュームを選択し、 * Next * （次へ）をクリックします。
+
[ リストア ] ウィンドウに [ レビュー ] ページが表示されます。

. 選択したリストア処理を確認し、「 * 完了 * 」をクリックします。
+
選択したターゲットホストボリュームのリストアが開始され、リストアページの結果リストセクションにタスクのステータスが表示されます。





== ファイルベースのリストアの新規作成

SANtricity Cloud Connector アプリケーションのリストアページの作成機能を使用すると、ファイルベースのリストアを新規作成できます。

SANtricity Cloud Connector で使用可能なファイルベースのバックアップがあることを確認します。

.手順
. SANtricity Cloud Connector アプリケーションの [ リストア ] ページで、 [* 作成 ] をクリックします。
+
[ 復元 ] ウィンドウが表示されます。

. [ 復元 ] ウィンドウで、目的のファイルベースのバックアップを選択します。
. 「 * 次へ * 」をクリックします。
+
[ リストア・ジョブの作成 ] ウィンドウに [ バックアップ・ポイントの選択 ] ページが表示されます。

. [ バックアップ・ポイントの選択 ] ページで、目的の完了済みバックアップを選択します。
. 「 * 次へ * 」をクリックします。
+
使用可能なファイル・システムまたはフォルダ / ファイル・ページのリストがリストア・ウィンドウに表示されます

. 復元するフォルダまたはファイルを選択し、 * 次へ * をクリックします。
+
[ リストア先の選択 ] ページが [ リストア ] ウィンドウに表示されます。

. 復元ボリュームを選択し、 * Next * （次へ）をクリックします。
+
[ リストア ] ウィンドウに [ レビュー ] ページが表示されます。

. 選択したリストア処理を確認し、「 * 完了 * 」をクリックします。
+
選択したターゲットホストボリュームのリストアが開始され、リストアページの結果リストセクションにタスクのステータスが表示されます。





== リストアを削除する

削除機能を使用すると、選択したリストア・アイテムをリストア・ページの結果リスト・セクションから削除できます。

ステータスが「 Completed 」、「 Failed 」、または「 Cancelled 」のリストアジョブがあることを確認します。

.手順
. [ 復元 ] ページで、 [ 削除 *] をクリックします。
+
削除の確認ウィンドウが表示されます。

. 「 *Type delete 」フィールドに「削除」と入力して、削除アクションを確認します。
. [ 削除（ Delete ） ] をクリックします。
+

NOTE: 中断されているリストアは削除できません。

+
選択したリストアが削除されます。


