---
permalink: config-linux/fc-assign-volume-nvme-task.html 
sidebar: sidebar 
keywords: express linux configuration, assign volume, assign namespace, 
summary: ボリュームを I/O 処理に使用できるように、ホストまたはホストクラスタにボリューム（ネームスペース）を割り当てる必要があります。これにより、ストレージアレイの 1 つ以上のネームスペースへのアクセスがホストまたはホストクラスタに許可されます。 
---
= ボリュームを割り当てます
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストまたはホストクラスタにボリューム（ネームスペース）を割り当てて、そのボリュームを I/O 処理に使用できるようにする必要があります。これにより、ストレージアレイの 1 つ以上のネームスペースへのアクセスがホストまたはホストクラスタに許可されます。

ボリュームを割り当てる際は、次のガイドラインに注意してください。

* ボリュームは一度に 1 つのホストまたはホストクラスタにのみ割り当てることができます。
* 割り当てられたボリュームは、ストレージアレイのコントローラ間で共有されます。
* あるホストまたはホストクラスタからボリュームへのアクセスに、同じネームスペース ID （ NSID ）を重複して使用することはできません。一意の NSID を使用する必要があります。


次の場合、ボリュームの割り当ては失敗します。

* すべてのボリュームが割り当てられている。
* ボリュームはすでに別のホストまたはホストクラスタに割り当てられています。


次の場合、ボリュームを割り当てることはできません。

* 有効なホストまたはホストクラスタが存在しません。
* すべてのボリューム割り当てが定義されている。


未割り当てのボリュームはすべて表示されますが、ホストが Data Assurance （ DA ）対応かどうかで処理は次のように異なります。

* DA 対応ホストの場合は、 DA 有効、 DA 無効のどちらのボリュームでも選択できます。
* DA 対応でないホストで DA が有効なボリュームを選択した場合、ボリュームをホストに割り当てる前にボリュームの DA を自動的に無効にする必要があるという警告が表示されます。


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. ボリュームを割り当てるホストまたはホストクラスタを選択し、 * ボリュームの割り当て * をクリックします。
+
ダイアログボックスに割り当て可能なすべてのボリュームが表示されます。任意の列をソートしたり、 * Filter * ボックスに何かを入力すると、特定のボリュームを簡単に見つけることができます。

. 割り当てる各ボリュームの横にあるチェックボックスを選択します。すべてのボリュームを選択する場合は、テーブルヘッダーのチェックボックスを選択します。
. [*Assign*] をクリックして、操作を完了します。


ホストまたはホストクラスタへのボリュームの割り当てが完了すると、次の処理が実行されます。

* 割り当てたボリュームに、次に使用可能な NSID が設定されます。ホストがこの NSID を使用してボリュームにアクセスします。
* ホストに関連付けられているボリュームの一覧にユーザが指定したボリューム名が表示されます。

