---
permalink: config-linux/iscsi-configure-array-side-network-task.html 
sidebar: sidebar 
keywords: configure iSCSI networking, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: アレイ側で iSCSI ネットワークを設定します。 
---
= アレイ側のネットワークを設定
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager の GUI を使用して、アレイ側の iSCSI ネットワークを設定します。

.必要なもの
* いずれかのストレージアレイコントローラの IP アドレスまたはドメイン名。
* System Manager GUI 、ロールベースアクセス制御（ RBAC ）、または LDAP のパスワード、およびストレージアレイへの適切なセキュリティアクセスのために設定されたディレクトリサービス。アクセス管理の詳細については、 SANtricity システムマネージャオンラインヘルプを参照してください。


このタスクでは、 System Manager のハードウェアページから iSCSI ポートの設定にアクセスする方法について説明します。設定には、 System （設定） > Configure iSCSI Ports （ iSCSI ポートの設定）メニューからもアクセスできます。

.手順
. ブラウザで、「 + https://<DomainNameOrIPAddress>+` 」という URL を入力します
+
「 IPAddress 」は、ストレージアレイコントローラの 1 つのアドレスです。

+
設定されていないアレイで初めて SANtricity システムマネージャを開くと、管理者パスワードの設定プロンプトが表示されます。ロールベースアクセス管理では、 admin 、 support 、 security 、 monitor の 4 つのローカルロールが設定されます。最後の 3 つのロールには、推測されにくいランダムなパスワードが設定されています。admin ロールのパスワードを設定したら、 admin クレデンシャルを使用してすべてのパスワードを変更できます。4 つのローカルユーザロールの詳細については、 SANtricity System Manager ユーザインターフェイスのオンラインヘルプを参照してください。

. 管理者パスワードの設定フィールドとパスワードの確認フィールドに管理者ロールの System Manager パスワードを入力し、 * パスワードの設定 * をクリックします。
+
プール、ボリュームグループ、ワークロード、または通知が設定されていない場合は、セットアップウィザードが起動します。

. セットアップウィザードを閉じます。
+
このウィザードは、あとで追加のセットアップタスクを実行する際に使用します。

. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示されている場合は、 * シェルフの背面を表示 * をクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. iSCSI ポートを設定するコントローラをクリックします。
+
コントローラのコンテキストメニューが表示されます。

. Configure iSCSI Port* （ iSCSI ポートの設定）を選択します。
+
Configure iSCSI Ports （ iSCSI ポートの設定）ダイアログボックスが開きます。

. ドロップダウンリストで、設定するポートを選択し、 * Next * をクリックします。
. 構成ポートの設定を選択し、 * 次へ * をクリックします。
+
すべてのポート設定を表示するには、ダイアログボックスの右側にある * Show more port settings * リンクをクリックします。

+
|===
| ポートの設定 | 説明 


 a| 
イーサネットポート速度の設定
 a| 
目的の速度を選択します。ドロップダウンリストに表示されるオプションは、ネットワークがサポートできる最大速度（ 10Gbps など）によって異なります。


NOTE: コントローラで使用可能なオプションの 25Gb iSCSI ホストインターフェイスカードは速度を自動ネゴシエートしません。各ポートの速度を 10Gb または 25Gb に設定する必要があります。すべてのポートを同じ速度に設定する必要があります。



 a| 
IPv4 を有効にする / IPv6 を有効にする
 a| 
一方または両方のオプションを選択して、 IPv4 ネットワークと IPv6 ネットワークのサポートを有効にします。



 a| 
TCP リスニングポート（ [Show more port settings] をクリックすると使用可能）
 a| 
必要に応じて、新しいポート番号を入力します。

リスニングポートは、コントローラがホスト iSCSI イニシエータからの iSCSI ログインをリスンするために使用する TCP ポート番号です。デフォルトのリスニングポートは 3260 です。3260 、または 49152~65535 の値を入力する必要があります。



 a| 
MTU サイズ（ * Show more port settings* をクリックすると使用可能）
 a| 
必要に応じて、 Maximum Transmission Unit （ MTU ；最大伝送ユニット）の新しいサイズをバイト単位で入力します。

デフォルトの Maximum Transmission Unit （ MTU ；最大転送単位）サイズは 1500 バイト / フレームです。1500~9000 の値を入力する必要があります。



 a| 
ICMP PING 応答を有効にします
 a| 
Internet Control Message Protocol （ ICMP ）を有効にする場合は、このオプションを選択します。ネットワーク接続されたコンピュータのオペレーティングシステムは、このプロトコルを使用してメッセージを送信します。ICMP メッセージを送信することで、ホストに到達できるかどうかや、そのホストとのパケットの送受信にどれくらいの時間がかかるかが確認されます。

|===
+
[*IPv4 を有効にする *] を選択した場合は、 [ 次へ *] をクリックすると、 IPv4 設定を選択するためのダイアログボックスが開きます。[*IPv6 を有効にする *] を選択した場合、 [ 次へ *] をクリックすると、 IPv6 設定を選択するためのダイアログボックスが開きます。両方のオプションを選択した場合は、 IPv4 設定のダイアログボックスが最初に開き、 * 次へ * をクリックすると、 IPv6 設定のダイアログボックスが開きます。

. IPv4 と IPv6 、またはその両方を自動または手動で設定します。すべてのポート設定を表示するには、ダイアログボックスの右側にある * Show more settings * リンクをクリックします。
+
|===
| ポートの設定 | 説明 


 a| 
自動的に設定を取得します
 a| 
設定を自動的に取得するには、このオプションを選択します。



 a| 
静的な設定を手動で指定します
 a| 
このオプションを選択した場合は、フィールドに静的アドレスを入力します。IPv4 の場合は、ネットワークのサブネットマスクとゲートウェイも指定します。IPv6 の場合は、ルーティング可能な IP アドレスとルータの IP アドレスも指定します。

|===
. [ 完了 ] をクリックします。
. System Manager を終了します。

