---
permalink: config-linux/iscsi-configure-host-side-network-task.html 
sidebar: sidebar 
keywords: configure iSCSI networking, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: ホスト側で iSCSI ネットワークを設定します。 
---
= ホスト側のネットワークを設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホスト側のネットワークを設定するには、いくつかの手順を実行する必要があります。

ホスト側の iSCSI ネットワークを設定するには、物理パスあたりのノードセッション数を設定し、適切な iSCSI サービスをオンにし、 iSCSI ポートのネットワークを設定し、 iSCSI iface バインドを作成し、イニシエータとターゲットの間に iSCSI セッションを確立します。

ほとんどの場合、 iSCSI CNA / NIC には標準で実装されているソフトウェアイニシエータを使用できます。最新のドライバ、ファームウェア、 BIOS をダウンロードする必要はありません。を参照してください https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^] コードの要件を確認します。

.手順
. /etc/iscsi/iscsid.conf ファイルの「 node.session.nr_sessions` 」変数で、物理パスあたりのデフォルトのセッション数を確認します。必要に応じて、デフォルトのセッション数を 1 に変更します。
+
[listing]
----
node.session.nr_sessions = 1
----
. /etc/iscsi/iscsid.conf ファイルの「 node.session.timeo.replacement_timeout` 」変数をデフォルト値の「 120 」から「 20 」に変更します。
+
[listing]
----
node.session.timeo.replacement_timeout=20
----
. 'iscsid' および '(open-)iSCSI' サービスがオンであり ' ブートが有効になっていることを確認します
+
* Red Hat Enterprise Linux 7 および 8 （ RHEL 7 および RHEL 8 ） *

+
[listing]
----
# systemctl start iscsi
# systemctl start iscsid
# systemctl enable iscsi
# systemctl enable iscsid
----
+
* SUSE Linux Enterprise Server 12 および 15 （ SLES 12 および SLES 15 ） *

+
[listing]
----
# systemctl start iscsid.service
# systemctl enable iscsid.service
----
+
オプションで '/etc/iscsi/iscsid.conf で 'node.startup=automatic' を設定してから 'iscsiadm コマンドを実行し ' 再起動後にセッションが持続するようにします

. ホスト IQN イニシエータ名を取得します。この名前は、アレイに対してホストを設定する際に使用します。
+
[listing]
----
# cat /etc/iscsi/initiatorname.iscsi
----
. iSCSI ポートのネットワークを設定します。
+

NOTE: iSCSI イニシエータは、パブリックネットワークポートに加えて、別々のプライベートセグメントまたは VLAN 上で 2 つ以上の NIC を使用する必要があります。

+
.. ifconfig -aコマンドを使用して'iSCSIポート名を確認します
.. iSCSI イニシエータポートの IP アドレスを設定します。イニシエータポートは、 iSCSI ターゲットポートと同じサブネット上にあることが必要です。
+
[listing]
----
# vim /etc/sysconfig/network-scripts/ifcfg-<NIC port>
----
+
編集：

+
[listing]
----
BOOTPROTO=none
ONBOOT=yes
NM_CONTROLLED=no
----
+
追加：

+
[listing]
----
IPADDR=192.168.xxx.xxx
NETMASK=255.255.255.0
----
+

NOTE: 必ず両方の iSCSI イニシエータポートのアドレスを設定してください。

.. ネットワークサービスを再起動します。
+
[listing]
----
# systemctl restart network
----
.. Linux サーバから iSCSI ターゲットポートのすべてに ping を実行できることを確認します。


. イニシエータとターゲットの間に iSCSI セッションを確立します（合計 4 つ）。
+
.. ifaceを使用する場合は、iSCSI ifaceバインドを2つ作成してiSCSIインターフェイスを設定します。
+
[listing]
----
# iscsiadm -m iface -I iface0 -o new
# iscsiadm -m iface -I iface0 -o update -n iface.net_ifacename -v <NIC port1>
----
+
[listing]
----
# iscsiadm -m iface -I iface1 -o new
# iscsiadm -m iface -I iface1 -o update -n iface.net_ifacename -v <NIC port2>
----
+

NOTE: インタフェースを一覧表示するには 'iscsiadm -m iface を使用します

.. iSCSI ターゲットを検出します。次の手順のために、 IQN （各検出で同じ）をワークシートに保存します。
+
[listing]
----
# iscsiadm -m discovery -t sendtargets -p 192.168.0.1:3260 -I iface0 -P 1
----
+
または

+
[listing]
----
# iscsiadm -m discovery -t sendtargets -p 192.168.0.1:3260
----
+

NOTE: IQN は次のような形式です。

+
[listing]
----
iqn.1992-01.com.netapp:2365.60080e50001bf1600000000531d7be3
----
.. iSCSIイニシエータとiSCSIターゲット間の接続を作成します。
+
[listing]
----
# iscsiadm -m node -T iqn.1992-01.com.netapp:2365.60080e50001bf1600000000531d7be3
-p 192.168.0.1:3260 -I iface0 -l
----
+
または

+
[listing]
----
# iscsiadm -m node -L all
----
.. ホストで確立されている iSCSI セッションの一覧を表示します。
+
[listing]
----
# iscsiadm -m session
----



