---
permalink: config-linux/iser-ib-configure-multipath-software-task.html 
sidebar: sidebar 
keywords: multipath software for Linux, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: マルチパスソフトウェアを設定します。これにより、物理パスの 1 つが中断された場合にストレージアレイへのパスが冗長化されます。 
---
= Eシリーズ- Linuxでのマルチパスソフトウェアの設定（iSER over InfiniBand）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイへのパスを冗長化するには、マルチパスソフトウェアを設定します。

.作業を開始する前に
必要なパッケージをシステムにインストールする必要があります。

* Red Hat （ RHEL ）ホストの場合、パッケージがインストールされていることを確認するには、「 rpm -q device-mapper-multipath 」を実行します。
* SLES ホストの場合 'rpm -q multipath-tools' を実行してパッケージがインストールされていることを確認します


オペレーティングシステムがまだインストールされていない場合は、オペレーティングシステムのベンダーから提供されたメディアを使用してください。

.このタスクについて
マルチパスソフトウェアは、物理パスの 1 つが中断された場合に備えて、ストレージアレイへのパスを冗長化します。マルチパスソフトウェアは、ストレージへのアクティブな物理パスを 1 つの仮想デバイスとしてオペレーティングシステムに提示します。また、フェイルオーバープロセスも管理して仮想デバイスを更新します。

Linux 環境では、 Device Mapper Multipath （ DM-MP ）ツールを使用します。RHEL および SLES では、デフォルトでは DM-MP は無効になっています。ホストで DM-MP コンポーネントを有効にするには、次の手順を実行します。

.手順
. multipath.conf ファイルがまだ作成されていない場合は、「 # touch /etc/multipath.conf 」コマンドを実行します。
. multipath.conf ファイルを空白のままにして、デフォルトのマルチパス設定を使用します。
. マルチパスサービスを開始します。
+
[listing]
----
# systemctl start multipathd
----
. uname -r コマンドを実行して ' カーネル・バージョンを保存します
+
[listing]
----
# uname -r
3.10.0-327.el7.x86_64
----
+
この情報は、ホストにボリュームを割り当てるときに使用します。

. multipathdデーモンをブート時に有効にします。
+
[listing]
----
systemctl enable multipathd
----
. initramfs イメージまたは initrd イメージを /boot ディレクトリに再構築します
+
[listing]
----
dracut --force --add multipath
----
. ブート構成ファイルで、新しく作成した /boot/initrams-* イメージまたは /boot/initrd-* イメージが選択されていることを確認します。
+
たとえば 'grub の場合は '/boot/grub/menu.lst' で 'grub2 の場合は '/boot/grub2/menu.cfg です

. を使用します https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-host-manually.html["ホストを手動で作成する"] ホストが定義されているかどうかを確認するには、オンラインヘルプの手順 を参照してください。各ホストタイプの設定が、で収集したカーネル情報に基づいていることを確認します <<step4,手順4.>>。
+

NOTE: 自動ロードバランシングは、カーネル3.9以前を実行しているホストにマップされているボリュームでは無効になります。

. ホストをリブートします。

