---
permalink: config-linux/nvme-ib-access-physical-targets-concept.html 
sidebar: sidebar 
keywords: NVMe volume physical, SLES 15, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 使用している SLES のバージョンに基づいて、デバイスターゲットに転送される I/O を設定できます（ SUSE Linux バージョン \ ）。 
---
= 物理 NVMe デバイスターゲットの NVMe ボリュームにアクセスします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用している OS （および拡張マルチパス方式）に基づいて、デバイスターゲットに転送される I/O を設定できます。

RHEL 8、RHEL 9、SLES 15の場合、I/OはLinuxホストによって物理NVMeデバイスターゲットに転送されます。ホストにはこのターゲットが単一の物理デバイスとして表示され、その物理パスはネイティブの NVMe マルチパス解決策で管理されます。



== 物理 NVMe デバイスは I/O ターゲットです

のリンクへのI/Oを実行することを推奨します `/dev/disk/by-id/nvme-eui.[uuid#]` 物理NVMeデバイスのパスに直接接続するのではなく `/dev/nvme[subsys#]n[id#]`。これら2つの場所間のリンクは、次のコマンドを使用して確認できます。

[listing]
----
# ls /dev/disk/by-id/ -l
lrwxrwxrwx 1 root root 13 Oct 18 15:14 nvme-eui.0000320f5cad32cf00a0980000af4112 -> ../../nvme0n1
----
I/Oはに実行されます `/dev/disk/by-id/nvme-eui.[uuid#]` 直接渡されます `/dev/nvme[subsys#]n[id#]` このコンテナでは、ネイティブのNVMeマルチパス解決策 を使用して、その下にすべてのパスが仮想化されてい

パスを表示するには、次のコマンドを実行します。

[listing]
----
# nvme list-subsys
----
出力例：

[listing]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:5700.600a098000a522500000000589aa8a6
\
+- nvme0 rdma traddr=192.4.21.131 trsvcid=4420 live
+- nvme1 rdma traddr=192.4.22.141 trsvcid=4420 live
----
「nvme list-subsys」コマンドに物理NVMeデバイスを指定すると、そのネームスペースへのパスに関する追加情報 が提供されます。

[listing]
----
# nvme list-subsys /dev/nvme0n1
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:5700.600a098000af44620000000058d5dd96
\
 +- nvme0 rdma traddr=192.168.130.101 trsvcid=4420 live non-optimized
 +- nvme1 rdma traddr=192.168.131.101 trsvcid=4420 live non-optimized
 +- nvme2 rdma traddr=192.168.130.102 trsvcid=4420 live optimized
 +- nvme3 rdma traddr=192.168.131.102 trsvcid=4420 live optimized
----
また、 multipath コマンドを使用して、ネイティブフェイルオーバーのパス情報も表示できます。

[listing]
----
#multipath -ll
----

NOTE: パス情報を表示するには、 /etc/multipath.conf で次のように設定する必要があります。

[listing]
----

defaults {
        enable_foreign nvme
}
----
出力例：

[listing]
----
eui.0000a0335c05d57a00a0980000a5229d [nvme]:nvme0n9 NVMe,Netapp E-Series,08520001
size=4194304 features='n/a' hwhandler='ANA' wp=rw
|-+- policy='n/a' prio=50 status=optimized
| `- 0:0:1 nvme0c0n1 0:0 n/a optimized    live
`-+- policy='n/a' prio-10 status=non-optimized
`- 0:1:1 nvme0c1n1 0:0 n/a non-optimized    live
----