---
permalink: config-linux/nvme-ib-define-host-task.html 
sidebar: sidebar 
keywords: define Linux host, express linux configuration, linux host, 
summary: SANtricity System Manager を使用して、ストレージアレイにデータを送信するホストを定義します。ホストの定義は、ストレージアレイが接続されているホストを認識して、ボリュームへの I/O アクセスを許可するために必要な手順の 1 つです。 
---
= ホストを定義します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager を使用して、ストレージアレイにデータを送信するホストを定義します。ホストの定義は、ストレージアレイが接続されているホストを認識して、ボリュームへの I/O アクセスを許可するために必要な手順の 1 つです。

ホストを定義する際は、次のガイドラインに注意してください。

* ホストに関連付けられたホストポート識別子を定義する必要があります。
* ホストに割り当てられたシステム名と同じ名前を指定してください。
* 選択した名前がすでに使用されている場合、この処理は失敗します。
* 名前は 30 文字以内にする必要があります。


.手順
. メニューから「 Storage [Hosts] 」を選択します。
. メニュー： Create [Host] をクリックします。
+
Create Host （ホストの作成）ダイアログボックスが表示されます。

. ホストの設定を必要に応じて選択します。
+
|===
| 設定 | 説明 


 a| 
名前
 a| 
新しいホストの名前を入力します。



 a| 
ホストオペレーティングシステムのタイプ
 a| 
ドロップダウンリストから次のいずれかのオプションを選択します。

** * Linux * SANtricity 11.60 以降
** * Linux DM-MP （カーネル 3.10 以降） * SANtricity 11.60 より前のバージョンで使用します




 a| 
ホストインターフェイスタイプ
 a| 
使用するホストインターフェイスタイプを選択します。



 a| 
ホストポート
 a| 
次のいずれかを実行します。

** * I/O インターフェイス * を選択します
+
ホストポートがログインしている場合は、リストからホストポート識別子を選択できます。これが推奨される方法です。

** * 手動で追加 *
+
ホストポートがログインしていない場合は、ホストの /etc/nvme/hostnqn を参照して hostnqn 識別子を確認し、ホスト定義に関連付けます。

+
ホストポート識別子を手動で入力するか、 /etc/nvme/hostnqn ファイル（一度に 1 つ）から * Host Ports * フィールドにコピー / 貼り付けてください。

+
ホストポート識別子は一度に 1 つずつ追加してホストに関連付ける必要がありますが、ホストに関連付けられている識別子をいくつでも選択することができます。各識別子は、 ［ * ホストポート * ］ フィールドに表示されます。必要に応じて、横の * X * を選択して識別子を削除することもできます。



|===
. [ 作成（ Create ） ] をクリックします。


ホストの作成が完了すると、 SANtricity System Manager によって、ホストに対して設定された各ホストポートのデフォルト名が作成されます。

デフォルトのエイリアスは「 <Hostname_Port number>` 」です。たとえば、「ホスト IPT 」用に作成される最初のポートのデフォルトのエイリアスは、 ipt_1 です。
