---
permalink: config-linux/nvme-roce-configure-switch-task.html 
sidebar: sidebar 
keywords: configure switch, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: NVMe over RoCE に関するベンダーの推奨事項に従ってスイッチを設定します。これらの推奨事項には、設定の指示とコードの更新が含まれる場合があります。 
---
= Eシリーズでスイッチを設定 - Linux（NVMe over RoCE）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe over RoCE に関するベンダーの推奨事項に従ってスイッチを設定します。これらの推奨事項には、設定の指示とコードの更新が含まれる場合があります。


CAUTION: *データ損失のリスクがあります。*NVMe/RoCEは、データ損失のない環境で実行する必要があります。ネットワーク上でグローバルポーズフレームベースのフロー制御またはプライオリティフロー制御（PFC）を使用してエンドツーエンドのフロー制御を有効にすることで、データ損失のリスクを排除できます。



== グローバル一時停止フレーム

グローバルポーズフレームは、フロー制御の最も基本的な形式であり、最も簡単に実装できます。トラフィックがネットワークポートに過負荷をかけると、ポーズフレームが生成され、そのポート上のすべてのトラフィックが停止します。これは、ネットワークポートが受信トラフィックをドロップすることなく処理を継続できるように、以前のトラフィックが十分に処理されるまで続きます。

.手順
. スイッチベンダーが提供するドキュメントを使用して、グローバルポーズフレームベースのフロー制御を*エンドツーエンド*で有効にします。
. この環境において、ホスト、アレイ、およびスイッチ間リンクに接続されているすべてのスイッチポートで、グローバルポーズフレームベースのフロー制御が有効になっていることを確認してください。




== 優先フロー制御

優先フロー制御（PFC）は、さまざまなタイプのトラフィックにさまざまな優先度レベルを割り当てる、より複雑な形式のフロー制御です。1つの優先度で過剰なトラフィックを受信すると、そのトラフィックは一時停止され、他の優先度レベルに対応するトラフィックは継続して処理されます。これにより、特定のタイプの大量のトラフィックが他の形式のトラフィックの速度を低下させることを防ぐことができます。

現時点では、11.80.1を実行している200Gb/s Ethernet HIC（PN 111-04583）を搭載したEF600 Eシリーズアレイ、またはサポートされている任意のNVMe/RoCE HICを搭載して実行しているEF80 Eシリーズアレイのいずれかを使用している必要があります。PFCパラメータはアレイにハードコードされており、NVMe/RoCEトラフィックをDSCP値 `106`で優先度3としてタグ付けする必要があります。

.手順
. PFC値を使用してネットワークを設定する方法の詳細については、スイッチベンダーのマニュアルを参照してください。
. 環境に最適な構成を選択するには、ネットワーク管理者に相談してください。


.次の手順
スイッチを設定したら、link:nvme-roce-setup-host-side-task.html["ホスト上でRoCE経由でNVMeイニシエータをセットアップする"]。
