---
permalink: config-linux/nvme-roce-setup-host-side-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: RoCE 環境で NVMe イニシエータを設定するには、 rdma-core および nvme-CLI パッケージをインストールして設定し、イニシエータの IP アドレスを設定し、ホストで NVMe-oF レイヤを設定します。 
---
= Eシリーズ- LinuxのホストでのRoCE経由のNVMeイニシエータの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RoCE 環境で NVMe イニシエータを設定するには、 rdma-core および nvme-CLI パッケージをインストールして設定し、イニシエータの IP アドレスを設定し、ホストで NVMe-oF レイヤを設定します。

.作業を開始する前に
最新の互換性のあるRHEL 9、RHEL 10、SLES 15、またはSLES 16サービスパックオペレーティングシステムを実行している必要があります。最新の要件の完全なリストについては、 https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]を参照してください。

.手順
. RDMA パッケージと nvme-CLI パッケージをインストールします。
+
*SLES 15またはSLES 16*

+
[listing]
----

# zypper install rdma-core
# zypper install nvme-cli
----
+
* RHEL 9 および RHEL 10 *

+
[listing]
----

# yum install rdma-core
# yum install nvme-cli
----



NOTE: NVIDIA HCA を使用していて、外部 DOCA ドライバーを使用したい場合は、link:https://developer.nvidia.com/doca-downloads["NVIDIA DOCAドキュメント"]この環境に適切にインストールする方法については、こちらをご覧ください。

. RHEL 9 の場合、ネットワークスクリプトをインストールします：
+
* RHEL 9*

+
[listing]
----
# yum install NetworkManager-initscripts-updown
----
+

NOTE: RHEL 10 ではネットワークスクリプトは利用できません。

. ホストのNQNを取得します。アレイに対してホストを設定する際に使用します。
+
[listing]
----
# cat /etc/nvme/hostnqn
----
. NVMe over RoCE の接続に使用されるイーサネットポートで、 IPv4 の IP アドレスを設定します。ネットワークインターフェイスごとに、そのインターフェイスに対応する変数を含む構成スクリプトを作成します。
+
この手順で使用する変数は、サーバハードウェアとネットワーク環境に基づいています。変数には 'IPADDR' と 'gateway' が含まれます次に、 SLES および RHEL の例を示します。

+
*SLES 15*

+
次の内容でサンプルファイルを作成します `/etc/sysconfig/network/ifcfg-eth4`。MTUはパケットの断片化を起こさずに達成できる最大値（通常は9000）に設定されます。

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.1.87/24'
GATEWAY='192.168.1.1'
MTU=9000
NAME='MT27800 Family [ConnectX-5]'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
次に'/etc/sysconfig/network/ifcfg-eth5`のサンプルファイルを作成します

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.2.87/24'
GATEWAY='192.168.2.1'
MTU=9000
NAME='MT27800 Family [ConnectX-5]'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
*RHEL 9、RHEL 10、またはSLES 16*

+
を使用します `nmtui` 接続を活動化および編集するためのツール。以下はサンプルファイルです `/etc/NetworkManager/system-connections/eth4.nmconnection` ツールは次のものを生成します。

+
[listing]
----

[connection]
id=eth4
uuid=<unique uuid>
type=ethernet
interface-name=eth4

[ethernet]
mtu=9000

[ipv4]
address1=192.168.1.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
+
以下はサンプルファイルです `/etc/NetworkManager/system-connections/eth5.nmconnection` ツールは次のものを生成します。

+
[listing]
----

[connection]
id=eth5
uuid=<unique uuid>
type=ethernet
interface-name=eth5

[ethernet]
mtu=9000

[ipv4]
address1=192.168.2.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
. ネットワークインターフェイスを有効にします。
+
[listing]
----

# nmcli connection up eth4
# nmcli connection up eth5
----
. ホストで NVMe-oF レイヤを設定します。次のファイルを `/etc/modules-load.d/` をロードするには `nvme_rdma` カーネルモジュールと、再起動後もカーネルモジュールが常にオンになっていることを確認します。
+
[listing]
----

# cat /etc/modules-load.d/nvme_rdma.conf
  nvme_rdma
----
. ホストをリブートします。
+
.. または、次のコマンドを実行して、再起動せずに `nvme_rdma`カーネルをロードできます：
+
[listing]
----

# modeprobe nvme_rdma
----


.  `nvme_rdma`カーネルモジュールがロードされていることを確認するには、次のコマンドを実行します。
+
[listing]
----
# lsmod | grep nvme
nvme_rdma              36864  0
nvme_fabrics           24576  1 nvme_rdma
nvme_core             114688  5 nvme_rdma,nvme_fabrics
rdma_cm               114688  7 rpcrdma,ib_srpt,ib_srp,nvme_rdma,ib_iser,ib_isert,rdma_ucm
ib_core               393216  15 rdma_cm,ib_ipoib,rpcrdma,ib_srpt,ib_srp,nvme_rdma,iw_cm,ib_iser,ib_umad,ib_isert,rdma_ucm,ib_uverbs,mlx5_ib,qedr,ib_cm
t10_pi                 16384  2 sd_mod,nvme_core
----
+
.次の手順
ホスト上でRoCE経由でNVMeイニシエータを設定した後、link:nvme-roce-configure-storage-connections-task.html["NVMe over RoCEポートの設定を構成します"]。


