---
permalink: config-linux/nvme-ib-access-sam-setup-wizard-task.html 
sidebar: sidebar 
keywords: access System Manager Linux, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: SANtricity System Manager のセットアップウィザードを使用して、ストレージアレイを設定します。 
---
= SANtricity System Managerを使用したストレージの設定- Linux（NVMe over InfiniBand）
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイを設定するには、 SANtricity System Manager のセットアップウィザードを使用します。

SANtricity System Manager は、各コントローラに組み込まれている Web ベースのインターフェイスです。ユーザーインターフェイスにアクセスするには、ブラウザでコントローラの IP アドレスを指定します。セットアップウィザードを使用してシステムを設定できます。

.作業を開始する前に
次のものがあることを確認します。

* アウトオブバンド管理：
* 次のいずれかのブラウザを使用して SANtricity System Manager にアクセスするための管理ステーション。
+
|===
| ブラウザ | 最小バージョン 


 a| 
Google Chrome
 a| 
八九



 a| 
Microsoft Edge の場合
 a| 
90



 a| 
Mozilla Firefox
 a| 
8時80分



 a| 
Safari
 a| 
14

|===


.このタスクについて
ウィザードは、 System Manager を開くかブラウザを更新したときに、次の条件の少なくとも 1 つに該当していれば自動的に再度起動されます。

* プールとボリュームグループが検出されていません。
* ワークロードが検出されていません。
* 通知が設定されていません。


.手順
. ブラウザで、「 + https://<DomainNameOrIPAddress>+` 」という URL を入力します
+
「 IPAddress 」は、ストレージアレイコントローラの 1 つのアドレスです。

+
設定されていないアレイで初めて SANtricity システムマネージャを開くと、管理者パスワードの設定プロンプトが表示されます。ロールベースアクセス管理では、 admin 、 support 、 security 、 monitor の 4 つのローカルロールが設定されます。最後の 3 つのロールには、推測されにくいランダムなパスワードが設定されています。admin ロールのパスワードを設定したら、 admin クレデンシャルを使用してすべてのパスワードを変更できます。4 つのローカルユーザロールの詳細については、 SANtricity System Manager ユーザインターフェイスのオンラインヘルプを参照してください。

. 管理者パスワードの設定フィールドとパスワードの確認フィールドに管理者ロールの System Manager パスワードを入力し、 * パスワードの設定 * をクリックします。
+
プール、ボリュームグループ、ワークロード、または通知が設定されていない場合は、セットアップウィザードが起動します。

. セットアップウィザードを使用して、次のタスクを実行します。
+
** * ハードウェア（コントローラとドライブ）の確認 * -- ストレージアレイ内のコントローラとドライブの数を確認しますアレイに名前を割り当てます。
** * ホストとオペレーティング・システムの確認 * -- ストレージ・アレイがアクセスできるホストとオペレーティング・システムの種類を確認します
** *Accept pools * -- 高速インストール方法の推奨されるプール構成を受け入れますプールはドライブの論理グループです。
** * アラートの設定 * -- ストレージアレイで問題が発生した場合に、 System Manager が自動通知を受信できるようにします。
** * AutoSupport を有効にする * -- ストレージアレイの状態を自動的に監視し、テクニカルサポートにディスパッチを送信します。


. ボリュームをまだ作成していない場合は、メニューからストレージ [ ボリューム ] 、 [ 作成 ] 、 [ ボリューム ] の順に選択してボリュームを作成します。
+
詳細については、 SANtricity System Manager のオンラインヘルプを参照してください。


