---
permalink: config-linux/nvme-fc-verify-linux-config-support-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 安定した稼働を確保するために、導入計画を作成し、 NetApp Interoperability Matrix Tool （ IMT ）を使用して構成全体がサポートされることを確認します。 
---
= Linux構成のサポート状況を確認し、Eシリーズ（NVMe over FC）の制限事項を確認する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
最初の手順として、 Linux 構成がサポートされていることを確認し、コントローラ、ホスト、およびリカバリの制限事項を確認する必要があります。



== Linux 構成がサポートされていることを確認する

安定した稼働を確保するために、導入計画を作成し、 NetApp Interoperability Matrix Tool （ IMT ）を使用して構成全体がサポートされることを確認します。

.手順
. にアクセスします https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]。
. [ 検索（解決策 Search ） ] タイルをクリックします。
. [Protocols [SAN Host] （プロトコル [SAN ホスト ] ）領域で、 * E シリーズ SAN ホスト * の横の * 追加ボタンをクリックします。
. ［ * 検索条件の絞り込み検索の表示 * ］ をクリックします。
+
[ 検索条件の絞り込み ] セクションが表示されます。このセクションでは、適用するプロトコル、およびオペレーティングシステム、ネットアップ OS 、ホストマルチパスドライバなど、構成のその他の条件を選択できます。

. 構成に必要な条件を選択し、互換性のある構成要素を確認します。
. 必要に応じて、使用するオペレーティングシステムとプロトコルに対して IMT に記載された更新を実行します。
+
選択した構成の詳細情報には、右ページ矢印をクリックして、 [View Supported Configurations] ページからアクセスできます。





== NVMe over FC の制限事項を確認します

NVMe over Fibre Channelを使用する前に、を参照してください https://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^] をクリックして、コントローラ、ホスト、およびリカバリの最新の制限事項を確認してください。



=== ストレージとディザスタリカバリの制限事項

* 非同期ミラーリングと同期ミラーリングはサポートされません。
* シンプロビジョニング（シンボリュームの作成）はサポートされていません。

