---
permalink: config-linux/nvme-fc-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: ホストでフェイルオーバーを実行するように設定します。 
---
= EシリーズLinuxのホストでのフェイルオーバーの設定（NVMe over FC）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイへのパスを冗長化するには、フェイルオーバーを実行するようにホストを設定します。

.作業を開始する前に
必要なパッケージをシステムにインストールする必要があります。

* Red Hat （ RHEL ）ホストの場合、パッケージがインストールされていることを確認するには、「 rpm -q device-mapper-multipath 」を実行します
* SLES ホストの場合 'rpm -q multipath-tools' を実行してパッケージがインストールされていることを確認します


 SLES 12 use Device Mapper Multipath (DMMP) for multipathing when using NVMe over Fibre Channel. RHEL 8, RHEL 9, and SLES 15 use a built-in Native NVMe Failover. Depending on which OS you are running, some additional configuration of multipath is required to get it running properly.


== SLES12のデバイスマッパーマルチパス(DMMP)の有効化

デフォルトでは、SLESのDM-MPは無効になっています。以下の手順で、ホスト上でDM-MPコンポーネントを有効にします。

.手順
. /etc/multipath.conf ファイルの devices セクションに、 NVMe E シリーズデバイスのエントリを次のように追加します。
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. システム起動時に起動するように「マルチパス」を設定します。
+
[listing]
----
# systemctl enable multipathd
----
. 現在実行されていない場合は、「マルチパス」を開始します。
+
[listing]
----
# systemctl start multipathd
----
. 「マルチパス」のステータスを確認して、アクティブで実行中であることを確認します。
+
[listing]
----
# systemctl status multipathd
----




== RHEL 8用のネイティブのNVMeマルチパスを設定します

.このタスクについて
ネイティブの NVMe マルチパスは、 RHEL 8 ではデフォルトで無効になっており、以下の手順で有効にする必要があります。

.手順
. ネイティブの NVMe マルチパスをオンにする「 m odprobe 」ルールを設定します。
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. 新しい modprobe パラメータを使用して 'initramfs' を再作成します
+
[listing]
----
# dracut -f
----
. サーバをリブートして、ネイティブの NVMe マルチパスを有効にします
+
[listing]
----
# reboot
----
. ホストのブート後にネイティブの NVMe マルチパスが有効になっていることを確認します。
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. コマンド出力が「 N 」の場合、ネイティブ NVMe マルチパスは無効のままです。
.. コマンド出力が「 Y 」の場合は、ネイティブ NVMe マルチパスが有効になり、検出した NVMe デバイスでこのコマンドが使用されます。





NOTE: RHEL 9およびSLES 15では、ネイティブのNVMeマルチパスはデフォルトで有効になっており、追加の設定は必要ありません。
