---
permalink: maintenance-e2800/batteries-overview-requirements-concept.html 
sidebar: sidebar 
keywords: E2800 battery fail, E2800 battery, E2800 battery replacement, replace E2800 battery, replacing E2800 battery, E2800, E-Series, eseries 
summary: E2800 バッテリの交換に関する要件と考慮事項を確認します。 
---
= E2800 バッテリの交換に際しての要件
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E2800 バッテリを交換する前に、要件と考慮事項を確認してください。

各コントローラキャニスターには、 AC 電源で障害が発生した場合にキャッシュデータを保持するバッテリが搭載されています。



== Recovery Guru のアラート

SANtricity System Manager の Recovery Guru から次のいずれかのステータスが報告された場合は、該当するバッテリを交換する必要があります。

* バッテリで障害が発生しまし
* バッテリの交換が必要です


SANtricity System Manager の Recovery Guru で詳細を確認し、問題にバッテリが搭載されていること、および先に対処する必要がある項目がほかにないことを確認します。



== 手順の概要

データを保護するために、障害が発生したバッテリはできるだけ早く交換する必要があります。

E2800 コントローラのバッテリを交換するために必要な手順の概要を次に示します。

. デュプレックス構成またはシンプレックス構成の該当する手順に従って、交換を準備します。
. コントローラキャニスターを取り外します。
. 障害が発生したバッテリを取り外します。
. 新しいバッテリを取り付けます。
. コントローラキャニスターを再度取り付けます。
. デュプレックス構成またはシンプレックス構成の該当する手順に従って交換を完了します。




== デュプレックス構成とシンプレックス構成です

バッテリを交換する手順は、コントローラの数が 1 台か 2 台かによって次のように異なります。

|===
| ストレージアレイのコントローラの数 | 実行する手順 


 a| 
2 台（デュプレックス）
 a| 
. コントローラをオフラインにします。
. コントローラキャニスターを取り外します。
. バッテリを交換します。
. コントローラキャニスターを交換します。
. コントローラをオンラインにします。




 a| 
1 台（シンプレックス）
 a| 
. ホスト I/O 処理を停止します。
. コントローラシェルフの電源をオフにします。
. コントローラキャニスターを取り外します。
. バッテリを交換します。
. コントローラキャニスターを交換します。
. コントローラシェルフに電源を投入します。


|===


== バッテリの交換に際しての要件

障害が発生したバッテリを交換する場合は、次の準備をしておく必要があります。

* 交換用バッテリ。
* ESD リストバンドを装着するか、静電気防止処置を施しておきます。
* コントローラキャニスターに接続する各ケーブルを識別するためのラベル。
* コントローラの SANtricity System Manager にアクセスできるブラウザを備えた管理ステーション。（ System Manager インターフェイスを開くには、ブラウザでコントローラのドメイン名または IP アドレスを指定します）。

