---
permalink: maintenance-e2800/batteries-prepare-replace-task.html 
sidebar: sidebar 
keywords: E2800 battery fail, E2800 battery, E2800 battery replacement, replace E2800 battery, replacing E2800 battery, E2800, E-Series, eseries 
summary: デュプレックスとシンプレックスのそれぞれに該当する手順に従って、 E2800 バッテリを交換する準備をします。 
---
= E2800 バッテリを交換する準備をします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バッテリ交換準備の手順は、デュプレックス構成（コントローラが 2 台）とシンプレックス構成（コントローラが 1 台）で異なります。

* デュプレックス構成については、を参照してください <<コントローラをオフラインにする（デュプレックス）>>。
* シンプレックス構成の場合は、を参照してください <<コントローラシェルフの電源をオフにする（シンプレックス）>>。


.作業を開始する前に
* 使用中のボリュームがないこと、またはボリュームを使用しているすべてのホストにマルチパスドライバがインストールされていることを確認します。
* を確認します link:batteries-overview-requirements-concept.html["E2800 バッテリの交換に際しての要件"]。




== コントローラをオフラインにする（デュプレックス）

デュプレックス構成の場合、障害が発生したバッテリを安全に取り外せるように、該当するコントローラをオフラインにする必要があります。オフラインに切り替えないコントローラはオンライン（最適状態）である必要があります。


NOTE: このタスクは、コントローラが 2 台のストレージアレイ（デュプレックス構成）でのみ実行します。

.手順
. SANtricity System Manager の Recovery Guru で詳細を確認し、問題にバッテリが搭載されていること、および先に対処する必要がある項目がほかにないことを確認します。
. Recovery Guru の詳細領域で、交換するバッテリを特定します。
. SANtricity システムマネージャを使用して、ストレージアレイの構成データベースをバックアップします。
+
コントローラを取り外すときに問題が発生した場合は、保存したファイルを使用して構成をリストアできます。RAID 構成データベースの現在の状態が保存されます。これには、コントローラ上のボリュームグループとディスクプールのすべてのデータが含まれます。

+
** System Manager から：
+
... メニューを選択します。 Support [ Support Center > Diagnostics ] （サポートセンター > 診断）。
... [ 構成データの収集 *] を選択します。
... [*Collect*]( 収集 ) をクリックします
+
ブラウザの Downloads フォルダに、「 * configurationdata-<ArrayName>-<dateTime >.7z * 」という名前でファイルが保存されます。



** または、次の CLI コマンドを使用して構成データベースをバックアップすることもできます。
+
'ave storageArray dbmDatabase sourceLocation=onboard contentType=all file="filename";`



. SANtricity システムマネージャを使用してストレージアレイのサポートデータを収集します。
+
コントローラの取り外し時に問題が発生した場合は、保存したファイルを使用して問題のトラブルシューティングを行うことができます。ストレージアレイに関するインベントリ、ステータス、およびパフォーマンスデータが 1 つのファイルに保存されます。

+
.. メニューを選択します。 Support [ Support Center > Diagnostics ] （サポートセンター > 診断）。
.. 「サポートデータの収集」を選択します。
.. [*Collect*]( 収集 ) をクリックします
+
ブラウザの Downloads フォルダに、「 * support-data.7z * 」という名前でファイルが保存されます。



. コントローラがオフラインでない場合は、 SANtricity System Manager を使用してオフラインにします。
+
** SANtricity システムマネージャで次の作業を行います。
+
... 「 * ハードウェア * 」を選択します。
... 図にドライブが表示されている場合は、 * Show back of shelf * を選択してコントローラを表示します。
... オフラインに切り替えるコントローラを選択します。
... コンテキストメニューから * オフラインに切り替え * を選択し、操作を確定します。
+

NOTE: オフラインにするコントローラを使用して SANtricity System Manager にアクセスしている場合は、「 SANtricity System Manager を利用できません」というメッセージが表示されます。別のコントローラを使用して SANtricity System Manager に自動的にアクセスするには、 * 代替ネットワーク接続に接続する * を選択します。



** または、次の CLI コマンドを使用してコントローラをオフラインにすることもできます。
+
* コントローラ A ： * 'et controller [a] availability=offline

+
* コントローラ B の場合： * 'et controller [b] availability=offline



. SANtricity System Manager でコントローラのステータスがオフラインに更新されるまで待ちます。
. に進みます link:batteries-remove-controller-canister-task.html["E2800 コントローラキャニスターを取り外します"]。
+

CAUTION: ステータスの更新が完了するまでは、他の処理を開始しないでください。





== コントローラシェルフの電源をオフにする（シンプレックス）

シンプレックス構成の場合、障害が発生したバッテリを安全に取り外せるように、コントローラシェルフの電源をオフにする必要があります。


NOTE: このタスクは、コントローラが 1 台のストレージアレイ（シンプレックス構成）でのみ実行します。

.手順
. SANtricity システムマネージャを使用して、ストレージアレイの構成データベースをバックアップします。
+
コントローラを取り外すときに問題が発生した場合は、保存したファイルを使用して構成をリストアできます。RAID 構成データベースの現在の状態が保存されます。これには、コントローラ上のボリュームグループとディスクプールのすべてのデータが含まれます。

+
** System Manager から：
+
... メニューを選択します。 Support [ Support Center > Diagnostics ] （サポートセンター > 診断）。
... [ 構成データの収集 *] を選択します。
... [*Collect*]( 収集 ) をクリックします
+
ブラウザの Downloads フォルダに、「 * configurationdata-<ArrayName>-<dateTime >.7z * 」という名前でファイルが保存されます。



** または、次の CLI コマンドを使用して構成データベースをバックアップすることもできます。
+
'ave storageArray dbmDatabase sourceLocation=onboard contentType=all file="filename";`



. SANtricity システムマネージャを使用してストレージアレイのサポートデータを収集します。
+
コントローラの取り外し時に問題が発生した場合は、保存したファイルを使用して問題のトラブルシューティングを行うことができます。ストレージアレイに関するインベントリ、ステータス、およびパフォーマンスデータが 1 つのファイルに保存されます。

+
.. メニューを選択します。 Support [ Support Center > Diagnostics ] （サポートセンター > 診断）。
.. 「サポートデータの収集」を選択します。
.. [*Collect*]( 収集 ) をクリックします
+
ブラウザの Downloads フォルダに、「 * support-data.7z * 」という名前でファイルが保存されます。



. ストレージアレイと接続されているすべてのホストの間で I/O 処理が発生しないようにします。たとえば、次の手順を実行します。
+
.. ストレージからホストにマッピングされた LUN に関連するすべてのプロセスを停止します。
.. ストレージからホストにマッピングされた LUN にアプリケーションがデータを書き込んでいないことを確認します。
.. アレイのボリュームに関連付けられているファイルシステムをすべてアンマウントします。
+

NOTE: ホスト I/O 処理を停止する具体的な手順はホストオペレーティングシステムや構成によって異なり、ここでは説明していません。環境内でホスト I/O 処理を停止する方法がわからない場合は、ホストをシャットダウンすることを検討してください。

+

CAUTION: * データ損失の可能性 * - I/O 処理の実行中にこの手順を続行すると、データが失われる可能性があります。



. キャッシュメモリ内のデータがドライブに書き込まれるまで待ちます。
+
キャッシュされたデータをドライブに書き込む必要がある場合は、コントローラの背面にある緑のキャッシュアクティブ LED が点灯します。この LED が消灯するまで待つ必要があります。

. SANtricity システムマネージャのホームページで、「 * 進行中の処理を表示」を選択します。
. すべての処理が完了したことを確認してから、次の手順に進みます。
. コントローラシェルフの両方の電源スイッチをオフにします。
. コントローラシェルフのすべての LED が消灯するまで待ちます。
. に進みます link:batteries-remove-controller-canister-task.html["E2800 コントローラキャニスターを取り外します"]。

