---
permalink: maintenance-e2800/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: E2800 replace HIC, E2800 replace host interface card, replacing E2800 HIC, E2800 replace HIC, adding E2800 HIC, upgrading E2800 HIC, E2800, E-Series, eseries 
summary: E2800 HIC の交換に関する要件を確認します。 
---
= E2800 HIC の交換に際しての要件
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E2800 のホストインターフェイスカード（ HIC ）を追加、アップグレード、交換する前に、要件と考慮事項を確認してください。



== 手順の概要

HIC を交換する手順は、コントローラの数が 1 台か 2 台かによって次のように異なります。

|===
| ストレージアレイのコントローラの数 | 実行する手順 


 a| 
1 台（ E2812 または E2824 シンプレックス）
 a| 
. ホスト I/O 処理を停止します
. コントローラシェルフの電源をオフにします
. コントローラキャニスターを取り外します
. バッテリを交換します
. コントローラキャニスターを交換します
. コントローラシェルフに電源を投入します




 a| 
2 台のコントローラ（ E2860 、 E2812 または E2824 ）
 a| 
. コントローラをオフラインにします
. コントローラキャニスターを取り外します
. バッテリを交換します
. コントローラキャニスターを交換します
. コントローラをオンラインにします


|===


== HIC の追加、アップグレード、交換に際しての要件

ホストインターフェイスカード（ HIC ）を追加、アップグレード、交換するときは、次の要件に注意してください。

* この手順でダウンタイムのメンテナンス時間をスケジュールしておきます。HIC を取り付けるときは電源をオフにする必要があるため、この手順が完了するまではストレージアレイのデータにアクセスできません。（これは、電源をオンにしたときに HIC の構成が両方のコントローラで同じになっている必要があるため、デュプレックス構成にも当てはまります。）
* ストレージアレイにコントローラが 1 台あるか 2 台あるかに応じて、 1 つまたは 2 つの HIC を用意しておきます。コントローラと互換性がある HIC を使用する必要があります。
+
デュプレックス構成（コントローラが 2 台）の場合は、 2 つのコントローラキャニスターに同じ HIC を取り付ける必要があります。HIC が一致していないと、交換用 HIC を搭載したコントローラをオンラインにしたときにロックダウン状態になります。

* 新しいホストポートの接続に必要なすべてのケーブル、トランシーバ、スイッチ、ホストバスアダプタ（ HBA ）を用意しておきます。
+
互換性のあるハードウェアについては、を参照してください https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperability Matrix を参照してください"^] または http://hwu.netapp.com/home.aspx["NetApp Hardware Universe の略"^]。

* ESD リストバンドを装着するか、静電気防止処置を施しておきます。
* No.1 プラスドライバを用意しておきます。
* コントローラキャニスターに接続する各ケーブルを識別するためのラベルを用意しておきます。
* コントローラの SANtricity System Manager にアクセスするためのブラウザを備えた管理ステーションを用意しておきます。（ System Manager インターフェイスを開くには、ブラウザでコントローラのドメイン名または IP アドレスを指定します）。

