---
permalink: maintenance-e2800/index.html 
sidebar: sidebar 
keywords: E2800 maintenance, E2800 repair, replace E2800 components, replacing E2800 components, 
summary: E2800 コンポーネントのメンテナンスを実施する。 
---
= ハードウェアのメンテナンス- E2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアのメンテナンス手順が必要になる場合があります。ここでは、E2800システムコンポーネントのメンテナンスに固有の手順について説明します。

このセクションの手順は、E2800システムがEシリーズ環境にすでに導入されていることを前提としています。



== システムコンホオネント

E2800 ストレージシステムでは、次のコンポーネントのメンテナンス手順を実行できます。

[cols="25,65"]
|===


 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/batteries-overview-requirements-concept.html["電池"]
 a| 
各コントローラキャニスターには、 AC 電源で障害が発生した場合にキャッシュデータを保持するバッテリが搭載されています。



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/controllers-overview-supertask-concept.html["コントローラ"]
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 System Manager の機能を実装します。



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/canisters-overview-supertask-concept.html["キャニスター"]
 a| 
キャニスターは 3 つのタイプに分類されます。電源 / ファンキャニスター（電源装置）は冗長な電源を提供し、 12 ドライブまたは 24 ドライブのコントローラシェルフまたはドライブシェルフで適切な冷却を行います。電源キャニスターは、 60 ドライブのコントローラシェルフまたはドライブシェルフで電源の冗長性を確保するために使用されます。 および 60 ドライブのコントローラシェルフまたはドライブシェルフの冷却に使用されるファンキャニスター。



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/drives-overview-supertask-concept.html["ドライブ"]
 a| 
ドライブは、データの物理ストレージメディアとして使用される電磁的な機械デバイスです。



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/hics-overview-supertask-concept.html["ホストインターフェイスカード（ HIC ）"]
 a| 
ホストインターフェイスカード（ HIC ）は、コントローラキャニスターにオプションで取り付けることができます。E2800 コントローラには、コントローラカード自体に搭載されたホストポートとオプションの HIC に搭載されたホストポートがあります。コントローラに搭載されたホストポートのことをベースボードホストポートと呼び、HIC に搭載されたホストポートのことを HIC ポートと呼びます。



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e2800/hpp-overview-supertask-concept.html["ホストポートプロトコル"]
 a| 
互換性と通信の確立のために、ホストのプロトコルを別のプロトコルに変換することができます。

|===