---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: SANtricity OS の新機能 
---
= SANtricity OS の新機能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表は、SANtricity OS 11.7で、EF300、EF600、E2800 / EF280、およびE5700 / EF570コントローラの管理が組み込まれた新機能を示しています。



== バージョン11.75の新機能

システムを11.80.x以降にアップグレードするには、11.70.5が実行されている必要があります。



== バージョン11.74の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
FIPS 140-3をサポート
 a| 
SASベースとNVMeベースの両方のSSDについて、特定のドライブでFIPS 140-3がサポートされるようになりました。FIPS 140-3レベルのSSDドライブは、すべてNVMeベースまたはすべてSASベースのドライブであれば、FIPS 140-2レベルのSSDドライブと共存できます。これらのレベルをボリュームグループとディスクプールで組み合わせて使用する場合は、グループまたはプールが下位レベルのセキュリティ（140 - 2）で動作することに注意してください。



 a| 
MFAとSSHのサポート
 a| 
SANtricity バージョン11.74以降では、リモートログイン機能を使用して、SSHキーやSSHパスワードの入力をユーザに求めることで多要素認証（MFA）を設定できます。ハードウェアセクションのメニューオプションが*リモートログインの変更*から*リモートログインの設定（SSH）*に変更されました。



 a| 
アクセストークン
 a| 
このリリースには、アクセストークンを作成するための新機能が含まれています。これらのトークンを使用すると、ユーザ名やパスワードを公開することなく、REST APIまたはコマンドラインインターフェイス（CLI）で認証できます。この機能は、アクセス管理セクションで提供されています。

|===


== バージョン11.73の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
リソースプロビジョニングとDULBEのサポート
 a| 
このリリースでは'リソースプロビジョニング機能とDULBEドライブ機能が完全にサポートされるようになりましたこのサポートには、リソースでプロビジョニングされたボリュームでホストからのUNMAPをより幅広く使用できるようにすることも含まれています。



 a| 
EF600 SAS（512e）の拡張
 a| 
このリリースでは、EF600ストレージシステム用にSAS-3エンクロージャへの拡張がサポートされます。この拡張では、 4KiB ブロックの NVMe SSD と 512e SAS SSD および HDD を共存させることができます。ただし、ブロックサイズが異なるドライブは、同じプールまたはボリュームグループに設定することはできません。



 a| 
qlc SSDのサポート
 a| 
このリリースでは、現在の世代のQLC SSDで、ドライブファームウェアでONTAP 機能が設定されていますが、Eシリーズ固有の全機能セットはサポートされていません。qlcドライブ（NVMeのみ）は低コストですが、書き込みパフォーマンスは低く、耐久性は低く、書き込みの多いワークロードには使用しないでください。



 a| 
TLS 1.3のサポート
 a| 
TLS 1.3の組み込み管理機能がサポートされるようになりました。この機能は、環境 System Managerと組み込みのWebサービスを有効または無効にする機能によってサポートされます。（TLS 1.3のサポートは、Web Services ProxyとUnified Managerの以前のリリースで追加されています）。



 a| 
RAID 1 DDPは最低8ドライブ
 a| 
このリリースでは、プール内に少なくとも11本のSSDがRAID 1 DDPに必要ありません。この最小構成では、プールにRAID 1ボリュームしか作成されていない場合、8ドライブのSSDプールが許可されるようになりました。



 a| 
EKMSキーの削除
 a| 
ストレージ管理者は、古いキーを削除するために外部キー管理サーバ（EKMS）を要求できるようになりました。キーの削除は、設置されているドライブに新しいキーが追加されたあとのキーの再入力プロセスでのみ実行されます。

|===


== バージョン 11.72 の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
SNMPv3 のサポート
 a| 
SNMPv3がアラート通知にサポートされるようになりました。メニューで設定できます：[Settings][Alerts]。SNMPv3 は、強力な認証とデータ暗号化によってセキュリティを提供します。



 a| 
複数のキーサーバへのキーのレプリケートをサポートする
 a| 
自己暗号化ドライブの外部キー管理の場合、外部キー管理の作成ダイアログに複数のキーサーバを追加するための新しいオプションが追加されました。



 a| 
ブラウザのバージョンを更新
 a| 
System Manager のブラウザの最小バージョンが更新されました。

|===


== バージョン 11.71 の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
EF300 拡張
| このリリースでは、 EF300 ストレージシステムの SAS-3 エンクロージャへの拡張がサポートされます。この拡張では、 4KiB ブロックの NVMe SSD と 512e SAS SSD および HDD を共存させることができます。ただし、ブロックサイズが異なるドライブは、同じプールまたはボリュームグループに設定することはできません。 


 a| 
iSCSI 設定の fec モードオプション
 a| 
25GB iSCSI ホストインターフェイスカードを使用するストレージアレイでは、 iSCSI ポートを設定するときに前方誤り訂正（ FEC ）モードを設定するための新しいオプションが追加されました。



 a| 
リモートストレージボリューム
 a| 
オプションのリモートストレージボリューム機能を使用すると、 iSCSI 接続を使用してリモートストレージシステムからローカルの E シリーズストレージシステムにボリュームをインポートできます。リモートストレージには、 iSCSI でアクセス可能であれば、 E シリーズシステムと同じブランドを使用することも、別のストレージベンダーのストレージを使用することもできます。



 a| 
FDE 以外のドライブに追加された完全消去（消去）機能
 a| 
ドライブ完全消去機能に FDE 以外手順のドライブが含まれるようになりました。ハードウェアページからドライブのコンテキストメニューを開いて「消去」を選択できます（以前は「 Secure Erase 」でした）。



 a| 
E メールアラート用のセキュアな接続
 a| 
暗号化された E メール通知を有効にするために、必要に応じて送信 E メール（アラート、 ASUP ディスパッチ）で認証クレデンシャルを指定できます。暗号化タイプには SMTPS および STARTTLS があります。



 a| 
AutoSupport の追加
 a| 
AutoSupport が有効になっていない場合、通知領域にアラートが表示されるようになりました。



 a| 
syslog アラートの形式が変更されました
 a| 
syslog アラートの形式で RFC 5424 がサポートされるようになりました。

|===


== バージョン 11.70 の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
新しいストレージシステムモデル– EF300
 a| 
このリリースでは、低コストのオール NVMe フラッシュストレージシステム EF300 が導入されました。EF300 には、 NVMe SSD ドライブ × 24 、コントローラごとにホストインターフェイスカード（ HIC ） × 1 が搭載されています。サポートされる NVMe over Fabrics ホストインターフェイスには、 NVMe over IB 、 NVMe over RoCE 、 NVMe over FC があります。サポートされる SCSI インターフェイスには、 FC 、 IB over iSER 、 IB over SRP があります。複数の EF300 ストレージシステムやその他の E シリーズストレージシステムを Unified Manager で表示して管理することができます。



 a| 
新しいリソースプロビジョニング機能（ EF300 および EF600 のみ）
 a| 
リソースプロビジョニング機能は、 EF300 および EF600 ストレージシステムで新たに導入されました。バックグラウンドの初期化プロセスを実行せずに、リソースでプロビジョニングしたボリュームをすぐに使用できます。



 a| 
512e ブロックサイズの追加オプション（ EF300 および EF600 のみ）
 a| 
EF300 および EF600 ストレージシステムでは、ボリュームを設定して 512 バイトまたは 4KiB のブロックサイズをサポートすることができます。512e 機能が追加され、 iSCSI ホストインターフェイスと VMware OS がサポートされるようになりました。可能であれば、 System Manager から適切なデフォルト値が提示されます。



 a| 
AutoSupport ディスパッチをオンデマンドで送信するための新しいオプションです
 a| 
新しい Send AutoSupport Dispatch 機能を使用すると、スケジュールされたディスパッチを待たずにテクニカルサポートにデータを送信できます。このオプションは、サポートセンターの [ サポート（ AutoSupport ） ] タブで使用できます。



 a| 
外部キー管理サーバの機能拡張
 a| 
外部キー管理サーバに接続するための機能拡張は次のとおりです。

* バックアップ・キーを作成する機能を省略します。
* クライアント証明書とサーバ証明書に加えて、キー管理サーバの中間証明書を選択します。




 a| 
証明書の機能拡張
 a| 
このリリースでは、 OpenSSL などの外部ツールを使用して証明書署名要求（ CSR ）を生成できます。この場合、署名済み証明書とともに秘密鍵ファイルをインポートする必要があります。



 a| 
ボリュームグループの新しいオフライン初期化機能が追加されました
 a| 
ボリュームの作成については、 System Manager でホストの割り当て手順をスキップする方法を使用して、新しく作成したボリュームをオフラインにすることができます。この機能は、SASドライブ上のRAIDボリュームグループにのみ該当します（動的ディスクプールや、EF300およびEF600ストレージシステムに含まれるNVMe SSDには該当しません）。この機能は、バックグラウンドで初期化を実行するのではなく、使用量が開始された時点でボリュームをフルパフォーマンスにする必要があるワークロードに対して利用されます。



 a| 
構成データの収集機能が新しく追加されました
 a| 
この新機能は、ボリュームグループとディスクプールのすべてのデータを含む、コントローラからRAID構成データを保存します（「save storageArray dbmDatabase」のCLIコマンドと同じ情報）。この機能は、テクニカルサポートを支援するために追加され、サポートセンターの診断タブにあります。



 a| 
12 ドライブケースのディスクプールのデフォルトの予約済み容量を変更
 a| 
以前は、 2 本のドライブに対応できる十分な予約済み（スペア）容量を備えた 12 ドライブのディスクプールが作成されていました。単一ドライブ障害に対応するようにデフォルトが変更され、よりコスト効率の高い小規模プールのデフォルトが提供されるようになりました。

|===