---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: SANtricity OS の新機能 
---
= SANtricity OS の新機能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、EF300、EF600、E2800 / EF280、およびE5700 / EF570コントローラの組み込みの管理用にSANtricity OS 11.8の新機能を示します。



== バージョン11.80の新機能

[cols="35h,~"]
|===
| 新機能 | 説明 


 a| 
強化されたボリュームパリティスキャン
 a| 
REST APIまたはCLIを使用して、ボリュームパリティスキャンをバックグラウンドプロセスとして起動できるようになりました。パリティスキャンは、スキャン処理を完了するために必要な限りバックグラウンドで実行されます。スキャン処理は、コントローラのリブートおよびフェイルオーバー処理の間も維持されます。



 a| 
Unified ManagerでのSAMLのサポート
 a| 
Unified ManagerでSecurity Assertion Markup Language（SAML）がサポートされるようになりました。Unified ManagerでSAMLを有効にすると、ユーザインターフェイスを操作するために、アイデンティティプロバイダに対して多要素認証を使用する必要があります。Unified ManagerでSAMLを有効にすると、IdPを経由せずにREST APIを使用して要求を認証することはできません。



 a| 
自動構成機能
 a| 
アレイの初期セットアップ時に自動構成機能で使用するボリュームのブロックサイズパラメータを設定できるようになりました。この機能は、CLIでは「blocksize」パラメータとしてのみ使用できます。



 a| 
コントローラファームウェアの暗号化署名
 a| 
コントローラファームウェアは暗号署名されています。シグネチャは、初回ダウンロード時および各コントローラのブート時にチェックされます。エンドユーザへの影響はありません。署名は、CAによって発行された拡張検証証明書によって裏付けられます。



 a| 
ドライブファームウェアの暗号化署名
 a| 
ドライブファームウェアは暗号署名されています。署名は最初のダウンロード時にチェックされ、CAによって発行された拡張検証証明書によってバックアップされます。ドライブファームウェアの内容がZIPファイルとして提供されるようになりました。ZIPファイルには、署名済みの古いファームウェアと署名済みの新しいファームウェアが含まれています。ユーザーは、ターゲットシステムで実行されているコードのリリースバージョンに基づいて適切なファイルを選択する必要があります。



 a| 
外部キーサーバ管理-証明書のキーサイズ
 a| 
新しいデフォルトの証明書キーサイズは3072ビット（2048から）です。最大4096ビットのキーサイズがサポートされます。デフォルト以外のキーサイズをサポートするには、NVSRAMビットを変更する必要があります。



 a| 
ブロックサイズが512bのドライブを使用した、より大きなダイナミックディスクプールサイズのサポート
 a| 
バージョン1プールバージョンタイプを使用しているお客様は、最大48 TBのディスクプールを使用できるようになりました。古いバージョンでは、最大24TBのディスクプールサイズがサポートされます。既存のディスクプールをより大きなサイズに変換する場合は、最初にすべてのボリュームを削除する必要があります。バージョン1のディスクプールが存在する場合、ダウングレード操作は制限されます。



 a| 
System ManagerとUnified Managerは、ブラウザの最小要件を満たしていないと起動しません。
 a| 
System ManagerまたはUnified Managerを起動するには、少なくともバージョンのブラウザが必要です。サポートされる最小バージョンは次のとおりです。

* Firefoxの最小バージョン80
* Chrome最小バージョン89
* エッジ最小バージョン90
* Safariの最小バージョン14




 a| 
FIPS 140-3 NVMe SSDドライブのサポート
 a| 
NetApp認定のFIPS 140-3 NVMe SSDドライブがサポートされるようになりました。これらは、ストレージアレイプロファイルおよびSystem Managerで正しく識別されます。



 a| 
EF300およびEF600でのSSD読み取りキャッシュのサポート
 a| 
SAS拡張構成のHDDを使用するEF300およびEF600コントローラでSSD読み取りキャッシュがサポートされるようになりました。



 a| 
EF300およびEF600でのiSCSIとFibre Channelの非同期リモートミラーリングのサポート
 a| 
NVMeおよびSASベースのボリュームを使用するEF300およびEF600コントローラで非同期リモートミラーリング（ARVM）がサポートされるようになりました。



 a| 
ベーストレイにドライブを搭載しないEF300およびEF600をサポート
 a| 
ベーストレイにNVMeドライブを搭載しないEF300およびEF600コントローラ構成がサポートされるようになりました。



 a| 
すべてのプラットフォームでUSBポートが無効になっている
 a| 
すべてのプラットフォームでUSBポートが無効になりました。

|===