---
permalink: getting-started/learn-terms-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, terms 
summary: E シリーズで使用される用語について説明します。 
---
= E シリーズの用語
:icons: font
:imagesdir: ../media/


[role="lead"]
E シリーズで使用される用語について説明します。

|===
| 期間 | 説明 


 a| 
コントローラ
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、機能を実装します。



 a| 
デュプレックス / シンプレックス構成
 a| 
デュプレックスは、ストレージアレイ内に 2 台のコントローラモジュールを配置した構成です。シンプレックスは、コントローラモジュールを 1 つだけ配置した構成です。



 a| 
HDD
 a| 
ハードディスクドライブ（ HDD ）は、磁気コーティングを施した金属製の回転式ディスクを使用するデータストレージデバイスです。



 a| 
HIC
 a| 
ホストインターフェイスカード（ HIC ）は、アレイをホストに接続します。コントローラキャニスターにオプションで取り付けることもできます。



 a| 
IB
 a| 
InfiniBand （ IB ）は、ハイパフォーマンスのサーバとストレージシステムの間のデータ転送用の通信標準です。



 a| 
IOPS
 a| 
IOPS は、 1 秒あたりの入出力処理数です。



 a| 
ミラーリング
 a| 
ミラーリングは、継続的な可用性を確保するためにデータボリュームを別のストレージアレイにレプリケートする機能です。



 a| 
プール
 a| 
プールは、論理的にグループ化された一連のドライブです。プールを使用して、ホストにアクセス可能な 1 つ以上のボリュームを作成することができます。



 a| 
電源 / ファンキャニスター
 a| 
電源 / ファンキャニスターは、シェルフに搭載されるアセンブリです。電源装置と一体型ファンで構成されます。



 a| 
ラックユニット（ U ）
 a| 
1 ラックユニット（省略形は U ）は、 44.50mm （ 1.75 インチ）と定義されています。



 a| 
（ SAS ）。
 a| 
Serial Attached SCSI （ SAS ）は、コントローラをディスクドライブに直接リンクするポイントツーポイントのシリアルプロトコルです。



 a| 
RoCE
 a| 
RDMA over Converged Ethernet （ RoCE ）は、イーサネットネットワークを介したリモートダイレクトメモリアクセス（ RDMA ）を可能にするネットワークプロトコルです。



 a| 
シェルフ
 a| 
シェルフは、キャビネットまたはラックに設置されるエンクロージャです。ストレージアレイのハードウェアコンポーネントを収容します。シェルフには、コントローラシェルフとドライブシェルフの 2 種類があります。コントローラシェルフは、コントローラとドライブを収容します。ドライブシェルフは、入出力モジュール（ IOM ）とドライブを収容します。



 a| 
スナップショット
 a| 
Snapshot イメージは、ボリュームのデータを特定の時点でキャプチャした論理コピーです。リストアポイントと同様に、 Snapshot イメージを使用して既知の正常なデータセットにロールバックできます。



 a| 
SSD の場合
 a| 
ソリッドステートディスク（ SSD ）は、ソリッドステートメモリ（フラッシュ）を使用してデータを永続的に格納するデータストレージデバイスです。SSD は従来のハードドライブをエミュレートしたものであり、ハードドライブと同じインターフェイスで利用できます。



 a| 
ストレージアレイ
 a| 
ストレージアレイは、シェルフ、コントローラ、ドライブ、ソフトウェア、およびファームウェアを収容します。



 a| 
ボリューム
 a| 
ボリュームは、アプリケーション、データベース、およびファイルシステムがデータを格納するコンテナです。ホストがストレージアレイのストレージにアクセスするために作成される論理コンポーネントです。



 a| 
ワークロード
 a| 
ワークロードは、アプリケーションをサポートするストレージオブジェクトです。一部のアプリケーションについては、特性が似たボリュームで構成されるように System Manager によってワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。

|===