---
permalink: config-vmware/verify-vmware-config-support-task.html 
sidebar: sidebar 
keywords: express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: VMware 構成がサポートされていることを確認します。 
---
= VMware 構成がサポートされていることを確認する
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安定した稼働を確保するために、導入計画を作成し、 NetApp Interoperability Matrix Tool （ IMT ）を使用して構成全体がサポートされることを確認します。

.手順
. にアクセスします http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]。
. [ 検索（解決策 Search ） ] タイルをクリックします。
. [Protocols [SAN Host] （プロトコル [SAN ホスト ] ）領域で、 * E シリーズ SAN ホスト * の横の * 追加ボタンをクリックします。
. ［ * 検索条件の絞り込み検索の表示 * ］ をクリックします。
+
[ 検索条件の絞り込み ] セクションが表示されます。このセクションでは、適用するプロトコル、およびオペレーティングシステム、ネットアップ OS 、ホストマルチパスドライバなど、構成のその他の条件を選択できます。構成に必要な条件を選択し、互換性のある構成要素を確認します。必要に応じて、使用するオペレーティングシステムとプロトコルに対して IMT に記載された更新を実行します。選択した構成の詳細情報には、右ページ矢印をクリックして、 [View Supported Configurations] ページからアクセスできます。

. 必要に応じて、使用するオペレーティングシステムとプロトコルに対して次の表に記載された更新を実行します。
+
|===
| オペレーティングシステムの更新 | プロトコル | プロトコル関連の更新 


 a| 
** 適切な機能とサポートを確保するために、ドライバのインストールが必要になる場合があります。HBA ドライバは、 ESXi シェルを使用するか、 ESXi ホストへのリモート SSH 接続を使用してインストールできます。どちらかの方法でホストにアクセスするには、 ESXi シェルと SSH アクセスを有効にする必要があります。ESXi シェルの詳細については、 ESXi での ESXi シェルの使用に関する VMware のナレッジベースを参照してください。インストールコマンドについては、 HBA ドライバ付属の手順書を参照してください。
** ブートコードとファームウェアを更新する方法は、 HBA ベンダーごとに異なります。たとえば、 vCenter プラグインを使用する方法や、 ESXi ホストに CIM プロバイダをインストールする方法などがあります。vCenter のプラグインを使用して、ベンダー固有の HBA に関する情報を取得できます。HBA のブートコードまたはファームウェアの更新に必要な手順書とソフトウェアの入手については、ベンダーの Web サイトでサポートセクションを参照してください。正しいブートコードまたはファームウェアの入手については、 _ VMware Compatibility Guide _ または HBA ベンダーの Web サイトを参照してください。

 a| 
FC
 a| 
ホストバスアダプタ（ HBA ）のドライバ、ファームウェア、ブートコード



 a| 
iSCSI
 a| 
ネットワークインターフェイスカード（ NIC ）のドライバ、ファームウェア、ブートコード



 a| 
（ SAS ）。
 a| 
ホストバスアダプタ（ HBA ）のドライバ、ファームウェア、ブートコード

|===

