---
sidebar: sidebar 
permalink: san-spvc-ic-storage-array-discovery.html 
keywords: discover arrays vCenter plugin, discover storage resources Plugin for vCenter, resolve certificates vCenter plugin 
summary: vCenter 向けプラグインインターフェイスを使用して、ネットワーク内のアレイの IP アドレスを検出します。 
---
= プラグインでストレージアレイを検出します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ストレージリソースを表示および管理するには、 Storage Plugin for vCenter インターフェイスを使用して、ネットワーク内のアレイの IP アドレスを検出する必要があります。



== 手順 1 ：検出するネットワークアドレスを入力します

.作業を開始する前に
* アレイコントローラのネットワーク IP アドレス（またはアドレスの範囲）を確認しておく必要があります。
* ストレージアレイが正しくセットアップおよび設定され、ストレージアレイのログインクレデンシャル（ユーザ名とパスワード）が必要です。


.手順
. [ 管理 ] ページで、 [ * 追加 / 検出 * ] を選択します。
+
[Enter Network Address Range] ダイアログボックスが表示されます。

. 次のいずれかを実行します。
+
** 1 つのアレイを検出するには、 * 単一のストレージアレイの検出 * オプションボタンを選択し、ストレージアレイのいずれかのコントローラの IP アドレスを入力します。
** 複数のストレージアレイを検出するには、「ネットワーク範囲内のすべてのストレージアレイを検出」ラジオボタンを選択し、開始ネットワークアドレスと終了ネットワークアドレスを入力してローカルサブネットワーク全体を検索します。


. [ 検出の開始 ] をクリックします。
+
検出プロセスが開始されると、ストレージアレイが検出されるときにダイアログボックスに表示されます。検出プロセスが完了するまでに数分かかることがあります。

+
管理可能なアレイが検出されない場合は、ストレージアレイがネットワークに適切に接続されていて、割り当てられたアドレスが範囲内にあることを確認してください。[ 新規検出パラメータ * ] をクリックして、 [ 追加 / 検出 ] ページに戻ります。

. 管理ドメインに追加するストレージアレイの横にあるチェックボックスをオンにします。
+
管理ドメインに追加する各アレイについて、クレデンシャルのチェックが実行されます。信頼されていない証明書に関する問題の解決が必要になる場合があります。

. 「 * 次へ * 」をクリックして、ウィザードの次の手順に進みます。
+
ストレージアレイに有効な証明書がある場合は、に進みます <<Step 3: Provide passwords>>。

+
有効な証明書がないストレージアレイがある場合は、自己署名証明書の解決ダイアログボックスが表示されます。に進みます <<Step 2: Resolve untrusted certificates during discovery>>。

+
CA 署名証明書をインポートする場合は、検出ウィザードをキャンセルし、左パネルから * 証明書の管理 * をクリックします。詳細については、オンラインヘルプを参照してください。





== 手順 2 ：検出時に信頼されていない証明書を解決する

証明書の問題を解決してから検出プロセスを開始する必要があります。

. [ 自己署名証明書の解決 ] ダイアログボックスが開いた場合は、信頼されていない証明書について表示される情報を確認します。詳細については、表の右端にある省略記号をクリックし、ポップアップメニューから「 * 表示 * 」を選択することもできます。
. 次のいずれかを実行します。
+
** 検出されたストレージアレイへの接続を信頼する場合は、 * Next * （次へ）をクリックし、 * Yes * （はい）をクリックして確認し、ウィザードの次のダイアログに進みます。自己署名証明書は信頼済みとしてマークされ、ストレージアレイがプラグインに追加されます。
** ストレージアレイへの接続を信頼しない場合は、「 * キャンセル」を選択し、各ストレージアレイのセキュリティ証明書戦略を検証してから追加してください。


. 「 * 次へ * 」をクリックして、ウィザードの次の手順に進みます。




== 手順 3 ：パスワードを入力する

検出の最後の手順として、管理ドメインに追加するストレージアレイのパスワードを入力する必要があります。

. 検出された各アレイの admin パスワードをフィールドに入力します。
. [ 完了 ] をクリックします。
+
指定したストレージアレイへの接続がシステムで確立されるまでに数分かかることがあります。処理が完了すると、ストレージアレイが管理ドメインに追加され、選択したグループ（指定されている場合）に関連付けられます。


