---
sidebar: sidebar 
permalink: san-spvc-ic-storage-provisioning.html 
keywords: create volumes vCenter plugin, provision Plugin for vCenter, vCenter plugin storage provisioning, vCenter plugin host 
summary: vCenter 向けプラグインを使用して、ボリュームの作成、ホストへのボリュームの割り当て、データストアへのボリュームの割り当てを行います。 
---
= プラグインでストレージをプロビジョニングします
:hardbreaks:
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ストレージをプロビジョニングするには、ボリュームを作成してホストにボリュームを割り当ててから、データストアにボリュームを割り当てます。


NOTE: ストレージのプロビジョニングの詳細については、プラグインインターフェイスからアクセスできるオンラインヘルプを参照してください。



== ボリュームを作成します

ボリュームは、ストレージアレイ上のストレージスペースを管理および編成するデータコンテナです。ストレージアレイで使用可能なストレージ容量からボリュームを作成すると、システムのリソースを整理するのに役立ちます。「ボリューム」という概念は、コンピュータ上のフォルダやディレクトリを使用してファイルにすばやくアクセスできるようにする方法に似ています。

ボリュームは、ホストから認識できる唯一のデータレイヤです。SAN 環境では、ボリュームは論理ユニット番号（ LUN ）にマッピングされます。これらの LUN は、ストレージアレイでサポートされている 1 つ以上のホストアクセスプロトコルを使用してアクセス可能なユーザデータを保持します。

.手順
. 管理ページで、ストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ボリュームの管理 ] 。
. メニューから「 Create [Volumes] 」を選択します。
+
Select Host （ホストの選択）ダイアログボックスが表示されます。

. ボリュームを割り当てるホストまたはホストクラスタをドロップダウンリストから選択するか、ホストまたはホストクラスタをあとで割り当てるように選択します。
. 選択したホストまたはホストクラスタのボリューム作成手順を続行するには、 * Next * をクリックします。
+
ワークロードの選択ダイアログボックスが表示されます。ワークロードには、ワークロードがサポートするアプリケーションのタイプに基づいて最適化された、特性が似たボリュームが含まれます。ワークロードを定義することも、既存のワークロードを選択することもできます。

. 次のいずれかを実行します。
+
** 既存のワークロード用のボリュームの作成 * オプションを選択し、ドロップダウンリストからワークロードを選択します。
** [ 新しいワークロードの作成 ] オプションを選択して、サポートされているアプリケーションまたは「その他」のアプリケーションの新しいワークロードを定義し、次の手順に従います。
+
... ドロップダウンリストから、新しいワークロードを作成するアプリケーションの名前を選択します。このストレージアレイで使用するアプリケーションがリストにない場合は、「 Other 」エントリのいずれかを選択します。
... 作成するワークロードの名前を入力します。




. 「 * 次へ * 」をクリックします。ワークロードがサポート対象のアプリケーションタイプに関連付けられている場合は、要求された情報を入力します。それ以外の場合は、次の手順に進みます。
+
Add/Edit Volumes （ボリュームの追加 / 編集）ダイアログボックスが表示されます。このダイアログでは、対応するプールまたはボリュームグループからボリュームを作成します。対象となる各プールおよびボリュームグループについて、使用可能なドライブの数と合計空き容量が表示されます。アプリケーション固有のワークロードがある場合、候補となる各プールまたはボリュームグループに、推奨されるボリューム構成に基づいて提示される容量が表示され、残りの空き容量が GiB 単位で表示されます。それ以外のワークロードの場合、プールまたはボリュームグループにボリュームを追加してレポート容量を指定した時点で容量が提示されます。

. ボリュームの追加を開始する前に、次の表に示すガイドラインを確認してください。
+
|===
| フィールド | 説明 


 a| 
空き容量
 a| 
ボリュームはプールまたはボリュームグループから作成されるため、選択するプールまたはボリュームグループに十分な空き容量が必要です。



 a| 
Data Assurance （ DA ）
 a| 
DA 対応ボリュームを作成する場合は、使用するホスト接続で DA がサポートされている必要があります。

** DA 対応ボリュームを作成する場合は、 DA に対応したプールまたはボリュームグループを選択します（プールとボリュームグループの候補テーブルで「 DA 」の横にある「はい」を探します）。
** DA 機能はプールおよびボリュームグループのレベルで提供されます。DA 保護は、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。新しいボリュームに DA 対応のプールまたはボリュームグループを選択すると、エラーがある場合には検出されて修正されます。
** ストレージアレイのコントローラで DA をサポートしていないホスト接続が使用されている場合、関連付けられているホストからは DA 対応ボリュームのデータにアクセスできません。




 a| 
ドライブセキュリティ
 a| 
セキュリティ有効ボリュームを作成するには、ストレージアレイのセキュリティキーを作成する必要があります。

** セキュリティ有効ボリュームを作成する場合は、セキュリティ対応のプールまたはボリュームグループを選択します（プールとボリュームグループの候補テーブルで「セキュリティ対応」の横にある「はい」を探します）。
** ドライブセキュリティ機能は、プールおよびボリュームグループのレベルで提供されます。セキュリティ対応ドライブを使用すると、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。セキュリティ有効ドライブでは、一意の暗号化キーを使用して、書き込み時にデータが暗号化され、読み取り時に復号化されます。
** プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でないドライブの両方を含めることができますが、暗号化機能を使用するためにはすべてのドライブがセキュリティ対応である必要があります。




 a| 
リソースのプロビジョニング
 a| 
リソースプロビジョニングボリュームを作成するには、すべてのドライブが Deallocated or Unwritten Logical Block Error （ DULBE ）オプションを適用した NVMe ドライブである必要があります。

|===
. 前の手順でほかにワークロードを選択したかアプリケーション固有のワークロードを選択したかに基づいて、次のいずれかの操作を実行します。
+
** * その他 * - 1 つ以上のボリュームの作成に使用する各プールまたはボリュームグループで、 * 新しいボリュームの追加 * をクリックします。
** * アプリケーション固有のワークロード * - 選択したワークロードについてシステムで推奨されるボリュームと特性を受け入れるには、 [ 次へ * ] をクリックします。選択したワークロードに対してシステムで推奨されるボリュームと特性を変更、追加、または削除するには、 [ ボリュームの編集 ] をクリックします。
+
次のフィールドが表示されます。

+
|===
| フィールド | 説明 


 a| 
ボリューム名
 a| 
ボリュームには、作成時にデフォルトの名前が割り当てられます。デフォルトの名前をそのまま使用することも、ボリュームに格納されたデータのタイプを表した名前を指定することもできます。



 a| 
レポート容量
 a| 
新しいボリュームの容量と単位（ MiB 、 GiB 、または TiB ）を定義します。シックボリュームの場合、最小容量は 1MiB であり、最大容量はプールまたはボリュームグループ内のドライブの数と容量で決まります。プールの容量は 4GiB 単位で割り当てられます。4GiB の倍数でない容量を割り当てた場合、その容量は使用できません。全容量を使用できるようにするため、 4GiB 単位で容量を指定してください。使用不可容量が存在する場合、その容量を使用するにはボリュームの容量を増やすしかありません。



 a| 
ボリュームタイプ
 a| 
アプリケーション固有のワークロードを選択した場合は、ボリュームタイプフィールドが表示されます。アプリケーション固有のワークロード用に作成されたボリュームのタイプを示します。



 a| 
ボリュームのブロックサイズ（ EF300 および EF600 のみ）
 a| 
ボリュームに対して作成できるブロックサイズが表示されます。

*** 512 ～ 512 バイト
*** 4K – 4 、 096 バイト




 a| 
セグメントサイズ（ Segment Size ）
 a| 
セグメントのサイジングに関する設定が表示されます。これは、ボリュームグループのボリュームについてのみ表示されます。セグメントサイズを変更することでパフォーマンスを最適化することができます。

* 許容される変更後のセグメントサイズ * –許容される変更後のセグメントサイズがシステムによって決定されます。現在のセグメントサイズの変更後のサイズとして適切でないものは、ドロップダウンリストに表示されません。通常、許容される変更後のサイズは、現在のセグメントサイズの倍または半分です。たとえば、ボリュームの現在のセグメントサイズが 32KiB であれば、ボリュームの新しいセグメントサイズとして 16KiB または 64KiB が許容されます。

* SSD キャッシュが有効なボリューム * – SSD キャッシュが有効なボリュームに対しては、セグメントサイズを 4KiB に指定することができます。4KiB のセグメントサイズを選択するのは、 SSD キャッシュが有効なボリュームで小さいブロックの I/O 処理を実行する（ I/O ブロックサイズが 16KiB 以下の場合など）場合のみにしてください。SSD キャッシュが有効なボリュームで大きいブロックのシーケンシャル処理を実行する場合は、セグメントサイズとして 4KiB を選択するとパフォーマンスが低下することがあります。

* セグメントサイズの変更にかかる時間 * –ボリュームのセグメントサイズの変更にかかる時間は、次の要因によって異なります。

*** ホストからの I/O 負荷
*** ボリュームの修正の優先順位
*** ボリュームグループ内のドライブの数
*** ドライブチャネルの数
*** ストレージアレイコントローラの処理能力


ボリュームのセグメントサイズを変更すると I/O パフォーマンスに影響しますが、データの可用性は維持されます。



 a| 
セキュリティ対応
 a| 
* 「 Secure Capable 」の横には、プールまたはボリュームグループ内のドライブが暗号化に対応している場合のみ「 SecureCapable 」と表示されます。ドライブセキュリティは、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止します。このオプションは、ドライブセキュリティ機能が有効になっていて、ストレージアレイのセキュリティキーが設定されている場合にのみ使用できます。プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でないドライブの両方を含めることができますが、暗号化機能を使用するためにはすべてのドライブがセキュリティ対応である必要があります。



| ダ | * 「 DA 」の横には、プールまたはボリュームグループのドライブで Data Assurance （ DA ）がサポートされている場合にのみ「 Yes 」と表示されます。DA を使用すると、ストレージシステム全体のデータの整合性が向上します。DA を使用すると、データがコントローラ経由でドライブに転送される際にストレージアレイがエラーの有無をチェックできます。新しいボリュームに DA を使用すると、すべてのエラーが検出されます。 
|===


. 選択したアプリケーションのボリューム作成手順を続行するには、 * 次へ * をクリックします。
. 最後の手順で、作成するボリュームの概要を確認し、必要に応じて変更を加えます。変更するには、「 * 戻る」をクリックします。ボリューム構成に問題がなければ、「 * 完了 * 」をクリックします。




== ホストアクセスを作成し、ボリュームを割り当てます

ホストは自動または手動で作成できます。

* * 自動 * -- (NVMe-oF ではなく ) SCSI ベースのホストの自動作成は、 Host Context Agent (HCA) によって開始されます。HCA は、ストレージアレイに接続されている各ホストにインストール可能なユーティリティです。HCA がインストールされている各ホストは、 I/O パスを経由してストレージアレイコントローラにホストの設定情報をプッシュします。コントローラは、ホスト情報に基づいてホストと関連するホストポートを自動的に作成し、ホストタイプを設定します。必要に応じて、ホストの設定を変更することもできます。HCA の自動検出が実行されると、ホストには次の属性が自動的に設定されます。
+
** ホストのシステム名から取得されたホスト名。
** ホストに関連付けられたホストポート識別子。
** ホストのホストオペレーティングシステムタイプ。





NOTE: Linux および Windows 用の Host Context Agent ソフトウェアは、から入手できます https://mysupport.netapp.com/site/downloads["ネットアップサポート - ダウンロード"^]。


NOTE: ホストはスタンドアロンホストとして作成されます。 HCA では、ホストクラスタの作成やホストクラスタへの追加が自動的に行われることはありません。

* * 手動 * –ホストの手動作成中に、ホストポート識別子をリストから選択するか、手動で入力して関連付けます。ホストの作成後、ボリュームへのアクセスを共有する場合は、ボリュームをホストに割り当てたり、ホストクラスタに追加したりできます。




==== HCA を使用したホストの自動検出

Host Context Agent （ HCA ）を使用してホストを自動的に検出し、検出された情報が正しいかを確認することができます。

.手順
. Manage （管理）ページで、ホスト接続があるストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ホストの設定 ] 。
+
Configure Hosts ページが開きます。

. メニューから「 Storage [Hosts] 」を選択します。
+
自動的に作成されたホストが表に表示されます。

. HCA から提供された情報（名前、ホストタイプ、ホストポート識別子）が正しいことを確認します。
. いずれかの情報を変更する必要がある場合は、ホストを選択し、 * 表示 / 設定の編集 * をクリックします。




==== ホストを手動で作成する

次のガイドラインを参照してください。

* 環境でストレージアレイを追加または検出しておく必要があります。
* ホストに関連付けられたホストポート識別子を定義する必要があります。
* ホストに割り当てられたシステム名と同じ名前を指定してください。
* 選択した名前がすでに使用されている場合、この処理は失敗します。
* 名前は 30 文字以内にする必要があります。


.手順
. Manage （管理）ページで、ホスト接続があるストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ホストの設定 ] 。
+
Configure Hosts ページが開きます。

. メニュー： Create [Host] をクリックします。
+
Create Host （ホストの作成）ダイアログボックスが表示されます。

. ホストの設定を必要に応じて選択します。
+
|===
| フィールド | 説明 


 a| 
名前
 a| 
新しいホストの名前を入力します。



 a| 
ホストオペレーティングシステムのタイプ
 a| 
新しいホストで実行しているオペレーティングシステムをドロップダウンリストから選択します。



 a| 
ホストインターフェイスタイプ
 a| 
（オプション）ストレージアレイで複数のタイプのホストインターフェイスがサポートされている場合、使用するホストインターフェイスタイプを選択します。



 a| 
ホストポート
 a| 
次のいずれかを実行します。

** * I/O インターフェイス * を選択します。通常は、ホストポートはログイン済みで、ドロップダウンリストに表示されます。リストからホストポート識別子を選択することができます。
** * 手動で追加 * 。ホストポート識別子がリストに表示されない場合は、ホストポートがログインしていません。HBA ユーティリティまたは iSCSI イニシエータユーティリティを使用して、ホストポート識別子を検索してホストに関連付けることができます。


ホストポート識別子を手動で入力するか、ユーティリティから（一度に 1 つずつ）ホストポートフィールドにコピーして貼り付けることができます。

ホストポート識別子は、一度に 1 つずつ選択してホストに関連付ける必要がありますが、ホストに関連付けられている識別子をいくつでも選択することができます。各識別子はホストポートフィールドに表示されます。必要に応じて、識別子の横にある X を選択して識別子を削除することもできます。



 a| 
CHAP イニシエータシークレットを設定する
 a| 
（オプション） iSCSI IQN を使用してホストポートを選択した場合または手動で入力した場合に、 Challenge Handshake Authentication Protocol （ CHAP ）を使用して認証するためにストレージアレイへのアクセスを試行するホストが必要な場合は、 Set CHAP initiator secret （ CHAP イニシエータシークレットの設定）チェックボックスを選択します。選択または手動で入力した iSCSI ホストポートごとに、次の手順を実行します。

** CHAP 認証用に各 iSCSI ホストイニシエータに設定されたものと同じ CHAP シークレットを入力します。相互 CHAP 認証（ホストが自身をストレージアレイに対して検証し、ストレージアレイが自身をホストに対して検証できるようにする双方向認証）を使用する場合は、ストレージアレイの初期セットアップまたは設定変更時に CHAP シークレットも設定する必要があります。
** ホストの認証が不要な場合は、このフィールドを空白のままにします。


現在使用されている iSCSI 認証方式は CHAP だけです。

|===
. [ 作成（ Create ） ] をクリックします。
. ホスト情報を更新する必要がある場合は、表からホストを選択し、 * 表示 / 設定の編集 * をクリックします。
+
ホストの作成が完了すると、ホストに設定されている各ホストポートのデフォルト名（ユーザラベル）が作成されます。デフォルトのエイリアスは「 <Hostname_Port number>` 」です。たとえば、ホスト IPT に対して最初に作成されたポートのデフォルトのエイリアスは「 ipt_1 」です。

. 次に、ボリュームをホストまたはホストクラスタに割り当てて、 I/O 処理に使用できるようにする必要があります。メニューを選択します。 Provisioning [ ホストの設定 ] 。
+
Configure Hosts ページが開きます。

. ボリュームを割り当てるホストまたはホストクラスタを選択し、 * ボリュームの割り当て * をクリックします。
+
ダイアログボックスに割り当て可能なすべてのボリュームが表示されます。列をソートしたり、フィルタボックスに何かを入力したりすると、特定のボリュームを簡単に見つけることができます。

. 割り当てる各ボリュームの横にあるチェックボックスを選択するか、テーブルヘッダーにあるチェックボックスを選択してすべてのボリュームを選択します。
. [*Assign*] をクリックして、操作を完了します。
+
システムは次の処理を実行します。

+
** 割り当てられたボリュームに次に使用可能な LUN 番号が受信されます。ホストはこの LUN 番号を使用してボリュームにアクセスします。
** ホストに関連付けられているボリュームの一覧にユーザが指定したボリューム名が表示されます。該当する場合、ホストに関連付けられているボリュームの一覧には、工場出荷時に設定されたアクセスボリュームも表示されます。






== vSphere Client でデータストアを作成します

vSphere Client でデータストアを作成する方法については、 VMware ドキュメントセンターで以下のトピックを参照してください。

* https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-7EB0CE06-02DD-4B31-85C7-E54993CC06DC.html["vSphere Client で VMFS データストアを作成します"^]




=== ボリューム容量を増やして既存のデータストアの容量を増やします

プールまたはボリュームグループ内の使用可能な空き容量を使用して、ボリュームのレポート容量（ホストに報告される容量）を拡張できます。プールとボリュームグループの詳細については、プラグインのオンラインヘルプを参照してください。

次の点を確認してください。

* ボリュームの関連付けられたプールまたはボリュームグループに十分な空き容量が必要です。
* ボリュームが最適状態で、変更中の状態ではありません。
* ボリュームでホットスペアドライブが使用されていない必要があります。（ボリュームグループ内のボリュームにのみ適用されます）。



NOTE: ボリュームの容量の拡張は、特定のオペレーティングシステムでのみサポートされています。LUN 拡張をサポートしていないホストオペレーティングシステム上でボリューム容量を拡張した場合、拡張した容量は使用できず、元のボリューム容量をリストアすることもできません。

.手順
. vSphere Client でプラグインに移動します。
. プラグインで、目的のストレージアレイを選択します。
. [* プロビジョニング * ] をクリックし、 [ * ボリュームの管理 * ] を選択します。
. 容量を拡張するボリュームを選択し、 * 容量を拡張 * を選択します。
+
容量の拡張の確認ダイアログボックスが表示されます。

. 続行するには、 * はい * を選択します。
+
レポート容量の拡張ダイアログボックスが表示されます。

+
このダイアログボックスには、ボリュームの現在のレポート容量と、ボリュームの関連付けられたプールまたはボリュームグループ内で使用可能な空き容量が表示されます。

. レポート容量の拡張に使用できるレポート容量を追加するには、 * ボックスを使用します。メビバイト（ MiB ）、ギビバイト（ GiB ）、またはテビバイト（ TiB ）のいずれかで表示するように容量の値を変更できます。
. [* 拡大（ * ） ] をクリックします
. 選択したボリュームで現在実行されている容量の拡張処理の進捗状況については、 Recent Tasks ペインを表示します。この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。
. ボリュームの容量が完了したら、次のトピックに示すように、 VMFS サイズを手動で拡張する必要があります。
+
** https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-B0D89816-02E5-4C42-AAFC-19751800A284.html["vSphere Client で VMFS データストアの容量を増やします"^]






=== ボリュームを追加して既存のデータストアの容量を拡張してください

. ボリュームを追加してデータストアの容量を増やすことができます。「ボリュームの作成」の手順に従います。
. 次に、ボリュームを目的のホストに割り当て、データストアの容量を増やします。次のトピックを参照してください。
+
** https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.hostclient.doc/GUID-B0D89816-02E5-4C42-AAFC-19751800A284.html["vSphere Client で VMFS データストアの容量を増やします"^]



