---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-installation.html 
keywords: install vCenter plugin, installing vCenter plugin, vCenter plugin, 
summary: SANtricity Storage Plugin for vCenter をインストールします。 
---
= vCenter 向けストレージプラグインをインストールします
:hardbreaks:
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter 向けストレージプラグインをインストールし、プラグインの登録を確認できます。



== インストールの前提条件を確認する

システムが次の要件を満たしていることを確認します。

* VMware vCenter Server Appliance のサポートされるバージョン： 6.7U3J 、 7.0U1 、または 7 。0U2,
* NetApp SANtricity OS バージョン： 11.60.2 以降
* サポートされるアプリケーションホストのバージョン： Windows 2016 または Windows 2019
* ホストシステムの CPU 要件：
+
** システムメモリ： 1.5GB
** ストレージスペース： 275 MB + 200 MB （ロギング）






== プラグインソフトウェアをインストールします

プラグインソフトウェアをインストールするには：

. アプリケーションサーバとして使用するホストにインストーラファイルをコピーし、インストーラをダウンロードしたフォルダにアクセスします。
. インストールファイルをダブルクリックします。
+
'santricity _savcenterplugin -windows_x64 --nn.nn.nnnn.exe`

+
上記のファイル名の「 nn.nn.nn.nnnn 」はバージョン番号です。

. インストールが開始されたら、画面の指示に従います。
+
インストール時に、いくつかの設定パラメータを入力するように求められます。

+
.. 最初の画面で、ソフトウェアに使用する言語を選択し、 * OK * をクリックします。
.. [ はじめに ] 画面で、 [ * 次へ * ] をクリックします。
.. 著作権画面で、 * 次へ * をクリックします。
.. [ ライセンス契約 ] 画面で、条項に同意するボックスを選択し、 [ 次へ ] をクリックします。
.. ソフトウェアをインストールするフォルダを選択し、「 * 次へ * 」をクリックします。
.. プラグインとストレージアレイの間で証明書の検証を実行する場合は、証明書の検証画面でチェックボックスを選択したままにします。この適用では、ストレージアレイ証明書がプラグインに対して信頼されているかどうかがチェックされます。証明書が信頼されていない場合は、プラグインに追加できません。証明書の検証を無視する場合は、チェックボックスを選択解除して、すべてのストレージアレイを自己署名証明書を使用してプラグインに追加できるようにします。「 * 次へ * 」をクリックします。
+
証明書の詳細については、プラグインインターフェイスから入手できるオンラインヘルプを参照してください。

.. HTTPS Web サービスポート画面で、デフォルトの設定を 8445 のままにするか、必要に応じてポート番号を変更します。「 * 次へ * 」をクリックします。
.. Pre-Installation Summary （インストール前の概要）画面で、 * Next （次へ） * をクリックしてファイルをインストールします。
.. Webserver Started というメッセージが表示されたら、 * OK * をクリックしてインストールを完了します。
.. [ 完了（ Done ） ] をクリックします。
+

NOTE: 必要に応じて、インストール後に証明書の検証と Web サービスポートの設定を変更できます。インストールディレクトリから、 wsconfig.xml ファイルを開きます。ストレージ・アレイの証明書検証を削除するには 'env' キー 'trust.all.arrays' を 'true' に変更しますWeb Services ポートを変更するには 'slport' の値を 0 ～ 65535 の範囲の任意のポート値に変更します使用するポート番号が別のプロセスにバインドされていないことを確認します。完了したら、変更を保存してプラグイン Web サーバを再起動します。プラグインを vCSA に登録したあとにプラグイン Web サーバのポート値が変更された場合は、変更されたポートの vCSA がプラグインに通信するように、プラグインの登録を解除して再登録する必要があります。



. *services.msc * コマンドを実行して、アプリケーションサーバーが正常にインストールされたことを確認します。
. アプリケーションサーバ（ VCP ）サービス * NetApp SANtricity Storage Plugin for vCenter * がインストールされ、サービスが開始されていることを確認します。




== プラグインを vCenter Server Appliance に登録します

プラグインソフトウェアをインストールしたら、 vCSA にプラグインを登録します。


NOTE: プラグインを登録できる vCSA は 1 つだけです。別の vCSA に登録するには、現在の vCSA からプラグインの登録を解除し、アプリケーションホストからアンインストールする必要があります。その後、プラグインを再インストールして他の vCSA に登録できます。

. コマンドラインでプロンプトを開き、次のディレクトリに移動します。
+
`< インストールディレクトリ >\vcenter-register-bin'

. vCenter の登録 .bat * ファイルを実行します。 vcenter-register.bat アクション registerPlugin^-vcenterHostname <vCenter FQDN>^-UserName <Administrator username>^`
. スクリプトが正常に完了したことを確認します。


ログは '%install_dir%/working/logs/vc-registration.log' に保存されます



== プラグインの登録を確認します

プラグインをインストールして登録スクリプトを実行したら、プラグインが vCenter Server Appliance に正常に登録されていることを確認します。

. vSphere Client から vCenter Server Appliance を開きます。
. メニューバーで、 [ 管理者 ][ クライアントプラグイン ] を選択します。
. vCenter 向け SANtricity ストレージプラグインが「 * enabled * 」と表示されていることを確認してください。
+
[ 無効 ] と表示され、アプリケーションサーバーと通信できないことを示すエラーメッセージが表示された場合は、アプリケーションサーバーに定義されているポート番号が使用中のファイアウォールを通過できることを確認します。デフォルトのアプリケーションサーバーの Transmission Control Protocol （ TCP ）ポート番号は 8445 です。


