---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-user-access.html 
keywords: user access vCenter plugin, user roles vCenter plugin, privileges vCenter plugin, access permissions vCenter plugin 
summary: vCenter 向け Storage Plugin のアクセス権限を設定します。 
---
= プラグインアクセス権限を設定します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter 向けストレージプラグインのアクセス権限を設定できます。この権限には、ユーザ、ロール、および権限が含まれます。



== 必要な vSphere 権限を確認します

vSphere Client 内でプラグインにアクセスするには、適切な vSphere 権限を持つロールが割り当てられている必要があります。vSphere の「データストアの設定」権限を持つユーザーは、プラグインへの読み取り / 書き込みアクセス権を持ち、「データストアの参照」権限を持つユーザーは読み取り専用アクセス権を持ちます。ユーザーがこれらの権限を持たない場合、プラグインに「不十分な権限」というメッセージが表示されます。

|===
| プラグインのアクセスタイプ | vSphere 権限が必要です 


| 読み取り / 書き込み（設定） | データストア。設定 


| 読み取り専用（表示） | データストア参照 
|===


== ストレージ管理者のロールを設定する

プラグインユーザに読み取り / 書き込み権限を付与するには、ロールを作成、クローニング、または編集します。vSphere Client でのロールの設定の詳細については、 VMware ドキュメントセンターの次のトピックを参照してください。

* https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-41E5E52E-A95B-4E81-9724-6AD6800BEF78.html["カスタムロールを作成します"^]




=== アクセスロールのアクション

. vSphere Client のホームページで、アクセス制御領域から * Administrator * を選択します。
. アクセス制御領域で * 役割 * をクリックします。
. 次のいずれかを実行します。
+
** * 新しい役割の作成 *: [ 役割の作成 *] アクションアイコンをクリックします。
** * 役割のクローン * ：既存の役割を選択し、 * 役割のクローン * アクションアイコンをクリックします。
** * 既存のロールの編集 *: 既存のロールを選択し、 * ロールの編集 * アクションアイコンをクリックします。





NOTE: 管理者ロールは編集できません。

上記の選択に応じて、適切なウィザードが表示されます。



=== 新しいロールを作成します

. 権限リストで、このロールに割り当てるアクセス権限を選択します。
+
プラグインへの読み取り専用アクセスを許可するには、 * Datastore * > * Browse * * datastore * を選択します。読み取り / 書き込みアクセスを許可するには、 * Datastore * > * Configure datastore * を選択します。

. 必要に応じて、リストに他の権限を割り当て、 [ * 次へ * ] をクリックします。
. ロールに名前を付け、概要を指定します。
. [ 完了 ] をクリックします。




=== ロールのクローンを作成します

. ロールに名前を付け、概要を指定します。
. [OK] をクリックしてウィザードを終了します。
. リストから複製されたロールを選択し、 * 役割の編集 * をクリックします。
. 権限リストで、このロールに割り当てるアクセス権限を選択します。
+
プラグインへの読み取り専用アクセスを許可するには、 [MENU] ： [Browse Datastore] を選択します。読み取り / 書き込みアクセスを許可するには、メニューから [ データストアの設定 ] を選択します。

. 「 * 次へ * 」をクリックします。
. 必要に応じて、名前と概要を更新します。
. [ 完了 ] をクリックします。




=== 既存のロールを編集します

. 権限リストで、このロールに割り当てるアクセス権限を選択します。
+
プラグインへの読み取り専用アクセスを許可するには、 [MENU] ： [Browse Datastore] を選択します。読み取り / 書き込みアクセスを許可するには、メニューから [ データストアの設定 ] を選択します。

. 「 * 次へ * 」をクリックします。
. 必要に応じて、名前または概要を更新します。
. [ 完了 ] をクリックします。




== vCenter Server Appliance のアクセス許可を設定します

ロールの権限を設定したら、 vCenter Server Appliance に権限を追加する必要があります。この権限は、指定されたユーザまたはグループにプラグインへのアクセスを許可します。

. メニューのドロップダウン・リストから、 *Hosts and Clusters* を選択します。
. アクセス制御領域から * vCenter Server Appliance * を選択します。
. [* アクセス許可 *] タブをクリックします。
. [ 権限の追加 ] アクションアイコンをクリックします。
. 適切なドメインとユーザ / グループを選択します。
. 読み取り / 書き込みプラグイン権限を許可する、作成されたロールを選択します。
. 必要に応じて、 [ 子に伝播（ * Propagate to children ） ] オプションを有効にします。
. [OK] をクリックします。



NOTE: 既存の権限を選択し、作成したロールを使用するように変更できます。* ただし、権限で正規表現を行わないようにするためには、読み取り / 書き込みプラグイン権限と同じ権限が役割に付与されている必要があります。 *

プラグインにアクセスするには、そのプラグインの読み取り / 書き込み権限を持つユーザアカウントで vSphere Client にログインする必要があります。

権限の管理の詳細については、 VMware ドキュメントセンターの次のトピックを参照してください。

* https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-3B78EEB3-23E2-4CEB-9FBD-E432B606011A.html["vCenter コンポーネントのアクセス許可の管理"^]
* https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-FAA074CC-E8C9-4F13-ABCF-6CF7F15F04EE.html["ロールと権限のベストプラクティス"^]

