---
permalink: vcenter-plugin/san-spvc-ic-reqs.html 
sidebar: sidebar 
keywords: upgrade vCenter 
summary: vCenterプラグインのインストールとアップグレードの要件および考慮事項 
---
= インストールとアップグレードの要件を確認
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Storage Plugin for vCenterをインストールまたはアップグレードする前に、インストール要件とアップグレード時の考慮事項を確認してください。



== インストールの要件

WindowsホストシステムにvCenter向けストレージプラグインをインストールして設定できます。プラグインのインストールには次の要件が含まれています

[cols="35h,~"]
|===
| 要件 | 説明 


 a| 
サポートされるバージョン
 a| 
* VMware vCenter Server Applianceのサポートされるバージョン：6.7U3J、7.0U1、7.0U2、7.0U3、および8.0。
* NetApp SANtricity OS バージョン： 11.60.2 以降
* サポートされるアプリケーションホストのバージョン：Windows 2016、Windows 2019、Windows 2022


互換性の詳細については、を参照してください http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]。



 a| 
複数のインスタンス
 a| 
WindowsホストにインストールできるvCenter向けStorage Pluginのインスタンスは1つだけで、1つのvCSAに登録できます。



 a| 
キャパシティプランニング
 a| 
vCenter向けストレージプラグインを実行してログを作成するために必要な十分なスペースがあります。使用可能なディスクスペースについて、システムが次の要件を満たしていることを確認してください。

* 必要なインストールスペース：275MB
* ストレージ容量：275 MB + 200 MB（ロギング）
* システムメモリ—1.5 GB




 a| 
使用許諾
 a| 
vCenter向けストレージプラグインは、ライセンスキーを必要としない、無償のスタンドアロン製品です。ただし、該当する著作権とサービス利用規約が適用されます。

|===


== アップグレード時の考慮事項

以前のバージョンからアップグレードする場合は、アップグレード前にプラグインをvCSAから登録解除する必要があります。

* アップグレード中は、プラグインの以前の構成設定のほとんどが保持されます。これには、ユーザパスワード、検出されたすべてのストレージシステム、サーバ証明書、信頼された証明書、サーバのランタイム設定などが含まれます。
* アップグレードプロセスでは*。vcenter.properties*ファイルは保持されないため、アップグレード前にプラグインの登録を解除する必要があります。アップグレードが完了したら、プラグインをvCSAに再度登録できます。
* リポジトリにロードされていたすべてのSANtricity OSファイルは、アップグレード中に削除されます。

