---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-host-creation-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: vCenter向けストレージプラグインを使用してストレージを管理するには、ネットワーク内の各ホストを検出または定義する必要があります。 
---
= ホスト作成の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter向けストレージプラグインを使用してストレージを管理するには、ネットワーク内の各ホストを検出または定義する必要があります。ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。



== ホストの手動作成

ホストの作成は、ストレージアレイが接続されているホストを認識して、ボリュームへのI/Oアクセスを許可するために必要な手順の1つです。ホストは手動で作成できます。

* *手動*--ホストを手動で作成するときに'ホスト・ポート識別子をリストから選択するか'手動で入力することによって'それらを関連付けますホストの作成後、ボリュームへのアクセスを共有する場合は、ボリュームをホストに割り当てたり、ホストクラスタに追加したりできます。




== ボリュームの割り当て方法

ホストからボリュームにI/Oを送信するには、ボリュームをボリュームに割り当てる必要があります。ボリュームの作成時にホストまたはホストクラスタを選択するか、あとからボリュームをホストまたはホストクラスタに割り当てることができます。ホストクラスタはホストのグループです。ホストクラスタを作成すると、同じボリュームを複数のホストに簡単に割り当てることができます。

ホストへのボリュームの割り当ては柔軟性が高く、ストレージの特定のニーズを満たすことができます。

* *ホストクラスタの一部ではなく、スタンドアロンホスト*--ボリュームを個々のホストに割り当てることができます。ボリュームにアクセスできるのは1つのホストだけです。
* *ホストクラスタ*--ボリュームをホストクラスタに割り当てることができますボリュームには、ホストクラスタ内のすべてのホストからアクセスできます。
* *ホストクラスタ内のホスト*--ホストクラスタの一部である個別のホストにボリュームを割り当てることができますホストはホストクラスタの一部ですが、ボリュームにアクセスできるのは個々のホストだけであり、ホストクラスタ内の他のホストからはアクセスできません。


ボリュームの作成時に、論理ユニット番号（LUN）が自動的に割り当てられます。LUNは、I/O処理中のホストとコントローラの間のアドレスとして機能します。LUNはボリュームが作成されたあとに変更できます。
