---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-activate-staged-os-software.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ソフトウェアファイルをより便利なタイミングでアクティブ化することもできます。 
---
= ステージング済みOSソフトウェアをアクティブ化します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ソフトウェアファイルはただちにアクティブ化することも、都合のいいタイミングでアクティブ化することもできます。この手順では、ソフトウェアファイルをあとでアクティブ化するように選択した場合を想定しています。

.このタスクについて
ファームウェアファイルは、アクティブ化せずに転送できます。あとでアクティブ化する理由は次のとおりです。

* * 時間帯 * -- ソフトウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがリブートしてフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
* * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします



NOTE: 起動後にアクティブ化プロセスを停止することはできません。

.手順
. メインビューで、* Manage *（管理）を選択します。必要に応じて、ステータス*列をクリックして、ページ上部の「OS Upgrade（waiting activation）」というステータスのすべてのストレージアレイをソートします。
. ソフトウェアをアクティブ化するストレージアレイを1つ以上選択し、メニューから[Upgrade Center][Activate Staged SANtricity Software]を選択します。
+
アップグレード処理では次の処理が実行されます。

+
** アップグレード前の健常性チェックは、アクティブ化プロセスの一環として実行されます。アップグレード前の健常性チェックでは、ストレージアレイのすべてのコンポーネントについて、アクティブ化を実行できる状態であるかがチェックされます。
** いずれかの健全性チェックでストレージアレイに問題が見つかった場合、アクティブ化は停止します。省略記号(...)をクリックします 「ログを保存」を選択してエラーを確認します。ヘルスチェックエラーを無視して、 [* Continue （続行） ] をクリックしてアクティブ化を続行することもできます。
** アップグレード前の健常性チェックのあとに、アクティブ化処理をキャンセルすることができます。
+
アップグレード前の健常性チェックが正常に完了すると、アクティブ化が実行されます。アクティブ化にかかる時間は、ストレージアレイの構成とアクティブ化しているコンポーネントによって異なります。



. （オプション）アクティブ化が完了したら、省略記号（…）をクリックすると、特定のストレージアレイに対してアクティブ化された項目のリストが表示されます。 次に、[ログの保存]を選択します。
+
ブラウザのDownloadsフォルダに'activate_log-<date>という名前でファイルが保存されますJSON形式


