---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-add-volumes-to-workload.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 既存または新規のワークロードに未割り当てのボリュームを追加する。 
---
= ワークロードにボリュームを追加する
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既存または新規のワークロードに未割り当てのボリュームを追加できます。

ボリュームをコマンドラインインターフェイス（CLI）を使用して作成した場合や別のストレージアレイから移行（インポート/エクスポート）した場合、それらのボリュームはワークロードに関連付けられません。

.手順
. 管理ページで、追加するボリュームが含まれているストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ボリュームの管理 ] 。
. [アプリケーションとワークロード]タブを選択します。
+
[アプリケーションとワークロード]ビューが表示されます。

. 「*ワークロードに追加*」を選択します。
+
ワークロードの選択ダイアログボックスが表示されます。

. 次のいずれかを実行します。
+
** *既存のワークロードにボリュームを追加する*-既存のワークロードにボリュームを追加する場合は、このオプションを選択します。ドロップダウンリストを使用してワークロードを選択します。そのワークロードに関連付けられているアプリケーションタイプが、追加するボリュームに割り当てられます。
** *新しいワークロードにボリュームを追加*--アプリケーションタイプの新しいワークロードを定義して新しいワークロードにボリュームを追加するには、このオプションを選択します。


. 「*次へ*」を選択して、ワークロードへの追加手順を続行します。
+
Select Volumes（ボリュームの選択）ダイアログボックスが表示されます。

. ワークロードに追加するボリュームを選択します。
. 選択したワークロードに追加するボリュームを確認します。
. ワークロードの設定が完了したら、[完了]をクリックします。

