---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-add-capacity-to-a-pool-or-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ドライブを追加して、既存のプールまたはボリュームグループの空き容量を拡張します。 
---
= プールまたはボリュームグループに容量を追加します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ドライブを追加することで、既存のプールまたはボリュームグループの空き容量を拡張することができます。

.作業を開始する前に
* ドライブのステータスが最適lである必要があります。
* ドライブタイプ（HDDまたはSSD）が同じである必要があります。
* プールまたはボリュームグループのステータスが最適である必要があります。
* プールまたはボリュームグループに含まれているドライブがいずれもセキュリティ対応ドライブの場合、セキュリティ対応ドライブの暗号化機能を引き続き使用するには、セキュリティ対応のドライブだけを追加します。


セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。

このタスクでは、プールまたはボリュームグループに含める空き容量を追加できます。この空き容量は追加ボリュームの作成に使用できます。この処理の実行中もボリューム内のデータには引き続きアクセスできます。

プールに一度に追加できるドライブは最大60本です。ボリュームグループに一度に追加できるドライブは最大2本です。最大数を超えるドライブを追加する必要がある場合は、手順 を繰り返します。（プールにはストレージアレイの上限を超えるドライブを含めることはできません）。


NOTE: ドライブの追加に伴い、予約済み容量の引き上げが必要になる場合があります。拡張処理の実行後にリザーブ容量を増やすことを検討してください。


NOTE: Data Assurance（DA）に対応していないプールまたはボリュームグループに容量を追加するときは、DA対応のドライブは使用しないでください。DA対応ドライブの機能をプールまたはボリュームグループで利用することはできません。DAに対応していないドライブの使用を検討してください。

.手順
. 管理ページで、プールまたはボリュームグループを含むストレージアレイを選択します。
. メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。
. ドライブを追加するプールまたはボリュームグループを選択し、*容量の追加*をクリックします。
+
Add Capacityダイアログボックスが表示されます。プールまたはボリュームグループと互換性がある未割り当てのドライブのみが表示されます。

. ドライブの選択...*で、既存のプールまたはボリュームグループに追加するドライブを1つ以上選択します。
+
ドライブのリストは、より適した未割り当てのドライブから順に表示されます。プールまたはボリュームグループに追加された合計空き容量が、選択した合計容量*のリストの下に表示されます。

+
.フィールドの詳細
====
[cols="25h,~"]
|===
| フィールド | 説明 


 a| 
シェルフ
 a| 
ドライブのシェルフの場所を示します。



 a| 
ベイ
 a| 
ドライブのベイの場所を示します



 a| 
容量（GiB）
 a| 
ドライブの容量を示します。

** できるだけ、プールまたはボリュームグループ内の既存のドライブと同じ容量のドライブを選択してください。
** 容量が小さい未割り当てのドライブを追加する必要がある場合は、プールまたはボリュームグループに現在含まれている各ドライブの使用可能容量が削減されることに注意してください。したがって、ドライブ容量はプールまたはボリュームグループ全体で同じになります。
** 容量が大きい未割り当てのドライブを追加する必要がある場合は、現在プールまたはボリュームグループに含まれているドライブの容量に合わせて、追加する未割り当てのドライブの使用可能容量が削減されることに注意してください。




 a| 
セキュリティ対応
 a| 
ドライブがセキュリティ対応かどうかを示します。

** プールやボリュームグループはドライブセキュリティ機能を使用して保護できますが、この機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。
** セキュリティ対応とセキュリティ対応でないドライブが混在したプールまたはボリュームグループを作成することは可能ですが、ドライブセキュリティ機能を有効にすることはできません。
** すべてのセキュリティ対応ドライブを備えたプールまたはボリュームグループは、暗号化機能が使用されていない場合でも、スペアリングまたは拡張のために非セキュア対応ドライブを受け入れることはできません。
** セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります




 a| 
DA対応
 a| 
ドライブがData Assurance（DA）対応かどうかを示します。

** DAに対応していないドライブを使用してDAに対応したプールまたはボリュームグループに容量を追加することは推奨されません。プールまたはボリュームグループのDA機能は無効になり、プールまたはボリュームグループに新たに作成したボリュームでDAを有効にすることもできなくなります。
** DA対応のドライブを使用してDAに対応していないプールまたはボリュームグループに容量を追加することは推奨されません。DA対応ドライブの機能をプールまたはボリュームグループで利用することはできないためです（ドライブの属性が一致しません）。DAに対応していないドライブの使用を検討してください。




 a| 
DULBE対応
 a| 
ドライブにDeallocated or Unwritten Logical Block Error（DULBE）に対応したオプションがあるかどうかを示します。DULBEはNVMeドライブのオプションです。このオプションにより、EF300またはEF600ストレージアレイでリソースプロビジョニングボリュームをサポートできます。

|===
====
. [ 追加（ Add ） ] をクリックします。
+
プールまたはボリュームグループにドライブを追加する場合、プールまたはボリュームグループの次の属性が無効になるようなドライブを選択すると、確認のダイアログボックスが表示されます。

+
** シェルフ損失の保護
** ドロワー損失の保護
** Full Disk Encryption機能
** Data Assurance機能
** DULBE機能


. 続行するには、[はい]をクリックします。それ以外の場合は、[キャンセル]をクリックします。


プールまたはボリュームグループに未割り当てのドライブを追加したあと、追加のドライブを含めるためにプールまたはボリュームグループの各ボリューム内のデータが再配置されます。
