---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-array-management-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Add/Discover機能を使用して、組織のネットワークで管理するストレージアレイを検索および追加します。 
---
= vCenter向けSANtricity Storage Pluginでのストレージアレイの管理について
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アド/検出機能を使用して、vCenter向けStorageプラグインで管理対象のストレージアレイを検索および追加します。[管理]ページでは、これらの検出されたアレイの名前の変更、削除、および新しいパスワードの入力もできます。



== アレイの検出に関する考慮事項

プラグインでストレージリソースを表示して管理するには、組織のネットワークで管理対象のストレージアレイを検出する必要があります。単一のアレイまたは複数のアレイを検出して追加できます。



=== 複数のストレージアレイ

複数のアレイを検出する場合は、ネットワークIPアドレスの範囲を入力すると、その範囲の各IPアドレスへの接続が個別に試行されます。接続に成功したストレージアレイがプラグインに表示され、管理ドメインに追加できます。



=== 単一のストレージアレイです

単一のアレイを検出する場合は、ストレージアレイのいずれかのコントローラのIPアドレスを1つ入力してから、そのアレイを管理ドメインに追加します。


NOTE: プラグインは、コントローラに割り当てられた範囲内の単一のIPアドレスまたはIPアドレスのみを検出して表示します。これらのコントローラに割り当てられている代替コントローラまたはIPアドレスが、この1つのIPアドレスまたはIPアドレス範囲外の場合、プラグインはそれらを検出または表示しません。ただし、ストレージアレイを追加すると、関連付けられているすべてのIPアドレスが検出され、管理ビューに表示されます。



=== ユーザクレデンシャル

追加する各ストレージアレイの管理者パスワードを指定する必要があります。



=== 証明書

検出プロセスでは、検出されたストレージアレイに信頼できるソースからの証明書があるかどうかが確認されます。システムは、ブラウザでとの接続を確立するすべての接続に対して、2種類の証明書ベースの認証を使用します。

* *信頼された証明書*--一方または両方のコントローラ証明書の有効期限が切れた場合、失効した場合、またはチェーン内に証明書がない場合は、認証局が提供する信頼された証明書を追加でインストールする必要があります。
* *自己署名証明書*--アレイは自己署名証明書を使用することもできます署名済み証明書をインポートせずにアレイを検出しようとすると、プラグインに自己署名証明書を受け入れるための追加の手順が表示されます。自己署名証明書が信頼済みとしてマークされ、ストレージアレイがプラグインに追加されます。ストレージアレイへの接続を信頼しない場合は、ストレージアレイをプラグインに追加する前に* Cancel *を選択し、ストレージアレイのセキュリティ証明書戦略を検証します。




== ストレージアレイのステータス

vCenter向けストレージプラグインを開くと、各ストレージアレイとの通信が確立され、各ストレージアレイのステータスが表示されます。

Manage-All *ページでは、ストレージアレイのステータスおよびストレージアレイ接続のステータスを表示できます。

|===
| ステータス | を示します 


| 最適 | ストレージアレイが最適な状態です。証明書の問題はなく、パスワードが有効です。 


| パスワードが無効です | 無効なストレージアレイパスワードが指定されました。 


| 信頼できない証明書です | HTTPS証明書が自己署名証明書でインポートされていないか、CA署名証明書でルート証明書と中間CA証明書がインポートされていないため、ストレージアレイとの1つ以上の接続が信頼されていません。 


| 要注意 | ストレージアレイにユーザによる修正操作が必要な問題があります。 


| ロックダウン | ストレージアレイがロックダウン状態です。 


| 不明です | ストレージアレイに一度も接続していません。この状況は、プラグインが起動中でまだストレージアレイに接続していない場合や、ストレージアレイがオフラインでプラグインの起動後に一度も接続されていない場合に発生することがあります。 


| オフラインです | プラグインは以前にストレージアレイに接続しましたが、現在はすべての接続が失われています。 
|===


== プラグインインターフェイスとSystem Managerの比較

ストレージアレイの基本的な操作にはStorage Plugin for vCenterを使用できますが、プラグインで使用できないタスクを実行するためにSystem Managerの起動が必要になる場合があります。

System Managerは、ストレージアレイのコントローラに組み込まれたアプリケーションであり、イーサネット管理ポートを介してネットワークに接続されます。System Managerにはアレイベースのすべての機能が含まれています。

次の表は、プラグインインターフェイスとSystem Managerインターフェイスのどちらを使用できるかをストレージアレイの特定のタスクで判断する際に役立ちます。

|===
| 機能 | プラグインインターフェイス | System Managerインターフェイス 


| 複数のストレージアレイのグループに対するバッチ処理 | はい。 | いいえ処理は1つのアレイに対して実行されます。 


| SANtricity OSファームウェアのアップグレード | はい。バッチ処理内の1つ以上のアレイ。 | はい。シングルアレイのみ。 


| 1つのアレイから複数のアレイに設定をインポートします | はい。 | いいえ 


| ホストとホストクラスタの管理（ボリュームの作成、割り当て、更新、削除） | はい。 | はい。 


| プールとボリュームグループの管理（作成、更新、セキュリティの有効化、削除） | はい。 | はい。 


| ボリュームの管理（作成、サイズ変更、更新、削除） | はい。 | はい。 


| SSDキャッシュの管理（作成、更新、削除） | はい。 | はい。 


| ミラーリングとSnapshotの管理 | いいえ | はい。 


| ハードウェア管理（コントローラステータスの表示、ポート接続の設定、コントローラのオフライン化、ホットスペアの有効化、ドライブの消去、 など） | いいえ | はい。 


| アラートの管理（Eメール、SNMP、syslog） | いいえ | はい。 


| セキュリティキーの管理 | いいえ | はい。 


| コントローラの証明書管理 | いいえ | はい。 


| コントローラのアクセス管理（LDAP、SAMLなど） | いいえ | はい。 


| AutoSupport 管理 | いいえ | はい。 
|===