---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-increase-capacity-of-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ボリュームのサイズを変更してレポート容量を拡張します。 
---
= vCenter向けSANtricityストレージプラグインでのボリュームの容量の拡張
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ボリュームのサイズを変更して、レポート容量を拡張できます。

.作業を開始する前に
次の点を確認してください。

* ボリュームの関連付けられたプールまたはボリュームグループに十分な空き容量が必要です。
* ボリュームが最適状態で、変更中の状態ではありません。
* ボリュームでホットスペアドライブが使用されていない必要があります。（ボリュームグループ内のボリュームにのみ適用されます）。


.このタスクについて
このタスクでは、プールまたはボリュームグループ内の使用可能な空き容量を使用してボリュームのレポート容量（ホストに報告される容量）を拡張する方法について説明します。このプールまたはボリュームグループ内の他のボリュームについて、今後必要になる容量を考慮してください。


NOTE: ボリュームの容量の拡張は、特定のオペレーティングシステムでのみサポートされています。サポートされていないホストオペレーティングシステム上でボリューム容量を拡張すると、拡張した容量は使用できなくなり、元のボリューム容量をリストアすることもできなくなります。

.手順
. [* Manage *（管理）]ページで、サイズを変更するボリュームを含むストレージ・アレイを選択します。
. メニューを選択します。 Provisioning [ ボリュームの管理 ] 。
. 容量を拡張するボリュームを選択し、 * 容量を拡張 * を選択します。
+
容量の拡張の確認ダイアログボックスが表示されます。

. 続行するには、 * はい * を選択します。
+
レポート容量の拡張ダイアログボックスが表示されます。このダイアログボックスには、ボリュームの現在のレポート容量と、ボリュームの関連付けられたプールまたはボリュームグループ内で使用可能な空き容量が表示されます。

. レポート容量の拡張に使用できるレポート容量を追加するには、 * ボックスを使用します。メビバイト（ MiB ）、ギビバイト（ GiB ）、またはテビバイト（ TiB ）のいずれかで表示するように容量の値を変更できます。
. [* 拡大（ * ） ] をクリックします
+
選択に基づいて、ボリュームの容量が拡張されます。この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。



.完了後
ボリュームの容量を拡張したら、それに応じてファイルシステムのサイズを手動で拡張する必要があります。方法は、使用しているファイルシステムによって異なります。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。
