---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-the-settings-for-a-host.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ホストまたはホストクラスタの名前、ホストのオペレーティングシステムタイプ、および関連付けられているホストクラスタを変更できます。 
---
= ホストの設定を変更します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ホストまたはホストクラスタの名前、ホストのオペレーティングシステムタイプ、および関連付けられているホストクラスタを変更できます。

.手順
. Manage （管理）ページで、ホスト接続があるストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ホストの設定 ] 。
+
Configure Hosts ページが開きます。

. 編集するホストを選択し、*表示/設定の編集*をクリックします。
+
ダイアログボックスが開き、現在のホスト設定が表示されます。

. ホストのプロパティを変更するには、[プロパティ*]タブが選択されていることを確認し、必要に応じて設定を変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
名前
 a| 
ユーザが指定したホストの名前を変更できます。ホストの名前は必ず指定する必要があります。



 a| 
関連付けられているホストクラスタです
 a| 
次のいずれかのオプションを選択できます。

** *なし*--ホストはスタンドアロンホストのままです。ホストがホストクラスタに関連付けられている場合は、ホストがクラスタから削除されます。
** *<ホストクラスタ>*--選択したクラスタにホストを関連付けます




 a| 
ホストオペレーティングシステムのタイプ
 a| 
定義したホストで実行されているオペレーティングシステムのタイプを変更できます。

|===
====
. ポート設定を変更するには、[*ホストポート*]タブをクリックし、必要に応じて設定を変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
ホストポート
 a| 
次のいずれかのオプションを選択できます。

** *追加-- Addを使用して'新しいホストポート識別子をホストに関連付けますホストポート識別子名の長さは、ホストインターフェイスのテクノロジによって決まります。Fibre ChannelとInfiniBandのホストポート識別子名は、16文字にする必要があります。iSCSI のホストポート識別子名は最大 223 文字です。ポートは一意である必要があります。すでに設定されているポート番号は使用できません。
** *Delete *-- Deleteを使用して、ホストポート識別子を削除(関連付けを解除)します。Deleteオプションを使用しても、ホストポートは物理的には削除されません。このオプションを選択すると、ホストポートとホストの間の関連付けが削除されます。ホストバスアダプタまたは iSCSI イニシエータを削除しないかぎり、ホストポートは引き続きコントローラで認識されます。



CAUTION: ホストポート識別子を削除すると、そのホストとの関連付けが解除されます。また、ホストはホストに割り当てられているボリュームにこのホストポート識別子経由でアクセスできなくなります。



 a| 
ラベル
 a| 
ポートラベル名を変更するには、* Edit *アイコン（鉛筆）をクリックします。ポートラベル名は一意である必要があります。すでに設定されているラベル名は使用できません。



 a| 
CHAPシークレット
 a| 
iSCSIホストにのみ表示されます。イニシエータ（iSCSIホスト）のCHAPシークレットを設定または変更できます。システムは、チャレンジハンドシェイク認証プロトコル（CHAP）方式を使用します。CHAPは初回のリンク確立時にターゲットとイニシエータのIDを検証します。認証は、CHAPシークレットと呼ばれる共有セキュリティキーに基づいて行われます。

|===
====
. [ 保存（ Save ） ] をクリックします。

