---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-storage-configuration-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ストレージアレイから別のストレージアレイにストレージ構成をインポートします。 
---
= ストレージ構成の設定をインポートします
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ストレージアレイから別のストレージアレイにストレージ構成をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

.作業を開始する前に
次の点を確認してください。

* ソースとして使用するストレージアレイのストレージをSystem Managerで設定しておきます。
* ターゲットストレージアレイの既存の構成は、System Managerでバックアップされます（メニュー：[設定][システム]>[ストレージアレイ構成の保存]）。
* でストレージ構成のレプリケートに関する要件を確認しておく必要があります link:vc-olh-import-settings-overview.html["設定のインポートの概要"]。
* ソースアレイとターゲットアレイが次の要件を満たしている必要があります。
+
** コントローラが配置されているシェルフが同じである必要があります。
** シェルフIDが同じである必要があります。
** 拡張シェルフの同一のスロットに同じドライブタイプが搭載されている。
** RBODエンクロージャタイプが同一である。
** HICが、ホストのData Assurance機能を含めて同一である。
** ターゲットアレイのステータスが最適lである必要があります。
** ターゲットアレイのボリューム容量がソースアレイよりも大きい。


* 次の制限事項を理解しておきます。
+
** デュプレックス構成からシンプレックス構成へのインポートはサポートされていませんが、シンプレックス構成からデュプレックス構成へのインポートは可能です。
** ソースアレイのディスクプールのボリュームが64TB以上の場合、ターゲットでインポートプロセスを実行できない。




.このタスクについて
インポートされる設定には、設定済みのボリューム（リポジトリボリュームでないシックボリュームのみ）、ボリュームグループ、プール、およびホットスペアドライブの割り当てが含まれます。

.手順
. [管理]ページで、[メニュー]、[アクション]、[設定のインポート]の順にクリックします。
+
設定のインポートウィザードが開きます。

. 設定の選択ダイアログで、*ストレージ構成*を選択し、*次へ*をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. [ソースの選択]ダイアログで、インポートする設定のアレイを選択し、[次へ]をクリックします。
. ターゲットの選択ダイアログで'新しい設定を受信する1つまたは複数のアレイを選択します
+

NOTE: ファームウェアが8.50未満のストレージアレイは選択できません。また、プラグインがそのアレイと通信できない場合（オフラインの場合や、証明書、パスワード、ネットワークに問題がある場合など）、このダイアログにアレイは表示されません。

. [ 完了 ] をクリックします。
+
Operationsページには、インポート処理の結果が表示されます。処理が失敗した場合は、その行をクリックすると詳細を確認できます。



.結果
ターゲットストレージアレイのストレージ構成がソースアレイと同じに設定されます。
