---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-pool-manually.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: プールの自動構成の要件を満たしていない場合は、プールを手動で作成できます。プールは、論理的にグループ化された一連のドライブです。 
---
= vCenter向けSANtricityストレージプラグインでのプールの手動作成
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
プールの自動構成の要件を満たしていない場合は、プールを手動で作成できます。プールは、論理的にグループ化された一連のドライブです。

.作業を開始する前に
* ドライブタイプ（HDDまたはSSD）が同じドライブが少なくとも11本必要です。
* シェルフ損失の保護を有効にするには、プールを構成するドライブが少なくとも6つのドライブシェルフに配置されていて、同じシェルフのドライブが3本以上含まれていないことが必要です。
* ドロワー損失の保護を有効にするには、プールを構成するドライブが少なくとも5つのドロワーに同じ数ずつ配置されている必要があります。
* EF600またはEF300ストレージアレイを設定する場合は、各コントローラが最初の12個のスロットと直近の12個のスロットに同じ数のドライブにアクセスできることを確認します。この構成により、コントローラは両方のドライブ側PCIeバスをより効果的に使用できます。プールの作成には、ストレージアレイのすべてのドライブを使用する必要があります。


.このタスクについて
プールの作成時に、ドライブタイプ、セキュリティ機能、Data Assurance（DA）機能、シェルフ損失の保護、ドロワー損失の保護など、その特性を確認します。

EF600およびEF300ストレージアレイについては、リソースのプロビジョニングやボリュームのブロックサイズも設定に含まれます。

.手順
. [管理]ページで、プールのストレージアレイを選択します。
. メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。
. メニュー：[Create Pool（プールの作成）]をクリックします。
+
Create Pool（プールの作成）ダイアログボックスが表示されます。

. プールの名前を入力します。
. （オプション）ストレージアレイに複数のタイプのドライブがある場合、使用するドライブタイプを選択します。
+
作成可能なすべてのプールの候補が表示されます。

. 次の特性に基づいて使用するプール候補を選択し、*作成*をクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 特性 | 使用 


 a| 
空き容量
 a| 
プールの空き容量がGiB単位で表示されます。アプリケーションのストレージニーズに合わせて、容量の候補となるプールを選択します。予約済み（スペア）容量もプール全体に分散され、空き容量に含まれることはありません。



 a| 
合計ドライブ数
 a| 
プール候補に含まれるドライブの数が表示されます。できるだけ多くのドライブが予約済み容量として自動的に確保されます（プール内の6本につき1本のドライブが予約済み容量として確保されます）。ドライブ障害が発生すると、予約済み容量を使用して再構築されたデータが格納されます。



 a| 
ドライブブロックサイズ（EF300およびEF600のみ）
 a| 
プール内のドライブが書き込めるブロックサイズ（セクターサイズ）が表示されます。値は次のとおりです。

** 512 -- 512バイトのセクターサイズ。
** 4K -- 4、096バイトのセクターサイズ。




 a| 
セキュリティ対応
 a| 
プール候補がセキュリティ対応ドライブだけで構成されているかどうかを示します。セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。

** プールはドライブセキュリティを使用して保護できますが、この機能を使用するには、すべてのドライブがセキュリティ対応である必要があります。
** FDEのみのプールを作成する場合は、SecureCapable列で「* Yes-fde」を検索してください。FIPSのみのプールを作成する場合は、「はい- FIPS *」または「はい- FIPS（混在）」を探します。「Mixed」は140-2と140-3レベルのドライブが混在していることを示します。これらのレベルを組み合わせて使用する場合は、プールが下位レベルのセキュリティ（140～2）で動作することに注意してください。
** セキュリティ対応かどうかがドライブによって異なるプールや、セキュリティレベルが異なるドライブが混在したプールを作成することもできます。プールにセキュリティ対応でないドライブが含まれている場合、プールをセキュリティ対応にすることはできません。




 a| 
セキュリティを有効化
 a| 
セキュリティ対応ドライブでドライブセキュリティ機能を有効にするオプションです。プールがセキュリティ対応で、セキュリティキーを作成している場合、チェックボックスを選択してセキュリティを有効にできます。


NOTE: 一度有効にしたドライブセキュリティは、プールを削除してドライブを消去しないかぎり解除できません。



 a| 
DA対応
 a| 
プール候補でData Assurance（DA）を使用できるかどうかを示します。DAは、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。DAを使用する場合は、DAに対応したプールを選択します。このオプションはDA機能が有効になっている場合にのみ使用できます。プールにはDAに対応したドライブとDAに対応していないドライブを含めることができますが、DAを使用するためにはすべてのドライブがDAに対応している必要があります。



 a| 
リソースプロビジョニング対応（EF300およびEF600のみ）
 a| 
プール候補でリソースプロビジョニングを使用できるかどうかを示します。リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。



 a| 
シェルフ損失の保護
 a| 
シェルフ損失の保護が使用可能かどうかを示します。シェルフ損失の保護が有効な場合、1台のドライブシェルフとの通信が完全に失われた場合でもプール内のボリューム上のデータへのアクセスが保証されます。



 a| 
ドロワー損失の保護
 a| 
ドロワー損失の保護が使用可能かどうかを示します。この保護は、使用しているドライブシェルフにドロワーが搭載されている場合にのみ提供されます。ドロワー損失の保護が有効な場合、ドライブシェルフの1台のドロワーとの通信が完全に失われた場合でもプール内のボリューム上のデータへのアクセスが保証されます。



 a| 
サポートされるボリュームのブロックサイズ（EF300およびEF600のみ）
 a| 
プール内のボリュームに対して作成できるブロックサイズが表示されます。

** 512n -- 512バイトネイティブ。
** 512e -- 512バイトエミュレーション。
** 4k -- 4,096バイト


|===
====

