---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-delete-host-or-host-cluster.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ホストまたはホストクラスタを削除して、ボリュームがそのホストに関連付けられないようにすることができます。 
---
= ホストまたはホストクラスタを削除
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ホストまたはホストクラスタを削除して、ボリュームがそのホストに関連付けられないようにすることができます。

.このタスクについて
ホストまたはホストクラスタを削除する際は、次のガイドラインに注意してください。

* ボリュームの割り当てはすべて削除され、関連付けられたボリュームを新しい割り当てに使用できるようになります。
* ホストが属するホストクラスタに固有の割り当てがある場合、ホストクラスタへの影響はありません。ただし、ホストが属するホストクラスタに他の割り当てがない場合は、ホストクラスタとそれに関連付けられている他のすべてのホストまたはホストポート識別子にデフォルトの割り当てが継承されます。
* ホストに関連付けられていたホストポート識別子の定義は削除されます。


.手順
. Manage （管理）ページで、ホスト接続があるストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ホストの設定 ] 。
+
Configure Hosts ページが開きます。

. 削除するホストまたはホストクラスタを選択し、* Delete *をクリックします。
+
確認ダイアログボックスが表示されます。

. 処理を実行することを確認し、* Delete *をクリックします。


.結果
ホストを削除すると、システムは次の処理を実行します。

* ホストを削除し、該当する場合はホストクラスタからも削除します。
* 割り当てられているボリュームへのアクセスを削除します。
* 関連付けられているボリュームの割り当てを解除します。
* ホストに関連付けられているホストポート識別子の関連付けを解除します。ホストクラスタを削除すると、システムは次の処理を実行します。
+
** ホストクラスタとそれに関連付けられているホスト（存在する場合）を削除します。
** 割り当てられているボリュームへのアクセスを削除します。
** 関連付けられているボリュームの割り当てを解除します。
** ホストに関連付けられているホストポート識別子の関連付けを解除します。



