---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-know-about-host-block-size-requirements.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: EF300システムとEF600システムの場合は、ボリュームを設定して512バイトまたは4KiBのブロックサイズ（「セクターサイズ」とも呼ばれる）をサポートすることができます。ボリュームの作成時に正しい値を設定する必要があります。 
---
= ホストブロックサイズの要件について、どのような点に注意する必要がありますか？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
EF300システムとEF600システムの場合は、ボリュームを設定して512バイトまたは4KiBのブロックサイズ（「セクターサイズ」とも呼ばれる）をサポートすることができます。ボリュームの作成時に正しい値を設定する必要があります。可能であれば、適切なデフォルト値が推奨されます。

ボリュームのブロックサイズを設定する前に、次の制限事項とガイドラインを確認してください。

* 一部のオペレーティングシステムと仮想マシン（現時点ではVMwareなど）は512バイトのブロックサイズを必要とし、4KiBをサポートしないため、ボリュームを作成する前にホストの要件を確認してください。通常、最適なパフォーマンスを得るには、ボリュームを4KiBのブロックサイズに設定します。ただし、ホストで4KiB（または「4Kn」）のブロックを使用できることを確認します。
* プールまたはボリュームグループ用に選択したドライブのタイプによって、サポートされるボリュームブロックサイズも次のように決まります。
+
** 512バイトブロックに書き込むドライブを使用してボリュームグループを作成する場合、作成できるのは512バイトブロックのボリュームのみです。
** 4KiBブロックに書き込むドライブを使用してボリュームグループを作成する場合は、512バイトまたは4KiBブロックでボリュームを作成します。


* アレイにiSCSIホストインターフェイスカードが搭載されている場合、すべてのボリュームは（ボリュームグループのブロックサイズに関係なく）512バイトブロックに制限されます。これは、特定のハードウェアの実装が原因です。
* 一度設定したブロックサイズは変更できません。ブロックサイズを変更する必要がある場合は、ボリュームを削除して再作成する必要があります。

