---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-why-are-some-drives-not-showing-up.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 容量の追加ダイアログで、既存のプールまたはボリュームグループに容量を追加できるドライブがすべて表示されるわけではありません。 
---
= 一部のドライブが表示されないのはなぜですか？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
容量の追加ダイアログで、既存のプールまたはボリュームグループに容量を追加できるドライブがすべて表示されるわけではありません。

ドライブを追加できない理由は次のとおりです。

* 未割り当てで、セキュリティ有効でないドライブを指定する必要があります。すでに別のプールやボリュームグループに含まれているドライブ、またはホットスペアとして設定されているドライブは使用できません。未割り当てだが、セキュリティ有効なドライブは、手動で消去すると使用可能になります。
* 最適な状態でないドライブは使用できません。
* 容量が小さすぎるドライブは使用できません。
* プールまたはボリュームグループ内でドライブのメディアタイプが一致している必要があります。次のものを混在させることはできません。
+
** ソリッドステートディスク（SSD）搭載のハードディスクドライブ（HDD）
** NVMeとSASドライブ
** ボリュームブロックサイズが512バイトおよび4KiBのドライブ


* プールまたはボリュームグループに含まれているドライブがすべてセキュリティ対応の場合は、セキュリティ対応でないドライブは表示されません。
* プールまたはボリュームグループに含まれているドライブがすべて連邦情報処理標準（FIPS）ドライブの場合、非FIPSドライブは表示されません。
* プールまたはボリュームグループに含まれているドライブがすべてData Assurance（DA）対応で、プールまたはボリュームグループにDA有効ボリュームが1つ以上ある場合は、DA非対応のドライブは使用できないためプールまたはボリュームグループに追加できません。ただし、プールまたはボリュームグループにDA有効ボリュームがない場合は、DA非対応のドライブをプールまたはボリュームグループに追加できます。DA対応と非対応のドライブが混在している場合は、DA対応ボリュームを作成できないことに注意してください。



NOTE: ストレージアレイの容量は、新しいドライブを追加するか、プールまたはボリュームグループを削除することで増やすことができます。
