---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-initialize-volumes.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 特定の障害状況からリカバリするために、ボリュームを手動で初期化します。 
---
= vCenter向けSANtricityストレージプラグインでのボリュームの初期化
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ボリュームは、最初に作成されるときに自動的に初期化されます。ただし、一定の障害状況からリカバリするために、ボリュームを手動で初期化するようRecovery Guruから指示される場合があります。

このオプションを使用する場合は、必ずテクニカルサポートの指示に従ってください。初期化するボリュームは1つ以上選択できます。

.作業を開始する前に
* すべてのI/O処理を停止しておきます。
* 初期化するボリューム上のデバイスまたはファイルシステムをすべてアンマウントしておく必要があります。
* ボリュームは最適状態であり、ボリュームで変更処理が実行されていません。*注意：*開始後に処理をキャンセルすることはできません。ボリュームのすべてのデータが消去されます。Recovery Guruの指示があった場合を除き、この処理は実行しないでください。この手順 を開始する前に、テクニカルサポートにお問い合わせください。


.このタスクについて
ボリュームを初期化しても、ボリュームのWWN、ホストの割り当て、割り当て済み容量、およびリザーブ容量の設定は保持されます。Data Assurance（DA）設定とセキュリティ設定も同じままです。

次のタイプのボリュームは初期化できません。

* Snapshotボリュームのベースボリューム
* ミラー関係のプライマリボリューム
* ミラー関係のセカンダリボリューム
* ボリュームコピーのソースボリューム
* ボリュームコピーのターゲットボリューム
* すでに初期化が進行中のボリューム


この手順 は、プールまたはボリュームグループから作成された標準ボリュームにのみ適用されます。

.手順
. 管理ページで、初期化するボリュームを含むストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ボリュームの管理 ] 。
. 任意のボリュームを選択し、メニューを選択します。More [Initialize volumes]。
+
Initialize Volumes（ボリュームの初期化）ダイアログボックスが表示されます。このダイアログボックスには、ストレージアレイ上のすべてのボリュームが表示されます。

. 初期化するボリュームを1つ以上選択し、処理を確定します。


.結果
システムは次の処理を実行します。

* 初期化されたボリュームからすべてのデータが消去されます。
* ブロックインデックスがクリアされます。これにより、書き込み前のブロックはゼロで埋められているかのように読み取られます（ボリュームは完全に空のように表示されます）。


この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。
