---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-delete-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: プールまたはボリュームグループの空き容量を増やすには、1つ以上のボリュームを削除してください。 
---
= ボリュームを削除します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
1つ以上のボリュームを削除して、プールまたはボリュームグループの空き容量を増やすことができます。

.作業を開始する前に
削除するボリュームで、次の点を確認します。

* すべてのデータがバックアップされます。
* すべての入出力（I/O）が停止しています。
* デバイスとファイルシステムがアンマウントされている。


.このタスクについて
通常、作成したボリュームのパラメータや容量が正しくない場合、またはストレージ構成のニーズを満たさなくなった場合に、ボリュームを削除します。ボリュームを削除すると、プールまたはボリュームグループの空き容量が増えます。


CAUTION: ボリュームを削除すると、それらのボリューム上のすべてのデータが失われます。

次のいずれかの条件に該当するボリュームは、*削除できない*ことに注意してください。

* ボリュームが初期化中である。
* ボリュームが再構築中である。
* ボリュームが属するボリュームグループにコピーバック処理を実行中のドライブが含まれている。
* ボリュームのステータスが失敗になった場合を除き、セグメントサイズの変更などの変更処理を実行中です。
* ボリュームにいずれかのタイプの永続的予約が設定されている。
* ボリュームがボリュームコピー処理のソースボリュームまたはターゲットボリュームで、処理のステータスが「保留」、「実行中」、または「失敗」である。



NOTE: ボリュームのサイズが指定したサイズ（現在は128TB）を超えると、削除処理がバックグラウンドで実行され、解放されたスペースをすぐに使用できなくなることがあります。

.手順
. [* Manage *（管理）]ページで、削除するボリュームを含むストレージ・アレイを選択します。
. メニューを選択します。 Provisioning [ ボリュームの管理 ] 。
. [ 削除（ Delete ） ] をクリックします。
+
ボリュームの削除ダイアログボックスが表示されます。

. 削除するボリュームを1つ以上選択し、処理を確定します。
. [ 削除（ Delete ） ] をクリックします。

