---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-settings-for-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ボリュームの名前、ホストの割り当て、セグメントサイズ、変更の優先順位、キャッシュ、 など。 
---
= ボリュームの設定を変更します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ボリュームの名前、ホストの割り当て、セグメントサイズ、変更の優先順位、キャッシュなど、ボリュームの設定を変更できます。 など。

.作業を開始する前に
変更するボリュームのステータスが「最適」であることを確認してください。

.手順
. 管理ページで、変更するボリュームが含まれているストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ボリュームの管理 ] 。
. 変更するボリュームを選択し、*表示/設定の編集*を選択します。
+
Volume Settings（ボリューム設定）ダイアログボックスが表示されます。選択したボリュームの設定がこのダイアログボックスに表示されます。

. ボリュームの名前とホストの割り当てを変更するには、* Basic *タブを選択します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
名前
 a| 
ボリュームの名前が表示されます。現在の名前が適切でない場合はボリュームの名前を変更します。



 a| 
容量
 a| 
選択したボリュームのレポート容量と割り当て容量が表示されます。



 a| 
プール/ボリュームグループ
 a| 
プールまたはボリュームグループの名前とRAIDレベルが表示されます。プールまたはボリュームグループがセキュリティ対応か、およびセキュリティ有効かを示します。



 a| 
ホスト
 a| 
ボリュームの割り当てが表示されます。I/O処理でボリュームにアクセスできるように、ボリュームをホストまたはホストクラスタに割り当てます。これにより、ストレージアレイ内の特定のボリューム、または複数のボリュームへのアクセスがホストまたはホストクラスタに許可されます。

** *割り当て先*--選択したボリュームにアクセスできるホストまたはホストクラスタを指定します
** * lun *：ホストがボリュームへのアクセスに使用するアドレス・スペースに割り当てられる番号ボリュームは、LUNの形式でホストに容量として提示されます。各ホストには独自のLUNアドレススペースがあります。したがって、同じLUNを複数のホストで使用して、異なるボリュームにアクセスできます。


NVMeインターフェイスの場合、この列にはネームスペースIDが表示されます。ネームスペースは、ブロックアクセス用にフォーマットされたNVMストレージです。SCSIの論理ユニットに相当し、ストレージアレイではボリュームに関連します。ネームスペースIDは、NVMeコントローラのネームスペースの一意の識別子です。1~255の値を設定できます。SCSIの論理ユニット番号（LUN）に相当します。



 a| 
識別子
 a| 
選択したボリュームの識別子が表示されます。

** World-Wide Identifier（WWID）。ボリュームの一意の16進数の識別子。
** Extended Unique Identifier（EUI）。ボリュームのEUI-64識別子。
** サブシステム識別子（SSID）。ボリュームのストレージアレイサブシステムの識別子。


|===
====
. プールまたはボリュームグループ内のボリュームの追加設定を変更するには、*詳細*タブを選択します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
アプリケーションとワークロードの情報
 a| 
ボリュームの作成時に、アプリケーション固有のワークロードまたはその他のワークロードを作成できます。該当する場合は、選択したボリュームのワークロード名、アプリケーションタイプ、およびボリュームタイプが表示されます。ワークロード名は必要に応じて変更できます。



 a| 
QoS設定
 a| 
* Data Assuranceを永続的に無効にする*-この設定は、ボリュームがData Assurance（DA）対応の場合にのみ表示されます。DAは、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。選択したボリュームのDAを完全に無効にする場合は、このオプションを使用します。DAは無効にすると再度有効にすることはできません。*読み取り前冗長性チェックを有効にする*--この設定は'ボリュームがシックボリュームの場合にのみ表示されます読み取り前冗長性チェックは、読み取りの実行時にボリュームのデータの整合性を確認する機能です。この機能を有効にしたボリュームでは、コントローラファームウェアによってデータに整合性がないと判断されると読み取りエラーを返します。



 a| 
コントローラ所有権
 a| 
ボリュームを所有するプライマリコントローラを定義します。コントローラ所有権は非常に重要であり、慎重に計画する必要があります。コントローラ間で総I/O数をできるだけ均等に分散する必要があります。



 a| 
セグメントサイジング
 a| 
セグメントのサイジングに関する設定が表示されます。これは、ボリュームグループのボリュームについてのみ表示されます。セグメントサイズを変更することでパフォーマンスを最適化することができます。*許容されるセグメントサイズの推移*-許容されるセグメントサイズの推移がシステムによって決定されます。現在のセグメントサイズの変更後のサイズとして適切でないものは、ドロップダウンリストに表示されません。通常、許容される変更後のサイズは、現在のセグメントサイズの倍または半分です。たとえば、ボリュームの現在のセグメントサイズが 32KiB であれば、ボリュームの新しいセグメントサイズとして 16KiB または 64KiB が許容されます。* SSDキャッシュが有効なボリューム*- SSDキャッシュが有効なボリュームでは、セグメントサイズを4KiBに指定することができます。4KiB のセグメントサイズを選択するのは、 SSD キャッシュが有効なボリュームで小さいブロックの I/O 処理を実行する（ I/O ブロックサイズが 16KiB 以下の場合など）場合のみにしてください。SSD キャッシュが有効なボリュームで大きいブロックのシーケンシャル処理を実行する場合は、セグメントサイズとして 4KiB を選択するとパフォーマンスが低下することがあります。*セグメントサイズの変更にかかる時間。*ボリュームのセグメントサイズの変更にかかる時間は、次の要因によって異なります。

** ホストからの I/O 負荷
** ボリュームの修正の優先順位
** ボリュームグループ内のドライブの数
** ドライブチャネルの数
** ストレージアレイコントローラの処理能力


ボリュームのセグメントサイズを変更すると I/O パフォーマンスに影響しますが、データの可用性は維持されます。



 a| 
修正の優先順位
 a| 
変更優先度の設定が表示されます。これは、ボリュームグループ内のボリュームについてのみ表示されます。変更優先度は、ボリュームの変更処理にどの程度の処理時間を割り当てるかをシステムパフォーマンスに対する相対的な優先度として定義したものです。修正の優先順位を上げると、システムパフォーマンスが低下する場合があります。優先度レベルを選択するには、スライダバーを動かします。*修正の優先順位率*--優先順位が最も低いとシステムのパフォーマンスは向上しますが、修正操作にかかる時間は長くなります。優先度を最も高くすると修正処理にかかる時間は短縮されますが、システムパフォーマンスが低下する可能性があります。



 a| 
キャッシュ
 a| 
キャッシュ設定が表示されます。この設定を変更すると、ボリュームの全体的なI/Oパフォーマンスを向上させることができます。



 a| 
SSD キャッシュ
 a| 
（この機能はEF600またはEF300ストレージシステムでは使用できません）。 SSDキャッシュの設定が表示されます。互換性のあるボリュームでこの設定を有効にすると、読み取り専用のパフォーマンスが向上します。互換性があるのは、同じドライブセキュリティ機能とData Assurance機能を共有しているボリュームです。SSDキャッシュ機能は、1つまたは複数のソリッドステートディスク（SSD）を使用して読み取りキャッシュを実装します。SSDの読み取り時間が速くなるため、アプリケーションパフォーマンスが向上します。読み取りキャッシュはストレージアレイ内にあるため、ストレージアレイを使用するすべてのアプリケーションでキャッシュが共有されます。キャッシュするボリュームを選択すると、あとは動的に自動でキャッシングが実行されます。

|===
====
. [ 保存（ Save ） ] をクリックします。


.結果
選択内容に基づいてボリューム設定が変更されます。
