---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-consolidate-free-capacity-for-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 選択したボリュームグループ上の既存の空きエクステントを統合するには、空き容量の統合オプションを使用します。この操作を実行すると、追加ボリュームを作成する際にボリュームグループ内の空き容量を最大限使用できるようになります。 
---
= ボリュームグループの空き容量を統合します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
選択したボリュームグループ上の既存の空きエクステントを統合するには、空き容量の統合オプションを使用します。この操作を実行すると、追加ボリュームを作成する際にボリュームグループ内の空き容量を最大限使用できるようになります。

.作業を開始する前に
* ボリュームグループに少なくとも1つの空き容量領域が含まれている必要があります。
* ボリュームグループ内のすべてのボリュームがオンラインで、ステータスが最適lである必要があります。
* ボリュームのセグメントサイズの変更など、実行中のボリューム変更処理がないことを確認してください。


この処理は開始後にキャンセルすることはできません。統合処理の実行中もデータには引き続きアクセスできます。

次のいずれかの方法を使用して、[Consolidate Free Capacity]ダイアログボックスを起動できます。

* ボリュームグループに対して1つ以上の空き容量領域が検出されると、通知領域のホームページに空き容量の統合に関する推奨事項が表示されます。[*空き容量の統合*（Consolidate free capacity）]リンクをクリックして、ダイアログボックスを起動します。
* 次のタスクで説明するように、[Pools & Volume Groups]ページから[Consolidate Free Capacity]ダイアログボックスを起動することもできます。


.空き容量領域についての詳細はこちらをご覧ください
====
空き容量領域は、ボリュームを削除した場合や、ボリュームの作成時に使用可能なすべての空き容量を使用しなかった場合に発生する空き容量です。1つ以上の空き容量領域があるボリュームグループでボリュームを作成する場合、ボリュームの容量はそのボリュームグループ内で最も大きい空き容量領域以内に制限されます。たとえば、ボリュームグループに合計15GiBの空き容量があり、最も大きい空き容量領域が10GiBであるとすると、作成できるボリュームのサイズは最大10GiBです。

ボリュームグループの空き容量を統合すると、書き込みパフォーマンスが向上します。ボリュームグループの空き容量は、ホストがファイルを書き込み、変更、削除するうちに徐々に断片化されていきます。最終的に、使用可能な容量は1つの連続したブロックに存在するのではなく、小さなフラグメントに分断されてボリュームグループ全体に分散した状態になります。これにより、ホストは新しいファイルを空きクラスタの使用可能な範囲に収まるフラグメントとして書き込む必要があるため、ファイルの断片化がさらに進みます。

選択したボリュームグループの空き容量を統合することで、ホストが新しいファイルを書き込む際のファイルシステムのパフォーマンスが向上します。また、統合プロセスは、新しいファイルが以降に断片化されないようにするのにも役立ちます。

====
.手順
. 管理ページで、ボリュームグループを含むストレージアレイを選択します。
. メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。
. 統合する空き容量があるボリュームグループを選択し、メニューから「Uncommon Tasks [ボリュームグループの空き容量を統合する]」を選択します。
+
[Consolidate Free Capacity]ダイアログボックスが表示されます。

. この操作を実行するかどうかを確認するには'consolidateと入力します
. [*統合（Consolidate）]をクリックし


ボリュームグループの空き容量領域の統合（デフラグ）が開始され、以降のストレージ設定タスク用に1つの連続した容量になります。

ナビゲーションサイドバーで、* Operations *を選択して、空き容量の統合操作の進行状況を表示します。この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。
