---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-upgrade-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 同じタイプの複数のストレージアレイのSANtricity ソフトウェアとNVSRAMのアップグレードを管理できます。 
---
= アップグレードの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter向けストレージプラグインでは、同じタイプの複数のストレージアレイのSANtricity ソフトウェアとNVSRAMのアップグレードを管理できます。



== アップグレードワークフロー

以下に、ソフトウェアのアップグレードを実行するための大まかなワークフローを示します。

. 最新のSANtricity OSファイルをサポートサイトからダウンロードします（リンクはサポートページから入手できます）。管理ホストシステム（ブラウザでプラグインにアクセスするホスト）にファイルを保存し、ファイルを解凍します。
. プラグインでは、SANtricity OSソフトウェアファイルとNVSRAMファイルをリポジトリ（ファイルが格納されているサーバの領域）にロードできます。
. リポジトリにファイルをロードしたら、アップグレードに使用するファイルを選択できます。SANtricity OSソフトウェアのアップグレードページで、OSソフトウェアファイルとNVSRAMファイルを選択します。ソフトウェアファイルを選択すると、互換性があるストレージアレイのリストがこのページに表示されます。次に、新しいソフトウェアでアップグレードするストレージアレイを選択します。（互換性のないアレイは選択できません）。
. ソフトウェアの転送とアクティブ化をすぐに開始することも、ファイルをステージングしてあとでアクティブ化することもできます。アップグレードプロセス中に、プラグインは次のタスクを実行します。
+
** ストレージアレイの健全性チェックが実行され、アップグレードの完了の妨げとなる状況がないかどうかが確認されます。健全性チェックでいずれかのアレイに問題が見つかった場合は、そのアレイをスキップして他のアレイのアップグレードを続行するか、プロセス全体を停止して該当するアレイのトラブルシューティングを行うことができます。
** 各コントローラにアップグレードファイルが転送されます。
** コントローラが一度に1台ずつリブートされ、新しいOSソフトウェアがアクティブ化されます。アクティブ化の際に、既存のOSファイルが新しいファイルに置き換えられます。





NOTE: ソフトウェアをあとでアクティブ化するように指定することもできます。



== アップグレード時の考慮事項

複数のストレージアレイをアップグレードする場合は、計画段階で主な考慮事項を確認してください。



=== 現在のバージョン

検出された各ストレージアレイについて、vCenter向けストレージプラグインの管理ページからSANtricity OSの現在のソフトウェアバージョンを表示できます。バージョンはSANtricity OSソフトウェア列に表示されます。各行のOSのバージョンをクリックするとポップアップダイアログボックスが表示され、コントローラのファームウェアとNVSRAMの情報を確認できます。



=== アップグレードが必要なその他のコンポーネント

アップグレードプロセスの一環として、ホストがコントローラと正しく連携するように、ホストのマルチパス/フェイルオーバードライバやHBAドライバのアップグレードも必要になることがあります。互換性の情報については、を参照してください link:https://imt.netapp.com/matrix/["Interoperability Matrix Tool で確認してください"^]。



=== デュアルコントローラ

ストレージアレイにコントローラが 2 台あり、マルチパスドライバがインストールされている場合は、アップグレードの実行中もストレージアレイで I/O の処理を継続できます。アップグレードの実行中は、次の処理が実行されます。

. コントローラ A のすべての LUN がコントローラ B にフェイルオーバーされます
. コントローラ A でアップグレードが実行されます
. コントローラ A に LUN が戻され、コントローラ B の LUN もすべて移されます。
. コントローラ B でアップグレードが実行されます


アップグレードの完了後、所有権のある正しいコントローラにボリュームが配置されるように、コントローラ間で手動でのボリュームの再配置が必要になることがあります。
