---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-unassign-volumes.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ボリュームへのI/Oアクセスが不要になった場合は、ホストまたはホストクラスタへの割り当てを解除できます。 
---
= ボリュームの割り当てを解除する
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ボリュームへのI/Oアクセスが不要になった場合は、ホストまたはホストクラスタへの割り当てを解除できます。

.このタスクについて
ボリュームの割り当てを解除する際は、次のガイドラインに注意してください。

* 最後に割り当てたボリュームをホストクラスタから削除する際に、特定のボリュームが割り当てられているホストがホストクラスタにある場合は、最後に割り当てたボリュームを削除する前にホストに割り当てられたボリュームを削除または移動してください。
* ホストクラスタ、ホスト、またはホストポートがオペレーティングシステムに登録されたボリュームに割り当てられている場合は、その登録をクリアしてからこれらのノードを削除する必要があります。


.手順
. Manage （管理）ページで、ホスト接続があるストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ホストの設定 ] 。
+
Configure Hosts ページが開きます。

. 編集するホストまたはホストクラスタを選択し、*ボリュームの割り当て解除*をクリックします。
+
現在割り当てられているすべてのボリュームを示すダイアログボックスが表示されます。

. 割り当てを解除する各ボリュームの横にあるチェックボックスを選択するか、テーブルヘッダーにあるチェックボックスを選択してすべてのボリュームを選択します。
. Unassign *をクリックします。


.結果
* 割り当てを解除したボリュームは新しい割り当てに使用できます。
* 変更がホストで設定されるまで、ボリュームは引き続きホストオペレーティングシステムで認識されます。

