---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-check-volume-redundancy.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: プールまたはボリュームグループ内のボリュームの冗長性をチェックして、そのボリューム上のデータに整合性があるかどうかを確認できます。冗長性データは、プールまたはボリュームグループ内のいずれかのドライブで障害が発生した場合に、交換用ドライブに迅速に情報を再構築するために使用されます。 
---
= ボリュームの冗長性をチェックします
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
テクニカルサポートから指示があった場合やRecovery Guruに記載されている場合は、プールまたはボリュームグループ内のボリュームの冗長性をチェックし、そのボリュームのデータに整合性があるかどうかを確認できます。

冗長性データは、プールまたはボリュームグループ内のいずれかのドライブで障害が発生した場合に、交換用ドライブに迅速に情報を再構築するために使用されます。

.作業を開始する前に
* プールまたはボリュームグループのステータスが最適である必要があります。
* プールまたはボリュームグループで実行中の変更処理がないことを確認する必要があります。
* RAID 0にはデータの冗長性がないため、RAID 0以外のすべてのRAIDレベルで冗長性をチェックできます。（プールはRAID 6としてのみ構成されます）。



NOTE: ボリュームの冗長性チェックは、Recovery Guruに記載されている場合にかぎり、テクニカルサポートの指示に従って実行してください。

このチェックは、一度に1つのプールまたはボリュームグループでのみ実行できます。ボリュームの冗長性チェックでは、次の処理が実行されます。

* RAID 3ボリューム、RAID 5ボリューム、またはRAID 6ボリューム内のデータブロックがスキャンされ、各ブロックの冗長性情報がチェックされます。（RAID 3をボリュームグループに割り当てるには、コマンドラインインターフェイスを使用する必要があります）。
* RAID 1のミラーリングされたドライブ上のデータブロックが比較されます。
* コントローラファームウェアがデータに整合性がないと判断した場合は、冗長性エラーが返されます。



NOTE: 同じプールまたはボリュームグループですぐに冗長性チェックを実行すると、原因 でエラーが発生する場合があります。この問題を回避するには、同じプールまたはボリュームグループで別の冗長性チェックを実行する前に、1~2分待ってください。

.手順
. 管理ページで、プールまたはボリュームグループを含むストレージアレイを選択します。
. メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。
. メニューから[一般的でないタスク]を選択します。[ボリュームの冗長性をチェック]。
+
[Check Redundancy]ダイアログボックスが表示されます。

. チェックするボリュームを選択し、checkと入力して、この処理を実行することを確定します。
. [*チェック（Check）]をクリックする。
+
ボリュームの冗長性チェック処理が開始されます。プールまたはボリュームグループ内のボリュームが、ダイアログボックスの表の一番上から順番にスキャンされます。各ボリュームがスキャンされるたびに、次の操作が実行されます。

+
** ボリュームテーブルでボリュームが選択されます。
** 冗長性チェックのステータスがStatus列に表示されます。
** メディアエラーまたはパリティエラーが発生するとチェックが停止され、エラーが報告されます。次の表に、冗長性チェックのステータスの詳細を示します。


+
.フィールドの詳細
====
[cols="25h,~"]
|===
| ステータス | 説明 


| 保留中です | これはスキャン対象の最初のボリュームです。冗長性チェックを開始するには、Start（開始）をクリックしていません。-or -プールまたはボリュームグループ内の他のボリュームで冗長性チェック処理が実行されています。 


| チェック中です | ボリュームは冗長性チェック中です。 


| 合格 | ボリュームは冗長性チェックにパスしました。冗長性情報に不整合は見つかりませんでした。 


| 失敗しました | ボリュームは冗長性チェックに失敗しました。冗長性情報に不整合が見つかりました。 


| メディアエラー | ドライブメディアが故障しており、読み取り不能です。Recovery Guruに表示される手順に従います。 


| パリティエラー | データの一部でパリティが想定される値ではありません。パリティエラーは深刻な問題を招く可能性があり、原因 によってデータが永久に失われる可能性があります。 
|===
====
. プールまたはボリュームグループ内の最後のボリュームをチェックした後、「* Done *」をクリックします。

