---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-provisioning-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ホストがアレイのストレージにアクセスできるように、ボリュームと呼ばれるデータコンテナを作成できます。 
---
= vCenter向けSANtricityストレージプラグインでのストレージのプロビジョニングについて
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter向けストレージプラグインでは、ボリュームと呼ばれるデータコンテナを作成して、ホストがアレイ上のストレージにアクセスできるようにすることができます。



== ボリュームのタイプと特性

ボリュームは、ストレージアレイ上のストレージスペースを管理および編成するデータコンテナです。

ストレージアレイで使用可能なストレージ容量からボリュームを作成すると、システムのリソースを整理するのに役立ちます。「ボリューム」という概念は、コンピュータ上のフォルダやディレクトリを使用してファイルにすばやくアクセスできるようにする方法に似ています。

ボリュームは、ホストから認識できる唯一のデータレイヤです。SAN 環境では、ボリュームは論理ユニット番号（ LUN ）にマッピングされます。これらのLUNは、FC、iSCSI、SASなど、ストレージアレイでサポートされている1つ以上のホストアクセスプロトコルを使用してアクセス可能なユーザデータを保持します。

プールまたはボリュームグループ内の各ボリュームには、格納されるデータのタイプに基づいて独自の特性があります。たとえば、次のような特性があります。

* *セグメントサイズ*-セグメントは、あるドライブに格納されるデータの量（KiB）です。この量に達すると、ストライプ（RAIDグループ）内の次のドライブへと進みます。セグメントサイズは、ボリュームグループの容量と同じかそれよりも小さくなります。プールのセグメントサイズは固定で、変更することはできません。
* *容量*-プールまたはボリュームグループの空き容量からボリュームを作成します。ボリュームを作成するには、プールまたはボリュームグループがすでに存在している必要があります。また、ボリュームを作成するための十分な空き容量がプールまたはボリュームグループに必要です。
* *コントローラ所有権*--すべてのストレージアレイは'1台または2台のコントローラを持つことができますシングルコントローラアレイでは、ボリュームのワークロードは単一のコントローラによって管理されます。デュアルコントローラアレイでは、ボリュームを「所有」する優先コントローラ（AまたはB）がボリュームに割り当てられます。デュアルコントローラ構成では、自動ロードバランシング機能を使用してボリューム所有権が自動的に調整され、コントローラ間でワークロードが移動する際の負荷の不均衡が解消されます。自動ロードバランシングはI/Oワークロードを自動的に分散する機能を提供し、ホストからの受信I/Oトラフィックは動的に管理されて両方のコントローラに分散されます。
* *ボリューム割り当て*--ボリュームの作成時または後で、ホストにボリュームへのアクセス権を与えることができます。すべてのホストアクセスは、論理ユニット番号（LUN）を使用して管理されます。ホストは、ボリュームに割り当てられているLUNを検出します。ボリュームを複数のホストに割り当てる場合は、クラスタリングソフトウェアを使用して、すべてのホストからボリュームを使用できるようにしてください。
+
ホストタイプでは、ホストがアクセスできるボリュームの数に制限がある場合があります。特定のホストで使用するボリュームを作成するときは、この制限に注意してください。

* *リソースプロビジョニング*-- EF600またはEF300ストレージアレイでは、バックグラウンド初期化プロセスなしですぐにボリュームを使用するように指定できます。リソースプロビジョニングボリュームは、SSDグループまたはプール内のシックボリュームです。ボリュームの作成時にはドライブ容量が割り当てられますが（ボリュームに割り当てられます）、ドライブブロックは割り当て解除されます（マッピング解除されます）。
* *わかりやすい名前*--ボリュームに任意の名前を付けることができますが、わかりやすい名前にすることをお勧めします。


ボリュームの作成時には、各ボリュームに容量が割り当てられ、名前、セグメントサイズ（ボリュームグループの場合のみ）、コントローラ所有権、およびボリュームとホストの割り当てが指定されます。ボリュームデータは、必要に応じてコントローラ間で自動的に負荷分散されます。



== ボリュームの容量

ストレージアレイ内のドライブは、データに対して物理ストレージ容量を提供します。データの格納を開始する前に、プールまたはボリュームグループと呼ばれる論理コンポーネントに割り当て容量を設定する必要があります。これらのストレージオブジェクトを使用して、ストレージアレイのデータを設定、格納、メンテナンス、および保持できます。



=== ボリュームの作成および拡張に必要な容量

プールまたはボリュームグループ内の未割り当て容量または空き容量からボリュームを作成できます。

* 未割り当て容量からボリュームを作成する場合は、プールまたはボリュームグループとボリュームを同時に作成できます。
* 空き容量からボリュームを作成する場合は、既存のプールまたはボリュームグループに追加のボリュームを作成します。ボリュームの容量を拡張したら、それに一致するようにファイルシステムのサイズを手動で拡張する必要があります。方法は、使用しているファイルシステムによって異なります。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。



NOTE: プラグインインターフェイスには、シンボリュームを作成するオプションはありません。



=== ボリュームのレポート容量

ボリュームのレポート容量は、割り当てられている物理ストレージ容量と同じです。物理ストレージ容量全体が存在している必要があります。物理的に割り当てられるスペースは、ホストに報告されるスペースと同じです。

通常は、ボリュームのレポート容量を、ボリュームが拡張すると予想される最大容量に設定します。ボリュームは、予測可能な高パフォーマンスをアプリケーションに提供します。これは主に、すべてのユーザ容量が作成時に予約されて割り当てられているためです。



=== 容量制限

ボリュームの最小容量は1MiBであり、最大容量はプールまたはボリュームグループ内のドライブの数と容量で決まります。

ボリュームのレポート容量を拡張するときは、次のガイドラインに注意してください。

* 小数点以下3桁まで指定できます（例：65.375GiB）。
* ボリュームグループで使用可能な最大値以下の容量を指定してください。ボリュームを作成する場合は、セグメントサイズの動的（DSS）変更のための追加容量が事前に割り当てられます。DSS変更は、ボリュームのセグメントサイズを変更できるソフトウェアの機能です。
* 一部のホストオペレーティングシステムでは、2TiBを超えるボリュームがサポートされます（最大レポート容量はホストオペレーティングシステムで決定されます）。実際には、一部のホストオペレーティングシステムでサポートされるのは最大128TiBのボリュームです。詳細については、ホストオペレーティングシステムのドキュメントを参照してください。




== アプリケーション固有のワークロード

ボリュームを作成する際には、ワークロードを選択して特定のアプリケーション用にストレージアレイの構成をカスタマイズします。

ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロードまたはインスタンスを定義できます。一部のアプリケーションでは、特性が似たボリュームで構成されるようにワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。

ボリュームの作成中に、ワークロードの使用に関する回答 の質問が表示されます。たとえば、Microsoft Exchange用のボリュームを作成する場合は、必要なメールボックスの数、メールボックスに必要とされる平均容量、およびデータベースのコピーをいくつ作成するかについて設定します。この情報に基づいて最適なボリューム構成が作成されるため、必要に応じて編集することができます。必要に応じて、ボリューム作成のこの手順をスキップできます。



=== ワークロードのタイプ

アプリケーション固有とその他の2種類のワークロードを作成できます。

* *アプリケーション固有*--アプリケーション固有のワークロードを使用してボリュームを作成する場合、アプリケーションワークロードのI/Oとアプリケーションインスタンスからの他のトラフィックの競合を最小限に抑えるために最適化されたボリューム構成が推奨される場合があります。I/Oタイプ、セグメントサイズ、コントローラ所有権、読み取り/書き込みキャッシュなどのボリューム特性が自動的に推奨され、次のアプリケーションタイプ用に作成されるワークロードに合わせて最適化されます。
+
** Microsoft SQL Server の場合
** Microsoft Exchange Server の略
** ビデオ監視アプリケーション
** VMware ESXi（ボリュームをVirtual Machine File Systemで使用する場合）
+
ボリュームの追加/編集ダイアログボックスを使用して、推奨されるボリューム構成を確認し、システムで推奨されるボリュームや特性を編集、追加、削除できます。



* *その他（または特定のボリューム作成サポートのないアプリケーション）*- 特定のアプリケーションに関連付けられていないワークロードを作成する場合や、ストレージアレイで使用する予定のアプリケーションに対する最適化が組み込まれていない場合は、その他のワークロードではボリューム構成を手動で指定する必要があります。ボリュームの追加/編集ダイアログボックスを使用して、ボリューム構成を手動で指定する必要があります。




=== アプリケーションとワークロードの表示

アプリケーションとワークロードを表示するには、System Managerを起動します。このインターフェイスから、アプリケーション固有のワークロードに関連する情報をいくつかの方法で表示できます。

* ボリュームタイルのアプリケーションとワークロードタブを選択すると、ストレージアレイのボリュームをワークロード別にグループ化し、ワークロードが関連付けられているアプリケーションタイプを表示できます。
* パフォーマンスタイルのアプリケーションとワークロードタブを選択して、論理オブジェクトのパフォーマンス指標（レイテンシ、IOPS、MB）を表示できます。オブジェクトはアプリケーションおよび関連付けられているワークロード別にグループ化されます。このパフォーマンスデータを定期的に収集することで、ベースラインとなる数値を設定して傾向を分析することができ、I/Oパフォーマンスに関する問題の調査に役立ちます。

