---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-alert-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ストレージアレイから別のストレージアレイにアラート設定をインポートします。 
---
= アラート設定をインポートします
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ストレージアレイから別のストレージアレイにアラート設定をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

次の点を確認してください。

* アラートは、ソースとして使用するストレージアレイのSystem Manager（メニュー：Settings [Alerts]）で設定します。
* ターゲットストレージアレイの既存の構成は、System Managerでバックアップされます（メニュー：[設定][システム]>[ストレージアレイ構成の保存]）。
* でストレージ構成のレプリケートに関する要件を確認しておく必要があります link:vc-olh-import-settings-overview.html["設定のインポートの概要"]。


インポート処理では、Eメール、SNMP、またはsyslogのいずれかのアラートを選択できます。

* *Email alerts *--メールサーバのアドレスとアラート受信者の電子メールアドレス。
* *Syslogアラート*-- syslogサーバのアドレスとUDPポート。
* *snmp alerts *-- SNMPサーバのコミュニティ名とIPアドレス。


.手順
. [管理]ページで、[メニュー]、[アクション]、[設定のインポート]の順にクリックします。
+
設定のインポートウィザードが開きます。

. Select Settings（設定の選択）ダイアログで、* Email alerts *、* SNMP alerts *、または* Syslog alerts *のいずれかを選択し、* Next（次へ）*をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. [ソースの選択]ダイアログで、インポートする設定のアレイを選択し、[次へ]をクリックします。
. ターゲットの選択ダイアログで'新しい設定を受信する1つまたは複数のアレイを選択します
+

NOTE: ファームウェアが8.50未満のストレージアレイは選択できません。また、プラグインがそのアレイと通信できない場合（オフラインの場合や、証明書、パスワード、ネットワークに問題がある場合など）、このダイアログにアレイは表示されません。

. [ 完了 ] をクリックします。
+
Operationsページには、インポート処理の結果が表示されます。処理が失敗した場合は、その行をクリックすると詳細を確認できます。



Eメール、SNMP、またはsyslogを使用して管理者にアラートを送信するようにターゲットストレージアレイが設定されます。
