---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-raid-level-is-best-for-my-application.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ボリュームグループのパフォーマンスを最大限に高めるには、適切なRAIDレベルを選択する必要があります。 
---
= アプリケーションに最適なRAIDレベルはどれですか？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ボリュームグループのパフォーマンスを最大限に高めるには、適切なRAIDレベルを選択する必要があります。

適切なRAIDレベルを特定するには、ボリュームグループにアクセスしているアプリケーションでの読み取りと書き込みの割合を把握します。これらの割合を取得するには、[パフォーマンス]ページを使用します。



== RAIDレベルとアプリケーションパフォーマンス

RAIDには、レベルと呼ばれる一連の構成が採用されており、ユーザデータと冗長性データのドライブに対する書き込み/読み出し方法が決定されます。RAIDレベルごとにパフォーマンス機能が異なります。読み取り比率が高いアプリケーションの場合、RAID 5ボリュームまたはRAID 6ボリュームを使用するとパフォーマンスが向上します。これは、RAID 5およびRAID 6構成の読み取りパフォーマンスが優れているためです。

読み取り比率が低い（書き込み中心の）アプリケーションの場合、RAID 5ボリュームまたはRAID 6ボリュームでは同様のパフォーマンスを実現できません。パフォーマンスの低下は、コントローラがデータと冗長性データをRAID 5ボリュームグループまたはRAID 6ボリュームグループのドライブに書き込む方法に起因します。

次の情報に基づいてRAIDレベルを選択します。



=== RAID 0

*概要 ：*

* 冗長性なし、ストライピングモード。
* RAID 0は、ボリュームグループ内のすべてのドライブにデータをストライピングします。


*データ保護機能：*

* 高可用性が求められる場合、RAID 0は推奨されません。RAID 0は重要度の低いデータに適しています。
* ボリュームグループ内の1本のドライブで障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、すべてのデータが失われます。


*必要なドライブ数：*

* RAIDレベル0には少なくとも1本のドライブが必要です。
* RAID 0ボリュームグループには30本を超えるドライブを含めることができます。
* ストレージアレイのすべてのドライブを含むボリュームグループを作成できます。




=== RAID 1またはRAID 10

*概要 ：*

* ストライピング/ミラーモード。


*どのように機能するか:*

* RAID 1では、ディスクミラーリングを使用して、2本のディスクに同時にデータが書き込まれます。
* RAID 10は、ドライブストライピングを使用して、複数のミラーリングされたドライブペアにデータをストライピングします。


*データ保護機能：*

* RAID 1とRAID 10は、ハイパフォーマンスと最高のデータ可用性を提供します。
* RAID 1とRAID 10は、ドライブミラーリングを使用して、あるドライブから別のドライブにまったく同じコピーを作成します。
* ドライブペアの一方のドライブで障害が発生した場合、ストレージアレイはデータやサービスを失うことなくもう一方のドライブに即座に切り替えることができます。
* 単一ドライブ障害が発生すると、関連付けられているボリュームはデグレード状態になります。ミラードライブがデータへのアクセスを許可します。
* ボリュームグループ内のドライブペアで障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、データが失われる可能性があります。


*必要なドライブ数：*

* RAID 1には、ユーザデータ用に1本、ミラーデータ用に1本、合計2本以上のドライブが必要です。
* 4本以上のドライブを選択すると、ボリュームグループ全体でRAID 10が自動的に設定されます。ユーザデータ用にドライブが2本、ミラーデータ用にドライブが2本です。
* ボリュームグループのドライブ数は偶数でなければなりません。ドライブ数が偶数ではなく未割り当てのドライブが残っている場合は、「* Pools & Volume Groups」に移動してボリュームグループにドライブを追加し、処理を再試行します。
* RAID 1とRAID 10のボリュームグループは、30本を超えるドライブで構成できます。ストレージアレイのすべてのドライブを含むボリュームグループを作成できます。




=== RAID 5

*概要 ：*

* 高I/Oモード。


*どのように機能するか:*

* ユーザデータと冗長性情報（パリティ）が複数のドライブにストライピングされます。
* 冗長性情報を格納するために、ドライブ1本分の容量が使用されます。


*データ保護機能*

* RAID 5ボリュームグループで1本のドライブに障害が発生すると、関連付けられているすべてのボリュームがデグレード状態になります。冗長な情報があるので、データには引き続きアクセスできます。
* RAID 5ボリュームグループで複数のドライブに障害が発生すると、関連付けられているすべてのボリュームに障害が発生し、すべてのデータが失われます。


*必要なドライブ数：*

* ボリュームグループには最低3本のドライブが必要です。
* 通常、ボリュームグループのドライブ数は最大30本に制限されます。




=== RAID 6

*概要 ：*

* 高I/Oモード。


*どのように機能するか:*

* ユーザデータと冗長性情報（デュアルパリティ）が複数のドライブにストライピングされます。
* 冗長性情報を格納するために、ドライブ2本分の容量が使用されます。


*データ保護機能：*

* RAID 6ボリュームグループで1本または2本のドライブに障害が発生すると、関連付けられているすべてのボリュームがデグレード状態になりますが、冗長性情報があるためデータには引き続きアクセスできます。
* RAID 6ボリュームグループで3本以上のドライブに障害が発生すると、関連付けられているすべてのボリュームに障害が発生し、すべてのデータが失われます。


*必要なドライブ数：*

* ボリュームグループには最低5本のドライブが必要です。
* 通常、ボリュームグループのドライブ数は最大30本に制限されます。



NOTE: プールのRAIDレベルは変更できません。ユーザーインタフェースは'プールを自動的にRAID 6として構成します



== RAIDレベルとデータ保護

RAID 1、RAID 5、およびRAID 6は、フォールトトレランス用に冗長性データをドライブメディアに書き込みます。冗長性データには、データのコピー（ミラー）、またはデータから導出されたエラー修正コードがあります。ドライブで障害が発生した場合は、冗長性データを使用して交換用ドライブに迅速に情報を再構築できます。

単一のボリュームグループ全体で単一のRAIDレベルを設定します。そのボリュームグループの冗長性データは、すべてボリュームグループ内に格納されます。ボリュームグループの容量は、メンバードライブのアグリゲート容量から冗長性データ用に確保された容量を引いた値です。冗長性を確保するために必要な容量は、使用するRAIDレベルによって異なります。
