---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-autosupport-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ストレージアレイから別のストレージアレイにAutoSupport 構成をインポートします。 
---
= vCenter向けSANtricityストレージプラグインでのAutoSupport設定のインポート
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ストレージアレイから別のストレージアレイにAutoSupport 構成をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

.作業を開始する前に
次の点を確認してください。

* AutoSupport は、ソースとして使用するストレージアレイのSystem Manager（メニュー：サポート[サポートセンター]）で設定します。
* ターゲットストレージアレイの既存の構成は、System Managerでバックアップされます（メニュー：[設定][システム]>[ストレージアレイ構成の保存]）。
* でストレージ構成のレプリケートに関する要件を確認しておく必要があります link:vc-olh-import-settings-overview.html["設定のインポートの概要"]。


.このタスクについて
インポートされる設定には、個別の機能（Basic AutoSupport 、AutoSupport OnDemand、Remote Diagnostics）、メンテナンス期間、配信方法、 およびディスパッチスケジュール。

.手順
. [管理]ページで、[メニュー]、[アクション]、[設定のインポート]の順にクリックします。
+
設定のインポートウィザードが開きます。

. 設定の選択ダイアログで、* AutoSupport *を選択し、*次へ*をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. [ソースの選択]ダイアログで、インポートする設定のアレイを選択し、[次へ]をクリックします。
. ターゲットの選択ダイアログで'新しい設定を受信する1つまたは複数のアレイを選択します
+

NOTE: ファームウェアが8.50未満のストレージアレイは選択できません。また、プラグインがそのアレイと通信できない場合（オフラインの場合や、証明書、パスワード、ネットワークに問題がある場合など）、このダイアログにアレイは表示されません。

. [ 完了 ] をクリックします。
+
Operationsページには、インポート処理の結果が表示されます。処理が失敗した場合は、その行をクリックすると詳細を確認できます。



.結果
ターゲットストレージアレイのAutoSupport 設定がソースアレイと同じに設定されます。
