---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-configuration-settings-for-a-pool.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 名前、容量アラートの設定、変更の優先順位、予約済み容量など、プールの設定を編集します。 
---
= vCenter向けSANtricityストレージプラグインでのプールの構成設定の変更
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
プールの名前、容量アラートの設定、変更の優先順位、予約済み容量などのプールの設定を編集できます。

.このタスクについて
このタスクでは、プールの構成設定を変更する方法について説明します。


NOTE: プラグインインターフェイスを使用してプールのRAIDレベルを変更することはできません。プラグインは、プールを自動的にRAID 6として構成します。

.手順
. [管理]ページで、プールがあるストレージアレイを選択します。
. メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。
. 編集するプールを選択し、*表示/設定の編集*をクリックします。
+
Pool Settings（プール設定）ダイアログボックスが表示されます。

. [*設定*]タブを選択し、必要に応じてプール設定を編集します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
名前
 a| 
ユーザが指定したプールの名前を変更できます。プールの名前は必ず指定する必要があります。



 a| 
容量アラート
 a| 
プールの空き容量が指定したしきい値以上になったときにアラート通知を送信できます。プールに格納されたデータが指定したしきい値を超えると、プラグインはメッセージを送信します。このため、ストレージスペースを追加したり、不要なオブジェクトを削除したりすることができます。アラートは、ダッシュボードの通知領域に表示され、サーバから管理者にEメールおよびSNMPトラップメッセージで送信できます。次の容量アラートを定義できます。

** *重大アラート*：プールの空き容量が指定したしきい値以上になったときに通知されます。しきい値の割合はスピンボックスで調整できます。この通知を無効にするには、チェックボックスをオンにします。
** *早期アラート*：プールの空き容量が指定したしきい値に達したときに通知されます。しきい値の割合はスピンボックスで調整できます。この通知を無効にするには、チェックボックスをオンにします。




 a| 
修正の優先順位
 a| 
システムパフォーマンスと比較したプールの変更処理の優先度レベルを指定できます。プールの変更処理の優先度を高くすると処理は高速に完了しますが、ホストのI/Oパフォーマンスは低下します。優先度を低くすると処理には時間がかかりますが、ホストのI/Oパフォーマンスへの影響は小さくなります。優先度レベルは、lowest、low、medium、high、highestの5つから選択できます。優先度レベルが高いほど、ホストのI/Oパフォーマンスとシステムパフォーマンスへの影響は大きくなります。

** *重大の再構築優先度*-このスライダバーは、複数のドライブに障害が発生した場合のデータ再構築処理の優先度を決定します。この状況では、一部のデータの冗長性が失われ、別のドライブ障害が発生した場合はデータの損失を招くおそれがあります。
** *デグレード再構築優先度*-このスライダバーは、ドライブ障害が発生した場合のデータ再構築処理の優先度を決定します。この状況では、データの冗長性は失われておらず、別のドライブ障害が発生してもデータの損失が発生することはありません。
** *バックグラウンド処理の優先度*-このスライダバーは、プールが最適な状態のときに実行されるバックグラウンド処理の優先度を決定します。たとえば、Dynamic Volume Expansion（DVE）、Instant Availability Format（IAF）、交換または追加したドライブへのデータの移行などがあります。




 a| 
予約済み容量（EF600またはEF300の場合は「最適化容量」）
 a| 
*予約済み容量*-ドライブ数を定義して、ドライブ障害に備えてプールに確保されている容量を特定できます。ドライブ障害が発生すると、予約済み容量を使用して再構築されたデータが格納されます。プールのデータ再構築プロセスでは、ボリュームグループで使用されるホットスペアドライブではなく、予約済み容量が使用されます。ドライブ数はスピンボックスで調整します。指定したドライブ数に応じて、スピンボックスの横にプールの予約済み容量が表示されます。予約済み容量については、次の点に注意してください。

** 予約済み容量はプールの合計空き容量から差し引かれるため、確保する容量がボリュームの作成に使用できる空き容量に影響します。予約済み容量に0を指定すると、プールのすべての空き容量がボリュームの作成に使用されます。
** 予約済み容量を減らすと、プールボリュームに使用できる容量が増えます。


*追加の最適化容量（EF600およびEF300アレイのみ）*--プールの作成時に、使用可能容量とパフォーマンスおよびドライブ寿命とのバランスが取れた、推奨される最適化容量が生成されます。このバランスを調整するには、使用可能容量を犠牲にしてパフォーマンスの向上とドライブ寿命の延長を図る場合はスライダを右に、パフォーマンスとドライブ寿命を犠牲にして使用可能容量を増やす場合は左に動かします。SSDドライブでは、その容量の一部が未割り当ての場合に寿命が長くなり、最大書き込みパフォーマンスが向上します。プールに関連付けられているドライブの未割り当て容量は、プールの予約済み容量、空き容量（ボリュームで使用されていない容量）、および使用可能容量のうちの最適化容量として確保された容量で構成されます。この最適化容量は使用可能容量を減らすことで最小レベルの最適化容量を確保するため、ボリュームの作成には使用できません。

|===
====
. [ 保存（ Save ） ] をクリックします。

