---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-pool-automatically.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 未割り当てのドライブが11本以上検出された場合、または既存のプールに対応する未割り当てのドライブが1本検出された場合、プールを自動的に作成できます。 
---
= プールを自動的に作成する
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
未割り当てのドライブが11本以上検出された場合、または既存のプールに対応する未割り当てのドライブが1本検出された場合、プールを自動的に作成できます。プールは、論理的にグループ化された一連のドライブです。

.作業を開始する前に
次のいずれかの条件に該当する場合は、Pool Auto-Configurationダイアログボックスを起動できます。

* ドライブタイプが類似する既存のプールに追加できる未割り当てドライブが1本以上検出された場合。
* 新しいプールの作成に使用できる未割り当てドライブが11本以上検出された場合（ドライブタイプが異なるために既存のプールに追加できない場合）。


.このタスクについて
プールの自動作成を使用すると、ストレージアレイ内のすべての未割り当てドライブを1つのプールに簡単に設定したり、既存のプールにドライブを追加したりできます。

次の点に注意してください。

* ストレージアレイにドライブを追加すると、ドライブが自動的に検出され、ドライブタイプと現在の構成に基づいて、1つまたは複数のプールを作成するように求められます。
* プールが以前に定義されている場合は、互換性があるドライブを既存のプールに追加するかどうかを確認するプロンプトが自動的に表示されます。新しいドライブを既存のプールに追加すると、システムによって、追加した新しいドライブを含む新しい容量にデータが自動的に再配分されます。
* EF600またはEF300ストレージアレイを設定する場合は、各コントローラが最初の12個のスロットと直近の12個のスロットに同じ数のドライブにアクセスできることを確認します。この構成により、コントローラは両方のドライブ側PCIeバスをより効果的に使用できます。プールの作成には、ストレージアレイのすべてのドライブを使用する必要があります。


.手順
. [管理]ページで、プールのストレージアレイを選択します。
. メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。
. メニューを選択します。More [Launch pool auto-configuration]。
+
新しいプール、ドライブが追加されている既存のプール、またはその両方が表示されます。新しいプールには、連番を付した名前がデフォルトで付けられます。

+
システムで次の処理が行われていることに注意してください。

+
** ドライブタイプ（HDDまたはSSD）が同じで容量が同等の十分な数のドライブがある場合は、単一のプールが作成されます。
** 未割り当て容量が異なるドライブタイプで構成されている場合は、複数のプールが作成されます。
** ストレージアレイにすでにプールが定義されている場合に、そのプールにドライブタイプが同じ新しいドライブを追加すると、既存のプールにドライブが追加されます。
** ドライブタイプが同じドライブを既存のプールに追加し、別のドライブタイプのドライブを使用して別のプールを作成する。


. 新しいプールの名前を変更するには、* Edit *アイコン（鉛筆）をクリックします。
. プールのその他の特性を表示するには、カーソルを合わせるか、詳細アイコン（ページ）をタッチします。
+
ドライブタイプ、セキュリティ機能、Data Assurance（DA）機能、シェルフ損失の保護、ドロワー損失の保護に関する情報が表示されます。

+
EF600およびEF300ストレージアレイについては、リソースのプロビジョニングとボリュームのブロックサイズについても設定が表示されます。

. [* 同意する * ] をクリックします。

