---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ホストからアクセス可能な1つ以上のボリュームのボリュームグループを作成できます。 
---
= ボリュームグループを作成します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ホストからアクセス可能な1つ以上のボリュームのボリュームグループを作成できます。ボリュームグループは、RAIDレベルや容量などの特性が同じボリュームのコンテナです。

.作業を開始する前に
次のガイドラインを確認してください。

* 未割り当てのドライブが少なくとも1本必要です。
* 1つのボリュームグループに含めることができるドライブ容量には制限があります。これらの制限はホストタイプによって異なります。
* シェルフ/ドロワー損失の保護を有効にするには、RAID 1を使用している場合を除き、少なくとも3台のシェルフまたはドロワーに配置されたドライブを使用するボリュームグループを作成する必要があります。最小のシェルフ/ドロワーは2台です。
* EF600またはEF300ストレージアレイを設定する場合は、各コントローラが最初の12個のスロットと直近の12個のスロットに同じ数のドライブにアクセスできることを確認します。この構成により、コントローラは両方のドライブ側PCIeバスをより効果的に使用できます。現在、ボリュームグループの作成時に、Advanced機能でドライブを選択することができます。


ボリュームグループの容量は、選択するRAIDレベルによって次のように異なります。

* RAID 1を使用する場合は、ドライブを一度に2本ずつ追加してミラーペアを構成する必要があります。ミラーリングとストライピング（RAID 10またはRAID 1+0）は、ドライブを4本以上選択した場合に実装されます。
* RAID 5を使用する場合は、少なくとも3本のドライブを追加してボリュームグループを作成する必要があります。
* RAID 6を使用する場合は、少なくとも5本のドライブを追加してボリュームグループを作成する必要があります。


.このタスクについて
ボリュームグループ作成時に、ドライブ数、セキュリティ機能、Data Assurance（DA）機能、シェルフ損失の保護、ドロワー損失の保護など、グループの特性を確認します。

EF600およびEF300ストレージアレイの場合は、リソースのプロビジョニング、ドライブブロックサイズ、ボリュームブロックサイズも設定に含まれます。


NOTE: 大容量ドライブとボリュームをコントローラ間で分散させる機能を利用して、1つのボリュームグループに複数のボリュームを作成すると、ストレージ容量を有効に活用してデータを保護するのに役立ちます。

.手順
. Manage（管理）ページで、ボリュームグループのストレージアレイを選択します。
. メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。
. メニュー：Create [Volume group]（ボリュームグループの作成）をクリックします。
+
Create Volume Group（ボリュームグループの作成）ダイアログボックスが表示されます。

. ボリュームグループの名前を入力します。
. データストレージと保護の要件に最も適したRAIDレベルを選択します。ボリュームグループ候補の表に、選択したRAIDレベルをサポートする候補だけが表示されます。
. （オプション）ストレージアレイに複数のタイプのドライブがある場合、使用するドライブタイプを選択します。
+
ボリュームグループ候補の表に、選択したドライブタイプとRAIDレベルをサポートする候補だけが表示されます。

. （オプション）ボリュームグループで使用するドライブを自動で定義するか手動で定義するかを選択できます。デフォルトでは、自動方式が選択されています。
+

CAUTION: ドライブの冗長性と最適なドライブ構成を理解している専門家でない場合は、手動で操作しないでください。

+
ドライブを手動で選択するには、ドライブを手動で選択する*（アドバンスト）リンクをクリックします。クリックすると、ドライブが自動的に選択されます（アドバンスト）*。

+
手動方式では、ボリュームグループを構成するドライブを選択できます。未割り当ての特定のドライブを選択して必要な容量を確保することができます。ストレージアレイにメディアタイプやインターフェイスタイプが異なるドライブが含まれている場合、新しいボリュームグループの作成用に選択できるのは1つのドライブタイプの未設定の容量のみです。

. 表示されたドライブ特性に基づいて、ボリュームグループで使用するドライブを選択し、*作成*をクリックします。


表示されるドライブ特性は、自動方式と手動方式のどちらを選択したかによって異なります。詳細については、SANtricity System Managerのドキュメントを参照してください。 https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-volume-group.html["ボリュームグループを作成します"^]。
