---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-host-cluster.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 複数のホストが同じボリュームへのI/Oアクセスを必要とする場合は、ホストクラスタを作成できます。 
---
= ホストクラスタを作成する
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
複数のホストが同じボリュームへのI/Oアクセスを必要とする場合は、ホストクラスタを作成できます。

ホストクラスタを作成する際は、次のガイドラインに注意してください。

* クラスタの作成に使用できるホストが複数ない場合、この処理は開始されません。
* ホストクラスタ内のホストはオペレーティングシステムが異なっていてもかまいません（異機種混在）。
* ホストクラスタのNVMeホストをNVMe以外のホストと混在させることはできません。
* Data Assurance（DA）対応ボリュームを作成する場合は、使用するホスト接続でDAがサポートされている必要があります。
+
ストレージアレイのコントローラで DA をサポートしていないホスト接続が使用されている場合、関連付けられているホストからは DA 対応ボリュームのデータにアクセスできません。

* 選択した名前がすでに使用されている場合、この処理は失敗します。
* 名前は 30 文字以内にする必要があります。


.手順
. Manage （管理）ページで、ホスト接続があるストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ホストの設定 ] 。
+
Configure Hosts ページが開きます。

. メニューを選択します。Create [Host cluster]（ホストクラスタの作成）。
+
Create Host Cluster（ホストクラスタの作成）ダイアログボックスが表示されます。

. ホストクラスタの設定を必要に応じて選択します。
+
|===
| 設定 | 説明 


| 名前 | 新しいホストクラスタの名前を入力します。 


| ボリュームアクセスを共有するホストを選択します | ドロップダウンリストから2つ以上のホストを選択します。このリストには、ホストクラスタにまだ含まれていないホストのみが表示されます。 
|===
. [ 作成（ Create ） ] をクリックします。
+
選択したホストが接続されているインターフェイスタイプのData Assurance（DA）機能が異なる場合、ホストクラスタでDAを使用できないことを示すメッセージがダイアログに表示されます。この場合、ホストクラスタにDA対応ボリュームを追加することはできません。続行するには「*はい」を選択し、キャンセルするには「*いいえ」を選択します。

+
DA を使用すると、ストレージシステム全体のデータの整合性が向上します。ホストとドライブの間でデータが移動されたときにストレージアレイがエラーの有無をチェックします。新しいボリュームに DA を使用すると、すべてのエラーが検出されます。



新しいホストクラスタが表に表示され、その下の行に割り当てられたホストが表示されます。

I/O処理に使用できるように、ボリュームをホストクラスタに割り当てる必要があります。に進みます link:vc-olh-assign-volumes-to-hosts.html["ホストにボリュームを割り当てます"]。
