---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-configuration-settings-for-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 名前やRAIDレベルなど、ボリュームグループの設定を編集します。 
---
= ボリュームグループの設定を変更します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
名前やRAIDレベルなど、ボリュームグループの設定を編集できます。

.作業を開始する前に
ボリュームグループにアクセスするアプリケーションが必要とするパフォーマンスを確保できるようにRAIDレベルを変更する場合は、次の前提条件を満たしていることを確認してください。

* ボリュームグループのステータスが最適である必要があります。
* ボリュームグループに、新しいRAIDレベルに変換するための十分な容量が必要です。


.手順
. 管理ページで、ボリュームグループを含むストレージアレイを選択します。
. メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。
. 編集するボリュームグループを選択し、*表示/設定の編集*をクリックします。
+
Volume Group Settings（ボリュームグループ設定）ダイアログボックスが表示されます。

. 「* Settings *」（設定）タブを選択し、必要に応じてボリュームグループの設定を編集します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
名前
 a| 
ユーザが指定したボリュームグループの名前を変更できます。ボリュームグループの名前は必ず指定する必要があります。



 a| 
RAIDレベル
 a| 
ドロップダウンメニューから新しいRAIDレベルを選択します。

** *RAID 0ストライピング*--ハイパフォーマンスを提供しますが'データの冗長性は提供しませんボリュームグループ内の1本のドライブで障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、すべてのデータが失われます。ストライピングRAIDグループは、2つ以上のドライブを1つの大容量論理ドライブにまとめます。
** *RAID 1ミラーリング*--高いパフォーマンスと最高のデータ可用性を提供し、企業レベルまたは個人レベルで機密データを保存するのに適しています。一方のドライブの内容をミラーペアのもう一方のドライブに自動的にミラーリングすることで、データを保護します。単一のドライブ障害からの保護を提供します。
** *RAID 10ストライピング/ミラーリング*-- RAID 0 (ストライピング)とRAID 1(ミラーリング)を組み合わせたもので'4台以上のドライブを選択した場合に実現されますRAID 10は、高いパフォーマンスとフォールトトレランスが必要な、データベースなどの大量のトランザクションを処理するアプリケーションに適しています。
** *RAID 5*--標準的なI/Oサイズが小さく読み取り処理の割合が高いマルチユーザー環境(データベースやファイルシステムストレージなど)に最適
** *RAID 6*-- RAID 5を超える冗長性を必要とするが'高い書き込みパフォーマンスは必要としない環境に最適ですRAID 3をボリュームグループに割り当てるには、コマンドラインインターフェイスを使用する必要があります。RAIDレベルの変更はキャンセルできません。変更中もデータは引き続き使用できます。




 a| 
最適化容量（EF600アレイのみ）
 a| 
ボリュームグループの作成時に、使用可能容量とパフォーマンスおよびドライブの寿命とのバランスに基づいて、推奨される最適化容量が決定されます。このバランスを調整するには、使用可能容量を犠牲にしてパフォーマンスの向上とドライブ寿命の延長を図る場合はスライダを右に、パフォーマンスとドライブ寿命を犠牲にして使用可能容量を増やす場合は左に動かします。SSDドライブでは、その容量の一部が未割り当ての場合に寿命が長くなり、最大書き込みパフォーマンスが向上します。ボリュームグループに関連付けられているドライブの未割り当て容量は、グループの空き容量（ボリュームで使用されていない容量）と、使用可能容量のうちの最適化容量として確保された容量で構成されます。この最適化容量は使用可能容量を減らすことで最小レベルの最適化容量を確保するため、ボリュームの作成には使用できません。

|===
====
. [ 保存（ Save ） ] をクリックします。


RAIDレベルの変更によって容量が減ったり、ボリュームの冗長性が失われたり、シェルフ/ドロワー損失の保護が失われた場合は、確認ダイアログボックスが表示されます。続行するには*はい*を選択し、続行しない場合は*いいえ*をクリックします。

.結果
ボリュームグループのRAIDレベルを変更すると、プラグインはボリュームグループを構成するすべてのボリュームのRAIDレベルを変更します。処理の実行中は、パフォーマンスが若干低下することがあります。
