---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-pools-and-volume-group-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ストレージをプロビジョニングするには、ストレージアレイで使用するハードディスクドライブ（HDD）またはソリッドステートディスク（SSD）ドライブを含むプールまたはボリュームグループを作成します。 
---
= プールとボリュームグループの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter向けストレージプラグインでストレージをプロビジョニングするには、ストレージアレイで使用するハードディスクドライブ（HDD）またはソリッドステートディスク（SSD）ドライブを格納するプールまたはボリュームグループを作成します。



== プロビジョニング

物理ハードウェアは、データを整理して簡単に取得できるように、論理コンポーネントにプロビジョニングされます。次の2種類のグループ化がサポートされています。

* プール
* ボリュームグループ


プールとボリュームグループは、ストレージアレイ内の最上位のストレージ単位であり、ドライブの容量を管理可能な区分に分割します。これらの論理区分内に、データが格納される個々のボリュームまたはLUNがあります。

ストレージシステムを導入したら、まず次の処理を実行して使用可能なドライブ容量をさまざまなホストに提供します。

* 十分な容量のプールまたはボリュームグループを作成しています
* パフォーマンス要件を満たすために必要な数のドライブをプールまたはボリュームグループに追加します
* 特定のビジネス要件を満たすために必要なレベルのRAID保護（ボリュームグループを使用している場合）を選択


同じストレージシステム上にプールまたはボリュームグループを複数作成することはできますが、1本のドライブを複数のプールまたはボリュームグループに所属させることはできません。その後、プールまたはボリュームグループのスペースを使用して、I/O用にホストに表示されるボリュームが作成されます。



== プール

プールは、物理ハードディスクドライブを1つの大きなストレージスペースに集約し、RAID保護を強化するために設計されています。プールに割り当てられたドライブをすべて使用して多数の仮想RAIDセットを作成したり、プールを構成する全ドライブにデータを均等に分散することができます。ドライブを減らしたり追加したりした場合は、アクティブドライブ全体にわたってデータの再分散が動的に実行されます。

プール機能はワンランク上のRAIDとして機能します。基盤となるRAIDアーキテクチャが仮想化されるため、リビルド、ドライブ拡張、ドライブ障害への対応といったタスクの処理に最適なパフォーマンスと柔軟性が提供されます。8+2構成（8本のデータディスクと2本のパリティディスク）では、RAIDレベルは自動的に6に設定されます。



=== ドライブが一致しません

プールにはHDDまたはSSDのいずれかを選択できます。ただし、ボリュームグループと同様に、プール内のすべてのドライブが同じテクノロジを使用する必要があります。どのドライブを含めるかは、コントローラが自動的に選択するため、選択したテクノロジに対応する十分な数のドライブがあることを確認する必要があります。



=== 障害ドライブの管理

プールの最小容量は11ドライブですが、ドライブに障害が発生した場合に備えて、1ドライブ分の容量がスペア容量として確保されます。このスペア容量を「予約済み容量」と呼びます。

プールが作成されると、一定量の容量が緊急用に保持されます。この容量はドライブ数で表されますが、実際の実装はドライブのプール全体に分散されます。保持されるデフォルトの容量は、プール内のドライブの数に基づきます。

プールの作成後、予約済み容量の値は増減できます。また、予約済み容量なし（0ドライブ分）に設定することもできます。保持可能な最大容量（ドライブ数）は10ですが、プール内のドライブの総数に基づいて、使用可能な容量はこれより少なくなる可能性があります。



== ボリュームグループ

ボリュームグループは、ストレージシステム内で容量をボリュームに割り当てる方法を定義します。ディスクドライブはRAIDグループにまとめられ、ボリュームは1つのRAIDグループ内の複数のドライブにまたがって実装されます。したがって、ボリュームグループの設定により、グループに含まれるドライブと、使用されているRAIDレベルが特定されます。

ボリュームグループを作成するときに、グループに含めるドライブはコントローラによって自動的に選択されます。グループのRAIDレベルは手動で選択する必要があります。ボリュームグループの容量は、選択したドライブの合計数にドライブの容量を掛けた値となります。



=== ドライブが一致しません

ボリュームグループ内のドライブのサイズとパフォーマンスを一致させる必要があります。ボリュームグループ内のドライブの容量が異なる場合、すべてのドライブが最小容量サイズとして認識されます。ボリュームグループ内のドライブの速度が異なる場合、すべてのドライブが最低速度で認識されます。これらの要素は、ストレージシステムのパフォーマンスと全体的な容量に影響します。

異なるドライブテクノロジ（HDDとSSDドライブ）を混在させることはできません。RAID 3、5、6は、最大30ドライブまでに制限されています。RAID 1およびRAID 10はミラーリングを使用するため、ディスク数は偶数にする必要があります。



=== 障害ドライブの管理

ボリュームグループに含まれるRAID 1/10、RAID 3、RAID 5、またはRAID 6のボリュームでドライブに障害が発生した場合に備えて、ボリュームグループではホットスペアドライブをスタンバイとして使用します。ホットスペアドライブにはデータは含まれず、ストレージアレイの冗長性レベルの向上に使用されます。

ストレージアレイのドライブで障害が発生した場合、障害が発生したドライブからホットスペアドライブに自動的に切り替わります。物理的にドライブを交換する必要はありません。ドライブ障害の発生時にホットスペアドライブが使用可能であれば、冗長性データを使用して障害が発生したドライブからホットスペアドライブにデータが再構築されます。



== プールまたはボリュームグループを使用するかどうかを決定します



=== プールを選択します

* 迅速なドライブのリビルドやストレージ管理の簡易化が必要な場合、ランダムワークロードが大量に発生する場合。
* 各ボリュームのデータをプールを構成する一連のドライブにランダムに分散する場合。プールまたはプール内のボリュームのRAIDレベルを設定または変更することはできません。プールではRAIDレベル6を使用します。




=== ボリュームグループを選択します

* システムの帯域幅を最大限に使用する必要がある場合、ストレージの設定を調整する機能、大量のシーケンシャルワークロードを利用する場合。
* データをRAIDレベルに基づいてドライブに分散する場合。ボリュームグループは作成時にRAIDレベルを指定できます。
* 各ボリュームのデータをボリュームグループを構成する一連のドライブにシーケンシャルに書き込む場合。



NOTE: プールとボリュームグループは共存可能なため、ストレージアレイにプールとボリュームグループの両方を含めることができます。



== プールの自動作成と手動作成

ストレージ構成に応じて、プールを自動的に作成することも、手動で作成することもできます。プールは、論理的にグループ化された一連のドライブです。

プールを作成して管理する前に、プールの自動作成方法と、プールを手動で作成する必要があるタイミングについて、次のセクションを確認してください。



=== 自動作成

ストレージアレイに未割り当て容量が検出されると、ストレージアレイで未割り当て容量が検出されるとプールの自動作成が開始されます。1つ以上のプールの作成、既存のプールへの未割り当て容量の追加、またはその両方を自動で実行するように求められます。

プールの自動作成は、次のいずれかの条件に該当する場合に実行されます。

* プールがストレージアレイに存在せず、新しいプールの作成に十分なドライブがない。
* 新しいドライブは、少なくとも1つのプールがあるストレージアレイに追加されます。プール内の各ドライブは、同じタイプ（HDDまたはSSD）であり、容量が同等である必要があります。次のタスクを実行するよう求められます。
* タイプが十分な数のドライブがある場合は、単一のプールを作成する。
* 未割り当て容量が異なるドライブタイプで構成されている場合は、複数のプールを作成する。
* ストレージアレイにすでにプールが定義されている場合は、既存のプールにドライブを追加し、同じタイプの新しいドライブをプールに追加する。
* タイプの異なる複数のドライブを追加した場合は、ドライブタイプが同じドライブを既存のプールに追加し、別のドライブタイプのドライブを使用して別のプールを作成する。




=== 手動作成

最適な構成を自動作成で判断できない場合は、プールを手動で作成できます。この状況は、次のいずれかの理由で発生する可能性があります。

* 新しいドライブが複数のプールに追加される可能性があります。
* 1つ以上の新しいプールの候補で、シェルフ損失の保護またはドロワー損失の保護を使用できる。
* 1つ以上の現在のプールの候補で、シェルフ損失の保護またはドロワー損失の保護のステータスを維持できません。ストレージアレイに複数のアプリケーションがあり、同じドライブリソース間で競合しないようにする場合は、プールを手動で作成することもできます。この場合、1つ以上のアプリケーション用に小規模なプールを手動で作成することを検討してください。データを分散するための多数のボリュームを含む大規模なプールにワークロードを割り当てるのではなく、1~2個のボリュームだけを割り当てることができます。特定のアプリケーションのワークロード専用の個別のプールを手動で作成すると、ストレージアレイの処理をより迅速に実行でき、競合が軽減されます。

