---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-know-about-the-resource-provisioned-volumes-feature.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。 
---
= リソースでプロビジョニングされるボリューム機能について、どのような点に注意する必要がありますか？
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。


NOTE: リソースプロビジョニング機能は現在使用できません。ビューによっては、コンポーネントがリソースプロビジョニング対応と報告される場合がありますが、リソースプロビジョニングボリュームを作成する機能は、あとで更新するまで無効になっています。



== リソースでプロビジョニングされたボリューム

リソースプロビジョニングボリュームは、SSDグループまたはプール内のシックボリュームです。ボリュームの作成時にはドライブ容量が割り当てられますが（ボリュームに割り当てられます）、ドライブブロックは割り当て解除されます（マッピング解除されます）。これに対し、従来のシックボリュームでは、Data Assurance保護情報のフィールドを初期化し、各RAIDストライプでデータとRAIDパリティの整合性を確保するために、すべてのドライブブロックがバックグラウンドボリューム初期化処理中にマッピングまたは割り当てられます。リソースプロビジョニングボリュームでは、時間制限付きのバックグラウンド初期化は実行されません。代わりに、各RAIDストライプは、ストライプ内のボリュームブロックへの最初の書き込み時に初期化されます。

リソースプロビジョニングボリュームはSSDボリュームグループおよびプールでのみサポートされます。グループまたはプール内のすべてのドライブでNVMeのDeallocated or Unwritten Logical Block Error（DULBE）エラーリカバリ機能がサポートされます。リソースでプロビジョニングされたボリュームを作成すると、そのボリュームに割り当てられていたすべてのドライブブロックが割り当て解除（マッピング解除）されます。また、ホストではNVMe Dataset Managementコマンドを使用して、ボリューム内の論理ブロックの割り当てを解除できます。ブロックの割り当てを解除すると、SSDの消耗度が改善され、書き込みパフォーマンスが最大化されます。向上率はドライブのモデルと容量によって異なります。



== 機能の有効化と無効化

DULBEがサポートされているシステムでは、リソースプロビジョニングがデフォルトで有効になっています。このデフォルト設定は、プールとボリュームグループで無効にできます。リソースプロビジョニングの無効化は、既存のボリュームに対する永続的な処理であり、元に戻すことはできません（つまり、これらのボリュームグループおよびプールのリソースプロビジョニングを再度有効にすることはできません）。

新しいボリュームのリソースプロビジョニングを再度有効にするには、[設定][システム]メニューを使用します。リソースのプロビジョニングを再度有効にすると、新しく作成したボリュームグループとプールのみに影響する点に注意してください。既存のボリュームグループおよびプールは変更されません。必要に応じて、[設定][システム]メニューからリソースプロビジョニングを再度無効にすることもできます。
