---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-enable-security-for-a-pool-or-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: プールまたはボリュームグループのドライブセキュリティを有効にして、プールまたはボリュームグループに含まれているドライブ上のデータへの不正アクセスを防止できます。 
---
= プールまたはボリュームグループのセキュリティを有効にします
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
プールまたはボリュームグループのドライブセキュリティを有効にして、プールまたはボリュームグループに含まれているドライブ上のデータへの不正アクセスを防止できます。

ドライブの読み取りおよび書き込みアクセスは、セキュリティキーが設定されたコントローラからのみ可能です。

.作業を開始する前に
* ドライブセキュリティ機能を有効にする必要があります。
* セキュリティキーを作成する必要があります。
* プールまたはボリュームグループの状態が最適lである必要があります。
* プールまたはボリュームグループ内のすべてのドライブがセキュリティ対応である必要があります。


.このタスクについて
ドライブセキュリティを使用する場合は、セキュリティ対応のプールまたはボリュームグループを選択します。プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でないドライブの両方を含めることができますが、暗号化機能を使用するためにはすべてのドライブがセキュリティ対応である必要があります。

一度有効にしたセキュリティを解除するには、プールまたはボリュームグループを削除してからドライブを消去する必要があります。

.手順
. 管理ページで、プールまたはボリュームグループを含むストレージアレイを選択します。
. メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。
. セキュリティを有効にするプールまたはボリュームグループを選択し、[メニュー:その他のセキュリティの有効化]をクリックします。
+
[セキュリティの有効化の確認]ダイアログボックスが表示されます。

. 選択したプールまたはボリュームグループのセキュリティを有効にすることを確認し、*有効*をクリックします。

