---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-resolve-untrusted-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 信頼されていない証明書を解決するには、ストレージアレイから自己署名証明書をインポートするか、信頼できる第三者機関から発行された認証局（CA）証明書をインポートします。 
---
= 信頼されていない証明書を
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
証明書ページでは、信頼されていない証明書を解決するために、ストレージアレイから自己署名証明書をインポートするか、信頼できる第三者機関から発行された認証局（CA）証明書をインポートします。

.作業を開始する前に
CA署名証明書をインポートする場合は、次の点を確認してください。

* ストレージアレイの各コントローラの証明書署名要求（.CSRファイル）を生成してCAに送信しておく必要があります。
* 信頼された証明書ファイルをCAから受け取っておきます。
* 証明書ファイルがローカルシステム上にある必要があります。


.このタスクについて
信頼されていない証明書の問題は、ストレージアレイからプラグインへのセキュアな接続を確立しようとしたときに、接続がセキュアであることが確認できなかった場合に発生します。信頼された追加のCA証明書のインストールが必要になる可能性があるのは、次のいずれかに該当する場合です。

* ストレージアレイを新たに追加した。
* 一方または両方の証明書の期限が切れているか失効している。
* 一方または両方の証明書のルート証明書または中間証明書がない。


.手順
. [証明書管理]を選択します。
. [*Trusted*]タブを選択します。
+
このページには、ストレージアレイについて報告されたすべての証明書が表示されます。

. 次のいずれかのメニューを選択します。Import [Certificates] CA certificate or menu：Import [Self-Signed storage array certificates]。自己署名証明書をインポートします。
. 表示を制限するには、[*次の証明書を表示...]フィルタリングフィールドを使用するか、いずれかの列見出しをクリックして証明書の行をソートします。
. ダイアログボックスで証明書を選択し、*インポート*をクリックします。
+
証明書がアップロードされて検証されます。


