---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-discover-storage-arrays.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: vCenter向けストレージプラグインでストレージリソースを表示および管理するには、ネットワーク内のアレイのIPアドレスを検出する必要があります。 
---
= ストレージアレイを検出
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
vCenter向けストレージプラグインでストレージリソースを表示および管理するには、ネットワーク内のアレイのIPアドレスを検出する必要があります。

.作業を開始する前に
* アレイコントローラのネットワーク IP アドレス（またはアドレスの範囲）を確認しておく必要があります。
* ストレージアレイが正しくセットアップおよび設定されている必要があります。
* ストレージアレイのパスワードは、System Managerのアクセス管理タイルを使用して設定する必要があります。


アレイの検出は複数の手順からなる手順 です。

* <<Step 1: Enter network addresses for discovery>>
* <<Step 2: Resolve untrusted certificates during discovery>>
* <<Step 3: Provide passwords>>




== 手順 1 ：検出するネットワークアドレスを入力します

ストレージアレイを検出する最初の手順として、ローカルサブネットワーク全体を検索するための単一のIPアドレスまたはIPアドレス範囲を入力します。追加/検出機能を使用すると、検出プロセスをガイドするウィザードが開きます。

.手順
. [* Manage *（管理）]ページで、[* Add/Discover*（追加/検出*）]を選択します。
+
[Enter Network Address Range] ダイアログボックスが表示されます。

. 次のいずれかを実行します。
+
** 1 つのアレイを検出するには、 * 単一のストレージアレイの検出 * オプションボタンを選択し、ストレージアレイのいずれかのコントローラの IP アドレスを入力します。
** 複数のストレージアレイを検出するには、「ネットワーク範囲内のすべてのストレージアレイを検出」ラジオボタンを選択し、開始ネットワークアドレスと終了ネットワークアドレスを入力してローカルサブネットワーク全体を検索します。


. [ 検出の開始 ] をクリックします。
+
検出プロセスが開始されると、ストレージアレイが検出されるときにダイアログボックスに表示されます。検出プロセスが完了するまでに数分かかることがあります。

+

NOTE: 管理可能なアレイが検出されない場合は、ストレージアレイがネットワークに適切に接続されていて、割り当てられたアドレスが範囲内にあることを確認してください。[ 新規検出パラメータ * ] をクリックして、 [ 追加 / 検出 ] ページに戻ります。

. 管理ドメインに追加するストレージアレイの横にあるチェックボックスをオンにします。
+
管理ドメインに追加する各アレイについて、クレデンシャルのチェックが実行されます。信頼されていない証明書に関する問題の解決が必要になる場合があります。

. 「 * 次へ * 」をクリックして、ウィザードの次の手順に進みます。
. ストレージアレイに有効な証明書がある場合は、に進みます <<Step 3: Provide passwords>>。有効な証明書がないストレージアレイがある場合は、自己署名証明書の解決ダイアログボックスが表示されます。に進みます <<Step 2: Resolve untrusted certificates during discovery>>。CA署名証明書をインポートする場合は、検出ダイアログをキャンセルしてに進みます link:vc-olh-import-certificates-for-arrays.html["アレイの証明書をインポートします"]。




== 手順 2 ：検出時に信頼されていない証明書を解決する

必要に応じて、証明書の問題を解決してから検出プロセスを開始する必要があります。

検出時に「信頼されていない証明書」のステータスが表示されるストレージアレイがある場合は、自己署名証明書の解決ダイアログボックスが表示されます。このダイアログで信頼されていない証明書を解決するか、CA証明書をインポートできます（を参照） link:vc-olh-import-certificates-for-arrays.html["アレイの証明書をインポートします"]）。

.手順
. [ 自己署名証明書の解決 ] ダイアログボックスが開いた場合は、信頼されていない証明書について表示される情報を確認します。詳細については、表の右端にある省略記号をクリックし、ポップアップメニューから「 * 表示 * 」を選択することもできます。
. 次のいずれかを実行します。
+
** 検出されたストレージアレイへの接続を信頼する場合は、* Next *（次へ）をクリックし、* Yes *（はい）をクリックして確認し、ウィザードの次のカードに進みます。自己署名証明書は信頼済みとしてマークされ、ストレージアレイがプラグインに追加されます。
** ストレージアレイへの接続を信頼しない場合は、キャンセル*を選択し、各ストレージアレイのセキュリティ証明書戦略を検証してからプラグインに追加してください。






== 手順 3 ：パスワードを入力する

検出の最後の手順として、管理ドメインに追加するストレージアレイのパスワードを入力する必要があります。

.手順
. 必要に応じて、アレイのグループを設定済みの場合、ドロップダウンを使用して検出されたアレイのグループを選択できます。
. 検出された各アレイの admin パスワードをフィールドに入力します。
. [ 完了 ] をクリックします。



NOTE: 指定したストレージアレイへの接続がシステムで確立されるまでに数分かかることがあります。

ストレージアレイが管理ドメインに追加され、指定した場合は選択したグループに関連付けられます。


NOTE: 管理操作を実行する場合は、起動オプションを使用して、1つ以上のストレージアレイのブラウザベースのSystem Managerを開くことができます。
