---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-media-scan-settings-for-a-volume.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: メディアスキャンは、ボリューム内のすべてのデータと冗長性情報をスキャンするバックグラウンド処理です。このオプションは、1つ以上のボリュームのメディアスキャン設定を有効または無効にしたり、スキャン期間を変更したりする場合に使用します。 
---
= ボリュームのメディアスキャン設定を変更します
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
メディアスキャンは、ボリューム内のすべてのデータと冗長性情報をスキャンするバックグラウンド処理です。このオプションは、1つ以上のボリュームのメディアスキャン設定を有効または無効にしたり、スキャン期間を変更したりする場合に使用します。

.作業を開始する前に
次の点を理解しておきます

* メディアスキャンは、スキャンする容量とスキャン期間に基づいて一定の速度で継続的に実行されます。優先度の高いバックグラウンドタスク（再構築など）によってバックグラウンドスキャンが一時的に中断されることはありますが、その場合も同じ速度で再開されます。
* ボリュームは、ストレージアレイとそのボリュームでメディアスキャンオプションが有効になっている場合にのみスキャンされます。そのボリュームで冗長性チェックも有効になっている場合、ボリュームに冗長性情報があるかぎり、ボリューム内の冗長性情報とデータの整合性がチェックされます。メディアスキャンでの冗長性チェックは、ボリュームの作成時にデフォルトで有効になります。
* スキャン中に回復不能なメディアエラーが発生した場合、可能であれば、冗長性情報を使用してデータが修復されます。
+
たとえば、最適なRAID 5ボリューム、または最適なRAID 6ボリュームまたは1本のドライブのみで障害が発生したRAID 6ボリュームには、冗長性情報が存在します。冗長性情報を使用して回復不能なエラーを修復できない場合は、読み取り不能セクターログにデータブロックが追加されます。イベントログには、修正可能なメディアエラーと修正不可能なメディアエラーの両方が記録されます。

* 冗長性チェックでデータと冗長性情報の間に不整合が検出された場合は、イベントログに報告されます。


.このタスクについて
メディアスキャンは、アプリケーションで頻繁に読み取られないディスクブロック上のメディアエラーを検出して修復します。これにより、ドライブ障害が発生しても、障害ドライブのデータが冗長性情報とボリュームグループまたはプール内の他のドライブのデータを使用して再構築されるため、データが失われることはありません。

次の操作を実行できます。

* ストレージアレイ全体のバックグラウンドメディアスキャンを有効または無効にします
* ストレージアレイ全体のスキャン期間を変更します
* 1つ以上のボリュームのメディアスキャンを有効または無効にします
* 1つ以上のボリュームの冗長性チェックを有効または無効にします


.手順
. 管理ページで、メディアスキャン設定を変更するボリュームが含まれているストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ボリュームの管理 ] 。
. 任意のボリュームを選択し、メニューを選択します。More [メディアスキャン設定の変更]。
+
Change Drive Media Scan Settings（ドライブメディアスキャン設定の変更）ダイアログボックスが表示されます。このダイアログボックスには、ストレージアレイ上のすべてのボリュームが表示されます。

. メディアスキャンを有効にするには、*スキャン期間中にメディアをスキャンする*チェックボックスをオンにします。メディアスキャンを無効にすると、すべてのメディアスキャン設定が一時停止されます。
. メディアスキャンを実行する日数を指定します。
. メディアスキャンを実行する各ボリュームの[*メディアスキャン*]チェックボックスをオンにします。メディアスキャンの実行を選択した各ボリュームに対して、冗長性チェックオプションが有効になります。冗長性チェックを実行しないボリュームが個々にある場合は、*冗長性チェック*チェックボックスの選択を解除します。
. [ 保存（ Save ） ] をクリックします。


.結果
選択内容に基づいて、バックグラウンドメディアスキャンに対する変更が適用されます。
