---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-upgrade-santricity-os.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ストレージアレイのソフトウェアとNVSRAMをアップグレードして、最新の機能とバグ修正をすべて適用します。 
---
= SANtricity OSをアップグレードします
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ストレージアレイのソフトウェアとNVSRAMをアップグレードして、最新の機能とバグ修正をすべて適用します。コントローラNVSRAMは、コントローラのデフォルトの設定を指定するコントローラファイルです。

次の点を確認してください。

* 最新のSANtricity OSファイルは、プラグインが実行されているホストシステムで使用できます。
* ソフトウェアのアップグレードをすぐにアクティブ化するかあとでアクティブ化するかを決めます。あとでアクティブ化する理由は次のとおりです。
+
** * 時間帯 * -- ソフトウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
** * パッケージのタイプ *-- 他のストレージアレイのファイルをアップグレードする前に ' 新しい OS ソフトウェアを 1 つのストレージアレイでテストすることをお勧めします





CAUTION: * データ損失のリスク、ストレージアレイの損傷のリスク * -- アップグレードの実行中にストレージアレイを変更しないでください。ストレージアレイの電源は切らないでください。

.手順
. ストレージアレイにコントローラが 1 台しかない場合やマルチパスドライバが使用されていない場合は、アプリケーションエラーを回避するためにストレージアレイへの I/O アクティビティを停止します。ストレージアレイにコントローラが 2 台あり、マルチパスドライバがインストールされている場合は、 I/O アクティビティを停止する必要はありません。
. メイン・ビューから* Manage *を選択し、アップグレードするストレージ・アレイを1つ以上選択します。
. メニューから[Upgrade]> SANtricity OS]>[Software]を選択します。
+
SANtricity OS ソフトウェアのアップグレードページが表示されます。

. サポートサイトからローカルマシンに最新のSANtricity OSソフトウェアパッケージをダウンロードします。
+
.. [新しいファイルをソフトウェアリポジトリに追加]をクリックします
.. 最新のSANtricity OSダウンロードを検索するためのリンクをクリックします。
.. [Download Latest Release] リンクをクリックします。
.. 以降の手順に従って、OSファイルとNVSRAMファイルをローカルマシンにダウンロードします。
+

NOTE: バージョン 8.42 以降のデジタル署名されたファームウェアが必要です。署名のないファームウェアをダウンロードしようとすると、エラーが表示されてダウンロードが中止されます。



. コントローラのアップグレードに使用する OS ソフトウェアファイルと NVSRAM ファイルを選択します。
+
.. ドロップダウンから、ローカルマシンにダウンロードしたOSファイルを選択します。
+
使用可能なファイルが複数ある場合は、日付が新しい順にファイルがソートされます。

+

NOTE: ソフトウェアリポジトリには、プラグインに関連付けられているすべてのソフトウェアファイルが一覧表示されます。使用するファイルが表示されない場合は、リンク * ソフトウェアリポジトリに新しいファイルを追加 * をクリックして、追加する OS ファイルが保存されている場所を参照します。

.. Select an NVSRAM file * ドロップダウンから、使用するコントローラファイルを選択します。
+
ファイルが複数ある場合は、日付が新しい順にファイルがソートされます。



. [Compatible Storage Array] テーブルで ' 選択した OS ソフトウェア・ファイルと互換性のあるストレージ・アレイを確認し ' アップグレードするアレイを選択します
+
** [ 管理 ] ビューで選択したストレージ・アレイおよび選択したファームウェア・ファイルと互換性のあるストレージ・アレイは ' デフォルトで [ 互換性のあるストレージ・アレイ ] テーブルで選択されています
** 選択したファームウェアファイルで更新できないストレージアレイは、ステータス * incompatible * と表示される互換性があるストレージアレイテーブルで選択できません。


. （オプション）ソフトウェアファイルをアクティブ化せずにストレージアレイに転送するには、 * OS ソフトウェアをストレージアレイに転送し、ステージング済みとしてマークし、あとでアクティブ化 * チェックボックスをオンにします。
. [ スタート ] ボタンをクリックします。
. すぐにアクティブ化するかあとでアクティブ化するかに応じて、次のいずれかを実行します。
+
** 「transfer」と入力して、アップグレードするアレイ上のOSソフトウェアの推奨バージョンを転送することを確認し、「Transfer」をクリックします。転送されたソフトウェアをアクティブにするには、メニューから[アップグレードセンター][ステージング済みSANtricity OSソフトウェアのアクティブ化]を選択します。
** アップグレード対象として選択したアレイ上のOSソフトウェアのバージョンを転送してアクティブ化することを確認するには'upgrade]と入力し'[*Upgrade*]をクリックします
+
アップグレード対象として選択した各ストレージアレイにソフトウェアファイルが転送され、ストレージアレイがリブートされてファイルがアクティブ化されます。

+
アップグレード処理では次の処理が実行されます。

** アップグレードプロセスの一環として、アップグレード前の健常性チェックが実行されます。アップグレード前の健常性チェックでは、ストレージアレイのすべてのコンポーネントについて、アップグレードを実行できる状態であるかがチェックされます。
** いずれかの健全性チェックでストレージアレイに問題が見つかった場合、アップグレードが停止します。省略記号(...)をクリックします 「ログを保存」を選択してエラーを確認します。ヘルスチェックエラーを無視するように選択し、 * Continue * をクリックしてアップグレードを続行することもできます。
** アップグレード前の健常性チェックのあとに、アップグレード処理をキャンセルすることができます。


. （オプション）アップグレードが完了したら、省略記号（…）をクリックすると、特定のストレージアレイのアップグレード対象の一覧が表示されます。 次に、[ログの保存]を選択します。
+
ブラウザのDownloadsフォルダに'upgrade_log-<date>という名前でファイルが保存されますJSON形式


