---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-remove-capacity.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ドライブを削除することで、既存のプールまたはSSDキャッシュの容量を減らすことができます。 
---
= vCenter向けSANtricity Storage Pluginで既存のプールまたはSSDキャッシュの容量を削減する
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ドライブを削除することで、既存のプールまたはSSDキャッシュの容量を減らすことができます。

ドライブを削除したあと、プールまたはSSDキャッシュの各ボリューム内のデータは残りのドライブに再配置されます。削除されたドライブは割り当てが解除され、その容量はストレージアレイの合計空き容量に加算されます。

.このタスクについて
容量を削除する際のガイドラインを次に示します。

* SSDキャッシュ内の最後のドライブを削除するには、まずSSDキャッシュを削除する必要があります。
* プール内のドライブの数を11本より少なくすることはできません。
* 一度に削除できるドライブは最大12本です。12本を超えるドライブを削除する必要がある場合は、手順 を繰り返します。
* 削除したドライブのデータがプールまたはSSDキャッシュ内の残りのドライブに再配置される際に、プールまたはSSDキャッシュにそのデータを十分に格納できる空き容量がない場合、ドライブは削除できません。


パフォーマンスへの影響は次のとおりです。

* プールまたはSSDキャッシュからドライブを削除すると、ボリュームのパフォーマンスが低下する可能性があります。
* プールまたはSSDキャッシュから容量を削除しても、予約済み容量は消費されません。ただし、プールまたはSSDキャッシュに残っているドライブの数に基づいて、予約済み容量が減少する可能性があります。


セキュリティ対応ドライブには、次のような影響があります。

* セキュリティ対応でない最後のドライブを削除すると、プール内に残るのはすべてセキュリティ対応のドライブになります。この場合、プールのセキュリティを有効にするオプションが表示されます。
* Data Assurance（DA）対応でない最後のドライブを削除すると、プール内に残るのはすべてDA対応のドライブになります。
* このプールに作成する新しいボリュームはすべてDA対応になります。既存のボリュームをDA対応にする場合は、ボリュームを削除してから再作成する必要があります。


.手順
. 管理ページで、ストレージアレイを選択します。
+
メニューを選択します。Provisioning（プロビジョニング）[Configure Pools and Volume Groups]（プールとボリュームグループの構成）。

. プールまたはSSDキャッシュを選択し、メニューをクリックします。More [容量の削除]
+
Remove Capacityダイアログボックスが表示されます。

. リストから1つ以上のドライブを選択します。
+
リストでドライブを選択または選択解除すると、選択した容量の合計フィールドが更新されます。このフィールドには、選択したドライブを削除後のプールまたはSSDキャッシュの合計容量が表示されます。

. [*削除]をクリックし、ドライブを削除することを確認します。


.結果
プールまたはSSDキャッシュの新しく削減された容量は、プールおよびボリュームグループビューに反映されます。
