---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-assign-volumes-to-hosts.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: I/O処理に使用できるように、ボリュームをホストまたはホストクラスタに割り当てる必要があります。 
---
= ホストにボリュームを割り当てます
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I/O処理に使用できるように、ボリュームをホストまたはホストクラスタに割り当てる必要があります。

ホストにボリュームを割り当てる際は、次のガイドラインに注意してください。

* ボリュームは一度に 1 つのホストまたはホストクラスタにのみ割り当てることができます。
* 割り当てられたボリュームは、ストレージアレイのコントローラ間で共有されます。
* あるホストまたはホストクラスタからボリュームへのアクセスに、同じ論理ユニット番号（LUN）を複数回使用することはできません。一意のLUNを使用する必要があります。
* 新しいボリュームグループでは、すべてのボリュームが作成されて初期化されるまでホストに割り当てると、ボリュームの初期化時間が短縮されます。ボリュームグループに関連付けられているボリュームをマッピングすると、すべてのボリュームの初期化速度が低下することに注意してください。


ボリューム割り当ては、ストレージアレイ内のそのボリュームへのアクセスをホストまたはホストクラスタに許可します。

このタスクでは、未割り当てのボリュームはすべて表示されますが、ホストがData Assurance（DA）対応かどうかで処理は次のように異なります。

* DA 対応ホストの場合は、 DA 有効、 DA 無効のどちらのボリュームでも選択できます。
* DA 対応でないホストで DA が有効なボリュームを選択した場合、ボリュームをホストに割り当てる前にボリュームの DA を自動的に無効にする必要があるという警告が表示されます。
+
次の場合、ボリュームの割り当ては失敗します。

* すべてのボリュームが割り当てられている。
* ボリュームはすでに別のホストまたはホストクラスタに割り当てられています。次の場合、ボリュームを割り当てることはできません。
* 有効なホストまたはホストクラスタが存在しません。
* ホストポート識別子がホストに対して定義されていない。
* すべてのボリューム割り当てが定義されている。


.手順
. Manage （管理）ページで、ホスト接続があるストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ホストの設定 ] 。
+
Configure Hosts ページが開きます。

. ボリュームを割り当てるホストまたはホストクラスタを選択し、 * ボリュームの割り当て * をクリックします。
+
ダイアログボックスに割り当て可能なすべてのボリュームが表示されます。列をソートしたり、フィルタボックスに何かを入力したりすると、特定のボリュームを簡単に見つけることができます。

. 割り当てる各ボリュームの横にあるチェックボックスを選択するか、テーブルヘッダーにあるチェックボックスを選択してすべてのボリュームを選択します。
. [*Assign*] をクリックして、操作を完了します。


ホストまたはホストクラスタへのボリュームの割り当てが完了すると、次の処理が実行されます。

* 割り当てられたボリュームに次に使用可能な LUN 番号が受信されます。ホストはこの LUN 番号を使用してボリュームにアクセスします。
* ホストに関連付けられているボリュームの一覧にユーザが指定したボリューム名が表示されます。該当する場合、ホストに関連付けられているボリュームの一覧には、工場出荷時に設定されたアクセスボリュームも表示されます。

