---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-storage.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 最初に特定のアプリケーションタイプのワークロードを作成して、ストレージを作成します。次に、特性が共通する複数のボリュームを作成し、ワークロードにストレージ容量を追加します。 
---
= vCenter向けSANtricityストレージプラグインでのストレージの作成
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter向けストレージプラグインでは、最初に特定のアプリケーションタイプのワークロードを作成することでストレージを作成します。次に、特性が共通する複数のボリュームを作成し、ワークロードにストレージ容量を追加します。



== 手順1：ワークロードを作成する

ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロードまたはインスタンスを定義できます。

.このタスクについて
一部のアプリケーションでは、特性が似たボリュームで構成されるようにワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。

次のアプリケーションタイプにかぎり、最適化されたボリューム構成が推奨されます。

* Microsoft SQL Server の場合
* Microsoft Exchange Server の略
* ビデオ監視
* VMware ESXi（ボリュームをVirtual Machine File Systemで使用する場合）


.手順
. 管理ページで、ストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ボリュームの管理 ] 。
. メニューを選択します。Create [Workload]。
+
[アプリケーションワークロードの作成]ダイアログボックスが表示されます。

. ドロップダウンリストを使用してワークロードを作成するアプリケーションのタイプを選択し、ワークロード名を入力します。
. [ 作成（ Create ） ] をクリックします。




== 手順2：ボリュームを作成する

ボリュームを作成してアプリケーション固有のワークロードにストレージ容量を追加し、作成したボリュームが特定のホストまたはホストクラスタに認識されるように設定します。

.このタスクについて
ほとんどのアプリケーションタイプでは、デフォルトでユーザ定義のボリューム構成が使用されますが、その他のタイプではボリューム作成時にスマート構成が適用されます。たとえば、Microsoft Exchangeアプリケーション用のボリュームを作成する場合は、必要なメールボックスの数、メールボックスに必要とされる平均容量、およびデータベースのコピーをいくつ作成するかについて設定します。この情報に基づいて最適なボリューム構成が作成されるため、必要に応じて編集することができます。

ボリュームは、メニューから作成できます。プロビジョニング[ボリュームの管理]>[作成]>[ボリューム]またはメニューからプロビジョニング[プールとボリュームグループの設定]>[作成]>[ボリューム]。どちらの選択でも手順 は同じです。

ボリュームを作成するプロセスは複数の手順で構成される手順 です。



=== 手順2a：ボリュームのホストを選択します

最初の手順では、ボリュームに特定のホストまたはホストクラスタを選択するか、あとからホストを割り当てることができます。

.作業を開始する前に
次の点を確認してください。

* 有効なホストまたはホストクラスタが定義されている（メニュー：Provisioning [Configure Hosts]）。
* ホストに対してホストポート識別子が定義されている。
* DA対応ボリュームを作成する場合、ホスト接続でData Assurance（DA）がサポートされている必要があります。ストレージアレイのコントローラで DA をサポートしていないホスト接続が使用されている場合、関連付けられているホストからは DA 対応ボリュームのデータにアクセスできません。


.このタスクについて
ボリュームを割り当てる際は、次のガイドラインに注意してください。

* ホストのオペレーティングシステムによって、ホストがアクセスできるボリュームの数に制限がある場合があります。特定のホストで使用するボリュームを作成するときは、この制限に注意してください。
* 割り当てることができる割り当ては、ストレージアレイのボリュームごとに1つです。
* 割り当てられたボリュームは、ストレージアレイのコントローラ間で共有されます。
* あるホストまたはホストクラスタからボリュームへのアクセスに、同じ論理ユニット番号（LUN）を複数回使用することはできません。一意のLUNを使用する必要があります。
* ボリューム作成プロセスの速度を上げる場合は、ホスト割り当ての手順を省略して、新しく作成したボリュームをオフラインにすることができます。



NOTE: ホストクラスタにボリュームを割り当てる場合、そのホストクラスタ内のいずれかのホストに対してすでに確立されている割り当てと競合していると、割り当ては失敗します。

.手順
. 管理ページで、ストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ボリュームの管理 ] 。
. メニューから「 Create [Volumes] 」を選択します。
+
Select Host （ホストの選択）ダイアログボックスが表示されます。

. ボリュームを割り当てるホストまたはホストクラスタをドロップダウンリストから選択するか、ホストまたはホストクラスタをあとで割り当てるように選択します。
. 選択したホストまたはホストクラスタのボリューム作成手順を続行するには、* Next.*をクリックします
+
ワークロードの選択ダイアログボックスが表示されます。





=== 手順2b：ボリュームのワークロードを選択します

2番目の手順では、ワークロードを選択して、VMwareなどの特定のアプリケーション用にストレージアレイの構成をカスタマイズします。

.このタスクについて
このタスクでは、ワークロード用のボリュームを作成する方法について説明します。一般に、ワークロードには、ワークロードがサポートするアプリケーションのタイプに基づいて最適化された、同様の特性を持つボリュームが含まれます。この手順でワークロードを定義するか、既存のワークロードを選択できます。

次のガイドラインに注意してください。

* アプリケーション固有のワークロードを使用する場合、アプリケーションワークロードのI/Oとアプリケーションインスタンスからの他のトラフィックの競合が最小限になるように最適化されたボリューム構成が提示されます。ボリュームの追加/編集ダイアログボックス（次の手順で使用可能）を使用して、推奨されるボリューム構成を確認し、システム推奨のボリュームや特性を編集、追加、削除できます。
* 他の種類のアプリケーションを使用する場合は、ボリュームの追加/編集ダイアログボックス（次の手順で使用可能）を使用して、ボリューム構成を手動で指定します。


.手順
. 次のいずれかを実行します。
+
** 既存のワークロード用のボリュームの作成 * オプションを選択し、ドロップダウンリストからワークロードを選択します。
** サポート対象のアプリケーションまたは「その他」のアプリケーションに対して新しいワークロードを定義するには、「*新しいワークロードを作成する」オプションを選択し、次の手順を実行します。
+
*** ドロップダウンリストから、新しいワークロードを作成するアプリケーションの名前を選択します。このストレージアレイで使用するアプリケーションが表示されていない場合は、「Other」エントリのいずれかを選択します。
*** 作成するワークロードの名前を入力します。




. 「 * 次へ * 」をクリックします。
. ワークロードがサポート対象のアプリケーションタイプに関連付けられている場合は、要求された情報を入力します。それ以外の場合は、次の手順に進みます。




=== 手順2c：ボリュームを追加または編集する

3つ目の手順では、ボリューム構成を定義します。

.作業を開始する前に
* プールまたはボリュームグループに十分な空き容量が必要です。
* 1つのボリュームグループに含めることができるボリュームの最大数は256です。
* プールで使用できる最大ボリューム数は、ストレージシステムのモデルによって異なります。
+
** 2、048ボリューム（EF600およびE5700シリーズ）
** 1、024ボリューム（EF300）
** 512ボリューム（E2800シリーズ）


* Data Assurance（DA）対応ボリュームを作成する場合は、使用するホスト接続でDAがサポートされている必要があります。
+
** DA対応ボリュームを作成する場合は、DAに対応したプールまたはボリュームグループを選択します（プールとボリュームグループの候補テーブルで「DA」の横にある「* Yes」を探します）。
** DA 機能はプールおよびボリュームグループのレベルで提供されます。DA 保護は、データがコントローラ経由でドライブに転送される際に発生する可能性があるエラーをチェックして修正します。新しいボリュームに DA 対応のプールまたはボリュームグループを選択すると、エラーがある場合には検出されて修正されます。
** ストレージアレイのコントローラで DA をサポートしていないホスト接続が使用されている場合、関連付けられているホストからは DA 対応ボリュームのデータにアクセスできません。


* セキュリティ有効ボリュームを作成するには、ストレージアレイのセキュリティキーを作成する必要があります。
+
** セキュリティ有効ボリュームを作成する場合は、セキュリティ対応のプールまたはボリュームグループを選択します（プールとボリュームグループの候補テーブルで「セキュリティ対応」の横にある「はい」を探します）。
** ドライブセキュリティ機能は、プールおよびボリュームグループのレベルで提供されます。セキュリティ対応ドライブを使用すると、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。セキュリティ有効ドライブでは、一意の暗号化キーを使用して、書き込み時にデータが暗号化され、読み取り時に復号化されます。
** プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でないドライブの両方を含めることができますが、暗号化機能を使用するためにはすべてのドライブがセキュリティ対応である必要があります。


* リソースプロビジョニングボリュームを作成するには、すべてのドライブが Deallocated or Unwritten Logical Block Error （ DULBE ）オプションを適用した NVMe ドライブである必要があります。


.このタスクについて
対応するプールまたはボリュームグループからボリュームを作成します。これらのプールは、ボリュームの追加と編集ダイアログボックスに表示されます。対象となる各プールおよびボリュームグループについて、使用可能なドライブの数と合計空き容量が表示されます。

アプリケーション固有のワークロードがある場合、候補となる各プールまたはボリュームグループに、推奨されるボリューム構成に基づいて提示される容量が表示され、残りの空き容量が GiB 単位で表示されます。それ以外のワークロードの場合、プールまたはボリュームグループにボリュームを追加してレポート容量を指定した時点で容量が提示されます。

.手順
. 前の手順でほかにワークロードを選択したかアプリケーション固有のワークロードを選択したかに基づいて、次のいずれかの操作を実行します。
+
** *その他*：1つ以上のボリュームの作成に使用する各プールまたはボリュームグループで'新しいボリュームの追加をクリックします
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| フィールド | 説明 


 a| 
ボリューム名
 a| 
ボリュームには、作成時にデフォルトの名前が割り当てられます。デフォルトの名前をそのまま使用することも、ボリュームに格納されたデータのタイプを表した名前を指定することもできます。



 a| 
レポート容量
 a| 
新しいボリュームの容量と単位（ MiB 、 GiB 、または TiB ）を定義します。シックボリュームの場合、最小容量は1MiBであり、最大容量はプールまたはボリュームグループに含まれるドライブの数と容量で決まります。コピーサービス（Snapshotイメージ、Snapshotボリューム、ボリュームコピー、およびリモートミラー）用のストレージ容量も必要であることに注意してください。そのため、 標準ボリュームにすべての容量を割り当てないでください。プールの容量は4GiB単位で割り当てられます。4GiBの倍数でない容量を割り当てた場合、その容量は使用できません。全容量を使用できるようにするため、4GiB単位で容量を指定してください。使用不可容量が存在する場合、その容量を使用するにはボリュームの容量を増やすしかありません。



 a| 
ボリュームのブロックサイズ（EF300およびEF600のみ）
 a| 
ボリュームに対して作成できるブロックサイズが表示されます。

*** 512 ～ 512 バイト
*** 4K – 4 、 096 バイト




 a| 
セグメントサイズ（ Segment Size ）
 a| 
セグメントのサイジングに関する設定が表示されます。これは、ボリュームグループのボリュームについてのみ表示されます。セグメントサイズを変更することでパフォーマンスを最適化することができます。*許容されるセグメントサイズの推移*-許容されるセグメントサイズの推移がシステムによって決定されます。現在のセグメントサイズの変更後のサイズとして適切でないものは、ドロップダウンリストに表示されません。通常、許容される変更後のサイズは、現在のセグメントサイズの倍または半分です。たとえば、ボリュームの現在のセグメントサイズが 32KiB であれば、ボリュームの新しいセグメントサイズとして 16KiB または 64KiB が許容されます。* SSDキャッシュが有効なボリューム*- SSDキャッシュが有効なボリュームでは、セグメントサイズを4KiBに指定することができます。4KiB のセグメントサイズを選択するのは、 SSD キャッシュが有効なボリュームで小さいブロックの I/O 処理を実行する（ I/O ブロックサイズが 16KiB 以下の場合など）場合のみにしてください。SSD キャッシュが有効なボリュームで大きいブロックのシーケンシャル処理を実行する場合は、セグメントサイズとして 4KiB を選択するとパフォーマンスが低下することがあります。*セグメントサイズの変更にかかる時間*-ボリュームのセグメントサイズの変更にかかる時間は、次の要因によって異なります。

*** ホストからの I/O 負荷
*** ボリュームの修正の優先順位
*** ボリュームグループ内のドライブの数
*** ドライブチャネルの数
*** ストレージアレイコントローラの処理能力


ボリュームのセグメントサイズを変更すると I/O パフォーマンスに影響しますが、データの可用性は維持されます。



 a| 
セキュリティ対応
 a| 
*「Secure Capable」の横には、プールまたはボリューム・グループ内のドライブがセキュア対応である場合のみ「Secure Capable」と表示されます。ドライブセキュリティは、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止します。このオプションは、ドライブセキュリティ機能が有効になっていて、ストレージアレイのセキュリティキーが設定されている場合にのみ使用できます。プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でないドライブの両方を含めることができますが、暗号化機能を使用するためにはすべてのドライブがセキュリティ対応である必要があります。



 a| 
ダ
 a| 
*はい*は、プールまたはボリュームグループ内のドライブがData Assurance（DA）をサポートしている場合にのみ「DA」の横に表示されます。DA を使用すると、ストレージシステム全体のデータの整合性が向上します。DA を使用すると、データがコントローラ経由でドライブに転送される際にストレージアレイがエラーの有無をチェックできます。新しいボリュームに DA を使用すると、すべてのエラーが検出されます。



 a| 
リソースのプロビジョニング（EF300およびEF600のみ）
 a| 
* Yes *は、ドライブがこのオプションをサポートしている場合にのみ、[Resource Provisioned（リソースのプロビジョニング）]の横に表示されます。リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。

|===
====
** *アプリケーション固有のワークロード*--選択したワークロードのシステム推奨のボリュームと特性を受け入れるには、[次へ]をクリックします。選択したワークロードのシステム推奨のボリュームと特性を変更、追加、または削除するには、[ボリュームの編集]をクリックします。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| フィールド | 説明 


 a| 
ボリューム名
 a| 
ボリュームには、作成時にデフォルトの名前が割り当てられます。デフォルトの名前をそのまま使用することも、ボリュームに格納されたデータのタイプを表した名前を指定することもできます。



 a| 
レポート容量
 a| 
新しいボリュームの容量と単位（ MiB 、 GiB 、または TiB ）を定義します。シックボリュームの場合、最小容量は1MiBであり、最大容量はプールまたはボリュームグループに含まれるドライブの数と容量で決まります。コピーサービス（Snapshotイメージ、Snapshotボリューム、ボリュームコピー、およびリモートミラー）用のストレージ容量も必要であることに注意してください。そのため、 標準ボリュームにすべての容量を割り当てないでください。プールの容量は 4GiB 単位で割り当てられます。4GiB の倍数でない容量を割り当てた場合、その容量は使用できません。全容量を使用できるようにするため、 4GiB 単位で容量を指定してください。使用不可容量が存在する場合、その容量を使用するにはボリュームの容量を増やすしかありません。



 a| 
ボリュームタイプ
 a| 
アプリケーション固有のワークロード用に作成されたボリュームのタイプを示します。



 a| 
ボリュームのブロックサイズ（EF300およびEF600のみ）
 a| 
ボリュームに対して作成できるブロックサイズが表示されます。

*** 512 -- 512バイト
*** 4k -- 4,096バイト




 a| 
セグメントサイズ（ Segment Size ）
 a| 
セグメントのサイジングに関する設定が表示されます。これは、ボリュームグループのボリュームについてのみ表示されます。セグメントサイズを変更することでパフォーマンスを最適化することができます。*許容されるセグメントサイズの推移*-許容されるセグメントサイズの推移がシステムによって決定されます。現在のセグメントサイズの変更後のサイズとして適切でないものは、ドロップダウンリストに表示されません。通常、許容される変更後のサイズは、現在のセグメントサイズの倍または半分です。たとえば、ボリュームの現在のセグメントサイズが 32KiB であれば、ボリュームの新しいセグメントサイズとして 16KiB または 64KiB が許容されます。* SSDキャッシュが有効なボリューム*- SSDキャッシュが有効なボリュームでは、セグメントサイズを4KiBに指定することができます。4KiB のセグメントサイズを選択するのは、 SSD キャッシュが有効なボリュームで小さいブロックの I/O 処理を実行する（ I/O ブロックサイズが 16KiB 以下の場合など）場合のみにしてください。SSD キャッシュが有効なボリュームで大きいブロックのシーケンシャル処理を実行する場合は、セグメントサイズとして 4KiB を選択するとパフォーマンスが低下することがあります。*セグメントサイズの変更にかかる時間*-ボリュームのセグメントサイズの変更にかかる時間は、次の要因によって異なります。

*** ホストからの I/O 負荷
*** ボリュームの修正の優先順位
*** ボリュームグループ内のドライブの数
*** ドライブチャネルの数
*** ストレージアレイコントローラの処理能力


ボリュームのセグメントサイズを変更すると I/O パフォーマンスに影響しますが、データの可用性は維持されます。



 a| 
セキュリティ対応
 a| 
*「Secure Capable」の横には、プールまたはボリューム・グループ内のドライブがセキュア対応である場合のみ「Secure Capable」と表示されます。ドライブセキュリティを使用すると、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。このオプションは、ドライブセキュリティ機能が有効になっていて、ストレージアレイのセキュリティキーが設定されている場合にのみ使用できます。プールまたはボリュームグループにはセキュリティ対応とセキュリティ対応でないドライブの両方を含めることができますが、暗号化機能を使用するためにはすべてのドライブがセキュリティ対応である必要があります。



 a| 
ダ
 a| 
*はい*は、プールまたはボリュームグループ内のドライブがData Assurance（DA）をサポートしている場合にのみ「DA」の横に表示されます。DA を使用すると、ストレージシステム全体のデータの整合性が向上します。DA を使用すると、データがコントローラ経由でドライブに転送される際にストレージアレイがエラーの有無をチェックできます。新しいボリュームに DA を使用すると、すべてのエラーが検出されます。



 a| 
リソースのプロビジョニング（EF300およびEF600のみ）
 a| 
* Yes *は、ドライブがこのオプションをサポートしている場合にのみ、[Resource Provisioned（リソースのプロビジョニング）]の横に表示されます。リソースプロビジョニングは、EF300およびEF600ストレージアレイで使用できる機能です。これにより、バックグラウンドの初期化プロセスを実行せずに、ボリュームをただちに使用できます。

|===
====


. 選択したアプリケーションのボリューム作成手順を続行するには、 * 次へ * をクリックします。




=== 手順2d：ボリュームの構成を確認します

最後の手順では、作成するボリュームの概要を確認し、必要に応じて変更を加えます。

.手順
. 作成するボリュームを確認します。変更するには、「 * 戻る」をクリックします。
. ボリューム構成に問題がなければ、「 * 完了 * 」をクリックします。


.完了後
* vSphere Clientで、ボリューム用のデータストアを作成します。
* アプリケーションがボリュームを使用できるように、アプリケーションホストのオペレーティングシステムに対して必要な変更を行います。
* オペレーティングシステム固有のユーティリティ（サードパーティベンダーから入手可能）を実行してから、SMcliコマンドを実行します。 `-identifyDevices` ボリューム名をホストストレージアレイ名に関連付けるには、次の手順を実行します。
+
SMcliはSANtricity OSに含まれており、SANtricityシステムマネージャからダウンロードできます。SANtricityシステムマネージャからSMcliをダウンロードする方法の詳細については、 https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["SANtricity System Managerオンラインヘルプのコマンドラインインターフェイス（CLI）のダウンロードのトピック"^]。


