---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-is-shelf-loss-protection-and-drawer-loss-protection.html 
keywords:  
summary:  
---
= シェルフ損失の保護およびドロワー損失の保護とは何ですか？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
シェルフ損失の保護とドロワー損失の保護は、シェルフまたはドロワーで単一障害が発生した場合にデータアクセスを維持するためのプールとボリュームグループの属性です。



=== シェルフ損失の保護

シェルフは、ドライブまたはドライブとコントローラを格納するエンクロージャです。シェルフ損失の保護が有効な場合、1台のドライブシェルフとの通信が完全に失われた場合でもプールまたはボリュームグループ内のボリューム上のデータへのアクセスが保証されます。通信が完全に失われるケースには、ドライブシェルフの電源喪失や、両方のI/Oモジュール（IOM）の障害などがあります。


NOTE: プールまたはボリュームグループですでにドライブに障害が発生している場合は、シェルフ損失の保護は保証されません。この状況で、ドライブシェルフへのアクセス、さらにその結果プールまたはボリュームグループ内の別のドライブへのアクセスを失うと、データが失われます。

シェルフ損失の保護の条件は、次の表で説明するように、保護の手法によって異なります。

|===
| レベル | シェルフ損失の保護の条件 | 必要なシェルフの最小数 


| プール | プールには少なくとも5つのシェルフのドライブが含まれている必要があり、各シェルフで同じ数のドライブが必要です。シェルフ損失の保護は大容量シェルフには適用されません。大容量シェルフがあるシステムの場合は、ドロワー損失の保護を参照してください。 | 5. 


| RAID 6 | ボリュームグループに同じドロワーのドライブが3本以上含まれない。 | 3. 


| RAID 3またはRAID 5 | ボリュームグループ内のドライブがすべて別々のシェルフに配置されている。 | 3. 


| RAID 1 | RAID 1ペアのドライブがそれぞれ別のシェルフに配置されている。 | 2. 


| RAID 0 | シェルフ損失の保護は実現できない。 | 該当なし 
|===


=== ドロワー損失の保護

ドロワーはシェルフのコンパートメントの1つで、引き出してドライブを設置します。ドロワーを備えているのは大容量シェルフのみです。ドロワー損失の保護が有効な場合、1つのドロワーとの通信が完全に失われた場合でもプールまたはボリュームグループ内のボリューム上のデータへのアクセスが保証されます。通信が完全に失われるケースには、ドロワーの電源喪失や、ドロワー内のコンポーネント障害などがあります。


CAUTION: プールまたはボリュームグループですでにドライブに障害が発生している場合は、ドロワー損失の保護は保証されません。この状況でドロワーにアクセスできなくなると（その結果プールまたはボリュームグループ内の別のドライブにアクセスできなくなると）、データが失われます。

ドロワー損失の保護の条件は、次の表で説明するように、保護の手法によって異なります。

|===
| レベル | ドロワー損失の保護の基準 | 必要なドロワーの最小数 


| プール | プール候補にはすべてのドロワーのドライブを含める必要があり、各ドロワーに同じ数のドライブが必要です。プールには少なくとも5つのドロワーのドライブが含まれている必要があり、各ドロワーに同じ数のドライブが必要です。60ドライブのシェルフでは、プールに含まれる15、20、25、30、35でドロワー損失の保護を実現できます。 40、45、50、55、または60ドライブ。初回作成後に、5の倍数でプールに追加できます。 | 5. 


| RAID 6 | ボリュームグループに同じドロワーのドライブが3本以上含まれない。 | 3. 


| RAID 3または5 | ボリュームグループ内のドライブがすべて別々のドロワーに配置されている | 3. 


| RAID 1 | ミラーペアのドライブがそれぞれ別のドロワーに配置されている。 | 2. 


| RAID 0 | ドロワー損失の保護は実現できない。 | 該当なし 
|===