---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-view-status.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: ストレージプラグインfor vCenterまたはvSphere Clientからシステムステータスを表示する 
---
= ステータスを表示します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
システムステータスは、Storage Plugin for vCenterまたはvSphere Clientで確認できます。

. vSphere Clientでプラグインを開きます。
. 次のパネルからステータスを表示します。
+
** *ストレージ・アレイのステータス*--[* Manage-All*]パネルに移動します検出された各アレイについて、行にStatus列が表示されます。
** *操作が進行中*--サイドパネルの*操作*をクリックすると、設定のインポートなど、長時間実行されているすべてのタスクが表示されます。Provisioningドロップダウンから、実行時間の長い処理を表示することもできます。[実行中の処理]ダイアログに表示された各処理について、完了率と処理が完了するまでの推定時間が表示されます。場合によっては、処理を停止したり、処理の優先度を変更したりできます。必要に応じて、[アクション（Actions）]列のリンクを使用して、オペレーションの優先度を停止または変更します。





CAUTION: 特に、処理を停止する場合は、ダイアログボックスに表示されているすべての警告テキストをお読みください。

プラグインに対して表示される処理を次の表に示します。その他の処理は、System Managerインターフェイスに表示される場合もあります。

|===
| 操作 | 処理のステータス | 対処方法 


| ボリュームの作成（64TiBを超えるシックプールボリュームのみ） | 実行中です | なし 


| ボリュームの削除（64TiBを超えるシックプールボリュームのみ） | 実行中です | なし 


| プールまたはボリュームグループに容量を追加してください | 実行中です | なし 


| ボリュームのRAIDレベルを変更します | 実行中です | なし 


| プールの容量を削減します | 実行中です | なし 


| プールボリュームのInstant Availability Format（IAF）処理の残り時間を確認します | 実行中です | なし 


| ボリュームグループのデータ冗長性をチェックします | 実行中です | なし 


| ボリュームを初期化 | 実行中です | なし 


| ボリュームの容量を拡張します | 実行中です | なし 


| ボリュームのセグメントサイズを変更します | 実行中です | なし 
|===