---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-host-access.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: vCenter向けストレージプラグインを使用してストレージを管理するには、ネットワーク内の各ホストを検出または定義する必要があります。 
---
= vCenter向けSANtricityストレージプラグインでのホストアクセスの作成
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter向けストレージプラグインを使用してストレージを管理するには、ネットワーク内の各ホストを検出または定義する必要があります。

.このタスクについて
ホストを作成すると、ストレージアレイへの接続とボリュームへのI/Oアクセスを提供するホストパラメータを定義できます。

ホストを作成する際は、次のガイドラインに注意してください。

* ホストに関連付けられたホストポート識別子を定義する必要があります。
* ホストに割り当てられたシステム名と同じ名前を指定してください。
* 選択した名前がすでに使用されている場合、この処理は失敗します。
* 名前は 30 文字以内にする必要があります。


.手順
. Manage （管理）ページで、ホスト接続があるストレージアレイを選択します。
. メニューを選択します。 Provisioning [ ホストの設定 ] 。
+
Configure Hosts ページが開きます。

. メニュー： Create [Host] をクリックします。
+
Create Host （ホストの作成）ダイアログボックスが表示されます。

. ホストの設定を必要に応じて選択します。
+
.フィールドの詳細
[%collapsible]
====
[cols="25h,~"]
|===
| 設定 | 説明 


 a| 
名前
 a| 
新しいホストの名前を入力します。



 a| 
ホストオペレーティングシステムのタイプ
 a| 
新しいホストで実行しているオペレーティングシステムをドロップダウンリストから選択します。



 a| 
ホストインターフェイスタイプ
 a| 
（オプション）ストレージアレイで複数のタイプのホストインターフェイスがサポートされている場合、使用するホストインターフェイスタイプを選択します。



 a| 
ホストポート
 a| 
次のいずれかを実行します。

** * I/Oインターフェイスの選択*--通常'ホストポートはログインしており'ドロップダウン・リストから使用できるようになっている必要がありますリストからホストポート識別子を選択することができます。
** *手動追加*--ホストポート識別子がリストに表示されない場合は'ホストポートがログインしていないことを意味しますHBA ユーティリティまたは iSCSI イニシエータユーティリティを使用して、ホストポート識別子を検索してホストに関連付けることができます。ホストポート識別子を手動で入力するか、ユーティリティから（一度に 1 つずつ）ホストポートフィールドにコピーして貼り付けることができます。ホストポート識別子は、一度に 1 つずつ選択してホストに関連付ける必要がありますが、ホストに関連付けられている識別子をいくつでも選択することができます。各識別子はホストポートフィールドに表示されます。必要に応じて、横の * X * を選択して識別子を削除することもできます。




 a| 
CHAP イニシエータシークレットを設定する
 a| 
（オプション）iSCSI IQNを使用してホストポートを選択または手動で入力し、ストレージアレイにアクセスしてCHAP（Challenge Handshake Authentication Protocol）を使用して認証するホストを必要とする場合は、[Set CHAP initiator secret]チェックボックスをオンにします。選択または手動で入力した iSCSI ホストポートごとに、次の手順を実行します。

** CHAP 認証用に各 iSCSI ホストイニシエータに設定されたものと同じ CHAP シークレットを入力します。相互 CHAP 認証（ホストが自身をストレージアレイに対して検証し、ストレージアレイが自身をホストに対して検証できるようにする双方向認証）を使用する場合は、ストレージアレイの初期セットアップまたは設定変更時に CHAP シークレットも設定する必要があります。
** ホストの認証が不要な場合は、このフィールドを空白のままにします。現在使用されている iSCSI 認証方式は CHAP だけです。


|===
====
. [ 作成（ Create ） ] をクリックします。
. ホスト情報を更新する必要がある場合は、表からホストを選択し、 * 表示 / 設定の編集 * をクリックします。


.結果
ホストの作成が完了すると、ホストに設定されている各ホストポートのデフォルト名（ユーザラベル）が作成されます。デフォルトのエイリアスは「 <Hostname_Port number>` 」です。たとえば、ホスト IPT に対して最初に作成されたポートのデフォルトのエイリアスは「 ipt_1 」です。

.完了後
I/O処理に使用できるように、ボリュームをホストに割り当てる必要があります。に進みます link:vc-olh-assign-volumes-to-hosts.html["ホストにボリュームを割り当てます"]。
