---
permalink: install-hw-cabling/index.html 
sidebar: sidebar 
keywords: cabling, cables, E-Series, eseries, E2800, E5700, EF300, EF600, DE212C, DE224C, DE460C 
summary: ホストをコントローラに直接接続するか、スイッチを使用します。 
---
= ケーブル接続の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストはコントローラに直接ケーブル接続することも、スイッチを使用してコントローラに接続することもできます。

ストレージシステムにドライブシェルフが含まれている場合は、それらをコントローラシェルフにケーブル接続する必要があります。ストレージシステムの他のコンポーネントに電源が投入されている状態で、新しいドライブシェルフを追加できます。また、アウトオブバンド管理のためにストレージシステムをネットワークに接続することもできます。

ケーブル接続情報は、ストレージシステムを設置または拡張するハードウェア設置担当者またはシステム管理者を対象としています。また、使用するハードウェアの設置とセットアップの手順書の説明に従ってストレージシステムが設置されていることを前提としています。



== 対象となるハードウェアモデル

ケーブル接続情報環境次のハードウェアモデル

|===
| * コントローラシェルフ * | * ドライブシェルフ * 


 a| 
EF600
 a| 
該当なし。



 a| 
E5724 、 EF570 、 E2812 、 E2824 、 EF280
 a| 
DE212C 、 DE224C



 a| 
E2860 、 E5760
 a| 
DE460C

|===


== ケーブル接続に関するその他の情報

次の構成でケーブル接続する場合は、を参照してください https://mysupport.netapp.com/ecm/ecm_download_file/ECMLP2859057["IOM ドライブシェルフを既存の E27XX 、 E56XX 、または EF560 コントローラシェルフに追加"^]

|===
| * コントローラシェルフ * | * ドライブシェルフ * 


 a| 
E2712 、 E2724 、 E5612 、 E5624 、 EF560
 a| 
DE212C 、 DE224C



 a| 
E2760 、 E5660
 a| 
DE460C

|===
その他のケーブル接続オプションについては、を参照してください https://mysupport.netapp.com/ecm/ecm_download_file/ECMLP2773533["『 E-Series Hardware Cabling Guide 』を参照してください"^] 古いシステムの場合。

ミラーリング機能をサポートするためのケーブル接続については、を参照してください https://www.netapp.com/us/media/tr-4656.pdf["同期および非同期ミラーリング機能の説明と導入ガイド"^]。
