---
permalink: maintenance-e4000/replace-drive-e4000.html 
sidebar: sidebar 
keywords:  
summary: E4000ドライブを交換する前に、要件と考慮事項を確認してください。 
---
= ドライブの交換要件- E4000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E4000ドライブを交換する前に、要件と考慮事項を確認してください。



== シェルフタイプ

12 ドライブ、 24 ドライブ、 60 ドライブのコントローラシェルフまたはドライブシェルフに搭載されたドライブを交換することができます。


NOTE: 標準の 24 ドライブシェルフでは、ドライブを交互に配置する必要があります。E4000コントローラに挿入するドライブが24本未満の場合は、コントローラの2つの部分を交互に使用する必要があります。一番左、次に一番右、というようにドライブを一度に 1 本ずつ配置します。



== ドライブの取り扱い

ストレージアレイのドライブは壊れやすいので注意して扱ってください。ドライブの取り扱いが適切でないことは、ドライブ障害の主要な原因です。

ストレージアレイのドライブの破損を防ぐために、次のルールに従ってください。

* 静電放電（ ESD ）防止処置を施す：
+
** 取り付け準備ができるまで、ドライブを ESD バッグに入れたままにしておきます。
** ESD バッグに金属製の工具やナイフを入れないでください。
+
ESD バッグを手で開けるか、バッグの上部をハサミで切り落とします。

** ESD バッグと梱包材は、あとでドライブの返却が必要になったときのために保管しておいてください。
** 作業中は常に ESD リストストラップを着用し、ストレージエンクロージャのシャーシの塗装されていない表面部分にリストストラップを接地させます。
+
リストストラップがない場合は、ドライブに触る前に、ストレージエンクロージャのシャーシの塗装されていない部分を手で触ります。



* ドライブは慎重に扱う：
+
** 取り外し、取り付け、持ち運びなど、ドライブを扱うときは常に両手で作業してください。
** ドライブをシェルフに取り付けるときは、無理に押し込まず、ドライブラッチにしっかりと固定されるまでそっと押し込んでください。
** ドライブはやわらかい場所に置き、他のドライブと重ねて置かないでください。
** ドライブをぶつけないでください。
** ドライブをシェルフから取り外すときは、ハンドルを外し、ドライブがスピンダウンするまで 60 秒待ってください。
** ドライブを発送するときは、必ず承認された梱包材を使用し


* 磁場を避ける：
+
** ドライブを磁気デバイスに近づけないでください。
+
磁場によってドライブに保存されているすべてのデータが破損したり、ドライブの回路が故障し、原因が修理不可能となる場合があります。




