---
permalink: maintenance-e4000/replace-controller-requirements-e4000.html 
sidebar: sidebar 
keywords:  
summary:  
---
= E4000 コントローラの交換に際しての要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E4000 コントローラを交換または追加する前に、要件と考慮事項を確認してください。

各コントローラキャニスターには、コントローラカードとバッテリが搭載されています。シンプレックス構成に 2 台目のコントローラを追加したり、障害が発生したコントローラを交換したりできます。



== 2 台目のコントローラの追加に際しての要件

シンプレックスバージョンのE4000コントローラシェルフには、2台目のコントローラキャニスターを追加できます。2 台目のコントローラを追加する前に、次の作業を完了しておく必要があります

* 現在取り付けられているコントローラキャニスターと同じパーツ番号の新しいコントローラキャニスター。
+

NOTE: これは、StorageGRIDアプライアンスには適用されません。

* 新しいコントローラポートの接続に必要なすべてのケーブル、トランシーバ、スイッチ、ホストバスアダプタ（ HBA ）。
+
互換性のあるハードウェアについては、または http://hwu.netapp.com/home.aspx["NetApp Hardware Universe の略"]を参照して https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperability Matrix を参照してください"]ください。

* ホストにマルチパスドライバがインストールされているため、両方のコントローラを使用できます。手順については、、 https://docs.netapp.com/us-en/e-series/config-windows/index.html["Windows の簡単な設定"]、またはを https://docs.netapp.com/us-en/e-series/config-vmware/index.html["VMware の簡単な設定"]参照し https://docs.netapp.com/us-en/e-series/config-linux/index.html["Linux の簡単な設定"]てください。
* ESD リストバンドを装着するか、静電気防止処置を施しておきます。
* No.1 プラスドライバ。
* 新しいケーブルを識別するためのラベル。
* コントローラの SANtricity System Manager にアクセスできるブラウザを備えた管理ステーション。（System Managerインターフェイスを開くには、コントローラのドメイン名またはIPアドレスをブラウザで指定します）。
+
必要に応じて、コマンドラインインターフェイス（ CLI ）を使用して一部の手順を実行できます。SANtricity System Manager（バージョン11.60以降）の場合は、System ManagerからCLIパッケージ（zipファイル）をダウンロードできます。これを行うには、System Managerで*[設定]>[システム]>[アドオン]>[コマンドラインインターフェイス]*に移動します。次に、 DOS C ：プロンプトなどのオペレーティングシステムプロンプトから問題 CLI コマンドを実行します。





== コントローラの交換に際しての要件

障害が発生したコントローラキャニスターを交換するときは、元のコントローラキャニスターからバッテリ、HIC、DIMMを取り外して交換用コントローラキャニスターに取り付ける必要があります。

コントローラキャニスターに障害が発生したかどうかは、次の 2 つの方法で確認できます。

* SANtricity System Manager の Recovery Guru で、コントローラキャニスターを交換するように指示されます。
* コントローラキャニスターの黄色の警告 LED が点灯して、コントローラに障害が発生したことが通知されます。


コントローラを交換する前に、次の作業を完了しておく必要があります。

* 交換するコントローラキャニスターと同じパーツ番号の交換用コントローラキャニスター。
* ESD リストバンドを装着するか、静電気防止処置を施しておきます。
* コントローラキャニスターに接続する各ケーブルを識別するためのラベル。
* No.1 プラスドライバ。
* コントローラの SANtricity System Manager にアクセスできるブラウザを備えた管理ステーション。（System Managerインターフェイスを開くには、コントローラのドメイン名またはIPアドレスをブラウザで指定します）。
+
必要に応じて、コマンドラインインターフェイス（ CLI ）を使用して一部の手順を実行できます。SANtricity System Manager（バージョン11.60以降）の場合は、System ManagerからCLIパッケージ（zipファイル）をダウンロードできます。これを行うには、System Managerで*[設定]>[システム]>[アドオン]>[コマンドラインインターフェイス]*に移動します。次に、 DOS C ：プロンプトなどのオペレーティングシステムプロンプトから問題 CLI コマンドを実行します。





=== デュプレックス構成の要件

コントローラシェルフにコントローラを 2 台搭載したデュプレックス構成の場合は、次の条件を満たしていれば、ストレージアレイの電源をオンにした状態でホスト I/O 処理を継続したままコントローラキャニスターを交換できます。

* シェルフのもう一方のコントローラキャニスターのステータスが「最適」である。
* SANtricity System Manager の Recovery Guru の詳細領域の「 * 削除してもよろしいですか？」というメッセージが表示され、このコンポーネントを削除しても安全であることを示します。




=== シンプレックス構成の要件

コントローラキャニスターが 1 つだけのシンプレックス構成の場合は、コントローラキャニスターの交換が完了するまでストレージアレイのデータにアクセスできません。ホスト I/O 処理を停止し、ストレージアレイの電源をオフにする必要があります。
