---
permalink: maintenance-e5700/batteries-intro-concept.html 
sidebar: sidebar 
keywords: E5700 battery, repair E5700 battery, replace E5700 battery, failed E5700 battery 
summary: E5700 バッテリの交換に関する要件と考慮事項を確認してください。 
---
= バッテリの交換要件- E5700
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E5700 バッテリを交換する前に、要件と考慮事項を確認してください。

各コントローラキャニスターには、 AC 電源で障害が発生した場合にキャッシュデータを保持するバッテリが搭載されています。



== Recovery Guru のアラート

SANtricity System Manager の Recovery Guru から次のいずれかのステータスが報告された場合は、該当するバッテリを交換する必要があります。

* バッテリで障害が発生しまし
* バッテリの交換が必要です


SANtricity System Manager の Recovery Guru で詳細を確認し、問題にバッテリが搭載されていること、および先に対処する必要がある項目がほかにないことを確認します。



== 手順の概要

データを保護するために、障害が発生したバッテリはできるだけ早く交換する必要があります。

E5700 コントローラ（ E5724 、 EF570 、または E5760 ）のバッテリを交換する手順の概要は次のとおりです。

. コントローラをオフラインにします（デュプレックスのみ）。
. コントローラキャニスターを取り外します。
. バッテリを交換します。
. コントローラキャニスターを交換します。
. コントローラをオンラインにします（デュプレックスのみ）。




== 要件

障害が発生したバッテリを交換する場合は、次の準備をしておく必要があります。

* 交換用バッテリ。
* ESD リストバンドを装着するか、静電気防止処置を施しておきます。
* コントローラキャニスターに接続する各ケーブルを識別するためのラベル。
* コントローラの SANtricity System Manager にアクセスできるブラウザを備えた管理ステーション。（ System Manager インターフェイスを開くには、ブラウザでコントローラのドメイン名または IP アドレスを指定します）。
+
必要に応じて、コマンドラインインターフェイス（ CLI ）を使用して一部の手順を実行できます。CLI にアクセスできない場合は、次のいずれかを実行できます。

+
** * SANtricity System Manager （バージョン 11.60 以降） * - System Manager から CLI パッケージ（ zip ファイル）をダウンロードします。[ 設定 ] 、 [ システム ] 、 [ アドオン ] 、 [ コマンドラインインターフェイス ] の順に選択します。次に、 DOS C ：プロンプトなどのオペレーティングシステムプロンプトから問題 CLI コマンドを実行します。
** * SANtricity Storage Manager/Enterprise Management Window （ EMW ）：ソフトウェアをダウンロードしてインストールするには ' エクスプレス・ガイドの指示に従ってくださいEMW から CLI コマンドを実行するには、次のメニューを選択します： Tools [Execute Script]



