---
permalink: maintenance-e5700/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: E5700 host interface card, E5700 HIC, replace E5700 HIC, failed E5700 HIC 
summary: E5700 HIC の交換に関する要件を確認します。 
---
= E5700 HIC の交換に際しての要件
:icons: font
:imagesdir: ../media/


[role="lead"]
E5700 でホストインターフェイスカード（ HIC ）を追加、アップグレード、交換する前に、要件と考慮事項を確認してください。



== 手順の概要

E5724 コントローラシェルフおよび E5760 コントローラシェルフに搭載された HIC を追加、アップグレード、交換することができます。

E5700 コントローラ（ E5724 または E5760 ）の HIC を交換する手順の概要は次のとおりです。

. コントローラをオフラインにします
. コントローラキャニスターを取り外します
. バッテリを交換します
. コントローラキャニスターを交換します
. コントローラをオンラインにします




== HIC の追加、アップグレード、交換に際しての要件

ホストインターフェイスカード（ HIC ）を追加、アップグレード、交換するときは、次の要件に注意してください。

* この手順のダウンタイムメンテナンス時間をスケジュールする必要があります。HIC を取り付けるときは電源をオフにする必要があるため、この手順が完了するまではストレージアレイのデータにアクセスできません。（これは、電源をオンにしたときに HIC の構成が両方のコントローラで同じになっている必要があるため、デュプレックス構成にも当てはまります。）
* コントローラと互換性がある HIC が 2 つ必要です。
+
デュプレックス構成（コントローラが 2 台）の場合は、 2 つのコントローラキャニスターに同じ HIC を取り付ける必要があります。HIC が一致していないと、交換用 HIC を搭載したコントローラをオンラインにしたときにロックダウン状態になります。

* 新しいホストポートの接続に必要なすべてのケーブル、トランシーバ、スイッチ、ホストバスアダプタ（ HBA ）を用意しておきます。
+
互換性のあるハードウェアについては、を参照してください https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperability Matrix を参照してください"^] または http://hwu.netapp.com/home.aspx["NetApp Hardware Universe の略"^]。

* ESD リストバンドを装着するか、静電気防止処置を施しておきます。
* No.1 プラスドライバを用意しておきます。
* コントローラキャニスターに接続する各ケーブルを識別するためのラベルを用意しておきます。
* コントローラの SANtricity System Manager にアクセスするためのブラウザを備えた管理ステーションを用意しておきます。（ System Manager インターフェイスを開くには、ブラウザでコントローラのドメイン名または IP アドレスを指定します）。

