---
permalink: maintenance-e5700/index.html 
sidebar: sidebar 
keywords: E5700 maintenance, repair E5700, replace E5700 components, E5724, EF570, E5760 
summary: E5700 ハードウェアの保守 
---
= E5700 ハードウェアのメンテナンス
:icons: font
:imagesdir: ../media/


[role="lead"]
E5700 ストレージシステムでは、次のコンポーネントのメンテナンス手順を実行できます。



== 電池

バッテリは、コントローラキャニスターに搭載されており、 AC 電源で障害が発生した場合にキャッシュデータを保持する役割があります。



== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 System Manager の機能を実装します。



== キャニスター

キャニスターは 3 つのタイプに分類されます。電源 / ファンキャニスター（電源装置）は冗長な電源を提供し、 12 ドライブまたは 24 ドライブのコントローラシェルフまたはドライブシェルフで適切な冷却を行います。電源キャニスターは、 60 ドライブのコントローラシェルフまたはドライブシェルフで電源の冗長性を確保するために使用されます。 および 60 ドライブのコントローラシェルフまたはドライブシェルフの冷却に使用されるファンキャニスター。



== ドライブ

ドライブは、データの物理ストレージメディアとして使用される電磁的な機械デバイスです。



== ホストインターフェイスカード（ HIC ）

ホストインターフェイスカード（ HIC ）は、コントローラキャニスターにオプションで取り付けることができます。E5700 コントローラには、コントローラカード自体に搭載されたホストポートとオプションの HIC に搭載されたホストポートがあります。コントローラに搭載されたホストポートのことをベースボードホストポートと呼び、HIC に搭載されたホストポートのことを HIC ポートと呼びます。



== ホストポートプロトコル

互換性と通信の確立のために、ホストのプロトコルを別のプロトコルに変換することができます。
