---
permalink: maintenance-ef50-ef80/controller-replace-prepare.html 
sidebar: sidebar 
keywords: ef50, ef80, prepare the impaired controller 
summary: EF50またはEF80ストレージシステムの障害コントローラを交換する準備として、交換用コントローラを開梱し、部品番号が正しいことを確認し、構成データベースをバックアップします。 
---
= コントローラの交換の準備 - EF50 および EF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF50またはEF80ストレージシステムの障害コントローラを交換する準備として、交換用コントローラを開梱し、MACアドレスをメモし、部品番号が正しいことを確認し、ストレージシステムの構成データベースをバックアップします。

.手順
. 交換用コントローラーを開梱し、静電気のない平らな場所に置いてください。
+
故障したコントローラを返送する際に使用するため、梱包材は保管しておいてください。

. 交換用コントローラの側面に記載されているMACアドレスをメモしておいてください。
+
MAC アドレスは、コントローラの交換手順で後ほど使用します。

. 交換用コントローラの部品番号が、SANtricity System Managerのコントローラの交換部品番号と同じであることを確認します。
+

CAUTION: *データアクセスが失われる可能性があります*：2つの部品番号が同じでない場合は、この手順を実行しないでください。コントローラの不一致があると、交換用コントローラをオンラインにしたときにロックダウンされます。

+
.. 交換用コントローラの側面に記載されている部品番号を控えておいてください。
.. Recovery Guruの詳細エリアに表示されている、障害が発生したコントローラの交換部品番号を確認します。
+
この番号を手動で調べる必要がある場合は、以下の手順に従ってください：

+
... *Hardware* > *Controllers and components* を選択します。
... 障害が発生したコントローラー（コントローラーAまたはコントローラーB）のコントローラーグラフィックを選択して、コンテキストメニューを表示します。
... 「 * 表示設定 * 」を選択します。
... [*Base] タブで、コントローラの交換パーツ番号 * をメモします。


.. 2 つの部品番号を比較して、同じであることを確認してください。
.. 次のステップは、部品番号が同じかどうかによって異なります：
+
[cols="1,2"]
|===
| 状況 | 操作 


 a| 
2つの部品番号は同じです
 a| 
次のステップに進んでください。



 a| 
2つの部品番号は異なります
 a| 
この手順を続行することはできません。

 https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]サポートが必要な場合は、お問い合わせください。

|===


. SANtricity System Manager を使用して、ストレージシステムの構成データベースをバックアップします。
+
コントローラーを削除した際に問題が発生した場合、保存したファイルを使用して設定を復元できます。システムは、コントローラー上のボリュームグループとディスクプールに関するすべてのデータを含む、RAID構成データベースの現在の状態を保存します。

+
.. *サポート›サポートセンター›診断*を選択します。
.. [ 構成データの収集 *] を選択します。
.. *Collect* を選択します。
+
ブラウザの Downloads フォルダに、「 * configurationdata-<ArrayName>-<dateTime >.7z * 」という名前でファイルが保存されます。





.次の手順
コントローラー交換の準備後、link:controller-replace-offline-controller.html["障害のあるコントローラをオフラインにします"]。
