---
permalink: maintenance-ef50-ef80/controller-replace-complete-replacement.html 
sidebar: sidebar 
keywords: ef50, ef80, how to complete the controller replacement process 
summary: EF50またはEF80ストレージシステムのコントローラー交換を完了するには、ストレージシステムのファームウェアが最新であることを確認し、ボリュームが所有者に返却されていることを確認し、システムサポートデータを収集し、故障した部品をNetAppに返送してください。 
---
= コントローラの交換を完了する - EF50およびEF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF50またはEF80ストレージシステムのコントローラー交換を完了するには、最新バージョンのSANtricity OSがインストールされていることを確認し、ボリュームが所有コントローラーに戻されていることを確認し、システムサポートデータを収集し、障害が発生した部品をNetAppに返却します。



== ステップ 1：最新バージョンの SANtricity OS であることを確認し、ボリューム所有権を確認し、サポートデータを収集する

SANtricity System Manager を使用して、最新バージョンの SANtricity OS がインストールされていることを確認し、すべてのボリュームが所有コントローラに戻されていることを検証し、サポートデータを収集して運用を再開できるようにします。

.手順
. ストレージシステムに最新バージョンのSANtricity OSがインストールされていることを確認してください：
+
.. *サポート* > *アップグレードセンター* を選択します
.. 必要に応じて、最新バージョンをインストールします。


. すべてのボリュームがそれぞれの所有コントローラに返されていることを確認します。
+
[cols="1,2"]
|===
| 状況 | 操作 


 a| 
Recovery Guruが存在し、ボリュームが優先パス上にない（所有コントローラに戻されていない）ことを示しています。
 a| 
.. ボリュームをそれぞれのコントローラーに再分配するには、*Storage* > *Volumes* > *More* を選択し、ドロップダウンメニューから *Redistribute volumes* を選択します。
.. Recovery Guruが存在し、ボリュームが優先パス上にないことを示しているかどうかを確認することで、すべてのボリュームがそれぞれの所有コントローラに再分配されていることを確認します。



NOTE: ボリュームがまだ所有しているコントローラに戻らない場合は、 https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]に連絡してください。



 a| 
Recovery Guruは存在しません（すべてのボリュームがそれぞれのコントローラーに戻されているようです）
 a| 
すべてのボリュームがそれぞれの所有コントローラーに戻されていることを確認するには、*ストレージ* > *ボリューム* > *その他* を選択し、ドロップダウンメニューから *ボリュームの所有権の変更* を選択してボリュームの所有者を表示します。

|===
. ストレージシステムに関するサポートデータを収集する
+
.. [ サポート * （ Support * ） ]>[ * サポートセンター * （ * Support Center * ） ]>[ * 診断 * （ Diagnostics * ） ] を選択
.. 「サポートデータの収集」を選択します。
.. *Collect* を選択します。
+
ブラウザの Downloads フォルダに、「 * support-data.7z * 」という名前でファイルが保存されます。







== ステップ2：故障した部品をNetAppに返却します

障害のある部品は、キットに付属するRMA指示書に従ってNetAppに返却してください。詳細については、 https://mysupport.netapp.com/site/info/rma["部品の返品と交換"]ページを参照してください。

.次の手順
これでコントローラの交換は完了です。通常の運用を再開することができます。
