---
permalink: maintenance-ef600/controllers-overview-supertask-concept.html 
sidebar: sidebar 
keywords: replace EF300 controller, replace EF600 controller, 
summary: EF300 または EF600 コントローラの交換に際しての要件と考慮事項 
---
= EF300 または EF600 コントローラの交換に際しての要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF300 または EF600 コントローラを交換する前に、要件と考慮事項を確認してください。

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 SANtricity System Manager の機能を実装します。



== コントローラの交換に際しての要件

コントローラを交換する前に、次の作業を完了しておく必要があります。

* 交換するコントローラキャニスターと同じパーツ番号の交換用コントローラキャニスター。
* ESD リストバンドを装着するか、静電気防止処置を施しておきます。
* コントローラキャニスターに接続する各ケーブルを識別するためのラベル。
* No.1 プラスドライバ。
* コントローラの SANtricity System Manager にアクセスできるブラウザを備えた管理ステーション。（ System Manager インターフェイスを開くには、ブラウザでコントローラのドメイン名または IP アドレスを指定します）。




== 電源を入れたまま交換してください

次の条件に該当する場合は、ストレージアレイの電源をオンにした状態でホスト I/O 処理を継続したままコントローラキャニスターを交換できます。

* シェルフのもう一方のコントローラキャニスターのステータスが「最適」である。
* SANtricity System Manager の Recovery Guru の詳細領域の「 * 削除してもよろしいですか？」というメッセージが表示され、このコンポーネントを削除しても安全であることを示します。

