---
permalink: maintenance-ef600/dimms-overview-supertask-concept.html 
sidebar: sidebar 
keywords: EF300, EF600, replace DIMM, EF300C, EF600C 
summary: EF300 または EF600 DIMM を交換する前に、要件と考慮事項を確認します。 
---
= DIMMの交換要件- EF300およびEF600
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF300、EF600、EF600C、またはEF300CストレージアレイのDIMMを交換する前に、要件と考慮事項を確認してください。

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM を交換する必要があります。EF300、EF600、EF300C、またはEF600Cコントローラの構成を確認し、正しいDIMMサイズが交換されたことを確認してください。


CAUTION: ストレージアレイの DIMM は壊れやすいので注意してください。適切に取り扱わないと破損するおそれがあります。

ストレージアレイの DIMM の破損を防ぐために、次のルールに従ってください。

* 静電放電（ ESD ）防止処置を施す：
+
** 取り付け準備ができるまで、 DIMM を ESD バッグに入れたままにしておきます。
** ESD バッグを手で開けるか、バッグの上部をハサミで切り落とします。ESD バッグに金属製の工具やナイフを入れないでください。
** ESD バッグと梱包材は、あとで DIMM の返却が必要になったときのために保管しておいてください。
+

CAUTION: 作業中は常に ESD リストストラップを着用し、ストレージエンクロージャのシャーシの塗装されていない表面部分にリストストラップを接地させます。



* DIMM は慎重に扱う：
+
** 取り外し、取り付け、持ち運びなど、 DIMM を扱うときは常に両手で作業してください。
** DIMM をシェルフに取り付けるときは、無理に押し込まず、ラッチにしっかりと固定されるまでそっと押し込んでください。
** DIMM を発送するときは、必ず承認された梱包材を使用し


* 磁場を避ける。DIMM を磁気デバイスに近づけないでください。

