---
permalink: maintenance-ef600/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: EF300, EF600, EF300C, EF600C, replace HIC, replace HIC, host interface card failed, HIC failure 
summary: EF300 または EF600 の HIC を交換する前に、要件と考慮事項を確認します。 
---
= EF300 または EF600 の HIC をアップグレードするための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF300、EF600、EF300C、またはEF600Cアレイのホストインターフェイスカード（HIC）をアップグレードまたは交換する前に、次の要件を確認してください。

* この手順でダウンタイムのメンテナンス時間をスケジュールしておきます。この手順が完了するまではストレージアレイのデータにアクセスできません。電源がオンになっているときは両方のコントローラで HIC の構成が同じである必要があるため、 HIC の構成を変更したときは電源をオフにする必要があります。HIC が一致していないと、交換用 HIC を搭載したコントローラをオンラインにしたときにロックダウン状態になります。
* 新しいホストポートの接続に必要なすべてのケーブル、トランシーバ、スイッチ、ホストバスアダプタ（ HBA ）を用意しておきます。
+
互換性のあるハードウェアについては、を参照してください https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperability Matrix を参照してください"^] または http://hwu.netapp.com/home.aspx["NetApp Hardware Universe の略"^]。

* ESD リストバンドを装着するか、静電気防止処置を施しておきます。
* No.1 プラスドライバを用意しておきます。
* コントローラキャニスターに接続する各ケーブルを識別するためのラベルを用意しておきます。
* コントローラの SANtricity System Manager にアクセスできるブラウザを備えた管理ステーション。（ System Manager インターフェイスを開くには、ブラウザでコントローラのドメイン名または IP アドレスを指定します）。
* HIC の交換やアップグレードによっては、ホストポートプロトコルの変更が必要になることがあります。の手順に従います xref:hpp-change-supertask-task.html[EF300 または EF600 のホストプロトコルを変更する] を参照してください。
* EF300 コントローラには、ホスト接続用の HIC ポート 2 が取り付けられている必要があります。

