---
permalink: maintenance-ef600/index.html 
sidebar: sidebar 
keywords: EF300 maintenance, EF600 maintenance, repairing EF300, repairing EF600, replace EF300 components, replace EF600 components 
summary: EF300 および EF600 ハードウェアをメンテナンスします 
---
= EF300 および EF600 ハードウェアをメンテナンスする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF300 および EF600 ストレージシステムの場合は、次のコンポーネントのメンテナンス手順を実行できます。



== 電池

バッテリはコントローラに搭載されており、 AC 電源で障害が発生した場合にキャッシュデータを保持します。



== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 SANtricity System Manager の機能を実装します。



== DIMM

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



== ドライブ

ドライブは、データの物理ストレージメディアとして使用されるデバイスです。



== ファン

EF300 または EF600 のコントローラシェルフまたはドライブシェルフには、コントローラを冷却するためのファンが 5 台ずつ搭載されています。



== ホストインターフェイスカード（ HIC ）

ホストインターフェイスカード（ HIC ）はコントローラキャニスターに取り付ける必要があります。EF600 コントローラには、オプションの HIC 上にホストポートがあります。HIC に搭載されたホストポートのことを HIC ポートと呼びます。



== ホストポートプロトコル

互換性と通信の確立のために、ホストのプロトコルを別のプロトコルに変換することができます。



== 電源装置

電源装置は、コントローラシェルフに電源の冗長性を提供します。



== SAS 拡張カード

SAS 拡張カードは、コントローラキャニスターに取り付けることができます。EF300 コントローラは SAS 拡張をサポートします。
