---
permalink: config-windows/configure-multipath-software-task.html 
sidebar: sidebar 
keywords: multipath software for Windows, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Windows 用のマルチパスソフトウェアを含む DSM パッケージをインストールします。 
---
= マルチパスソフトウェアを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイへのパスを冗長化するには、 SANtricity Windows DSM パッケージをインストールし、 Windows 向けのマルチパスパッケージを使用します。

.必要なもの
適切な管理者権限またはスーパーユーザ権限です。

.このタスクについて
マルチパスソフトウェアは、物理パスの 1 つが中断された場合に備えて、ストレージアレイへのパスを冗長化します。マルチパスを使用するには、 SANtricity DSM パッケージをインストールする必要があります。このパッケージには、 Windows 向けのマルチパスソフトウェアが含まれています。

Windows のインストール環境では、フェイルオーバーにネイティブの MPIO Device Specific Module （ DSM ；デバイス固有モジュール）ドライバを使用します。SANtricity Windows DSM パッケージをインストールして有効にする場合、マルチパスを使用するためにそれ以上の操作を行う必要はありません。

.手順
. から * SANtricity * Windows DSM * パッケージをダウンロードします https://mysupport.netapp.com/site/products/all/details/eseries-santricityos/downloads-tab["SANtricity OS ソフトウェアのページ"^]。ソフトウェアバージョン SANtricity を選択し、ライセンス契約に同意して、 [ 追加ダウンロード ] の下の [*Windows DSM*] を選択します。
. SANtricity * Windows DSM * インストーラーを実行します。実行するインストールパッケージをダブルクリックします。
. インストールウィザードを使用して、管理ステーションにパッケージをインストールします。

