---
permalink: config-windows/configure-ip-address-dhcp-task.html 
sidebar: sidebar 
keywords: IP address, DHCP, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Dynamic Host Configuration Protocol\ （ DHCP ；動的ホスト構成プロトコル）を使用して、 Windows の簡単な方法で IP アドレスを提供します。 
---
= DHCP を使用して IP アドレスを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ステーションとストレージアレイ間の通信を設定するには、動的ホスト構成プロトコル（ DHCP ）を使用して IP アドレスを指定します。

.作業を開始する前に
次のものがあることを確認します。

* ストレージ管理ポートと同じサブネットに DHCP サーバをインストールして設定します。


.このタスクについて
各ストレージアレイにはコントローラが 1 台（シンプレックス）または 2 台（デュプレックス）含まれ、コントローラごとにストレージ管理ポートが 2 つあります。各管理ポートには IP アドレスが割り当てられます。

以下の手順では、コントローラを 2 台搭載したストレージアレイ（デュプレックス構成）を使用します。

.手順
. 管理ステーションと各コントローラ（ A および B ）の管理ポート 1 にイーサネットケーブルを接続します（まだ接続していない場合）。
+
DHCP サーバは、各コントローラのポート 1 に IP アドレスを割り当てます。

+

NOTE: どちらのコントローラの管理ポート 2 も使用しないでください。ポート 2 はネットアップのテクニカルサポート用に予約されています。

+

NOTE: イーサネットケーブルを外して再接続するか、ストレージアレイの電源を再投入すると、 DHCP によって IP アドレスが再度割り当てられます。このプロセスは、静的 IP アドレスが設定されるまで行われます。ケーブルを外したり、アレイの電源を再投入したりしないことを推奨します。

+
DHCP によって割り当てられた IP アドレスをストレージアレイが 30 秒以内に取得できない場合は、次のデフォルトの IP アドレスが設定されます。

+
** コントローラ A 、ポート 1 ： 169.254.128.101
** コントローラ B 、ポート 1 ： 169.254.128.102
** サブネットマスク： 255.255.0.0


. 各コントローラの背面にある MAC アドレスラベルを確認し、ネットワーク管理者に各コントローラのポート 1 の MAC アドレスを伝えます。
+
MAC アドレスは、ネットワーク管理者が各コントローラの IP アドレスを特定するために必要です。ブラウザからストレージシステムに接続するには、 IP アドレスが必要です。


