---
permalink: config-windows/install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Windows Unified Host Utilities, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Windows の簡単な方法で Windows Unified Host Utilities をインストールする。 
---
= Windows Unified Host Utilities をインストールして設定します
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows Unified Host Utilities ツールを使用して、ホストコンピュータをネットアップストレージシステムに接続し、ホストコンピュータで必要なパラメータを設定できます。また、ネットアップストレージとの間で最適な読み取り / 書き込みパフォーマンスを達成するために、適切なディスクタイムアウトを設定することもできます。


NOTE: 詳細については、の「 _Windows Host Utilities Installation Guide 」を参照してください http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["ネットアップのマニュアル： Host Utilities"^]。

.手順
. を使用します http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^] をクリックして、インストールする Unified Host Utilities の適切なバージョンを確認します。
+
サポートされる構成ごとに対応するバージョンが表示されます。

. から Unified Host Utilities をダウンロードします http://mysupport.netapp.com["ネットアップサポート"^]。
+

NOTE: このユーティリティパッケージは、 SANtricity ストレージマネージャインストーラを使用してインストールすることはできません。

+

NOTE: または、 SANtricity SMdevices ユーティリティを使用して Unified Host Utility ツールと同じ機能を実行することもできます。SMdevices ユーティリティは SMutils パッケージに含まれています。SMutils パッケージは、ホストがストレージアレイから認識する内容を確認するためのユーティリティをまとめたパッケージです。SANtricity ソフトウェアのインストールに含まれています。


