---
permalink: upgrade-controllers/complete-upgrade-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, vendor ID, upgrade status, upgrade validate 
summary: コントローラのアップグレードを完了するには、コントローラシェルフの電源をオンにし、コントローラのソフトウェアのバージョンを確認します。その後、サポートデータを収集し、運用を再開できます。 
---
= Eシリーズコントローラのアップグレードの完了
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラのアップグレードを完了するには、コントローラシェルフの電源をオンにし、コントローラのソフトウェアのバージョンを確認します。その後、サポートデータを収集し、運用を再開できます。

デュプレックスのコントローラドライブトレイのコントローラをアップグレードする場合は、同じ手順を繰り返して 2 台目のコントローラのアップグレードを実行します。



== 手順 1 ：コントローラの電源をオンにします

コントローラシェルフの電源をオンにして、正しく動作していることを確認する必要があります。

.手順
. コントローラドライブトレイに接続された各ドライブトレイの背面にある電源スイッチをオンにします
. ドライブがスピンアップするまで 2 分待ちます。
. コントローラドライブトレイの背面にある電源スイッチをオンにします
. 電源投入プロセスが完了するまで 3 分待ちます。
. E2800 コントローラまたは E5700 コントローラを交換する場合は、ドライブセキュリティの状況に応じて次のいずれかの手順に進みます。
+
|===
| コントローラの交換の種類 | 手順および前提条件 


 a| 
いずれのドライブもセキュリティ保護されていない、外部キー管理でも内部キー管理でもない
 a| 
次の手順に進みます。



 a| 
セキュリティ保護されたドライブとセキュリティ保護されていないドライブが混在している、内部キー
 a| 
内部セキュリティキーを作成してから、そのセキュリティキーを手動でインポートしてセキュリティ保護されたドライブのロックを解除する必要があります。ドライブのロックが解除されると、ドライブにアクセスできるようになります。

.. 内部セキュリティキーを作成します
.. 内部キー管理を使用して 1 本以上のドライブがセキュリティ保護されている場合のコントローラの交換
.. SMclientコマンドを実行します。 `set allDrives nativeState`。
.. 両方のコントローラがリブートするまで待ちます。




 a| 
すべてのドライブがセキュリティ保護されている、内部キー管理
 a| 
内部キー管理を使用して 1 本以上のドライブがセキュリティ保護されている場合のコントローラの交換



 a| 
セキュリティ保護されたドライブとセキュリティ保護されていないドライブが混在している、外部キー
 a| 
次の手順に進みます。

コントローラの交換の完了後、コントローラが自動的に外部キー管理サーバと再同期され、ドライブのロックが解除されてアクセスできるようになります。


NOTE: 内部キー管理でセキュリティ保護されたドライブが混在している状況で、コントローラを交換したあとにデジタル表示ディスプレイにロックダウンコード「 L5 」が表示される場合は、テクニカル・サポートにお問い合わせください。



 a| 
すべてのドライブがセキュリティ保護されている、外部キー管理、コントローラ交換用手順の内部キー管理に一時的に切り替えている
 a| 
最初に、内部キー管理手順を使用して、セキュリティ保護されたドライブのロックを解除する必要があります。ドライブのロックを解除したあと、ストレージアレイの新しい外部セキュリティキーを作成して外部キー管理に戻します。

.. 内部キー管理を使用して 1 本以上のドライブがセキュリティ保護されている場合のコントローラの交換
.. 外部セキュリティキーを作成します
.. SMclientコマンドを実行します。 `set allDrives nativeState`。
.. 両方のコントローラがリブートするまで待ちます。




 a| 
すべてのドライブがセキュリティ保護されている、外部キー管理、コントローラの交換用手順の内部キー管理に一時的に切り替えていない
 a| 
外部キー管理を使用し、すべてのドライブがセキュリティ保護されている場合のコントローラの交換詳細については、を参照してください https://docs.netapp.com/us-en/e-series/upgrade-controllers/upgrade-unlock-drives-task.html#external-key-management["外部キー管理"^]。

|===




== 手順 2 ：コントローラとトレイのステータスを確認する

LED とストレージ管理ソフトウェアを使用して、コントローラとトレイのステータスを確認できます。

.手順
. コントローラ A の LED を参照して、正しくブートしていることを確認します。
+
リブート中は、ホストリンク保守操作必要 LED が緑色に点灯します。

+
コントローラのリブートが完了したら、ストレージ管理ソフトウェアを使用して新しいコントローラキャニスターを検出できます。

. コントローラドライブトレイのいずれかの保守操作必要 LED が点灯している場合やコントローラ保守操作必要 LED が点灯している場合は、次の手順を実行します。
+
.. コントローラキャニスターが正しく取り付けられていること、およびすべてのケーブルが正しく装着されていることを確認します。必要に応じて、コントローラキャニスターを再度取り付けます。
.. コントローラドライブトレイの保守操作必要 LED とコントローラ保守操作必要 LED をもう一度確認します。問題が解決しない場合は、テクニカルサポートにお問い合わせください。


. デュプレックス構成の場合は、コントローラ B について手順 1 と手順 2 を繰り返します
. LED とストレージ管理ソフトウェアを使用して、ストレージアレイ内のすべてのトレイのステータスを確認します。ステータスが「要注意」のコンポーネントがある場合は、 Recovery Guru を使用してトラブルシューティングします。問題が解決しない場合は、テクニカルサポートにお問い合わせください。




== 手順 3 ：コントローラのソフトウェアのバージョンを確認する

新しいコントローラが正しいオペレーティングシステム（コントローラファームウェア）レベルと NVSRAM で動作していることを確認する必要があります。

.手順
. コントローラのアップグレードでプロトコルが変更になる場合（ Fibre Channel から iSCSI など）、ストレージアレイに対して定義されたホストがすでにあるときは、新しいホストポートをホストに関連付けます。
+
.. System Manager で、メニューから「 Storage [Hosts] 」を選択します。
.. ポートを関連付けるホストを選択し、 * 表示 / 設定の編集 * をクリックします。
+
ダイアログボックスが開き、現在のホスト設定が表示されます。

.. [ ホストポート *] タブをクリックします。
+
ダイアログボックスに現在のホストポート識別子が表示されます。

.. 各ホストに関連付けられているホストポート識別子の情報を更新するには、古いホストアダプタのホストポート ID を新しいホストアダプタの新しいホストポート ID に置き換えます。
.. 各ホストについて手順 d を繰り返します。
.. [ 保存（ Save ） ] をクリックします。


+
互換性のあるハードウェアについては、を参照してください https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperability Matrix を参照してください"^] および http://hwu.netapp.com/home.aspx["NetApp Hardware Universe の略"^]。

. ヘッド交換の準備ですべてのシンボリュームでライトバックキャッシュを無効にしていた場合は、ライトバックキャッシュを再度有効にします。
+
.. System Manager で、メニューから「 Storage [Volumes] 」を選択します。
.. 任意のボリュームを選択し、メニューを選択します。 More [ キャッシュ設定の変更 ] 。
+
[ キャッシュ設定の変更 ] ダイアログボックスが表示されます。このダイアログボックスには、ストレージアレイ上のすべてのボリュームが表示されます。

.. [基本]*タブを選択し、読み取りキャッシュと書き込みキャッシュの設定を有効にします。
.. [ 保存（ Save ） ] をクリックします。


. ヘッド交換の準備で SAML が無効になっていた場合は、 SAML を再度有効にします。
+
.. System Manager で、メニューから「 Settings 」（設定）「 Access Management 」（アクセス管理）を選択します。
.. SAML * タブを選択し、ページの指示に従います。


. GUI または CLI のいずれかを使用して、ストレージアレイに関するサポートデータを収集します。
+
** System Managerを使用して、ストレージアレイのサポートバンドルを収集して保存します。
+
*** System Manager で、次のメニューを選択します。 Support [Support Center] > [Diagnostics （診断） ] タブ。次に、 [ サポートデータの収集 ] を選択し、 [ * 収集 ] をクリックします。
+
ブラウザの Downloads フォルダに、「 upport-data.7z 」という名前でファイルが保存されます。

+
シェルフにドロワーが搭載されている場合、そのシェルフの診断データは「 tray -component-state-capture.7z 」という別の圧縮ファイルにアーカイブされます



** ストレージアレイに関する包括的なサポートデータを収集するには、 CLI を使用して「 save storageArray supportData 」コマンドを実行します。
+

NOTE: サポートデータの収集時は、ストレージアレイのパフォーマンスに一時的に影響が及ぶことがあります。



. ストレージアレイの構成の変更をネットアップテクニカルサポートに連絡します。
+
.. でメモしておいたコントローラドライブトレイのシリアル番号を用意します xref:prepare-upgrade-controllers-task.adoc[コントローラをアップグレードする準備をします]。
.. ネットアップサポートサイトにログインします http://mysupport.netapp.com/eservice/assistant["mysupport.netapp.com/eservice/assistant"^]。
.. [ * カテゴリ 1 * ] の下のドロップダウン・リストから [ * 製品登録 * ] を選択します。
.. [**Comments**] テキスト・ボックスに次のテキストを入力しますシリアル番号は ' コントローラ・ドライブ・トレイのシリアル番号に置き換えてください
+
「シリアル番号：シリアル番号に対して警告を作成してください。アラート名は「 E-Series Upgrade 」にする必要があります。アラート・テキストは ' のようになります

+
「注意：このシステムのコントローラは、元の構成からアップグレードされています。交換用コントローラを注文する前にコントローラ構成を確認し、システムがアップグレードされたことをディスパッチに通知します。

.. フォームの下部にある [*Submit*] ボタンをクリックします。




.次の手順
コントローラのアップグレードが完了し、通常の運用を再開できます。
