---
permalink: upgrade-controllers/install-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, installing new controller, install new controller, install battery, installing battery, install controller canister 
summary: 古いコントローラを取り外したら、新しいコントローラをコントローラドライブトレイに取り付けることができます 
---
= 新しいコントローラを設置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
古いコントローラを取り外したら、新しいコントローラをコントローラドライブトレイに取り付けることができます

.このタスクについて
コントローラドライブトレイの各コントローラについて、次の手順を実行しますデュプレックスのコントローラドライブトレイのコントローラをアップグレードする場合は、同じ手順を繰り返して 2 台目のコントローラキャニスターを取り付けます。

.作業を開始する前に
次のものがあることを確認します。

* ESD リストバンドを装着するか、静電気防止処置を施します。
* 元のコントローラキャニスターのバッテリ、または注文した新しいバッテリ。
* 新しいコントローラキャニスター。




== 手順 1 ：バッテリを取り付ける

元のコントローラキャニスターから取り外したバッテリ、または注文した新しいバッテリを取り付けます。

.手順
. 新しいコントローラキャニスターを開封し、取り外し可能なカバーを上にして、静電気防止処置を施した平らな場所に置きます。
. カバーのボタンを押し下げながらスライドし、カバーを取り外します。
. バッテリのスロットが手前になるようにコントローラキャニスターの向きを変えます。
. バッテリを新しいコントローラキャニスターに挿入します。
+
バッテリが新しいキャニスターの壁面のリベットの下の位置にくるまでスライドします。

+
.. 固定用ハンドルを 45 度傾けて、バッテリ下部のコネクタをキャニスターのコネクタに合わせます。
.. カチッという音がするまでバッテリを下に押し、固定用ハンドルを上に動かしてコントローラバッテリをコントローラキャニスターに固定します。
+

TIP: E5XX コントローラドライブトレイにコントローラバッテリが正しく装着されていることを確認するには、一度引き出してから再度挿入します。カチッという音がして収まり、固定用ハンドルを小刻みに動かしても直立した状態から動かなければ、正しい位置に固定されています。

.. カチッという音がして上部ラッチカバーが固定されるまで上部カバーを前方にスライドして、新しいコントローラキャニスターに上部カバーを再度取り付けます。
+
カチッという音がしてラッチが固定されると、ラッチの下部がシャーシの金属製のスロットに収まります。



. コントローラキャニスターを裏返し、バッテリが正しく取り付けられていることを確認します。




== 手順 2 ：新しいコントローラキャニスターを取り付ける

新しいコントローラキャニスターをコントローラシェルフに取り付けます。

.手順
. 新しいコントローラキャニスターをスライドしてコントローラドライブトレイに最後まで押し込みますリリースハンドルをコントローラキャニスターの中央に向けて回転させ、所定の位置に固定します。
. 新しいコントローラキャニスターに Fibre Channel HIC または InfiniBand HIC が搭載されている場合は、 SFP+ トランシーバ（ Fibre Channel ）または QSFP+ トランシーバ（ InfiniBand ）をコントローラキャニスターに取り付け、ホストケーブルを再接続します。
+
アップグレードに関係する HIC によっては、古いコントローラキャニスターから取り外した SFP+ トランシーバまたは QSFP+ トランシーバを再利用できる場合があります。

. コントローラドライブトレイとドライブトレイの間のすべてのケーブルを再接続します。
+
ドライブのケーブル接続構成が古いコントローラと同じ場合は、ケーブルに付けておいたラベルを使用して正しく再接続できます。



.次の手順
ドライブセキュリティ機能が有効になっている場合は、に進みますlink:upgrade-unlock-drives-task.html["ドライブのロックを解除する"]。それ以外の場合は、に進みますlink:complete-upgrade-controllers-task.html["コントローラのアップグレードを完了する"]。
