---
permalink: upgrade-controllers/overview-requirements-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3 
summary: E シリーズコントローラのアップグレードと交換に関する要件を確認します。 
---
= Eシリーズノアップグレードノコウリョジコウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラをアップグレードする前に、次の考慮事項を確認してください。


NOTE: 各Eシリーズコントローラでサポートされる構成の詳細については、を参照して https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e2800-models["E シリーズハードウェアの概要"]ください。



== ハードウェアとファームウェアの要件

* * デュプレックスおよびシンプレックスコントローラのアップグレード *
+
デュプレックスのコントローラドライブトレイの場合は、両方のコントローラを交換します。シンプレックスのコントローラドライブトレイの場合は、 1 台のコントローラを交換します。どちらの場合も、コントローラドライブトレイの電源をオフにする必要がありますそのため、交換が完了するまではストレージアレイのデータにアクセスできません。

* * トレイおよび棚 *
+
Eシリーズコントローラシェルフのストレージアレイは、通常、SANtricity System Managerユーザインターフェイスで管理します。

* * コントローラのバッテリ *
+
新しいコントローラはバッテリを取り付けていない状態で出荷されます。可能な場合は、古いコントローラからバッテリを取り外し、そのバッテリを新しいコントローラに取り付けてください。ただし、一部のコントローラのアップグレードでは、古いコントローラのバッテリが新しいコントローラに対応していません。その場合は、新しいコントローラと一緒にバッテリを注文して、これらのタスクを開始する前に準備しておく必要があります。

* * 同期ミラーリングと非同期ミラーリング *
+
ストレージアレイの同期ミラーリングでは、プライマリサイトとリモートサイトの間の接続として iSCSI または Fibre Channel のみがサポートされます。新しいコントローラのホストインターフェイスカード（ HIC ）構成に iSCSI 接続または Fibre Channel 接続が含まれていない場合、同期ミラーリングはサポートされません。

+
非同期ミラーリングでは、ローカルストレージアレイとリモートストレージアレイで異なるバージョンのファームウェアを実行していてもかまいません。サポートされるファームウェアの最小バージョンは、 SANtricity ファームウェアバージョン 7.84 です。




NOTE: E4000コントローラの場合、ミラーリングはファイバチャネル接続でのみサポートされます。

* * ストレージオブジェクトの制限 *
+
コントローラをミッドレンジモデルからエントリレベルモデル（5x00モデルから2x00モデルなど）に変更すると、ストレージ管理ソフトウェアでサポートされる一部のストレージオブジェクト（ボリュームなど）の数が古い構成よりも少なくなります。古い構成でストレージオブジェクトの制限を超えていないことを確認する必要があります。

+
詳細については、を参照してください http://hwu.netapp.com/home.aspx["Hardware Universe"^] 。

* *新しいモデルへのアップグレード*
+
コントローラを交換して新しいモデルにアップグレードする際は、現在のストレージアレイにインストールされているプレミアム機能が新しいモデルではサポートされない場合があることに注意してください。

+
Eシリーズコントローラをアップグレードするときは、ストレージアレイで使用しているプレミアム機能のうち、新しいコントローラでサポートされない機能はすべて無効にする必要があります。

* *アクセスボリュームを使用したインバンド管理*
+
** E4000では、Accessボリュームを使用したインバンド管理はサポートされていません。
+
E4000コントローラにアップグレードする前に、定義済みのすべてのホストおよびホストクラスタからアクセスボリュームのマッピングを解除します。



* * EF50およびEF80のミラー ケーブル配線*
+
EF80およびEF50システムは高速200GbE/100GbEの外部接続により、2つのコントローラ間のコントローラ間通信が可能になります。各コントローラには、スロット4に専用のインターフェース カードが搭載されています。このカードは2つのポートを備えており、システムには0.5mの200GbEケーブルが2本付属しています。

+
これらのケーブルを使用して、コントローラーのポートを以下のように接続してください：

+
** コントローラAのポートe4aからコントローラBのポートe4a
** コントローラAのポートe4bからコントローラBのポートe4b
+

NOTE: ケーブルの接続は、説明どおりに正確に行うことが非常に重要です。詳細については、 https://docs.netapp.com/us-en/e-series/install-hw-ef50-ef80/install-cable.html#step-1-cable-the-inter-controller-mirroring-connections["コントローラ間ミラーリング接続のケーブル接続 - EF50およびEF80"]を参照してください。



+
コントローラ間の通信には、他のホスト ポート（スロット1、スロット2、またはスロット3）を使用しないでください。これらはサポートされていません。EF50およびEF80アレイを正しく動作させるには、コントローラ間の適切なケーブル接続が不可欠です。





== アップグレード時の互換性

各ストレージアレイモデルでサポートされているアップグレードパスを確認します。

[role="tabbed-block"]
====
.EF50およびEF80コントローラのアップグレード互換性
--
[cols="h,d,d,d"]
|===
| アップグレードパス | バッテリ | 機能のサポート | SAS-3 シェルフ 


| EF300からEF50またはEF80  a| 
新しいバッテリーを注文します。
 a| 
* EF50とEF80は、デュプレックス構成のみをサポートしています。
* EF50およびEF80は64Gb Fibre Channelホスト インターフェイス カードをサポートします
* EF80 はデュアル 200Gbe NVMe over RoCE および NVMe over Infiniband ホスト インターフェイス カードをサポートします
* EF50およびEF80は、コントローラあたり最大24台のNVMeドライブをサポートします
* EF50およびEF80は、TLCおよびQLC NVMeドライブ構成をサポートしています
* EF50およびEF80はベースボード ホスト ポートをサポートしていません
* EF50およびEF80は、同期ミラーリングまたは非同期ミラーリングをサポートしていません。
* EF50およびEF80はRemote Storage Volumesをサポートしていません
* EF50およびEF80は、シンプロビジョニングボリュームをサポートしていません。
* EF50は最大2枚のhost interface cardをサポートし、EF80は最大3枚のhost interface cardをサポートします。



NOTE: EF300からEF50またはEF80にアップグレードする場合、SANtricity System Managerのユーザーインターフェイスを使用してホストプロトコルを設定できます。詳細については、 https://docs.netapp.com/us-en/e-series/maintenance-ef50-ef80/io-module-change-protocol.html["ホストI/Oモジュールのプロトコルを変更する - EF50およびEF80"]を参照してください。
 a| 
* EF50およびEF80はSAS拡張をサポートしていません。




| EF600からEF80へ  a| 
新しいバッテリーを注文します。
 a| 
* EF80はデュプレックス構成のみをサポートします
* EF80は64Gb Fibre Channelホスト インターフェイス カードをサポートします
* EF80 はデュアル 200Gbe NVMe over RoCE および NVMe over Infiniband ホスト インターフェイス カードをサポートします
* EF80はコントローラあたり最大24台のNVMeドライブをサポートします
* EF50およびEF80は、TLCおよびQLC NVMeドライブ構成をサポートしています
* EF80はベースボード ホスト ポートをサポートしていません
* EF80は同期ミラーリングまたは非同期ミラーリングをサポートしていません
* EF80はリモート ストレージ ボリュームをサポートしていません
* EF80はシンプロビジョニングボリュームをサポートしていません
* EF80は最大3枚のホスト インターフェイス カードをサポートします。
+

NOTE: EF600からEF80にアップグレードする場合、SANtricity System Managerのユーザーインターフェイスを使用してホストプロトコルを設定できます。詳細については、 https://docs.netapp.com/us-en/e-series//maintenance-ef50-ef80/io-module-change-protocol.html["ホストI/Oモジュールのプロトコルを変更する - EF50およびEF80"]を参照してください。


 a| 
* EF80はSAS拡張をサポートしていません。


|===
--
.E4000コントローラのアップグレード互換性
--
[cols="h,d,d,d"]
|===
| アップグレードパス | バッテリ | 機能のサポート | SAS-3 シェルフ 


| E2800からE4000へ  a| 
新しいバッテリーを注文します。
 a| 
* E4000はARVM iSCSIをサポートしない
* E4000のベースボードポートはiSCSIのみで、FCに変更することはできません。
* E4000でサポートできるドライブは300台のみ
* E4000でサポートできるボリュームは512個のみ
* E4000はSAS構成をサポートしていません。
* E4000はRemote Storage Volumesをサポートしない
* E4000では、Accessボリュームを使用したインバンド管理はサポートされていません。

 a| 
E4000コントローラではSAS-3シェルフを使用する必要があります。



| E5700からE4000へ  a| 
新しいバッテリーを注文します。
 a| 
* E4000はARVM iSCSIをサポートしない
* E4000のベースボードポートはiSCSIのみで、FCに変更することはできません。
* E4000でサポートできるドライブは300台のみ
+
** E5700は最大480本のドライブをサポート


* E4000でサポートできるボリュームは512個のみ
+
** E5700では最大2、048個のボリュームをサポート可能


* InfiniBandホストインターフェイスカードのサポートは利用できません
* E4000はSAS構成をサポートしていません。
* E4000はRemote Storage Volumesをサポートしない
* E4000では、Accessボリュームを使用したインバンド管理はサポートされていません。

 a| 
E4000コントローラではSAS-3シェルフを使用する必要があります。

|===
--
.EF600 / EF300コントローラのアップグレード時の互換性
--
[cols="h,d,d,d"]
|===
| アップグレードパス | バッテリ | 機能のサポート | SAS-3 シェルフ 


| 別のホストインターフェイスカードを使用したEF600からEF600への  a| 
古いバッテリを再利用します。
 a| 
* シンプロビジョニングボリュームはサポートされない
* 同期ミラーリングはサポートされない

| EF600コントローラでSAS-3シェルフを使用する必要があります。 


| EF300からEF600へ  a| 
古いバッテリを再利用します。
 a| 
* シンプロビジョニングボリュームはサポートされない
* 同期ミラーリングはサポートされない

 a| 
EF600コントローラでSAS-3シェルフを使用する必要があります。

|===
--
.レガシーコントローラのアップグレード時の互換性
--
[cols="h,d,d,d,d"]
|===
| アップグレードパス | バッテリ | ベンダーID | 機能のサポート | SAS-3 シェルフ 


| E2x00 から E2x00  a| 
古いバッテリを再利用します。
 a| 
追加の手順が必要です。
 a| 
E2700では従来のSnapshotはサポートされません。
 a| 
E2800 コントローラは、 SAS-2 シェルフには配置できません。



| E2x00 から E5x00  a| 
新しいバッテリーを注文します。
 a| 
E2600からE5500またはE5600にアップグレードする場合、またはE2700からE5400にアップグレードする場合は、追加の手順が必要です。
 a| 
* E5500 または E5600 では、従来の Snapshot はサポートされません。
* iSCSI HIC を搭載した E5500 または E5600 では、従来のリモートボリュームミラーリング（ RVM ）はサポートされません。
* iSCSI HIC を搭載した E5500 または E5600 では、 Data Assurance はサポートされません。
* E5700 コントローラは SAS-2 シェルフには配置できません。

 a| 
E5400、E5500、およびE5600コントローラはSAS-3シェルフには配置できません。



| E5x00 から E2x00  a| 
新しいバッテリーを注文します。
 a| 
E5500またはE5600からE2600にアップグレードする場合、またはE5400からE2700にアップグレードする場合は、追加の手順が必要です。
 a| 
E2700では従来のSnapshotはサポートされません。
 a| 
E5400、E5500、およびE5600コントローラはSAS-3シェルフには配置できません。



| E5x00 から E5x00  a| 
古いバッテリを再利用します。
 a| 
E5400からE5500またはE5600にアップグレードする場合は、追加の手順が必要です。
 a| 
* E5500 または E5600 では、従来の Snapshot はサポートされません。
* iSCSI HIC を搭載した E5400 または E5500 では、従来のリモートボリュームミラーリング（ RVM ）はサポートされません。
* iSCSI HIC を搭載した E5400 または E5500 では、 Data Assurance はサポートされません。
* E5700 コントローラは SAS-2 シェルフには配置できません。

 a| 
E5400、E5500、およびE5600コントローラはSAS-3シェルフには配置できません。



| EF5x0 から EF5x0 に変更します  a| 
古いバッテリを再利用します。
 a| 
EF540からEF550またはEF560にアップグレードする場合は、追加の手順が必要です。
 a| 
* EF550 / EF560 では、従来の Snapshot はサポートされません。
* iSCSI を搭載した EF550 / EF560 では、 Data Assurance はサポートされません。
* EF570 コントローラは、 SAS-3 シェルフには配置できません。

 a| 
EF540、EF550、およびEF560コントローラはSAS-3シェルフには配置できません。

|===
--
====


== SAS エンクロージャ

E5700 では、ヘッドのアップグレードにより、 DE5600 および DE6600 の SAS-2 エンクロージャがサポートされます。SAS-2 エンクロージャに E5700 コントローラが搭載されている場合、ベースホストポートのサポートは無効になります。

|===
| SAS-2 シェルフ | SAS-3 シェルフ 


 a| 
SAS-2 シェルフには次のモデルがあります。

* DE1600 、 DE5600 、および DE6600 ドライブトレイ
* E5400 、 E5500 、および E5600 コントローラドライブトレイ
* EF540 / EF550 / EF560 フラッシュアレイ
* E2600 および E2700 コントローラドライブトレイ

 a| 
SAS-3 シェルフには次のモデルがあります。

* E4000 コントローラシェルフ
* EF600コントローラシェルフ^1^
* EF300コントローラシェルフ^1^
* E2800 コントローラシェルフ
* E5700 コントローラシェルフ
* DE212C 、 DE224C 、および DE460C ドライブシェルフ


|===
注：

. EF600およびEF300コントローラでは、拡張としてSAS-3シェルフのみを使用できます。




== SAS-2 から SAS-3 への投資の保護

SAS-2 システムを新しい SAS-3 コントローラシェルフ（ E57XX / EF570 / E28XX ）の背後で使用するように再構成できます。


NOTE: この手順には Feature Product Variance Request （ FPVR ）が必要です。FPVR の申請については、営業チームにお問い合わせください。
