---
permalink: upgrade-controllers/overview-requirements-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade compatibility, upgrade SAS shelf, upgrade SAS shelves, upgrade SAS enclosures, SAS-2 to SAS-3 
summary: E シリーズコントローラのアップグレードと交換に関する要件を確認します。 
---
= アップグレード時の考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラをアップグレードする前に、次の考慮事項を確認してください。



== ハードウェアとファームウェアの要件

* * デュプレックスおよびシンプレックスコントローラのアップグレード *
+
デュプレックスのコントローラドライブトレイの場合は、両方のコントローラを交換します。シンプレックスのコントローラドライブトレイの場合は、 1 台のコントローラを交換します。どちらの場合も、コントローラドライブトレイの電源をオフにする必要がありますそのため、交換が完了するまではストレージアレイのデータにアクセスできません。

* * トレイおよび棚 *
+
E2800 または E5700 のコントローラシェルフを搭載したストレージアレイは、一般に SANtricity System Manager ユーザインターフェイスで管理されます。E2800 または E5700 のコントローラシェルフの管理には、 SANtricity Storage Manager インターフェイスも使用できます。この手順に記載されている他のコントローラドライブトレイは、いずれも SANtricity ストレージマネージャを使用します。

* * コントローラのバッテリ *
+
新しいコントローラはバッテリを取り付けていない状態で出荷されます。可能な場合は、古いコントローラからバッテリを取り外し、そのバッテリを新しいコントローラに取り付けてください。ただし、一部のコントローラのアップグレードでは、古いコントローラのバッテリが新しいコントローラに対応していません。その場合は、新しいコントローラと一緒にバッテリを注文して、これらのタスクを開始する前に準備しておく必要があります。

* * ベンダー ID *
+
一部のコントローラのアップグレードでは、 SCSI Inquiry で表示されるデータのベンダー ID が「 LSI 」から「 netapp 」に変わります。ベンダー ID が「 LSI 」から「 NetApp 」に変わると、 Windows 、 VMware 、 AIX の各オペレーティング・システムでデバイスを再利用するための追加の手順が必要になります。このアップグレード手順には、これらのオペレーティングシステムの手順が含まれています。

* * 同期ミラーリングと非同期ミラーリング *
+
ストレージアレイの同期ミラーリングでは、プライマリサイトとリモートサイトの間の接続として iSCSI または Fibre Channel のみがサポートされます。新しいコントローラのホストインターフェイスカード（ HIC ）構成に iSCSI 接続または Fibre Channel 接続が含まれていない場合、同期ミラーリングはサポートされません。

+
非同期ミラーリングでは、ローカルストレージアレイとリモートストレージアレイで異なるバージョンのファームウェアを実行していてもかまいません。サポートされるファームウェアの最小バージョンは、 SANtricity ファームウェアバージョン 7.84 です。

* * ストレージオブジェクトの制限 *
+
コントローラを 5x00 モデルから 2x00 モデルに変更した場合、新しいストレージアレイの構成では、ストレージ管理ソフトウェアでサポートされる一部のストレージオブジェクト（ボリュームなど）の数が古い構成よりも少なくなります。古い構成でストレージオブジェクトの制限を超えていないことを確認する必要があります。を参照してください http://hwu.netapp.com/home.aspx["Hardware Universe"^] を参照してください。





== 新しいモデルにアップグレードします

コントローラを交換して新しいモデルにアップグレードする際は、現在のストレージアレイにインストールされているプレミアム機能が新しいモデルではサポートされない場合があることに注意してください。たとえば、 E2700 コントローラでは、従来の Snapshot プレミアム機能はサポートされません。

E2600 コントローラを E2700 コントローラに交換する際、ストレージアレイで従来の Snapshot 機能を使用していた場合は、コントローラを交換する前に、その機能を無効にして、その機能に関連付けられているすべてのボリューム（ Snapshot とリポジトリ）を削除するか変換する必要があります。従来の Snapshot を更新された Snapshot 機能に変換できます。コントローラドライブトレイをアップグレードする前に、ストレージアレイで使用しているプレミアム機能に新しいコントローラでサポートされない機能が含まれている場合は、それらの機能を無効にしてください。



== アップグレード時の互換性

[role="lead"]
各ストレージアレイモデルでサポートされているアップグレードパスを確認します。



=== E2x00 から E2x00

* * バッテリー * ：古いバッテリーを再利用します。
* * ベンダー ID * ：追加の手順が必要です。
* * 機能のサポート * ： E2700 では、従来の Snapshot はサポートされません。
* * SAS-2 シェルフ * ： E2800 コントローラは SAS-2 シェルフには配置できません。




=== E2x00 から E5x00

* * バッテリー * ：新しいバッテリーを注文します。
* * ベンダー ID * ： E2600 から E5500 または E5600 にアップグレードする場合、または E2700 から E5400 にアップグレードする場合は、追加の手順が必要です。
* * 機能サポート * ：
+
** E5500 または E5600 では、従来の Snapshot はサポートされません。
** iSCSI HIC を搭載した E5500 または E5600 では、従来のリモートボリュームミラーリング（ RVM ）はサポートされません。
** iSCSI HIC を搭載した E5500 または E5600 では、 Data Assurance はサポートされません。
** E5700 コントローラは SAS-2 シェルフには配置できません。


* * SAS-3 シェルフ * ： E5400 、 E5500 、および E5600 コントローラは SAS-3 シェルフには配置できません。




=== E5x00 から E2x00

* * バッテリー * ：新しいバッテリーを注文します。
* * ベンダー ID * ： E5500 または E5600 から E2600 にアップグレードする場合、または E5400 から E2700 にアップグレードする場合は、追加の手順が必要です。
* * 機能のサポート * ： E2700 では、従来の Snapshot はサポートされません。
* * SAS-3 シェルフ * ： E5400 、 E5500 、および E5600 コントローラは SAS-3 シェルフには配置できません。




=== E5x00 から E5x00

* * バッテリー * ：古いバッテリーを再利用します。
* * ベンダー ID * ： E5400 から E5500 または E5600 にアップグレードする場合は、追加の手順が必要です。
* * 機能サポート * ：
+
** E5500 または E5600 では、従来の Snapshot はサポートされません。
** iSCSI HIC を搭載した E5400 または E5500 では、従来のリモートボリュームミラーリング（ RVM ）はサポートされません。
** iSCSI HIC を搭載した E5400 または E5500 では、 Data Assurance はサポートされません。
** E5700 コントローラは SAS-2 シェルフには配置できません。


* * SAS-3 シェルフ * ： E5400 、 E5500 、および E5600 コントローラは SAS-3 シェルフには配置できません。




=== EF5x0 から EF5x0 に変更します

* * バッテリー * ：古いバッテリーを再利用します。
* * ベンダー ID * ： EF540 から EF550 または EF560 にアップグレードする場合は、追加の手順が必要です。
* * 機能サポート * ：
+
** EF550 / EF560 では、従来の Snapshot はサポートされません。
** iSCSI を搭載した EF550 / EF560 では、 Data Assurance はサポートされません。
** EF570 コントローラは、 SAS-3 シェルフには配置できません。


* * SAS-3 シェルフ * ： EF540 、 EF550 、および EF560 コントローラは SAS-3 シェルフには配置できません。




=== SAS エンクロージャ

E5700 では、ヘッドのアップグレードにより、 DE5600 および DE6600 の SAS-2 エンクロージャがサポートされます。SAS-2 エンクロージャに E5700 コントローラが搭載されている場合、ベースホストポートのサポートは無効になります。

|===
| SAS-2 シェルフ | SAS-3 シェルフ 


 a| 
SAS-2 シェルフには次のモデルがあります。

* DE1600 、 DE5600 、および DE6600 ドライブトレイ
* E5400 、 E5500 、および E5600 コントローラドライブトレイ
* EF540 / EF550 / EF560 フラッシュアレイ
* E2600 および E2700 コントローラドライブトレイ

 a| 
SAS-3 シェルフには次のモデルがあります。

* E2800 コントローラシェルフ
* E5700 コントローラシェルフ
* DE212C 、 DE224C 、および DE460C ドライブシェルフ


|===


=== SAS-2 から SAS-3 への投資の保護

SAS-2 システムを新しい SAS-3 コントローラシェルフ（ E57XX / EF570 / E28XX ）の背後で使用するように再構成できます。


NOTE: この手順には Feature Product Variance Request （ FPVR ）が必要です。FPVR の申請については、営業チームにお問い合わせください。
