---
permalink: upgrade-controllers/prepare-upgrade-controllers-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller requirements, upgrade controller key management, prepare upgrade controller, upgrade controller preparation, preparing controller upgrade 
summary: ドライブセキュリティキーを保存し、サポートデータを収集し、コントローラをオフラインにして、コントローラをアップグレードする準備をします。 
---
= コントローラをアップグレードする準備をします
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラをアップグレードする準備として、ドライブセキュリティキーを保存し（使用している場合）、シリアル番号を記録し、サポートデータを収集し、特定の機能を無効にし、コントローラをオフラインにします。


NOTE: サポートデータの収集時は、ストレージアレイのパフォーマンスに一時的に影響が及ぶことがあります。

.手順
. 既存のストレージアレイのオペレーティングシステム（コントローラファームウェア）が現在のコントローラに対応する最新のバージョンに更新されていることを確認してください。SANtricity System Manager のメニューから、 Support [Upgrade Center] を選択して、ソフトウェアとファームウェアのインベントリを表示します。
+

NOTE: SANtricity OS バージョン 8.50 をサポートするコントローラにアップグレードする場合は、新しいコントローラを取り付けて電源をオンにしたあとに、最新バージョンの SANtricity OS と最新の NVSRAM をインストールする必要があります。このアップグレードを行わないと、ストレージアレイを自動ロードバランシング（ ALB ）の対象として設定できないことがあります。

. コントローラを交換する際にドライブセキュリティ機能も使用している場合は、次の表に示すセキュリティタイプ（内部または外部）とドライブの状態に応じた手順を実行します。
+

NOTE: ドライブセキュリティは、 Full Disk Encryption （ FDE ）ドライブまたは連邦情報処理標準（ FIPS ）ドライブを使用してセキュリティを強化するストレージアレイの機能です。これらのドライブにドライブセキュリティ機能を使用すると、データにアクセスするためのセキュリティキーが必要になります。

+
|===
| セキュリティタイプとコンテキスト | 手順 


 a| 
内部キー管理、 1 つ以上のドライブがロックされています
 a| 
.. 内部セキュリティキーファイルを管理クライアント（ System Manager へのアクセスに使用するブラウザを備えたシステム）の既知の場所にエクスポートします。「 export storageArray securityKey 」 CLI コマンドを使用します。セキュリティキーに関連付けられているパスフレーズを入力し、コマンドの保存場所を指定する必要があります。このコマンドの使用方法については、 _ コマンドラインリファレンス _ を参照してください。
.. 内部セキュリティキーに関連付けられているパスフレーズを確認します。




 a| 
外部キー管理、すべてのドライブがロックされている、コントローラの交換時に一時的に内部キー管理に切り替えることができる（推奨）
 a| 
次の手順を順番に実行します。

.. 外部 KMS のサーバアドレスとポート番号を記録します。System Manager で、メニューの [ 設定 ] 、 [ システム ] 、 [ セキュリティキー管理 ] 、 [ キー管理サーバ設定の表示 / 編集 ] の順に選択します。
.. コントローラの交換後にストレージアレイとキー管理サーバが相互に認証できるように、クライアント証明書とサーバ証明書がローカルホストに保存されていることを確認します。証明書を保存するには、 'ave storageArray keyManagementCertificate' CLI コマンドを使用します。コマンドは必ず 2 回実行してください。 1 回は「 certificateType 」パラメータを「 client 」に設定し、もう 1 回はパラメータを「 server 」に設定して実行してください。このコマンドの使用方法については、 _ コマンドラインリファレンス _ を参照してください。
.. 「不可能な storageArray externalKeyManagement 」 CLI コマンドを実行して、内部キー管理に切り替えます。
.. 内部セキュリティキーファイルを管理クライアント（ System Manager へのアクセスに使用するブラウザを備えたシステム）の既知の場所にエクスポートします。「 export storageArray securityKey 」 CLI コマンドを使用します。セキュリティキーに関連付けられているパスフレーズを入力し、コマンドの保存場所を指定する必要があります。このコマンドの使用方法については、 _ コマンドラインリファレンス _ を参照してください。
.. 内部セキュリティキーに関連付けられているパスフレーズを確認します。




 a| 
外部キー管理、すべてのドライブがロックされている、コントローラの交換時に一時的に内部キー管理に切り替えることはできない
 a| 
次の手順を順番に実行します。

.. 外部 KMS のサーバアドレスとポート番号を記録します。System Manager で、メニューの [ 設定 ] 、 [ システム ] 、 [ セキュリティキー管理 ] 、 [ キー管理サーバ設定の表示 / 編集 ] の順に選択します。
.. コントローラの交換後にストレージアレイとキー管理サーバが相互に認証できるように、クライアント証明書とサーバ証明書がローカルホストに保存されていることを確認します。証明書を保存するには、 'ave storageArray keyManagementCertificate' CLI コマンドを使用します。コマンドは必ず 2 回実行してください。 1 回は「 certificateType 」パラメータを「 client 」に設定し、もう 1 回はパラメータを「 server 」に設定して実行してください。このコマンドの使用方法については、 _ コマンドラインリファレンス _ を参照してください。




 a| 
外部キー管理、一部のドライブがロックされています
 a| 
追加の手順は必要ありません。

|===



NOTE: クライアント証明書とサーバ証明書を取得するには、ストレージアレイが最適な状態である必要があります。証明書を取得できない場合は、新しい CSR を作成して署名し、 EKMS からサーバ証明書をダウンロードする必要があります。

. ストレージアレイのシリアル番号をメモします。
+
.. System Manager で、次のメニューを選択します。 Support [Support Center] > Support Resources タブ ] 。
.. 下にスクロールして「 Launch detailed storage array information 」 * と進み、「 * Storage Array Profile 」を選択します。
+
画面にレポートが表示されます。

.. ストレージアレイプロファイルでシャーシのシリアル番号を確認するには、「 * 検索 * 」テキストボックスに「 * シリアル番号 * 」と入力し、「 * 検索 * 」をクリックします。
+
一致するすべてのキーワードが強調表示されます。すべての結果を一度に 1 つずつスクロールするには、 * 検索 * をクリックします。

.. 「シャーシのシリアル番号」を記録します。
+
このシリアル番号は、の手順を実行する際に必要になります link:complete-upgrade-controllers-task.html["コントローラのアップグレードを完了する"]。



. GUI または CLI のいずれかを使用して、ストレージアレイに関するサポートデータを収集します。
+
** Storage Manager の System Manager または Array Management Window で、ストレージアレイのサポートバンドルを収集して保存します。
+
*** System Manager で、次のメニューを選択します。 Support [Support Center] > [Diagnostics （診断） ] タブ。次に、 [ サポートデータの収集 ] を選択し、 [ * 収集 ] をクリックします。
*** Array Management Window ツールバーから、次のメニューを選択します。 Monitor [Health] （ヘルス） > Collect Support Data Manually （サポートデータを手動で収集）。次に、名前を入力し、サポートバンドルを保存するシステム上の場所を指定します。
+
ブラウザの Downloads フォルダに、「 upport-data.7z 」という名前でファイルが保存されます。

+
シェルフにドロワーが搭載されている場合、そのシェルフの診断データは「 tray -component-state-capture.7z 」という別の圧縮ファイルにアーカイブされます。



** ストレージアレイに関する包括的なサポートデータを収集するには、 CLI を使用して「 save storageArray supportData 」コマンドを実行します。


. ストレージアレイと接続されているすべてのホストの間で I/O 処理が発生しないようにします。
+
.. ストレージからホストにマッピングされた LUN に関連するすべてのプロセスを停止します。
.. ストレージからホストにマッピングされた LUN にアプリケーションがデータを書き込んでいないことを確認します。
.. アレイのボリュームに関連付けられているファイルシステムをすべてアンマウントします。
+

NOTE: ホスト I/O 処理を停止する具体的な手順はホストオペレーティングシステムや構成によって異なり、ここでは説明していません。環境内でホスト I/O 処理を停止する方法がわからない場合は、ホストをシャットダウンすることを検討してください。

+

CAUTION: * データ損失の可能性 * - I/O 処理の実行中にこの手順を続行すると、データが失われる可能性があります。



. ストレージアレイでミラー関係が確立されている場合は、セカンダリストレージアレイのすべてのホスト I/O 処理を停止します。
. 非同期ミラーリングまたは同期ミラーリングを使用している場合は、 System Manager または Array Management Window を使用して、ミラーペアの削除とミラーリング関係の非アクティブ化を行います。
. シンボリュームとしてホストに報告されるシンプロビジョニングボリュームがあり、古いアレイで UNMAP 機能をサポートするファームウェア（ 8.25 以降のファームウェア）を実行している場合は、すべてのシンボリュームでライトバックキャッシュを無効にします。
+
.. System Manager で、メニューから「 Storage [Volumes] 」を選択します。
.. 任意のボリュームを選択し、メニューを選択します。 More [ キャッシュ設定の変更 ] 。
+
[ キャッシュ設定の変更 ] ダイアログボックスが表示されます。このダイアログボックスには、ストレージアレイ上のすべてのボリュームが表示されます。

.. [*Basic*] タブを選択し、リード・キャッシュとライト・キャッシュの設定を変更します。
.. [ 保存（ Save ） ] をクリックします。
.. キャッシュメモリ内のデータがディスクにフラッシュされるまで 5 分待ちます。


. コントローラで Security Assertion Markup Language （ SAML ）が有効になっている場合は、テクニカルサポートに連絡して SAML 認証を無効にします。
+

NOTE: SAML を有効にした場合、 SANtricity System Manager インターフェイスで無効にすることはできません。SAML の設定を無効にする場合は、テクニカルサポートにお問い合わせください。

. 実行中のすべての処理が完了するまで待ってから、次の手順に進みます。
+
.. System Manager の * Home * ページで、 * View Operations in Progress * を選択します。
.. 続行する前に、 [ 操作中 ] ウィンドウに表示されているすべての操作が完了していることを確認してください。


. コントローラドライブトレイの電源をオフにします
+
コントローラドライブトレイのすべての LED が消灯するまで待ちます。

. コントローラドライブトレイに接続されている各ドライブトレイの電源をオフにします
+
すべてのドライブがスピンダウンするまで 2 分待ちます。



に進みます link:remove-controllers-task.html["コントローラを取り外します"]。
