---
permalink: upgrade-controllers/reconfigure-sas-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, reconfigure SAS-2, SAS-2, SAS-3, convert controller shelf, convert drive shelf, 
summary: 承認済みの SAS-2 アレイ（ E2700 、 E550/EF5500 、 E5600 / EF560 ）のコントローラシェルフをドライブシェルフに変換し、そのシェルフと承認済みの SAS-2 ドライブシェルフ（ DE1600 、 DE5600 、 DE6600 ）を新しい認定済みの SAS-3 アレイ（ E2800 、 E5700 / EF570 、 E5700 ）と認定済みの SAS-3 ドライブシェルフ（ DE212C 、 DE224C 、 DE460C ）の背後に配置できます。 データ保持なし： 
---
= 新しい SAS-3 コントローラシェルフの背後での SAS-2 システムの再構成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必要に応じて、新しい SAS-3 コントローラシェルフの背後で使用するように SAS-2 システムを再構成できます。

認定を受けた SAS-2 アレイには、 E2700 、 E550/EF5500 、 E5600 / EF560 があります。承認済みの SAS-2 ドライブシェルフには DE1600 、 DE5600 、および DE6600 があります。承認されている SAS-3 アレイには E2800 および E5700 / EF570 があります。承認済みの SAS-3 ドライブシェルフには DE212C 、 DE224C 、および DE460C があります。

この手順では、承認済みの SAS-2 アレイのコントローラシェルフをドライブシェルフに変換し、そのシェルフをデータ保持がない新しい承認済みの SAS-3 アレイとドライブシェルフの背後に配置します。

この 手順 環境 IOM12 および IOM12B ドライブシェルフを使用します。


NOTE: この手順 は、シェルフの IOM のホットスワップや交換に使用されます。つまり、 IOM12 モジュールを別の IOM12 モジュールに交換するか、 IOM12B モジュールを別の IOM12B モジュールに交換しなければなりません。（シェルフに IOM12 モジュールを 2 台搭載することも、 IOM12B モジュールを 2 つ使用することもできます）

この手順は複雑であるため、次のものが必要です。

* Feature Product Variance Request （ FPVR ）が必要です。FPVR の申請については、ネットアッププロフェッショナルサービスにお問い合わせください。
+

NOTE: FPVR を取得せずに手順を試行すると、ドライブ障害が発生し、コントローラがロックダウンする可能性があります。

* データをバックアップできる場合は、ネットアッププロフェッショナルサービスの支援なしでこの手順を実行できます。
* データをバックアップできない場合は、ネットアッププロフェッショナルサービスにお問い合わせ手順ください。
* 両方のアレイで手順の準備が完了していることを確認します。
+
** * 既存のアレイ * ： SANtricity OS 8.25 以降を搭載した既存のアレイの電源をオンにしておきます。
** * 新しいアレイ * ：新しいアレイを開封し、電源はオフにしておきます。


* ドライブシェルフに変換する SAS-2 コントローラシェルフのシリアル番号をメモします。




== 手順 1 ：コントローラの電源をオフにする（データ保持なし）

コントローラの電源をオフにする前に、すべての処理をシャットダウンする必要があります。

.手順
. 既存の SAS-2 アレイにまだアクセス可能な場合は、すべてのボリュームグループを削除し、両方のコントローラの電源をオフにして、すべてのケーブルを取り外します。
. ドライブシェルフに変換する SAS-2 コントローラシェルフのシリアル番号をメモします。
. 既存のアレイでドライブセキュリティを使用している場合は、セキュリティキーを利用できることを確認してください。




== 手順 2 ：コントローラを取り付ける（データ保持なし）

シャットダウンが完了したら、アレイのコントローラを交換できます。

.手順
. IOM または ESM を搭載した既存のアレイの両方のコントローラを交換します。
. 可能であれば、既存のアレイから取り外したホストケーブルとネットワークケーブルを新しいアレイのコントローラに接続します。
+

NOTE: 新しいアレイのホスト接続によっては、別のケーブルが必要になる場合があります。

. 新しいアレイのコントローラ背後でドライブシェルフをケーブル接続します。
+
既存のコントローラドライブトレイとそれに接続されたドライブトレイをドライブシェルフとして新しいアレイのコントローラにケーブル接続できるようになります。

+

NOTE: SAS-2 から SAS-3 への接続には、 SAS HD から Mini-SAS へのケーブルが必要です。特定のコントローラおよび拡張シェルフ構成の詳細なケーブル接続情報については、を参照してください link:../install-hw-cabling/index.html["ケーブル配線"] または https://library.netapp.com/ecm/ecm_download_file/ECMLP2588749["『 E-Series Hardware Cabling Guide 』を参照してください"^]。





== 手順 3 ：コントローラの電源をオンにする（データ保持なし）

インストールが完了したら、コントローラの電源をオンにし、構成の変更をネットアップテクニカルサポートに送信します。

.手順
. 新しいアレイとそれに接続されたドライブシェルフの電源をオンにします。
. をインストールして、管理ポートと IP アドレスを設定します https://mysupport.netapp.com/tools/info/ECMLP2563821I.html["SANtricity クイックコネクト"^] ユーティリティ。
. 既存のアレイでドライブセキュリティを使用していた場合は、セキュリティキーをインポートします。
. この手順を実行する前に既存のアレイからボリュームグループを削除できなかった場合は、すべての外部ドライブをネイティブとして扱うように設定する必要があります。ドライブをネイティブに設定する方法の詳細については、 SANtricity オンラインヘルプを参照してください。
. 構成の変更をネットアップテクニカルサポートに送信します。
+
.. 手順 2 でメモしておいた古いコントローラドライブトレイのシリアル番号を用意します。
.. にログインします http://mysupport.netapp.com/eservice/assistant["ネットアップサポートサイト"^]。
.. [ フィードバックカテゴリ * ] のドロップダウンリストから、 [ インストール済み製品 ] > [ 分解リクエスト * ] を選択します。
.. 「 * ケースを作成 * 」を選択します。「 * Comments * 」テキストボックスに次のテキストを入力します。シリアル番号はコントローラドライブトレイのシリアル番号に置き換えてください。
+
「資格がシステム内の別のシリアル番号に移動されたため、このシリアル番号を無効にしてください。これを SN notes で参照してください

.. [ 送信 ] を選択します。




SAS-2 から SAS-3 への構成の変更がネットアップテクニカルサポートに送信されます。
