---
permalink: upgrade-controllers/remount-volumes-lsi-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, remount volume, upgrade LSI, vendor ID 
summary: コントローラのアップグレードでベンダー ID が LSI から NETAPP に変わった場合は、ボリュームを再マウントします。 
---
= ベンダーが LSI から NETAPP に変わった場合は、ボリュームを再マウントします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラのアップグレードでベンダー ID が LSI から NETAPP に変わった場合は、ホストタイプに応じた適切な手順を実行します。

* <<AIX ホストでボリュームを再マウントします>>
* <<VMware ホストでボリュームを再マウントします>>
* <<Windows ホストでボリュームを再マウントします>>




== AIX ホストでボリュームを再マウントします

コントローラの交換後、ストレージアレイの新しいボリュームに加えて、元のボリュームも使用停止のボリュームとして表示されることがあります。

.ステップ
失敗したボリュームが表示される場合は 'cfgmgr' コマンドを実行します



== VMware ホストでボリュームを再マウントします

コントローラを交換したあと、次のような状況になることがあります。

* ストレージアレイのボリュームの新しいパスに加えて、元のパスも稼働していないパスとして表示される。
* ストレージアレイのボリュームのリストで、ベンダー ID が LSI のままになる。これは、ボリュームが最初に LSI のルールで要求されたために、ボリュームがオンラインに戻ったあとも同じ LSI のルールが使用される場合に発生することがあります。
* LSI から NETAPP への変更が表示名に反映されない。これは、初回検出後に表示名が無償テスト版になったために発生することがあります。この場合は、表示名を手動で変更できます。


.手順
. 各ホストで再スキャンを実行します。
. このサブシステムに対するすべてのホスト I/O 処理を停止します。
. ネットアップのルールでボリュームを再利用します。
+
.. esxcli storage core device list コマンドを実行します。コマンドの出力を確認し、名前が「 aa.xxxx 」の形式のボリュームを特定します。
.. コマンド「 esxcli storage core claiming reclaim -d naa.xxxxx 」を実行して、ベンダー ID を LSI から NETAPP に変更します。






== Windows ホストでボリュームを再マウントします

コントローラを交換したら、 Windows ホストでボリュームを再マウントして、接続されたホストがアップグレード後のストレージアレイにあるボリュームで I/O 処理を実行できるようにする必要があります。

.手順
. * デバイスマネージャー * で、 * 非表示デバイスを表示 * を選択します。
. Device Manager * に表示された NetApp SCSI ディスク・デバイスごとに、エントリーを右クリックし、 * Uninstall * を選択します。
+
Windows のダイアログボックスでホストのリブートが必要であることを示すメッセージが表示された場合は、ハードウェアのスキャンとリブートに進む前に、すべてのボリュームのアンインストールを完了します。

. [ * デバイスマネージャ * ] を右クリックし、 [ * ハードウェア変更のスキャン * ] を選択します。
. ホストをリブートします。

