---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: E2800 および E5700 のコントローラをアップグレードする際にドライブセキュリティ機能が有効になっている場合は、ドライブのロックを手動で解除する必要があります。 
---
= Eシリーズドライブのロック解除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
これらのコントローラのドライブセキュリティ機能により、ドライブが部分的、外部、または内部でロックダウンされます。ドライブセキュリティ機能が有効になっている場合は、それらのドライブのロックを手動で解除する必要があります。

次の場合は、該当する手順に従います。

* <<内部キー管理>>
* <<外部キー管理>>




== 内部キー管理

すべてのドライブがロックされている場合の内部キー管理の手順は、次のとおりです。

.このタスクについて
新しくスワップしたコントローラは、デジタル表示ディスプレイに*L5*というコードでロックダウンされます。このロックダウンは、ドライブが自動コード同期（ACS）を実行できない場合に発生します。セキュリティキーがインポートされると、ACSは新しいコントローラを再開して更新します。


NOTE: 管理ポート 1 を使用していない場合は、他のデフォルト IP アドレスを使用してみてください。 +Ctrl A ポート 1 ： 169.254.128.101 + Ctrl A ポート 2 ： 169.254.128.102 + Ctrl B ポート 1 ： 169.254.128.101 + Ctrl B ポート 2 ： 169.254.128.102

.手順
. ストレージアレイとSANtricity クライアントのラップトップまたはPCを、直接、プライベートなイーサネット接続で接続します。これを行うには：
+
.. RJ45イーサネットケーブルを使用して、ラップトップをコントローラAの管理ポート1に接続します
.. 接続を完了するには、ラップトップをコントローラAと同じサブネット内のIPアドレスに割り当てなければならない場合があります。コントローラAのロックダウン時には、コントローラAのデフォルトの管理アドレスは169.254.128.101です。そのため、ラップトップを「169.254.128.201」などのサブネットに割り当てることができます。


. IPアドレス169.254.128.101、ユーザ名* admin *、パスワードを空白にして、から保存したセキュリティキーを使用して、CLIコマンドを使用して内部キーをインポートし `import storageArray securityKey file`link:prepare-upgrade-controllers-task.html["コントローラをアップグレードする準備をします"]ます。このコマンドの使用方法については、を参照して https://docs.netapp.com/us-en/e-series-cli/index.html["コマンドラインインターフェイスリファレンス"]ください。
+
*例：* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
また、次の呼び出しを使用して、REST APIから内部キーをインポートすることもできます。 `/storage-systems/{system-id}/security-key/import`



コントローラはドライブから自動ノード同期プロセスを続行し、リブートします。リブート後は、元の IP 構成を使用してコントローラにアクセスできるようになります。



== 外部キー管理

すべてのドライブがロックされている場合の外部キー管理の手順は、次のとおりです。

.このタスクについて
新しくスワップしたコントローラは、デジタル表示ディスプレイに*L5*というコードでロックダウンされます。このロックダウンは、ドライブが自動コード同期（ACS）を実行できない場合に発生します。セキュリティキーがインポートされると、ACSは新しいコントローラを再開して更新します。

.手順
. ストレージアレイとSANtricity クライアントのラップトップまたはPCを、直接、プライベートなイーサネット接続で接続します。これを行うには：
+
.. RJ45イーサネットケーブルを使用して、ラップトップをコントローラAの管理ポート1に接続します
.. 接続を完了するには、ラップトップをコントローラAと同じサブネット内のIPアドレスに割り当てなければならない場合があります。コントローラAのロックダウン時には、コントローラAのデフォルトの管理アドレスは169.254.128.101です。そのため、ラップトップを「169.254.128.201」などのサブネットに割り当てることができます。


. で保存したセキュリティキーを使用してlink:prepare-upgrade-controllers-task.html["コントローラをアップグレードする準備をします"]、ユーザ名* admin *、パスワードは空白のまま、IPアドレス169.254.128.101に外部キーをインポートします。
+
*例：* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
また、次の呼び出しを使用してREST APIから外部キーをインポートすることもできます。 `/storage-systems/{system-id}/security-key/import`

+
コントローラはドライブから自動ノード同期プロセスを続行し、リブートします。リブート後は、元の IP 構成を使用してコントローラにアクセスできるようになります。

. （オプション）必要に応じて、次の手順を実行してドライブのキーを変更できます。
+
*例：* `SMcli <original_controller _ip> -u admin -p "<original_array_password>" -c "create storageArray securityKey" passPhrase=\"passPhraseString\" file=\"filename\";”`


