---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: E2800 および E5700 のコントローラをアップグレードする際にドライブセキュリティ機能が有効になっている場合は、ドライブのロックを手動で解除する必要があります。 
---
= ドライブのロックを解除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E2800 および E5700 のコントローラをアップグレードする場合、それらのコントローラのドライブセキュリティ機能により、ドライブが部分的、外部、または内部でロックされます。ドライブセキュリティ機能が有効になっている場合は、それらのドライブのロックを手動で解除する必要があります。

次の場合は、該当する手順に従います。

* <<Internal key management>>
* <<External key management>>




== 内部キー管理

すべてのドライブがロックされている場合の内部キー管理の手順は、次のとおりです。

新しくスワップしたコントローラは、デジタル表示ディスプレイにコード L5 が表示されてロックダウンされます。このロックダウンは、ストレージアレイのドライブで自動ノード同期（ ACS ）を実行できない場合に発生します。ACS は、セキュリティキーがインポートされると、新しいコントローラを再開して更新します。


NOTE: 管理ポート 1 を使用していない場合は、他のデフォルト IP アドレスを使用してみてください。 +Ctrl A ポート 1 ： 192.168.128.101 + Ctrl A ポート 2 ： 192.168.128.102 + Ctrl B ポート 1 ： 192.168.129.101 + Ctrl B ポート 2 ： 192.168.129.102

.手順
. 手順 2 でアレイコントローラに直接接続するために使用するラップトップまたは PC に SANtricity クライアントをインストールします。
. RJ45 イーサネットケーブルを使用して、ラップトップまたは PC をコントローラ A の管理ポート 1 に直接接続します。ラップトップの IP アドレスを同じサブネットに設定しなければならない場合もあります。
. IP アドレス 192.168.128.101 （ username * admin * ）とパスワードブランクを使用して、「 import storageArray securityKey file 」 CLI コマンドを使用して内部キーをインポートし、からセキュリティキーを保存します link:prepare-upgrade-controllers-task.html["コントローラをアップグレードする準備をします"]。このコマンドの使用方法については、 _ コマンドラインリファレンス _ を参照してください。
+
* 例： * `S MCLI 192.168.128.101 -u admin -c "import storageArray securityKey file=\"Directory&filename\" passphrase="passasraseString\";"`



コントローラはドライブから自動ノード同期プロセスを続行し、リブートします。リブート後は、元の IP 構成を使用してコントローラにアクセスできるようになります。



== 外部キー管理

すべてのドライブがロックされている場合の外部キー管理の手順は、次のとおりです。

新しくスワップしたコントローラは、デジタル表示ディスプレイにコード L5 が表示されてロックダウンされます。このロックダウンは、ストレージアレイのドライブで自動ノード同期（ ACS ）を実行できない場合に発生します。ACS は、セキュリティキーがインポートされると、新しいコントローラを再開して更新します。


NOTE: クライアント証明書とサーバ証明書を取得するには、ストレージアレイが最適な状態である必要があります。証明書を取得できない場合は、新しい CSR を作成して署名し、 EKMS からサーバ証明書をダウンロードする必要があります。

.手順
. 手順 2 でアレイコントローラに直接接続するために使用するラップトップまたは PC に SANtricity クライアントをインストールします。
. RJ45 イーサネットケーブルを使用して、ラップトップまたは PC をコントローラ A の管理ポート 1 に直接接続します。ラップトップの IP アドレスを同じサブネットに設定しなければならない場合もあります。
. デフォルトの IP アドレス 192.168.128.101 でユーザ名 * admin * とパスワードブランクを使用して 'et storageArray externalKeyManagement' CLI コマンドを使用して外部キー管理サーバを設定し 'ServerAddress' と 'erverPort' をから保存します link:prepare-upgrade-controllers-task.html["コントローラをアップグレードする準備をします"]。このコマンドの使用方法については、 _ コマンドラインリファレンス _ を参照してください。
+
* 例： * `S MCLI 192.168.128.101 -u admin -c "set storageArray externalKeyManagement serverAddress=<ServerIPAddress>ServerPort=<ServerPort>;"`

. デフォルトの IP アドレス 192.168.128.101 でユーザ名 *admin* とパスワードを空白にして、 'torageArray keyManagementCertificate' CLI コマンドを使用して証明書をダウンロードします。これは、クライアント証明書用に 1 回、サーバ証明書用に 2 回目です。このコマンドの使用方法については、 _ コマンドラインリファレンス _ を参照してください。
+
* 例 A ： * `S MCLI 192.168.128.101 -u admin -c "download storageArray keyManagementCertificate certificateType=client file=\"Directory&filename\";"

+
* 例 B ： * `S MCLI 192.168.128.101 -u admin -c "download storageArray keyManagementCertificate certificateType=server file=\"Directory&filename\";"

. から保存されたセキュリティキーを使用します link:prepare-upgrade-controllers-task.html["コントローラをアップグレードする準備をします"]を使用して、外部キーを IP アドレス 192.168.128.101 にインポートし、ユーザ名 * admin * とパスワードは空白のままにします。このコマンドの使用方法については、 _ コマンドラインリファレンス _ を参照してください。
+
* 例： * `S MCLI 192.168.128.101 -u admin -c "import storageArray securityKey file=\"Directory&filename\" passphrase="passasraseString\";"`



コントローラはドライブから自動ノード同期プロセスを続行し、リブートします。リブート後は、元の IP 構成を使用してコントローラにアクセスできるようになります。
