---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: E2800 および E5700 のコントローラをアップグレードする際にドライブセキュリティ機能が有効になっている場合は、ドライブのロックを手動で解除する必要があります。 
---
= ドライブのロックを解除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
E2800およびE5700のコントローラをアップグレードする場合、それらのコントローラのドライブセキュリティ機能によって、ドライブが部分的、外部、または内部的にロックされます。ドライブセキュリティ機能が有効になっている場合は、それらのドライブのロックを手動で解除する必要があります。

次の場合は、該当する手順に従います。

*  key management
*  key management




== 内部キー管理

すべてのドライブがロックされている場合の内部キー管理の手順は、次のとおりです。

新しくスワップしたコントローラは、デジタル表示ディスプレイに*L5*というコードでロックダウンされます。このロックダウンは、ドライブが自動コード同期（ACS）を実行できない場合に発生します。セキュリティキーがインポートされると、ACSは新しいコントローラを再開して更新します。


NOTE: 管理ポート 1 を使用していない場合は、他のデフォルト IP アドレスを使用してみてください。 +Ctrl A ポート 1 ： 192.168.128.101 + Ctrl A ポート 2 ： 192.168.128.102 + Ctrl B ポート 1 ： 192.168.129.101 + Ctrl B ポート 2 ： 192.168.129.102

.手順
. ストレージアレイとSANtricity クライアントのラップトップまたはPCを、直接、プライベートなイーサネット接続で接続します。これを行うには：
+
.. RJ45イーサネットケーブルを使用して、ラップトップをコントローラAの管理ポート1に接続します
.. 接続を完了するには、ラップトップをコントローラAと同じサブネット内のIPアドレスに割り当てる必要がありますコントローラのロックダウン中、コントローラAはデフォルトで192.168.128.101の管理アドレスになります。そのため、ラップトップを「192.168.128.201」などのサブネットに割り当てることができます。


. IPアドレス192.168.128.101（username * admin *）とパスワードブランクを使用して、を使用して内部キーをインポートします `import storageArray securityKey file` からセキュリティキーを保存したCLIコマンド link:prepare-upgrade-controllers-task.html["コントローラをアップグレードする準備をします"]。このコマンドの使用方法については、を参照してください https://docs.netapp.com/us-en/e-series-cli/index.html["コマンドラインインターフェイスリファレンス"]。
+
* 例： * `S MCLI 192.168.128.101 -u admin -c "import storageArray securityKey file=\"Directory&filename\" passphrase="passasraseString\";"`

+
また、次の呼び出しを使用して、REST APIから内部キーをインポートすることもできます。 `/storage-systems/{system-id}/security-key/import`



コントローラはドライブから自動ノード同期プロセスを続行し、リブートします。リブート後は、元の IP 構成を使用してコントローラにアクセスできるようになります。



== 外部キー管理

すべてのドライブがロックされている場合の外部キー管理の手順は、次のとおりです。

新しくスワップしたコントローラは、デジタル表示ディスプレイに*L5*というコードでロックダウンされます。このロックダウンは、ドライブが自動コード同期（ACS）を実行できない場合に発生します。セキュリティキーがインポートされると、ACSは新しいコントローラを再開して更新します。


NOTE: クライアント証明書とサーバ証明書を取得するには、ストレージアレイが最適な状態である必要があります。証明書を取得できない場合は、新しい証明書署名要求（CSR）を作成し、外部キー管理サーバからサーバ証明書をインポートする必要があります。

.手順
. ストレージアレイとSANtricity クライアントのラップトップまたはPCを、直接、プライベートなイーサネット接続で接続します。これを行うには：
+
.. RJ45イーサネットケーブルを使用して、ラップトップをコントローラAの管理ポート1に接続します
.. 接続を完了するには、ラップトップをコントローラAと同じサブネット内のIPアドレスに割り当てる必要がありますコントローラのロックダウン中、コントローラAはデフォルトで192.168.128.101の管理アドレスになります。そのため、ラップトップを「192.168.128.201」などのサブネットに割り当てることができます。


. デフォルトのIPアドレス192.168.128.101、ユーザ名* admin *、パスワードを空白にして、を使用して外部キー管理サーバをセットアップします `set storageArray externalKeyManagement` CLIコマンドを実行し、を指定します `serverAddress` および `serverPort` 保存元 link:prepare-upgrade-controllers-task.html["コントローラをアップグレードする準備をします"]。このコマンドの使用方法については、を参照してください https://docs.netapp.com/us-en/e-series-cli/index.html["コマンドラインインターフェイスリファレンス"]。
+
* 例： * `S MCLI 192.168.128.101 -u admin -c "set storageArray externalKeyManagement serverAddress=<ServerIPAddress>ServerPort=<ServerPort>;"`

+
また、次の呼び出しによって、REST APIを使用して外部キー管理サーバをセットアップすることもできます。 `/storage-systems/{system-id}/external-key-server`

. デフォルトのIPアドレス192.168.128.101（ユーザ名*admin*およびパスワードブランク）を使用し、を使用して証明書をインポートします `storageArray keyManagementCertificate` CLIコマンド：クライアント証明書用に1回、サーバ証明書用に2回
+
* 例 A ： * `S MCLI 192.168.128.101 -u admin -c "download storageArray keyManagementCertificate certificateType=client file=\"Directory&filename\";"

+
* 例 B ： * `S MCLI 192.168.128.101 -u admin -c "download storageArray keyManagementCertificate certificateType=server file=\"Directory&filename\";"

+
また、次の呼び出しを使用して、REST API経由でキーサーバ証明書をインポートすることもできます。 `/storage-systems/{system-id}/external-key-server/certificate`

. から保存されたセキュリティキーを使用します link:prepare-upgrade-controllers-task.html["コントローラをアップグレードする準備をします"]を使用して、外部キーを IP アドレス 192.168.128.101 にインポートし、ユーザ名 * admin * とパスワードは空白のままにします。
+
* 例： * `S MCLI 192.168.128.101 -u admin -c "import storageArray securityKey file=\"Directory&filename\" passphrase="passasraseString\";"`

+
また、次の呼び出しを使用してREST APIから外部キーをインポートすることもできます。 `/storage-systems/{system-id}/security-key/import`



コントローラはドライブから自動ノード同期プロセスを続行し、リブートします。リブート後は、元の IP 構成を使用してコントローラにアクセスできるようになります。
