---
permalink: remote-storage-volumes/import-remote-storage-task.html 
sidebar: sidebar 
keywords: import Remote Storage Volumes, RTV import, import remote volumes, remote storage E-Series 
summary: リモートストレージデバイスのインポートは、 SANtricity システムマネージャのリモートストレージのインポートウィザードを使用して実行します。リモートストレージのインポート機能を使用すると、リモートストレージデバイスからローカルの E シリーズアレイにデータを移動できます。 
---
= SANtricityリモートストレージボリューム用のリモートストレージのインポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートシステムからローカルの E シリーズストレージシステムへのストレージのインポートを開始するには、 SANtricity System Manager ユーザインターフェイスでリモートストレージのインポートウィザードを使用します。

.必要なもの
* E シリーズストレージシステムがリモートストレージシステムと通信できるように設定されている必要があります。を参照してください link:setup-remote-volumes-concept.html["ハードウェアを設定する"]。
* リモートストレージシステムについて、次の情報を収集します。
+
** iSCSI IQN
** iSCSI IP アドレス
** リモートストレージデバイス（ソースボリューム）の LUN 番号


* ローカルの E シリーズストレージシステムの場合、データのインポートに使用するボリュームを作成または選択します。ターゲットボリュームが、次の要件を満たしている必要があります。
+
** リモートストレージデバイス（ソースボリューム）のブロックサイズと一致します。
** には、リモートストレージデバイスと同じかそれ以上の容量が必要です。
** の状態が「最適」で、利用可能です。要件の一覧については、を参照してください link:system-reqs-concept.html["要件と制限事項"]。


* 推奨：インポートプロセスを開始する前に、リモートストレージシステムのボリュームをバックアップしてください。


.このタスクについて
このタスクでは、リモートストレージデバイスとローカルの E シリーズストレージシステム上のボリュームの間のマッピングを作成します。設定が完了すると、インポートが開始されます。


NOTE: 多くの変数がインポート操作とその完了時間に影響を与える可能性があるため、最初は小さい「テスト」インポートを実行する必要があります。これらのテストを使用して、すべての接続が想定どおりに機能し、インポート処理が適切な時間で完了することを確認します。

.手順
. SANtricity システム・マネージャーで、 * ストレージ > リモート・ストレージ * をクリックします。
. [ リモートストレージのインポート ] をクリックします。
+
リモートストレージをインポートするためのウィザードが表示されます。

. ソースの設定パネルの手順 1a で、接続情報を入力します。
+
.. [ * 名前 * ] フィールドに、リモート・ストレージ・デバイスの名前を入力します。
.. iSCSI 接続プロパティ * で、リモートストレージデバイスに対して IQN 、 IP アドレス、およびポート番号（デフォルトは 3260 ）を入力します。
+
別の iSCSI 接続を追加する場合は、 * + 別の IP アドレスを追加 * をクリックして、リモートストレージの IP アドレスを追加します。完了したら、 * 次へ * をクリックします。

+
[ 次へ ] をクリックすると、 [ ソースの設定 ] パネルの手順 1b が表示されます。



. [*LUN*] フィールドで ' リモート・ストレージ・デバイスに使用するソース LUN を選択し '[ 次へ ] をクリックします
+
ターゲットの設定パネルが開き、インポートのターゲットとして使用するボリューム候補が表示されます。ブロックサイズ、容量、またはボリュームの可用性が原因で、一部のボリュームが候補のリストに表示されません。

. E シリーズストレージシステムのターゲットボリュームを表から選択します。必要に応じて、スライダを使用してインポートの優先度を変更します。「 * 次へ * 」をクリックします。「 continue 」と入力し、「 * Continue * 」をクリックして、次のダイアログボックスで操作を確認します。
+
ターゲットボリュームの容量がソースボリュームよりも大きい場合、 E シリーズシステムに接続されているホストにはその容量は報告されません。新しい容量を使用するには、インポート処理が完了して切断されたあとに、ホストでファイルシステムの拡張処理を実行する必要があります。

+
ダイアログで設定を確定すると、 [ レビュー（ Review ） ] パネルが表示されます。

. Review （レビュー）画面で、指定したリモートストレージデバイス、ターゲット、およびインポート設定が正しいことを確認します。[ 完了 ] をクリックして ' リモート・ストレージの作成を完了します
+
別のインポートを開始するかどうかを確認するダイアログボックスが表示されます。

. 必要に応じて、 * はい * をクリックして別のリモートストレージインポートを作成します。[ はい ] をクリックすると、 [ ソースの設定 ] パネルの手順 1a に戻ります。ここで、既存の構成を選択するか、新しい構成を追加できます。別のインポートを作成しない場合は、「 * いいえ」をクリックしてダイアログを終了します。
+
インポートプロセスが開始されると、ターゲットボリューム全体がコピーされたデータで上書きされます。ホストがこのプロセス中にターゲットボリュームに新しいデータを書き込むと、その新しいデータはリモートデバイス（ソースボリューム）に伝播されます。

. リモートストレージパネルの View Operations （操作の表示）ダイアログで、操作の進行状況を表示します。
+
インポート処理が完了するまでの時間は、リモートストレージシステムのサイズ、インポートの優先度設定、ストレージシステムと関連するボリュームの両方の I/O 負荷の量によって異なります。インポートが完了すると、ローカルボリュームがリモートストレージデバイスの複製になります。

. 2 つのボリューム間の関係を解除する準備ができたら、インポートオブジェクトの「処理を実行中」ビューで「 * 切断」を選択します。関係が切断されると、ローカルボリュームのパフォーマンスは通常の状態に戻り、リモート接続による影響はなくなります。

