---
permalink: remote-storage-volumes/modify-remote-storage-task.html 
sidebar: sidebar 
keywords: modify Remote Storage Volumes settings, RTV settings, remote volume settings, remote storage E-Series 
summary: 設定済みのリモートストレージインポートの接続設定は、 SANtricity システムマネージャのリモートストレージ画面にある設定の表示 / 編集オプションを使用して変更できます。 
---
= リモートストレージの接続設定の変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定の表示 / 編集オプションを使用して、任意のリモートストレージ構成の接続設定を編集、追加、または削除できます。

接続プロパティを変更すると、実行中のインポートに影響します。中断を避けるため、インポートが実行されていないときにのみ接続プロパティを変更してください。

.手順
. SANtricity システムマネージャのリモートストレージ画面で、結果リストセクションから目的のリモートストレージオブジェクトを選択します。
. [* 設定の表示 / 編集 * ] をクリックします。
+
Remote Storage Settings （リモートストレージ設定）画面が表示されます。

. [ 接続のプロパティ *] タブをクリックします。
+
リモートストレージのインポート用に設定されている IP アドレスとポートの設定が表示されます。

. 次のいずれかを実行します。
+
** * 編集 * - リモート・ストレージ・オブジェクトの対応するライン・アイテムの横にある * 編集 * をクリックします変更した IP アドレスまたはポート情報をフィールドに入力します。
** * Add * – * Add * をクリックし、表示されるフィールドに新しい IP アドレスとポート情報を入力します。[ * 追加 ] をクリックして確定すると、リモートストレージオブジェクトのリストに新しい接続が表示されます。
** * 削除 * - リストから目的の接続を選択し、 * 削除 * をクリックします。表示されたフィールドに「削除」と入力して操作を確認し、「削除」をクリックします。リモートストレージオブジェクトのリストから接続が削除されます。


. [ 保存（ Save ） ] をクリックします。
+
変更した接続設定がリモートストレージオブジェクトに適用されます。


