---
permalink: remote-storage-volumes/system-reqs-concept.html 
sidebar: sidebar 
keywords: Remote Storage Volumes requirements, RTV requirements, RTV restrictions, remote volumes, remote storage E-Series 
summary: ご使用のシステムがリモートストレージボリュームの互換性に関する要件を満たしている必要があります。 
---
= リモートストレージの要件と制限事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リモートストレージボリューム機能を設定する前に、次の要件と制限事項を確認してください。



== ハードウェア要件



=== サポートされているプロトコル

リモートストレージボリューム機能の初回リリースでは、 iSCSI プロトコルと IPv4 プロトコルのみがサポートされます。

を参照してください http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^] リモートストレージボリューム機能で使用されるホストと E シリーズ（デスティネーション）アレイの間の最新のサポート情報と構成情報。



=== ストレージシステムの要件

E シリーズストレージシステムには次のものが必要です。

* 2 台（デュプレックスモード）
* 1 つ以上の iSCSI 接続を介して両方の E シリーズコントローラがリモートストレージシステムと通信するための iSCSI 接続
* SANtricity OS 11.71 以降
* サブモデル ID （ SMID ）で有効化されたリモートストレージ機能


リモートシステムには、 E シリーズストレージシステムと別のベンダーのシステムを使用できます。iSCSI 対応のインターフェイスを含める必要があります。



== ボリューム要件：

インポートに使用するボリュームは、サイズ、ステータス、およびその他の条件の要件を満たしている必要があります。



=== リモートストレージボリューム

インポートのソースボリュームを「リモートストレージボリューム」と呼びます。 このボリュームは次の条件を満たしている必要があります。

* 別のインポートに含めることはできません
* オンラインステータスである必要があります


インポートが開始されると、コントローラファームウェアによってリモートストレージボリュームがバックグラウンドで作成されます。そのため、リモートストレージボリュームは System Manager では管理できず、インポート処理にのみ使用できます。

作成されたリモートストレージボリュームは、 E シリーズシステム上の他の標準ボリュームと同様に扱われますが、次の例外があります。

* リモートストレージデバイスのプロキシとして使用できます。
* 他のボリュームコピーや Snapshot の候補として使用することはできません。
* インポートの実行中は Data Assurance 設定を変更できません。
* ホストはインポート処理専用に予約されているため、どのホストにもマッピングできません。


各リモートストレージボリュームは 1 つのリモートストレージオブジェクトにのみ関連付けられます。ただし、 1 つのリモートストレージオブジェクトを複数のリモートストレージボリュームに関連付けることができます。リモートストレージボリュームは、次の組み合わせによって一意に識別されます。

* リモートストレージのオブジェクト ID
* リモートストレージデバイスの LUN 番号




=== ターゲットボリュームの候補

ターゲットボリュームが、ローカルの E シリーズシステムのデスティネーションボリュームです。

デスティネーションボリュームは、次の条件を満たしている必要があります。

* RAID / DDP ボリュームである必要があります。
* リモートストレージボリュームと同じかそれ以上の容量が必要です。
* リモートストレージボリュームと同じブロックサイズが必要です。
* 有効な状態（最適）である必要があります。
* ボリュームコピー、 Snapshot コピー、非同期ミラーリング、同期ミラーリングの関係を確立することはできません。
* 再設定処理を実行できません：動的ボリューム拡張、動的容量拡張、動的セグメントサイズ、動的 RAID 移行、動的な容量削減、 最適化。
* インポートを開始する前にホストにマッピングすることはできません（ただし、インポートの開始後にマッピングすることはできます）。
* Flash Read Cached （ FRC ）を有効にできません。


System Manager は、リモートストレージのインポートウィザードの一環として、これらの要件を自動的にチェックします。デスティネーションボリュームを選択する際には、すべての要件を満たすボリュームだけが表示されます。



== 制限事項

リモートストレージ機能には、次の制限事項があります。

* ミラーリングを無効にする必要があります。
* E シリーズシステムのデスティネーションボリュームに Snapshot が存在しないようにします。
* インポートを開始する前に、 E シリーズシステムのデスティネーションボリュームをホストにマッピングしないでください。
* E シリーズシステムのデスティネーションボリュームでリソースプロビジョニングが無効になっている必要があります。
* リモートストレージボリュームをホストまたは複数のホストに直接マッピングすることはできません。
* Web Services Proxy はサポートされていません。
* iSCSI CHAP シークレットはサポートされません。
* SMcli はサポートされません。
* VMware データストアはサポートされません。
* インポートペアが存在する場合、関係 / インポートペアにあるストレージシステムは一度に 1 つだけアップグレードできます。




== プロダクションインポートの準備

本番環境のインポートの前にテストインポートまたは「リハーサル」を実行して、ストレージとファブリックが適切に構成されていることを確認する必要があります。

インポート処理および完了時間には、多くの変数が影響を及ぼす可能性があります。プロダクションインポートが正常に完了し、継続時間の見積もりが得られるように、これらのテストインポートを使用して、すべての接続が想定どおりに機能していること、およびインポート処理が適切な時間で完了していることを確認できます。その後、プロダクションインポートを開始する前に、目的の結果を得るための調整を行うことができます。
