---
permalink: remote-storage-volumes/view-import-progress-task.html 
sidebar: sidebar 
keywords: Remote Storage Volumes, RTV, remote volumes, remote storage E-Series 
summary: 各リモートストレージのインポートのステータスは、 SANtricity システムマネージャのリモートストレージ画面の結果リストセクションに表示されます。 
---
= SANtricityリモートストレージボリュームのインポートの進捗状況を管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インポートプロセスが開始されると、進行状況を表示して対処することができます。

インポート処理ごとに、 Operations in Progress ページには、完了率と推定残り時間が表示されます。処理には、インポートの優先順位の変更、処理の停止と再開、および処理との切断が含まれます。


NOTE: 進行中の操作は、ホームページ（ * Home > Show operations in progress * ）から表示することもできます。

.手順
. SANtricity システムマネージャで、リモートストレージページに移動し、 * View Operation* を選択します。
+
[ 処理を実行中 ] ダイアログが表示されます。

. 必要に応じて、 [ アクション ] 列のリンクを使用して、オペレーションの停止と再開、優先度の変更、またはオペレーションからの切断を行います。
+
** * 優先度の変更 * –「優先度の変更」を選択して、処理中または保留中の処理の優先度を変更します。オペレーションに優先度を適用し、 * OK * をクリックする。
** * 停止 * - リモート・ストレージ・デバイスからのデータのコピーを一時停止するには、 * 停止 * を選択します。インポートペア間の関係はそのままです。インポート操作を続行する準備ができたら、 * 再開 * を選択できます。
** * 再開 * - 停止したプロセスまたは停止したプロセスを中断した時点から開始するには、 [* 再開 ] を選択します。次に、レジューム操作に優先度を適用し、 * OK * をクリックします。
+
再開操作は、インポートを最初から * 再開しません * 。最初からプロセスを再開する場合は、「 * 切断」を選択し、リモートストレージのインポートウィザードを使用してインポートを再作成する必要があります。

** * 切断 * –停止、完了、または失敗したインポート処理のソースボリュームとデスティネーションボリュームの関係を解除するには、「 * 切断」を選択します。



