---
permalink: install-hw-ef50-ef80/install-prepare.html 
sidebar: sidebar 
keywords:  
summary: EF50またはEF80ストレージシステムを設置する準備として、設置場所の準備、ストレージシステムの吊り上げに関する注意事項の理解、箱の開梱と梱包明細書との照合、およびサポート特典を受けるためのストレージシステムの登録を行ってください。 
---
= インストールの準備 - EF50およびEF80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EF50またはEF80ストレージシステムを設置する準備として、設置場所の準備、ストレージシステムの吊り上げに関する注意事項の理解、箱の開梱と梱包明細書との照合、およびサポート特典を受けるためのストレージシステムの登録を行ってください。



== ステップ1：サイトの準備

設置場所と使用予定のキャビネットまたはラックが、ご使用のストレージシステムの仕様を満たしていることを確認してください。

.手順
.  https://hwu.netapp.com["NetApp Hardware Universe の略"^]を使用して、お客様の設置場所がストレージシステムの環境要件および電気要件を満たしていることを確認してください。
. ストレージシステムとスイッチ類を収納するのに十分なキャビネットまたはラックのスペースがあることを確認してください。
+
必要に応じて、ストレージシステムの正確な寸法については https://hwu.netapp.com["NetApp Hardware Universe の略"^]を参照してください。

+
** ストレージシステム用2U
** ほとんどのスイッチで1U


. 必要なネットワークスイッチを設置します。
. 管理ソフトウェアでサポートされているブラウザを使用していることを確認してください。
+
** Google Chrome（バージョン89以降）
** Microsoft Edge（バージョン90以降）
** Mozilla Firefox（バージョン80以降）
** Safari（バージョン14以降）


. 設置に必要な以下の機器と工具を入手してください：
+
** 静電気放電（ESD）ストラップ
** プラスドライバー（#2）
** 懐中電灯






== ステップ2：持ち上げ時の注意事項を理解する

箱を開ける前、そして後でストレージシステムを設置する際には、ストレージシステムの重量を把握しておく必要があります。そうすることで、持ち上げたり移動したりする際に必要な予防措置を講じることができます。

EF50またはEF80ストレージシステムは、最大61.5 lbs（27.9 kg）の重量があります。ストレージシステムを持ち上げるには、2人で作業するか、油圧リフトを使用してください。

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20、A30、A50、C30、C60の重量注意アイコン]



== ステップ3：箱を開ける

設置場所と使用予定のキャビネットまたはラックがストレージシステムの仕様を満たしていることを確認し、持ち上げ時の注意事項を理解したら、すべての箱を開梱し、内容物を梱包明細書に記載されている品目と比較してください。

.手順
. すべての箱を慎重に開けて、中身を整理して並べます。
. 開封した内容物を梱包明細書と照らし合わせてください。
+
配送箱の側面にあるQRコードをスキャンすると、梱包明細書を入手できます。

+

NOTE: 相違点があれば、今後の対応のために記録しておいてください。

+
以下の項目は、箱の中に入っている可能性のある内容物の一部です。

+
必要に応じて、 https://hwu.netapp.com/["NetApp Hardware Universe の略"^]を参照して、その他のサポートされているケーブルとその用途を確認してください。

+
[cols="9,9,5"]
|===


| *ハードウェア* | *ケーブル* |  


 a| 
** ドライブを備えたストレージシステム
** スイッチ
** ラックマウント用ハードウェアと手順書
** ベゼル

 a| 
** コントローラ間ミラーリング用Ethernetケーブル
** 管理用イーサネットケーブル（RJ-45ケーブル）
** ネットワークケーブル
** 電源ケーブル

|  
|===




== ステップ4：ストレージシステムを登録する

設置場所がストレージシステムの仕様を満たしていることを確認し、注文した部品がすべて揃っていることを確認したら、ストレージシステムを登録してください。

. アカウントを作成し、でハードウェアを登録します http://mysupport.netapp.com/["ネットアップサポート"^]。
+
登録手続きには、各コントローラーのシリアル番号（SN）が必要です。シリアル番号は以下の場所に記載されています：

+
** 各コントローラで
** 梱包明細書に記載
** 確認メールに記載
+
image::../media/drw_ef50-ef80_sn_label_ieops-2689.svg[シリアル番号ラベルの例]





.次の手順
ストレージシステムを設置する準備ができたら、link:install-hardware.html["ハードウェアを設置する"]。
