---
permalink: upgrade-santricity/overview-upgrade-consider-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: ストレージアレイの SANtricity OS コントローラのソフトウェアとファームウェア、およびドライブファームウェアのアップグレードに関する考慮事項を確認します。 
---
= アップグレード時の考慮事項
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレードを正しく行うために、アップグレードに関する次の考慮事項を確認してください。



== コントローラのアップグレード（単一または複数）

コントローラをアップグレードする前に、以下の重要な考慮事項を確認し



=== 現在のバージョン

ソフトウェアとファームウェアの現在のバージョンを次のように表示できます。

* シングルコントローラの場合は、 SANtricity システムマネージャインターフェイスを使用します。[Upgrade Center] メニューに移動し、 [* Software and Firmware Inventory] のリンクをクリックします。
* 複数のコントローラの場合は、 SANtricity Unified Manager インターフェイスを使用します。検出されたストレージアレイの * Manage * ページに移動します。バージョンは、「 * SANtricity OS ソフトウェア * 」列に表示されます。各行の SANtricity OS のバージョンをクリックするとポップアップダイアログボックスが表示され、コントローラのファームウェアと NVSRAM の情報を確認できます。




=== アップグレードに含まれるコンポーネント

SANtricity OS のアップグレードプロセスには、次のコンポーネントが含まれています。

* *System Manager* -- System Manager はストレージアレイを管理するソフトウェアです。
* * コントローラファームウェア * -- コントローラファームウェアは、ホストとボリューム間の I/O を管理します。
* * IOM ファームウェア * - I/O モジュール（ IOM ）ファームウェアは、コントローラとドライブシェルフの間の接続を管理します。また、コンポーネントのステータスも監視します。
* * スーパーバイザー・ソフトウェア * -- スーパーバイザー・ソフトウェアは、ソフトウェアが実行されるコントローラ上の仮想マシンです。




=== 個別にアップグレードするコンポーネント

次のコンポーネントは個別にアップグレードする必要があります。

* * コントローラ NVSRAM * -- コントローラ NVSRAM は、コントローラのデフォルト設定を指定するコントローラファイルです。NVSRAM のアップグレード手順は、コントローラのアップグレード手順に含まれています。
* * ドライブファームウェア * -- を参照してください link:upgrade-drive-firmware-task.html["ドライブファームウェアをアップグレードします"] を参照してください。
* * マルチパス / フェイルオーバードライバ * -- アップグレードプロセスの一環として、ホストがコントローラと正しく連携するように、ホストのマルチパス / フェイルオーバードライバのアップグレードも必要になる場合があります。Microsoft Windows 以外のオペレーティングシステムを実行するホストがストレージシステムに I/O 接続されている場合は、それらのホストのマルチパスドライバをアップグレードします。互換性の情報については、を参照してください https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperability Matrix を参照してください"^]。アップグレード手順については、を参照してください link:../config-linux/index.html["Linux の簡単な設定"]、 link:../config-windows/index.html["Windows の簡単な設定"]または link:../config-vmware/index.html["VMware の簡単な設定"]。
* * SANtricity Unified Manager *：Unified Managerは、E4000、E2800、E5700、EF300、EF600モデルなど、複数のストレージシステムを管理するソフトウェアです。Unified Manager は SANtricity Web サービスプロキシの一部です。 RESTful API サーバをホストシステムに別途インストールして、数百台規模の新旧の NetApp E シリーズストレージシステムを管理します。詳細については、を参照してください link:../web-services-proxy/index.html["SANtricity Web Services Proxy の概要"]。
* * ユーティリティー * -- SANtricity Windows ホスト・ユーティリティー、 SANtricity Linux ホスト・ユーティリティー、 SANtricity Windows DSM など、他の管理ユーティリティーを個別にアップグレードする必要があります。これらのユーティリティの詳細については、を参照してください link:../config-linux/index.html["Linux の簡単な設定"]、 link:../config-windows/index.html["Windows の簡単な設定"]または link:../config-vmware/index.html["VMware の簡単な設定"]。
* * レガシーシステム * -- 古いストレージ・システムを含むストレージ・ネットワークにストレージ・システムが含まれている場合 ' 従来の SANtricity ストレージ・マネージャのエンタープライズ管理ウィンドウ（ EMW ）を使用して ' すべてのストレージ・システムのエンタープライズ・ビューを提供する必要がありますこの場合は、 SANtricity Storage Manager の新しいメンテナンスリリースがないかどうかを確認してください。




=== デュアルコントローラと I/O 処理

ストレージアレイにコントローラが 2 台あり、マルチパスドライバがインストールされている場合は、アップグレードの実行中もストレージアレイで I/O の処理を継続できます。アップグレードの実行中は、次の処理が実行されます。

. コントローラ A のすべての LUN がコントローラ B にフェイルオーバーされます
. コントローラ A でアップグレードが実行されます
. コントローラ A に LUN が戻され、コントローラ B の LUN もすべて移されます。
. コントローラ B でアップグレードが実行されます


アップグレードの完了後、所有権のある正しいコントローラにボリュームが配置されるように、コントローラ間で手動でのボリュームの再配置が必要になることがあります。



=== ヘルスチェック

健全性チェックは、アップグレードプロセスの一環として実行されます。この健全性チェックでは、ストレージアレイのすべてのコンポーネントについて、アップグレードを実行できる状態であるかがチェックされます。次の状況に該当する場合、アップグレードを実行できないことがあり

* 割り当てられたドライブで障害が発生し
* ホットスペアを使用中です
* 不完全なボリュームグループです
* 同時に実行できません
* ボリュームが見つからない
* コントローラのステータスが最適でない
* イベントログイベントが多すぎます
* 構成データベースの検証に失敗しました
* ドライブの DACstore のバージョンが古い


アップグレード前の健常性チェックは、アップグレードとは別に実行することもできます。



=== 即時アップグレードまたは段階的アップグレード

アップグレードはただちにアクティブ化することも、ステージングしてあとでアクティブ化することもできます。あとでアクティブ化する理由は次のとおりです。

* * 時間帯 * -- ソフトウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。I/O 負荷とキャッシュサイズによっては、コントローラのアップグレードに通常 15~25 分かかります。アクティブ化の際にはコントローラがリブートしてフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
* * パッケージのタイプ * -- 他のストレージアレイ上のファイルをアップグレードする前に ' 新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストすることをお勧めします




== ドライブファームウェアのアップグレード

ドライブファームウェアをアップグレードする前に、以下の重要な考慮事項を確認してください。



=== ドライブの互換性

各ドライブファームウェアファイルには、ファームウェアが実行されるドライブタイプに関する情報が含まれています。ファームウェアファイルは互換性のあるドライブにのみダウンロードできます。アップグレードプロセスの実行中に、 System Manager で自動的に互換性がチェックされます。



=== ドライブのアップグレード方法

ドライブファームウェアのアップグレード方式には、オンラインとオフラインの 2 種類があります。

|===
| オンラインアップグレード | オフラインアップグレード 


 a| 
オンラインアップグレードでは、ドライブが一度に 1 つずつ順番にアップグレードされます。ストレージアレイでの I/O の処理はアップグレードの実行中も継続されます。I/O を停止する必要はありませんオンラインアップグレードが可能なドライブの場合は、自動的にオンライン方式が使用されます。

オンラインアップグレードを実行できるドライブには、次のものがあります。

* 「最適」状態のプール内のドライブ
* 「最適」状態の冗長化されたボリュームグループ内のドライブ（ RAID 1 、 RAID 5 、および RAID 6 ）
* 未割り当てのドライブ
* スタンバイのホットスペアドライブ


ドライブファームウェアのオンラインアップグレードには数時間かかることがあり、その間はストレージアレイでボリューム障害が発生する可能性があります。ボリューム障害は次の状況で発生する可能性があります。

* RAID 1 または RAID 5 のボリュームグループで、あるドライブをアップグレードしているときに 1 本のドライブで障害が発生した場合。
* RAID 6 のプールまたはボリュームグループで、あるドライブをアップグレードしているときに別の 2 本のドライブで障害が発生した場合。

 a| 
オフラインアップグレードでは、同じドライブタイプのすべてのドライブが同時にアップグレードされます。この方式では、選択したドライブに関連付けられているボリュームへの I/O アクティビティを停止する必要があります。複数のドライブを同時に並行してアップグレードできるため、全体的なダウンタイムは大幅に短縮されます。オフラインアップグレードしか実行できないドライブの場合は、自動的にオフライン方式が使用されます。

次のドライブではオフライン方式を使用する必要があります。

* 非冗長ボリュームグループ内のドライブ（ RAID 0 ）
* 最適状態でないプールまたはボリュームグループ内のドライブ
* SSD キャッシュ内のドライブ


|===