---
permalink: upgrade-santricity/upgrade-drive-firmware-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: ドライブのファームウェアをアップグレードして、最新の機能とバグ修正をすべて適用します。 
---
= ドライブファームウェアをアップグレードします
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブのファームウェアをアップグレードするには、この手順に従ってください。これにより、最新の機能と修正がすべて適用されます。



== 手順 1 ：ドライブファームウェアファイルをダウンロードします

この手順では、ネットアップサポートサイトにアクセスして、ドライブファームウェアファイルを管理クライアントにダウンロードします。

.手順
. SANtricity システムマネージャで、メニューから Support [Upgrade Center] を選択します。
. Drive Firmware upgrade （ドライブファームウェアのアップグレード）で、 * NetApp Support * （ネットアップサポート）をクリックして、ネットアップサポートサイトにログインします。
. サポートサイトで、 * ダウンロード * タブをクリックし、 * ディスクドライブとファームウェアのマトリックス * を選択します。
. 「 * E-Series and EF-Series Disk Firmware. * 」を選択します
. 画面に表示される手順に従ってファイルをダウンロードします。




== 手順 2 ：ドライブファームウェアのアップグレードを開始する

この手順では、ドライブのファームウェアをアップグレードします。

.作業を開始する前に
* ディスクツーディスクバックアップ、（計画的なファームウェアアップグレードの影響を受けないボリュームグループへの）ボリュームコピー、またはリモートミラーを使用して、データをバックアップします。
* ストレージアレイのステータスが最適 l であることを確認してください。
* すべてのドライブのステータスが最適 l であることを確認してください。
* ストレージアレイで構成の変更が実行されていないことを確認します。
* ドライブのオフラインアップグレードのみが可能な場合は、ドライブに関連付けられているすべてのボリュームへの I/O アクティビティを停止することを理解します。


.手順
. System Manager Upgrade Center （メニュー：サポート [Upgrade Center] ）で、「 Drive Firmware upgrade 」セクションから「 * Begin Upgrade * 」をクリックします。
+
使用中のドライブファームウェアファイルを示すダイアログボックスが表示されます。

. サポートサイトからダウンロードしたファイルを展開（解凍）します。
. [* Browse] をクリックし、サポートサイトからダウンロードした新しいドライブファームウェアファイルを選択します。
+
ドライブファームウェアファイルのファイル名は、「 .dhUC101212CSS600_30602291_MS01_2800_0002 」のようになります。拡張子は「 .dlp 」です。

+
ドライブファームウェアファイルは一度に 1 つずつ、最大 4 つまで選択できます。同じドライブに複数のドライブファームウェアファイルが対応している場合は、ファイル競合エラーが発生します。アップグレードに使用するドライブファームウェアファイルを決定し、それ以外のファイルは削除します。

. 「 * 次へ * 」をクリックします。
+
ドライブの選択ダイアログボックスが表示され、選択したファイルでアップグレードできるドライブが一覧表示されます。

+
対応しているドライブのみが表示されます。

+
ドライブに対して選択したファームウェアが、 * 推奨ファームウェア * 情報領域に表示されます。ファームウェアを変更する必要がある場合は、 ［ * 戻る ］ をクリックして前のダイアログに戻ります。

. 実行するアップグレードのタイプを選択します。
+
** * オンライン（デフォルト） * - ストレージ・アレイが I/O を処理している間に ' ファームウェア・ダウンロードをサポートできるドライブを表示しますこのアップグレード方式を選択した場合は、これらのドライブを使用している関連付けられたボリュームへの I/O を停止する必要はありません。これらのドライブは、ストレージアレイによるドライブへの I/O の処理中に 1 つずつアップグレードされます。
** * オフライン（並行処理） * -- ドライブを使用するすべてのボリュームですべての I/O アクティビティが停止されている間に ' ファームウェアのダウンロードのみをサポートできるドライブを表示しますこのアップグレード方式を選択すると、アップグレード対象のドライブを使用するすべてのボリュームで I/O アクティビティをすべて停止する必要があります。冗長性がないドライブはオフラインで処理する必要があります。この要件には、 SSD キャッシュ、 RAID 0 ボリュームグループ、またはデグレード状態のプールやボリュームグループに関連付けられているドライブが含まれます。オフライン（並行）アップグレードは、通常、オンライン（デフォルト）方式よりも高速です。


. テーブルの最初の列で、アップグレードするドライブを選択します。
. [ * スタート * ] をクリックし、操作を確定します。
+
アップグレードを停止する必要がある場合は、 * 停止 * をクリックします。実行中のファームウェアのダウンロードは完了します。開始されていないファームウェアのダウンロードはキャンセルされます。

+

CAUTION: ドライブファームウェアのアップグレードを停止すると、データが失われたり、ドライブを使用できなくなったりする可能性があります。

. （オプション）アップグレードされた内容のリストを表示するには、 * ログの保存 * をクリックします。
+
ブラウザの Downloads フォルダに、「 drive upgrade_log-timestamp.txt 」という名前でファイルが保存されます。

. 手順のアップグレード中に次のいずれかのエラーが発生した場合は、推奨される対処方法を実行してください。
+
|===
| ファームウェアのダウンロードエラー | 対処方法 


 a| 
** 割り当てられたドライブで障害が発生し

 a| 
エラーの理由の 1 つとして、ドライブに適切な署名がない可能性があります。該当するドライブが認定済みのドライブであることを確認します。詳細については、テクニカルサポートにお問い合わせください。

ドライブを交換する場合は、交換用ドライブの容量が交換する障害ドライブと同じかそれよりも大きいことを確認してください。

障害が発生したドライブの交換は、ストレージアレイで I/O を受信中に実行できます



 a| 
ストレージアレイをチェックしてください
 a| 
** 各コントローラに IP アドレスが割り当てられていることを確認します。
** コントローラに接続されているすべてのケーブルが破損していないことを確認します。
** すべてのケーブルがしっかりと接続されていることを確認します。




 a| 
統合ホットスペアドライブ
 a| 
ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
不完全なボリュームグループです
 a| 
1 つ以上のボリュームグループまたはディスクプールが不完全な場合は、ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
すべてのボリュームグループで実行中の排他的処理（バックグラウンドメディア / パリティスキャン以外）
 a| 
1 つ以上の排他的な処理を実行中の場合は、その処理を完了してからファームウェアをアップグレードする必要があります。System Manager で処理の進捗状況を監視します。



 a| 
ボリュームが見つからない
 a| 
ファームウェアをアップグレードする前に、ボリュームが見つからない状態を修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
いずれかのコントローラの状態が最適以外である必要があります
 a| 
いずれかのストレージアレイコントローラを確認する必要があります。ファームウェアをアップグレードする前に、この状態を修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
コントローラオブジェクトグラフ間でストレージパーティション情報が一致しません
 a| 
コントローラ上のデータの検証中にエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
SPM の検証でデータベースコントローラのチェックが失敗する
 a| 
コントローラでストレージパーティションマッピングデータベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
構成データベースの検証（ストレージアレイのコントローラのバージョンでサポートされている場合）
 a| 
コントローラで構成データベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
MEL 関連のチェック
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去 7 日間に 10 個を超える DDE 情報または重大 MEL イベントが報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
2 個を超えるページ 2C 重大 MEL イベントが過去 7 日以内に報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
2 個を超えるデグレードドライブチャネル重大 MEL イベントが過去 7 日以内に報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去 7 日間に 4 個を超える重大 MEL エントリが生成されます
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。

|===


これでドライブファームウェアのアップグレードは完了です。通常の運用を再開することができます。
