---
permalink: upgrade-santricity/upgrade-multiple-controller-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: SANtricity Unified Manager を使用して、同じタイプの複数のストレージアレイの SANtricity OS ソフトウェアをアップグレードします。 
---
= 複数のコントローラのソフトウェアとファームウェアをアップグレードします
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Unified Manager では、同じタイプの複数のコントローラをアップグレードできます。

.作業を開始する前に
* レビュー link:overview-upgrade-consider-task.html["アップグレード時の考慮事項"]。
* ソフトウェアのアップグレードをすぐにアクティブ化するかあとでアクティブ化するかを決定します。あとでアクティブ化する理由は次のとおりです。
+
** * 時間帯 * -- ソフトウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
** * パッケージのタイプ *-- 他のストレージアレイのファイルをアップグレードする前に ' 新しい OS ソフトウェアを 1 つのストレージアレイでテストすることをお勧めします


* 以下の注意事項を確認してください



CAUTION: データ損失のリスク、ストレージアレイの破損のリスク - アップグレードの実行中にストレージアレイに対する変更を行わないでください。ストレージアレイの電源は切らないでください。


CAUTION: StorageGRID アプライアンス（ SG5612 や SG5760 など）で SANtricity OS をアップグレードする場合は、この手順を続行する前にアプライアンスをメンテナンスモードにして I/O アクティビティを停止する必要があります。停止しないと、データが失われる可能性があります。詳細な手順については、使用している StorageGRID アプライアンスのインストールとメンテナンスの手順を参照してください。



== 手順 1 ：アップグレード前の健常性チェックを実行する

健全性チェックはアップグレードプロセスの一環として実行されますが、開始前に別途実行することもできます。健全性チェックでは、ストレージアレイのコンポーネントについて、アップグレードを実行できる状態であるかがチェックされます。

.手順
. Unified Manager を開きます。
. メインビューで * Manage * を選択し、メニューから Upgrade Center [Pre-Upgrade Health Check] を選択します。
+
[Pre-Upgrade Health Check] ダイアログ・ボックスが開き ' 検出されたすべてのストレージ・システムが一覧表示されます

. 必要に応じて、ストレージシステムのリストをフィルタまたはソートして、状態が現在「最適」でないすべてのシステムを確認します。
. 健全性チェックを実行するストレージシステムのチェックボックスを選択します。
. [ スタート ] ボタンをクリックします。
+
健全性チェックの実行中、ダイアログボックスに進捗状況が表示されます。

. 健全性チェックが完了したら、各行の右側にある省略記号（ ... ）をクリックして、詳細情報を表示したり他のタスクを実行したりできます。
+

NOTE: 健全性チェックでいずれかのアレイに問題が見つかった場合は、そのアレイをスキップして他のアレイのアップグレードを続行するか、プロセス全体を停止して該当するアレイのトラブルシューティングを行うことができます。





== 手順 2 ：サポートサイトからソフトウェアファイルをダウンロードする

この手順では、ネットアップサポートサイトにアクセスして、新しいダウンロード可能パッケージ（ DLP ）ソフトウェアファイルを管理ホストシステムに保存します。

.手順
. ストレージアレイにコントローラが 1 台しかない場合やマルチパスドライバが使用されていない場合は、アプリケーションエラーを回避するためにストレージアレイへの I/O アクティビティを停止します。ストレージアレイにコントローラが 2 台あり、マルチパスドライバがインストールされている場合は、 I/O アクティビティを停止する必要はありません。
. Unified Manager のメインビューで * Manage * を選択し、アップグレードするストレージアレイを 1 つ以上選択します。
. メニューからアップグレードセンター [Upgrade SANtricity OS Software] を選択します。
+
SANtricity OS ソフトウェアのアップグレードページが表示されます。

. ネットアップサポートサイトからローカルマシンに最新の SANtricity OS ソフトウェアパッケージをダウンロードします。
+
.. [ 新しいファイルをソフトウェアリポジトリに追加する *] をクリックします。
.. 最新の * SANtricity OS ダウンロード * を検索するためのリンクをクリックします。
.. [Download Latest Release] リンクをクリックします。
.. 以降の手順に従って、 SANtricity OS ファイルと NVSRAM ファイルをローカルマシンにダウンロードします。


+

NOTE: バージョン 8.42 以降のデジタル署名されたファームウェアが必要です。署名のないファームウェアをダウンロードしようとすると、エラーが表示されてダウンロードが中止されます。





== 手順 3 ：ソフトウェアファイルをコントローラに転送する

SANtricity OS ソフトウェアファイルと NVSRAM ファイルをリポジトリにロードして、 Unified Manager アップグレードセンターからアクセスできるようにします。


CAUTION: データ損失のリスク、ストレージアレイの破損のリスク - アップグレードの実行中にストレージアレイに対する変更を行わないでください。ストレージアレイの電源は切らないでください。

.手順
. Unified Manager のメインビューで * Manage * を選択し、アップグレードするストレージアレイを 1 つ以上選択します。
. メニューからアップグレードセンター [Upgrade SANtricity OS Software] を選択します。
+
SANtricity OS ソフトウェアのアップグレードページが表示されます。

. ネットアップサポートサイトからローカルマシンに最新の SANtricity OS ソフトウェアパッケージをダウンロードします。
+
.. [ 新しいファイルをソフトウェアリポジトリに追加する *] をクリックします。
.. 最新の * SANtricity OS ダウンロード * を検索するためのリンクをクリックします。
.. [Download Latest Release] リンクをクリックします。
.. 以降の手順に従って、 SANtricity OS ファイルと NVSRAM ファイルをローカルマシンにダウンロードします。


+

NOTE: バージョン 8.42 以降のデジタル署名されたファームウェアが必要です。署名のないファームウェアをダウンロードしようとすると、エラーが表示されてダウンロードが中止されます。

. コントローラのアップグレードに使用する OS ソフトウェアファイルと NVSRAM ファイルを選択します。
+
.. [Select a SANtricity OS software file*] ドロップダウンから、ローカルマシンにダウンロードした OS ファイルを選択します。
+
使用可能なファイルが複数ある場合は、日付が新しい順にファイルがソートされます。

+

NOTE: ソフトウェアリポジトリには、 Web サービスプロキシに関連付けられているすべてのソフトウェアファイルが表示されます。使用するファイルが表示されない場合は、リンク * ソフトウェアリポジトリに新しいファイルを追加 * をクリックして、追加する OS ファイルが保存されている場所を参照します。

.. Select an NVSRAM file * ドロップダウンから、使用するコントローラファイルを選択します。
+
ファイルが複数ある場合は、日付が新しい順にファイルがソートされます。



. [Compatible Storage Array] テーブルで ' 選択した OS ソフトウェア・ファイルと互換性のあるストレージ・アレイを確認し ' アップグレードするアレイを選択します
+
** [ 管理 ] ビューで選択したストレージ・アレイおよび選択したファームウェア・ファイルと互換性のあるストレージ・アレイは ' デフォルトで [ 互換性のあるストレージ・アレイ ] テーブルで選択されています
** 選択したファームウェアファイルで更新できないストレージアレイは、ステータス * incompatible * と表示される互換性があるストレージアレイテーブルで選択できません。


. （オプション）ソフトウェアファイルをアクティブ化せずにストレージアレイに転送するには、 * OS ソフトウェアをストレージアレイに転送し、ステージング済みとしてマークし、あとでアクティブ化 * チェックボックスをオンにします。
. [ スタート ] ボタンをクリックします。
. すぐにアクティブ化するかあとでアクティブ化するかに応じて、次のいずれかを実行します。
+
** 「 * transfer * 」と入力して、アップグレード対象として選択したアレイの OS ソフトウェアのバージョンを転送することを確認し、「 * Transfer * 」をクリックします。
+
転送されたソフトウェアをアクティブにするには、メニューから [Upgrade Center] [Activate Staged OS Software] を選択します。

** アップグレード対象として選択したアレイ上の OS ソフトウェアのバージョンを転送してアクティブ化することを確認するには、 * upgrade * と入力し、 * Upgrade * をクリックします。
+
アップグレード対象として選択した各ストレージアレイにソフトウェアファイルが転送され、ストレージアレイがリブートされてファイルがアクティブ化されます。



+
アップグレード処理では次の処理が実行されます。

+
** アップグレードプロセスの一環として、アップグレード前の健常性チェックが実行されます。アップグレード前の健常性チェックでは、ストレージアレイのすべてのコンポーネントについて、アップグレードを実行できる状態であるかがチェックされます。
** いずれかの健全性チェックでストレージアレイに問題が見つかった場合、アップグレードが停止します。省略符号 (...) をクリックして * ログを保存 * を選択すると、エラーを確認できます。ヘルスチェックエラーを無視するように選択し、 * Continue * をクリックしてアップグレードを続行することもできます。
** アップグレード前の健常性チェックのあとに、アップグレード処理をキャンセルすることができます。


. （オプション）アップグレードが完了したら、省略記号（ ... ）をクリックし、「 * ログを保存」を選択すると、特定のストレージアレイのアップグレード内容のリストが表示されます。
+
ブラウザの Downloads フォルダに 'upgrade_log-<date>.json ` という名前でファイルが保存されます





== 手順 4 ：ステージング済みソフトウェアファイルをアクティブ化する（オプション）

ソフトウェアファイルはただちにアクティブ化することも、都合のいいタイミングでアクティブ化することもできます。この手順では、ソフトウェアファイルをあとでアクティブ化するように選択した場合を想定しています。


NOTE: 起動後にアクティブ化プロセスを停止することはできません。

.手順
. Unified Manager のメインビューで、 * Manage * を選択します。必要に応じて、 Status 列をクリックして、ステータスが「 OS Upgrade （ Awaiting activation ）」のすべてのストレージアレイをソートします。
. ソフトウェアをアクティブ化するストレージアレイを 1 つ以上選択し、メニューから [Upgrade Center] [Activate Staged OS Software] を選択します。
+
アップグレード処理では次の処理が実行されます。

+
** アップグレード前の健常性チェックは、アクティブ化プロセスの一環として実行されます。アップグレード前の健常性チェックでは、ストレージアレイのすべてのコンポーネントについて、アクティブ化を実行できる状態であるかがチェックされます。
** いずれかの健全性チェックでストレージアレイに問題が見つかった場合、アクティブ化は停止します。省略符号 (...) をクリックして * ログを保存 * を選択すると、エラーを確認できます。ヘルスチェックエラーを無視して、 [* Continue （続行） ] をクリックしてアクティブ化を続行することもできます。
** アップグレード前の健常性チェックのあとに、アクティブ化処理をキャンセルすることができます。アップグレード前の健常性チェックが正常に完了すると、アクティブ化が実行されます。アクティブ化にかかる時間は、ストレージアレイの構成とアクティブ化しているコンポーネントによって異なります。


. （オプション）アクティブ化が完了したら、省略記号（ ... ）をクリックし、「ログを保存」を選択すると、特定のストレージアレイに対してアクティブ化された内容のリストが表示されます。
+
ブラウザの Downloads フォルダに 'activate_log-<date>.json という名前でファイルが保存されます



これでコントローラソフトウェアのアップグレードは完了です。通常の運用を再開することができます。
