---
permalink: upgrade-santricity/upgrade-single-controller-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: 単一の E シリーズコントローラのソフトウェアとファームウェアをアップグレードする。 
---
= 単一のコントローラのソフトウェアとファームウェアをアップグレードします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラを 1 台アップグレードすることで、最新の機能と修正をすべて利用できます。

このプロセスでは、ストレージアレイのソフトウェア、および必要に応じて IOM ファームウェアと不揮発性静的ランダムアクセスメモリ（ NVSRAM ）をアップグレードします。

.作業を開始する前に
* レビュー link:overview-upgrade-consider-task.html["アップグレード時の考慮事項"]。
* コントローラ NVSRAM ファイルを OS ファームウェアと同時にアップグレードするかどうかを決定します。
+
通常は、すべてのコンポーネントを同時にアップグレードする必要があります。ただし、パッチを適用していたり、カスタムバージョンのコントローラ NVSRAM ファイルを使用していて、上書きしたくない場合は、アップグレードを中止することもできます。

* IOM ファームウェアをアップグレードするかどうかを決定します。
+
通常は、すべてのコンポーネントを同時にアップグレードする必要があります。ただし、 IOM ファームウェアを SANtricity OS ソフトウェアアップグレードの一部としてアップグレードしない場合や、テクニカルサポートから IOM ファームウェアをダウングレードするよう依頼された場合は（ファームウェアのダウングレードにはコマンドラインインターフェイスを使用する必要があります）、アップグレードを中止することもできます。

* OS のアップグレードを今すぐアクティブ化するか、あとでアクティブ化するかを決定します。
+
あとでアクティブ化する理由には、次のものがあります

+
** * 時間帯 * –ソフトウェアとファームウェアのアクティブ化には時間がかかることがあるため、 I/O 負荷の低い時間帯に実行できます。アクティブ化の際にはコントローラがフェイルオーバーするため、アップグレードが完了するまではパフォーマンスが通常よりも低下する可能性があります。
** * パッケージのタイプ * –新しいソフトウェアとファームウェアを 1 つのストレージアレイでテストしてから、他のストレージアレイでファイルをアップグレードできます。






== 手順 1 ：サポートサイトからソフトウェアファイルをダウンロードする

この手順では、ネットアップサポートサイトにアクセスして、新しいダウンロード可能パッケージ（ DLP ）ソフトウェアファイルを管理ホストシステムに保存します。

アップグレードに必要な時間は、ストレージアレイの構成とアップグレードするコンポーネントによって異なります。

.手順
. ストレージアレイにコントローラが 1 台しかない場合やマルチパスドライバがインストールされていない場合は、アプリケーションエラーを回避するためにストレージアレイへの I/O アクティビティを停止します。ストレージアレイにコントローラが 2 台あり、マルチパスドライバがインストールされている場合は、 I/O アクティビティを停止する必要はありません。
+

CAUTION: StorageGRID アプライアンス（ SG5612 や SG5760 など）で SANtricity OS をアップグレードする場合は、この手順を続行する前にアプライアンスをメンテナンスモードにして I/O アクティビティを停止する必要があります。停止しないと、データが失われる可能性があります。詳細な手順については、使用している StorageGRID アプライアンスのインストールとメンテナンスの手順を参照してください。

. System Manager インターフェイスで、メニューから Support [Upgrade Center] を選択します。
. 「 SANtricity OS Software upgrade 」というラベルの付いた領域で、「 NetApp SANtricity OS Downloads 」をクリックしてネットアップサポートサイトを開きます。
. ダウンロードページから、 * E-Series SANtricity OS Controller Software* を選択します。
+

NOTE: バージョン 8.42 以降のデジタル署名されたファームウェアが必要です。署名のないファームウェアをダウンロードしようとすると、エラーが表示されてダウンロードが中止されます。

. 画面に表示される手順に従って、コントローラモデルに対応する最新の OS ソフトウェアをダウンロードします。NVSRAM もアップグレードする場合は、 1 台のコントローラの NVSRAM ファイルをダウンロードします。




== 手順 2 ：ソフトウェアファイルをコントローラに転送する

この手順では、アップグレードプロセスを開始できるように、ソフトウェアファイルをコントローラに転送します。コンポーネントが管理クライアントからコントローラにコピーされ、フラッシュメモリのステージング領域に配置されます。


CAUTION: * データ損失のリスク、ストレージアレイの損傷のリスク * -- アップグレードの実行中にストレージアレイを変更しないでください。ストレージアレイの電源は切らないでください。

.手順
. （オプション）。特定のメンテナンス期間にアップグレードを実行する場合は、アップグレード前の健常性チェックを実行して、ストレージアレイに重大な問題が発生していないかどうかを事前に確認することを推奨します。その場合は、 System Manager の Upgrade Center （メニュー：サポート [Upgrade Center] ）からアップグレード前の健常性チェック * を選択し、画面に表示される指示に従います。それ以外の場合は、アップグレードプロセスで健全性チェックが実行されるため、この手順は省略できます。
. この時点で IOM ファームウェアをアップグレードしない場合は、 * IOM の自動同期を中断 * をクリックし、ダイアログボックスの指示に従います。
+
ストレージアレイにコントローラが 1 台しかない場合、 IOM ファームウェアはアップグレードされません。

. System Manager のアップグレードセンターで、「 SANtricity OS ソフトウェアのアップグレード」から「 * アップグレードの開始」をクリックします。
+
SANtricity OS ソフトウェアのアップグレードダイアログが表示されます。

. アップグレードプロセスを開始するファイルを 1 つ以上選択します。
+
.. SANtricity OS ソフトウェアファイルを選択するには、「 * 参照」をクリックし、サポートサイトからダウンロードした OS ソフトウェアファイルを選択します。
.. 参照 * をクリックし、サポートサイトからダウンロードした NVSRAM ファイルに移動して、コントローラ NVSRAM ファイルを選択します。コントローラ NVSRAM ファイルの名前は 'N2800-830000-000.dll' のようになります


+
次の処理が行われます。

+
** デフォルトでは、現在のストレージアレイ構成と互換性のあるファイルだけが表示されます。
** アップグレードするファイルを選択すると、ファイルの名前とサイズが表示されます。


. （オプション）アップグレードする SANtricity OS ソフトウェアファイルを選択した場合、ファイルをアクティブ化せずにコントローラに転送するには、 [ ファイルを今すぐ転送するが、アップグレードしない（後でアップグレードをアクティブ化する） *] チェックボックスをオンにします。
. [ * スタート * ] をクリックし、操作を確定します。
+
アップグレード前の健常性チェックの間は処理をキャンセルできますが、転送またはアクティブ化の実行中はキャンセルできません。

. （オプション）アップグレードされた内容のリストを表示するには、 * ログの保存 * をクリックします。
+
ブラウザの Downloads フォルダに、「 drive upgrade_log-timestamp.txt 」という名前でファイルが保存されます。



ソフトウェアファイルをすでにアクティブ化している場合は、に進みます <<手順 4 ：ソフトウェアとファームウェアのアップグレードを完了する>>; それ以外の場合は、に進みます <<手順 3 ：ソフトウェアファイルをアクティブ化する>>。



== 手順 3 ：ソフトウェアファイルをアクティブ化する

この手順は、ソフトウェアまたはファームウェアが転送済みでアクティブ化されていない場合にのみ実行します。この状態を確認するには、 System Manager のホームページまたはアップグレードセンターのページの通知領域で通知を探します。

アクティブ化処理を実行すると、現在のソフトウェアとファームウェアが新しいソフトウェアとファームウェアに置き換えられます。起動後にアクティブ化プロセスを停止することはできません。

.手順
. System Manager インターフェイスで、メニューから Support [Upgrade Center] を選択します。
. 「 SANtricity OS ソフトウェアのアップグレード」というラベルの付いた領域で、 * アクティブ化 * をクリックし、操作を実行することを確認します。
. （オプション）アップグレードされた内容のリストを表示するには、 * ログの保存 * をクリックします。
+
ブラウザの Downloads フォルダに、「 drive upgrade_log-timestamp.txt 」という名前でファイルが保存されます。





== 手順 4 ：ソフトウェアとファームウェアのアップグレードを完了する

Software and Firmware Inventory （ソフトウェアとファームウェアのインベントリ）ダイアログボックスでバージョンを確認して、ソフトウェアとファームウェアのアップグレードを完了します。

.作業を開始する前に
* ソフトウェアまたはファームウェアをアクティブ化しておく必要があります。


.手順
. System Manager の Hardware ページにすべてのコンポーネントが表示されていることを確認します。
. [Software and Firmware Inventory] ダイアログボックスをチェックして、新しいソフトウェアとファームウェアのバージョンを確認します（ [Menu] ： [Upgrade Center] を選択し、 [* Software and Firmware Inventory] のリンクをクリックします）。
. コントローラ NVSRAM をアップグレードした場合、既存の NVSRAM に適用されていたカスタム設定はアクティブ化のプロセスで失われます。カスタム設定については、アクティブ化のプロセスの完了後に NVSRAM に再度適用する必要があります。
. 手順のアップグレード中に次のいずれかのエラーが発生した場合は、推奨される対処方法を実行してください。
+
|===
| ファームウェアのダウンロードエラー | 対処方法 


 a| 
割り当てられたドライブで障害が発生し
 a| 
エラーの理由の 1 つとして、ドライブに適切な署名がない可能性があります。該当するドライブが認定済みのドライブであることを確認します。詳細については、テクニカルサポートにお問い合わせください。

ドライブを交換する場合は、交換用ドライブの容量が交換する障害ドライブと同じかそれよりも大きいことを確認してください。

障害が発生したドライブの交換は、ストレージアレイで I/O を受信中に実行できます



 a| 
ストレージアレイをチェックしてください
 a| 
** 各コントローラに IP アドレスが割り当てられていることを確認します。
** コントローラに接続されているすべてのケーブルが破損していないことを確認します。
** すべてのケーブルがしっかりと接続されていることを確認します。




 a| 
統合ホットスペアドライブ
 a| 
ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
不完全なボリュームグループです
 a| 
1 つ以上のボリュームグループまたはディスクプールが不完全な場合は、ファームウェアをアップグレードする前に、このエラーを修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
すべてのボリュームグループで実行中の排他的処理（バックグラウンドメディア / パリティスキャン以外）
 a| 
1 つ以上の排他的な処理を実行中の場合は、その処理を完了してからファームウェアをアップグレードする必要があります。System Manager で処理の進捗状況を監視します。



 a| 
ボリュームが見つからない
 a| 
ファームウェアをアップグレードする前に、ボリュームが見つからない状態を修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
いずれかのコントローラの状態が最適以外である必要があります
 a| 
いずれかのストレージアレイコントローラを確認する必要があります。ファームウェアをアップグレードする前に、この状態を修正する必要があります。System Manager を起動し、 Recovery Guru を使用して問題を解決します。



 a| 
コントローラオブジェクトグラフ間でストレージパーティション情報が一致しません
 a| 
コントローラ上のデータの検証中にエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
SPM の検証でデータベースコントローラのチェックが失敗する
 a| 
コントローラでストレージパーティションマッピングデータベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
構成データベースの検証（ストレージアレイのコントローラのバージョンでサポートされている場合）
 a| 
コントローラで構成データベースのエラーが発生しました。この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
MEL 関連のチェック
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去 7 日間に 10 個を超える DDE 情報または重大 MEL イベントが報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
2 個を超えるページ 2C 重大 MEL イベントが過去 7 日以内に報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
2 個を超えるデグレードドライブチャネル重大 MEL イベントが過去 7 日以内に報告されました
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。



 a| 
過去 7 日間に 4 個を超える重大 MEL エントリが生成されます
 a| 
この問題を解決するには、テクニカルサポートにお問い合わせください。

|===


.次の手順
これでコントローラソフトウェアのアップグレードは完了です。通常の運用を再開することができます。
