---
permalink: web-services-proxy/array-intro-concept.html 
sidebar: sidebar 
keywords: Web Services, WSP, SANtricity API, discover storage WSP, 
summary: ネットワーク内のストレージシステムを管理するには、まずそれらを検出し、管理リストに追加する必要があります。 
---
= SANtricity Webサービスプロキシを使用したストレージシステムの管理
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワーク内のストレージシステムを管理するには、まずそれらを検出し、管理リストに追加する必要があります。



== ストレージシステムを検出

自動検出を設定するか、ストレージシステムを手動で検出できます。



=== ストレージシステムを自動的に検出します

wsconfig.xml ファイルの設定を変更することにより、ネットワークでストレージシステムが自動的に検出されるように指定できます。デフォルトでは、 IPv6 の自動検出は無効になっており、 IPv4 は有効になっています。

管理 IP アドレスまたは DNS アドレスを 1 つ指定するだけで、ストレージシステムを追加することができます。パスが設定されていない場合や設定されていてルーティング可能な場合、サーバはすべての管理パスを自動的に検出します。


NOTE: 初回接続後に、 IPv6 プロトコルを使用してコントローラの設定からストレージシステムを自動的に検出しようとすると、検出に失敗することがあります。原因としては、 IP アドレスの転送時の問題のほか、ストレージシステムで IPv6 が有効になっているがサーバでは有効になっていない場合などが考えられます。

.作業を開始する前に
IPv6 の検出設定を有効にする前に、接続の問題を軽減するために、ストレージシステムへの IPv6 接続がインフラでサポートされていることを確認してください。

.手順
. 次の場所にある wsconfig.xml ファイルを開きます。
+
** （ Windows ） - C ： \Program Files\NetApp\Virtual Web Services Proxy
** （ Linux ） - /opt/netapp/santricity_web_services_proxy


. 自動検出文字列で ' 必要に応じて設定を true から false に変更します次の例を参照してください。
+
[listing]
----
<env key="autodiscover.ipv6.enable">true</env>
----
+

NOTE: パスが設定されていても、サーバがアドレスにルーティングできるように設定されていないと、断続的に接続エラーが発生します。ホストからルーティング可能な IP アドレスを設定できない場合は、自動検出をオフにします（設定を「 false 」に変更します）。

. ファイルを保存します。




=== API エンドポイントを使用してストレージシステムを検出および追加する

API エンドポイントを使用してストレージシステムを検出し、管理リストに追加することができます。この手順は、ストレージシステムと API の間に管理接続を作成します。


NOTE: このタスクでは、これらのシステムを対話型の API ドキュメントで管理できるように、 REST API を使用してストレージシステムを検出および追加する方法について説明します。ただし、ストレージシステムの管理には、使いやすいインターフェイスを備えた Unified Manager を使用することもできます。詳細については、 Unified Manager のオンラインヘルプを参照してください。

.作業を開始する前に
SANtricity バージョン 11.30 以降のストレージシステムの場合は、 SANtricity System Manager インターフェイスで SYMbol の従来の管理インターフェイスを有効にしておく必要があります。そうしないと、 Discovery エンドポイントが失敗します。この設定は、 System Manager を開いてメニューから選択できます。 [ 設定 ] 、 [ システム ] 、 [ その他の設定 ] 、 [ 管理インターフェイスの変更 ] の順に選択します。

.手順
. にログインします link:install-login-task.html["対話型の API ドキュメント"]。
. 次の手順でストレージシステムを検出します。
+
.. API ドキュメントのドロップダウンで「 * V2 」が選択されていることを確認し、「 * Storage-Systems * 」カテゴリを展開します。
.. [* POST:/ DISCOVERY * （ POST ： / 検出） ] エンドポイントをクリックし、 [* Try it out * （実行してみる * ） ] をクリックします。
.. 次の表の説明に従って、パラメータを入力します。
+
|===


 a| 
startIP

endIP
 a| 
string には、ネットワーク内の 1 つ以上のストレージシステムの開始 IP アドレスと終了 IP アドレスの範囲を指定します。



 a| 
エージェントを使用します
 a| 
次のいずれかの値に設定します。

*** True = ネットワークスキャンにインバンドエージェントを使用します。
*** false = ネットワークスキャンにインバンドエージェントを使用しません。




 a| 
ConnectionTimeout ( 接続タイムアウト
 a| 
接続がタイムアウトするまでのスキャンの許容秒数を入力します。



 a| 
最大ポート数を使用します
 a| 
ネットワークスキャンに使用するポートの最大数を入力します。

|===
.. [* Execute] をクリックします。
+

NOTE: API の操作はユーザへの確認なしで実行されます。

+
検出プロセスがバックグラウンドで実行されます。

.. コード 202 が返されることを確認します。
.. [* 応答本文 *] で、リクエスト ID に返された値を探します。次の手順で結果を表示するには、要求 ID が必要です。


. 検出結果を次のように表示します。
+
.. [Get ： /discovery * endpoint] をクリックし、 [* Try it out * ] をクリックします。
.. 前の手順で確認したリクエスト ID を入力します。[*Request ID*] を空白のままにすると、エンドポイントは、最後に実行された要求 ID にデフォルトで設定されます。
.. [* Execute] をクリックします。
.. コード 200 が返されることを確認します。
.. 応答の本文で、要求 ID とストレージシステムの文字列を特定します。次の例のような文字列が表示されます。
+
[listing]
----
"storageSystems": [
    {
      "serialNumber": "123456789",
      "wwn": "000A011000AF0000000000001A0C000E",
      "label": "EF570_Array",
      "firmware": "08.41.10.01",
      "nvsram": "N5700-841834-001",
      "ipAddresses": [
        "10.xxx.xx.213",
        "10.xxx.xx.214"
      ],
----
.. WWN 、ラベル、および IP アドレスの値を書き留めます。次の手順で必要になります。


. 次の手順に従ってストレージシステムを追加します。
+
.. [*POST:/ ストレージシステム *] エンドポイントをクリックし、 [*Try it OUT*] をクリックします。
.. 次の表の説明に従って、パラメータを入力します。
+
|===


 a| 
ID
 a| 
このストレージシステムの一意の名前を入力してください。ラベル（ GET ： /discovery の応答に表示）を入力することもできますが、任意の文字列を指定できます。このフィールドに値を指定しないと、自動的に一意の識別子が割り当てられます。



 a| 
コントローラアドレス
 a| 
応答に表示された GET ： /discovery の応答に IP アドレスを入力します。デュアルコントローラの場合は、 IP アドレスをカンマで区切って指定します。例：

「 IP アドレス 1 」、「 IP アドレス 2 」



 a| 
検証
 a| 
Web Services がストレージ・システムに接続できることを確認するために 'true' を入力します



 a| 
パスワード
 a| 
ストレージシステムの管理パスワードを入力します。



 a| 
WWN
 a| 
ストレージシステムの WWN （ GET ： /discovery の応答に表示）を入力します。

|===
.. "EnableTrace" : true の後のすべての文字列を削除して、文字列セット全体を次の例のようにします。
+
[listing]
----
{
  "id": "EF570_Array",
  "controllerAddresses": [
    "Controller-A-Mgmt-IP","Controller-B-Mgmt_IP"
  ],
  "validate":true,
  "password": "array-admin-password",
  "wwn": "000A011000AF0000000000001A0C000E",
  "enableTrace": true
}
----
.. [* Execute] をクリックします。
.. コードの応答がエンドポイントが正常に実行されたことを示す 201 であることを確認します。
+
*Post: /storage-systems * エンドポイントがキューに登録されます。次の手順では、 * GET ： /storage-systems * エンドポイントを使用して結果を表示できます。



. 次の手順でリストへの追加を確認します。
+
.. Get ： /storage-system * エンドポイントをクリックします。
+
パラメータは必要ありません。

.. [* Execute] をクリックします。
.. コードの応答がエンドポイントが正常に実行されたことを示す 200 であることを確認します。
.. 応答の本文で、ストレージシステムの詳細を確認します。管理対象アレイのリストに追加されていれば、戻り値は次のようになります。
+
[listing]
----
[
  {
    "id": "EF570_Array",
    "name": "EF570_Array",
    "wwn": "000A011000AF0000000000001A0C000E",
    "passwordStatus": "valid",
    "passwordSet": true,
    "status": "optimal",
    "ip1": "10.xxx.xx.213",
    "ip2": "10.xxx.xx.214",
    "managementPaths": [
      "10.xxx.xx.213",
      "10.xxx.xx.214"
  ]
  }
]
----






== 管理可能なストレージシステムの数をスケールアップ

デフォルトでは、最大 100 台のストレージシステムを API で管理できます。さらに多くの管理が必要な場合は、サーバのメモリ要件を増やす必要があります。

サーバは 512MB のメモリを使用するように設定されています。ネットワーク内のストレージシステムが 100 台増えるごとに、この値に 250MB 追加します。物理的なメモリよりも多くのメモリを追加しないでください。オペレーティングシステムやその他のアプリケーション用に十分な容量を確保してください。


NOTE: デフォルトのキャッシュサイズは 8 、 192 イベントです。MEL イベントのキャッシュのおおよそのデータ使用量は、 8 、 192 イベントごとに 1MB です。したがって、デフォルトのままにすると、ストレージシステムのキャッシュ使用量は約 1MB になります。


NOTE: メモリに加えて、ストレージシステムごとにネットワークポートが使用されます。Linux と Windows では、ネットワークポートはファイルハンドルとみなされます。ほとんどのオペレーティングシステムでは、セキュリティ対策として、プロセスまたはユーザが一度に開くことができるファイルハンドル数が制限されています。特に Linux 環境では、開いている TCP 接続がファイルハンドルとみなされるため、 Web Services Proxy を使用するとこの制限を簡単に超えてしまいます。修正方法はシステムによって異なるため、この値を引き上げる方法については、オペレーティングシステムのドキュメントを参照してください。

.手順
. 次のいずれかを実行します。
+
** Windows の場合は、 appserver64.init ファイルに移動します。行「 vmarg.3 = -Xmx512M 」を探します
** Linux の場合は、 webserver.sh ファイルに移動します。行「 java_options="-Xmx512M"` 」を探します


. メモリを増やすには '512' を MB 単位で希望するメモリに置き換えます
. ファイルを保存します。

