---
permalink: web-services-proxy/install-reqs-task.html 
sidebar: sidebar 
keywords: installation, download, install proxy, 
summary: Web Services Proxy のインストールとアップグレードの要件と考慮事項 
---
= SANtricity Webサービスプロキシのインストール要件とアップグレード要件を確認します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Web Services Proxy をインストールする前に、インストール要件とアップグレード時の考慮事項を確認してください。



== インストールの要件

Web Services Proxy は Windows または Linux のホストシステムにインストールして設定できます。

プロキシインストールには次の要件があります。

[cols="35h,~"]
|===
| 要件 | 説明 


 a| 
ホスト名の制限
 a| 
Web Services Proxy をインストールするサーバのホスト名に、 ASCII 文字、数字、ハイフン（ - ）のみが含まれていることを確認してください。この要件は、サーバの自己署名証明書の生成に使用される Java Keytool の制限によるものです。サーバのホスト名にアンダースコア（ _ ）などの他の文字が含まれていると、インストール後に Web サーバを起動できません。



 a| 
オペレーティングシステム
 a| 
プロキシは次のオペレーティングシステムにインストールできます。

* Linux の場合
* Windows の場合


互換性があるオペレーティングシステムとファームウェアの一覧については、を参照してください http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"^]。



 a| 
Linux ：その他の考慮事項
 a| 
Web サーバが適切に機能するためには、 Linux Standard Base （ init-functions ）が必要です。オペレーティングシステムに応じた lsb/insserv パッケージをインストールする必要があります。詳細については、 Readme ファイルの「 Additional packages required 」セクションを参照してください。



 a| 
複数のインスタンス
 a| 
Web Services Proxy のインスタンスはサーバごとに 1 つしかインストールできませんが、ネットワーク内の複数のサーバにインストールすることができます。



 a| 
キャパシティプランニング
 a| 
Web Services Proxy では、ロギング用に十分なスペースが必要です。使用可能なディスクスペースについて、システムが次の要件を満たしていることを確認してください。

* 必要なインストールスペース： 275MB
* ロギングスペースの最小値 -- 200MB
* システムメモリ： 2 GB ' ヒープ領域はデフォルトで 1 Gb です


ディスクスペース監視ツールを使用して、永続的ストレージとロギングに使用可能なディスクドライブスペースを確認できます。



 a| 
使用許諾
 a| 
Web Services Proxy は、ライセンスキーを必要としない無償のスタンドアロン製品です。ただし、該当する著作権とサービス利用規約が適用されます。グラフィカルモードまたはコンソールモードでプロキシをインストールする場合は、エンドユーザライセンス契約（ EULA ）に同意する必要があります。

|===


== アップグレード時の考慮事項

以前のバージョンからアップグレードする場合は、保持される項目と削除される項目があることに注意してください。

* Web Services Proxy については、以前の設定が保持されます。これには、ユーザパスワード、検出されたすべてのストレージシステム、サーバ証明書、信頼された証明書、サーバのランタイム設定などが含まれます。
* Unified Manager については、リポジトリにロードされていたすべての SANtricity OS ファイルがアップグレード時に削除されます。

