---
permalink: web-services-proxy/install-wsp-task.html 
sidebar: sidebar 
keywords: installation, download, install proxy, 
summary: インストールを行うには、ファイルをダウンロードし、 Linux サーバまたは Windows サーバにプロキシパッケージをインストールします。 
---
= SANtricity Webサービスプロキシファイルのインストールまたはアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
インストールを行うには、ファイルをダウンロードし、 Linux サーバまたは Windows サーバにプロキシパッケージをインストールします。これらの手順を使用してプロキシをアップグレードすることもできます。



== Web Services Proxy ファイルをダウンロード

ネットアップサポートサイトのソフトウェアダウンロードページから、インストールファイルと readme ファイルをダウンロードできます。

ダウンロードパッケージには、 Web Services Proxy と Unified Manager インターフェイスが含まれています。

.手順
. に進みます https://mysupport.netapp.com/site/downloads["ネットアップサポート - ダウンロード"^]。
. E シリーズ SANtricity Web サービスプロキシ * を選択します。
. 指示に従ってファイルをダウンロードします。サーバに適したダウンロードパッケージ（ Windows の場合は EXE 、 Linux の場合は BIN または RPM ）を選択してください。
. プロキシと Unified Manager をインストールするサーバにインストールファイルをダウンロードします。




== Windows サーバまたは Linux サーバにをインストールします

Web Services Proxy と Unified Manager は、 3 つのモード（グラフィカル、コンソール、サイレント）のいずれかを使用するか、 RPM ファイル（ Linux のみ）を使用してインストールできます。

.作業を開始する前に
* link:install-reqs-task.html["インストール要件を確認します"]。
* プロキシと Unified Manager をインストールするサーバに正しいインストールファイル（ Windows の場合は EXE 、 Linux の場合は BIN ）をダウンロードしておきます。




=== グラフィカルモードでのインストール

グラフィカルモードでのインストールは、 Windows と Linux のどちらでも実行できます。グラフィカルモードでは、 Windows 形式のインターフェイスにプロンプトが表示されます。

.手順
. インストールファイルをダウンロードしたフォルダにアクセスします。
. Windows または Linux のインストールを起動します。
+
** Windows -- インストールファイルをダブルクリックします
+
'santricity _webservices-windows_x64-nn.nn.nnnn.exe'

** Linux -- 次のコマンドを実行します : 'tricity _webservices -linux_x64-nn.nn.nnnn.bin
+
上記ファイル名の「 nn.nn.nn.nnnn 」はバージョン番号です。



+
インストールプロセスが開始され、 NetApp SANtricity Web サービスプロキシ + Unified Manager のスプラッシュ画面が表示されます。

. 画面の指示に従います。
+
インストール時に、複数の機能を有効にし、いくつかの設定パラメータを入力するように求められます。選択した内容は、必要に応じてあとで構成ファイルで変更できます。

+

NOTE: アップグレードの実行中、構成パラメータの入力は求められません。

. Webserver Started というメッセージが表示されたら、 * OK * をクリックしてインストールを完了します。
+
Install Complete （インストールの完了）ダイアログボックスが表示されます。

. Unified Manager または対話型の API ドキュメントを起動する場合はチェックボックスをクリックし、 * Done * をクリックします。




=== コンソールモードでのインストール

コンソールモードでのインストールは、 Windows と Linux のどちらでも実行できます。コンソールモードでは、ターミナルウィンドウにプロンプトが表示されます。

.手順
. 次のコマンドを実行します :`< インストールファイル名 >-i console`
+
上記のコマンドでは、「 <install filename> 」はダウンロードしたプロキシインストールファイルの名前を表します（例： 'tricity _webservices-windows_x64.nn.nn.nnnn.exe'） 。

+

NOTE: インストール・プロセス中にいつでもインストールをキャンセルするには ' コマンドプロンプトで quit を入力します

+
インストールプロセスが開始され、「 Launching Installer -- Introduction 」というメッセージが表示されます。

. 画面の指示に従います。
+
インストール時に、複数の機能を有効にし、いくつかの設定パラメータを入力するように求められます。選択した内容は、必要に応じてあとで構成ファイルで変更できます。

+

NOTE: アップグレードの実行中、構成パラメータの入力は求められません。

. インストールが完了したら、 Enter キーを押してインストーラを終了します。




=== サイレントモードでのインストール

サイレントモードでのインストールは、 Windows と Linux のどちらでも実行できます。サイレントモードでは、メッセージやスクリプトはターミナルウィンドウに表示されません。

.手順
. 次のコマンドを実行します。「 < インストールファイル名 > -i silent 」
+
上記のコマンドでは、「 <install filename> 」はダウンロードしたプロキシインストールファイルの名前を表します（例： 'tricity _webservices-windows_x64.nn.nn.nnnn.exe'） 。

. Enter キーを押します。
+
インストールプロセスが完了するまでに数分かかることがあります。インストールが完了すると、ターミナルウィンドウにコマンドプロンプトが表示されます。





=== RPM コマンドでのインストール（ Linux のみ）

RPM パッケージ管理システムと互換性がある Linux システムでは、オプションの RPM ファイルを使用して Web Services Proxy をインストールできます。

.手順
. プロキシと Unified Manager をインストールするサーバに RPM ファイルをダウンロードします。
. ターミナルウィンドウを開きます。
. 次のコマンドを入力します。
+
「 rpm -u SANtricity_webservices-nn.nn.nnnn -n x86_64 」 rpm を指定します

+

NOTE: 上記コマンドの「 nn.nn.nn.nnnn 」はバージョン番号です。

+
インストールプロセスが完了するまでに数分かかることがあります。インストールが完了すると、ターミナルウィンドウにコマンドプロンプトが表示されます。


