---
permalink: web-services-proxy/install-login-task.html 
sidebar: sidebar 
keywords: log in API, log in Unified Manager 
summary: Web Services API と Unified Manager にアクセスしてログインします。 
---
= API と Unified Manager にログインします
:icons: font
:imagesdir: ../media/


[role="lead"]
Web Services には、 REST API と直接やり取りできる API ドキュメントが含まれています。また、複数の E シリーズストレージシステムを管理するためのブラウザベースのインターフェイスである Unified Manager も含まれています。



== Web Services API にログインします

Web Services Proxy をインストールしたら、ブラウザから対話型の API ドキュメントにアクセスできます。

API ドキュメントは Web Services の各インスタンスと一緒に実行されるほか、ネットアップサポートサイトから PDF 版を入手することもできます。対話型バージョンにアクセスするには、ブラウザを開き、 Web Services の場所（組み込みバージョンのコントローラまたはプロキシのサーバ）を示す URL を入力します。


NOTE: Web Services API は OpenAPI 仕様（旧称 Swagger 仕様）を実装しています。

初回ログイン時は「 admin 」クレデンシャルを使用します。「 admin 」は、すべての機能とロールにアクセスできるスーパー管理者とみなされます。

.手順
. ブラウザを開きます。
. 組み込み実装またはプロキシ実装の URL を入力します。
+
** 組み込み：「 + https://<controller>:<port>/devmgr/docs/+` 」
+
この URL で、「 <controller> 」はコントローラの IP アドレスまたは FQDN 、「 <port> 」はコントローラの管理ポート番号（デフォルトは 8443 ）です。

** プロキシ :`+http[s]://<server>:<port>/devmgr/docs/+`
+
この URL で、「 <server> 」はプロキシがインストールされているサーバの IP アドレスまたは FQDN 、「 <port> 」はリスニングポート番号（デフォルトは HTTP が 8080 、 HTTPS が 8443 ）です。

+

NOTE: リスニングポートがすでに使用されている場合は競合が検出され、別のリスニングポートを選択するように求められます。

+
ブラウザで API ドキュメントが開きます。



. 対話型の API ドキュメントが開いたら、ページ右上のドロップダウンメニューから * utils * を選択します。
. [*Login*] カテゴリをクリックすると、使用可能なエンドポイントが表示されます。
. [*POST:/ ログイン *] エンドポイントをクリックし、 [*Try it Out*] をクリックします。
. 初めてのログインの場合は、ユーザ名とパスワードに admin を入力します。
. [* Execute] をクリックします。
. ストレージ管理のエンドポイントにアクセスするには、右上のドロップダウンメニューから「 * v2 * 」を選択します。
+
エンドポイントの上位レベルのカテゴリが表示されます。API ドキュメントのナビゲート方法を以下に示します。

+
|===
| 面積（ Area ） | 説明 


 a| 
ドロップダウンメニュー
 a| 
ページ右上にあるドロップダウンメニューで、 API ドキュメントのバージョン 2 （ V2 ）、 SYMbol インターフェイス（ SYMbol V2 ）、ログイン用の API ユーティリティ（ utils ）を切り替えることができます。


NOTE: API ドキュメントのバージョン 1 はプレリリース版であり、一般には提供されていないため、 V1 はドロップダウンメニューに含まれていません。



 a| 
カテゴリ
 a| 
API ドキュメントは、上位レベルのカテゴリ（ Administration や Configuration など）別に編成されています。カテゴリをクリックすると、関連するエンドポイントが表示されます。



 a| 
エンドポイント
 a| 
エンドポイントを選択すると、そのエンドポイントの URL パス、必須パラメータ、応答本文、および URL から返される可能性のあるステータスコードが表示されます。



 a| 
ぜひお試しください
 a| 
[* 試してみてください * ] をクリックして、エンドポイントを直接操作します。このボタンは、エンドポイントの各ビューに表示されます。

ボタンをクリックすると、パラメータを入力するためのフィールドが表示されます（該当する場合）。値を入力して、 * Execute * をクリックします。

対話型ドキュメントでは、 JavaScript を使用して直接 API に要求が送信されます。テスト要求ではありません。

|===




== Unified Manager にログインします

Web Services Proxy をインストールしたら、 Unified Manager にアクセスして Web ベースのインターフェイスで複数のストレージシステムを管理できます。

Unified Manager にアクセスするには、ブラウザを開き、プロキシがインストールされている場所の URL を入力します。サポートされるブラウザとバージョンを次に示します。

|===
| ブラウザ | 最小バージョン 


 a| 
Google Chrome
 a| 
79



 a| 
Microsoft Internet Explorer の略
 a| 
11.



 a| 
Microsoft Edge の場合
 a| 
79



 a| 
Mozilla Firefox
 a| 
70



 a| 
Safari
 a| 
12.

|===
.手順
. ブラウザを開き、次の URL を入力します。
+
「 + http [s] ： //< サーバ > ： <port>/um+`

+
この URL では、「 <server> 」は Web Services Proxy がインストールされているサーバの IP アドレスまたは FQDN 、「 <port> 」はリスニングポート番号（デフォルトは HTTP が 8080 、 HTTPS が 8443 ）です。

+
Unified Manager のログインページが開きます。

. 初めてのログインの場合は、ユーザ名に「 admin 」と入力し、管理ユーザのパスワードを設定して確認します。
+
パスワードには 30 文字まで使用できます。ユーザとパスワードの詳細については、 Unified Manager オンラインヘルプのアクセス管理に関するセクションを参照してください。


