---
permalink: web-services-proxy/polling-intro-concept.html 
sidebar: sidebar 
keywords: polling Web Services Proxy, WSP statistics, poll WSP, 
summary: 検出されたストレージシステム上のすべてのディスクおよびボリュームの統計に対して自動ポーリングを設定できます。 
---
= SANtricity Web Services Proxy統計の自動ポーリングを管理します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
検出されたストレージシステム上のすべてのディスクおよびボリュームの統計に対して自動ポーリングを設定できます。



== 統計の概要

統計情報として、データ収集速度とストレージシステムのパフォーマンスに関する情報が提供されます。

Web Services Proxy では、次のタイプの統計にアクセスできます。

* 統計の生データ -- データ収集時のデータポイントの合計カウンタ。読み取り処理の合計数や書き込み処理の合計数に使用できます。
* 統計の分析 -- 特定の間隔について計算された情報。1 秒あたりの読み取り I/O 処理数（ IOPS ）や書き込みスループットなどがあります。


統計の生データは線形であり、通常、有用なデータを得るためには少なくとも 2 つの収集データポイントが必要になります。統計の分析データは統計の生データから導き出され、重要な指標を提供します。統計の生データから導出可能な多くの値が、わかりやすいポイントインタイム形式で統計の分析データに提示されます。

統計の生データは、自動ポーリングが有効になっているかどうかに関係なく取得できます。URL の最後に 'useCache=true' クエリー文字列を追加すると ' 最後のポーリングからキャッシュされた統計情報を取得できますキャッシュされた情報を使用すると、統計の取得パフォーマンスが大幅に向上します。ただし、設定されたポーリング間隔以下の速度で複数の呼び出しを行うと、同じデータが取得されます。



== 統計機能

Web Services Proxy は、サポートされているハードウェアモデルおよびソフトウェアバージョンからコントローラとインターフェイスの統計の生データと分析データを取得できる API エンドポイントを提供します。



=== 統計の生データの API

* '+/storage-systems/{system-id }/controller-statistics+`
* '+/storage-systems/{system-id }/drive-statistics/{ ディスク ID のオプションリスト }+`
* '+/storage-systems/{system-id }/interface-statistics</1> { インターフェイス ID のオプションリスト }+`
* '+/storage-systems/{system-id }/volume-statistics</1> { ボリューム ID のオプションリスト }+`




=== 統計の分析データの API

* 「 +/storage-systems/{id}/Analyzed-controller-statistics/+` 」
* '+/storage-systems/{id}/analyzed-drive-statistics/{ ディスク ID のオプションリスト }+`
* '+/storage-systems/{id}/analyzed-interface-statistics</1> { インターフェイス ID のオプションリスト }+`
* '+/storage-systems/{id}/analyzed-volume-statistics/{ ボリューム ID のオプションリスト }+`


これらの URL は前回のポーリングから統計の分析データを取得するため、ポーリングが有効な場合にのみ使用できます。これらの URL には、次の入力出力データが含まれます。

* 1 秒あたりの処理数
* スループット（メガバイト / 秒）
* 応答時間（ミリ秒）


ストレージパフォーマンスの最も一般的な指標である統計の各ポーリング間の差異に基づいて計算されます。分析されていない統計よりもこれらの統計の方がよく使用され


NOTE: システムの起動時はさまざまな指標の計算に使用する統計が以前に収集されないため、統計の分析データを利用するには、起動後に少なくとも 1 回はポーリングサイクルが完了している必要があります。また、累積カウンタがリセットされた場合、次回のポーリングサイクルで予測できないデータが返されることがあります。



== ポーリング間隔を設定します

ポーリング間隔を設定するには、 wsconfig.xml ファイルを変更して、ポーリング間隔を秒単位で指定します。


NOTE: 統計はメモリにキャッシュされるため、ストレージシステムごとにメモリ使用量が 1.5MB ほど増えることがあります。

.作業を開始する前に
* ストレージシステムがプロキシで検出されている必要があります。


.手順
. 次の場所にある wsconfig.xml ファイルを開きます。
+
** （ Windows ） - C ： \Program Files\NetApp\Virtual Web Services Proxy
** （ Linux ） - /opt/netapp/santricity_web_services_proxy


. 「 <env-entries</1> 」タグ内に次の行を追加します。「 n 」はポーリング要求の間隔を秒数で表します。
+
[listing]
----
<env key="stats.poll.interval">n</env>
----
+
たとえば、 60 を入力すると、 60 秒間隔でポーリングが開始されます。つまり、前のポーリング期間に関係なく、そのポーリング期間が終了してから 60 秒後にポーリングを開始するように要求されます。統計にはいずれも、取得時の正確な時刻がタイムスタンプとして記録されます。システムは、 60 秒の計算の基準となるタイムスタンプまたは時間差を使用します。

. ファイルを保存します。

